Update Export-DnsServerZone.md
MicrosoftDocs/windows-powershell-docs pull request #2102
Opened 2020-09-02 04:43 UTC by BlackV

You cannot include a path when using this command, if you include a path in this filename the export will fail. if you only include a file name the file will export to the system32 dns folder with the name you supplied (not you current working directory either).
The help is plain wrong

2020-09-02 05:08 UTC, opbld30 commented
Docs Build status updates of commit _[d46fdd5](https://github.com/BlackV/windows-powershell-docs/commits/d46fdd5e24d876aec126a357d190d01ecd60def5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Export-DnsServerZone.md](https://github.com/BlackV/windows-powershell-docs/blob/patch-1/docset/windows/dnsserver/Export-DnsServerZone.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009020443449059-2102%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WqyqAGiIErNMl6Zwu2tCg3r%2BkjIfnh%2BYCzjE4L4mF9w%3D&st=2020-09-02T05%3A03%3A13Z&se=2020-10-03T05%3A08%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-13 19:19 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-09-13 22:07 UTC, tseward requested changes

2020-09-13 22:07 UTC, tseward commented on docset/windows/dnsserver/Export-DnsServerZone.md
> +You CANNOT include a file path. the file will be exported to the SYSTEM32 DNS Folder
Replace with something like:

File is exported to %windir%\System32\dns.

This will make it clear to the reader where to find the exported file.

2020-09-13 22:11 UTC, get-itips commented on docset/windows/dnsserver/Export-DnsServerZone.md
> +You CANNOT include a file path. the file will be exported to the SYSTEM32 DNS Folder
```suggestion
Please note: This parameter does not supports including a file path. File will be exported to %windir%\System32\dns\ folder
```

2020-09-13 22:11 UTC, get-itips commented on docset/windows/dnsserver/Export-DnsServerZone.md
> +You CANNOT include a file path. the file will be exported to the SYSTEM32 DNS Folder
Adding @tseward suggestion and my own

2020-09-14 14:03 UTC, dariomws reviewed
Agree with @tseward and @get-itips.

Also, I think we can update the description too as we have this information there:
"By default, the cmdlet places the file in the Domain Name System (DNS) directory which, by default, is C:\Windows\System32\dns."

We can replace it with:
"The cmdlet places the file in the Domain Name System (DNS) directory which, by default, is C:\Windows\System32\dns."

And the same update could be applied to W2012 and W2012 R2 versions.

2020-09-29 17:32 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-30 02:25 UTC, JohanFreelancer9 commented on docset/windows/dnsserver/Export-DnsServerZone.md
> +You CANNOT include a file path. the file will be exported to the SYSTEM32 DNS Folder
```suggestion
Please note that this parameter does not support including a file path. The file will be exported to the %windir%\System32\dns\ folder.
```

2020-09-30 02:26 UTC, JohanFreelancer9 commented on docset/windows/dnsserver/Export-DnsServerZone.md
> +You CANNOT include a file path. the file will be exported to the SYSTEM32 DNS Folder
Slight edit of the suggestion of @get-itips.

2020-09-30 02:30 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-30 15:29 UTC, e0i commented
Please feel free to re-open this PR by incorporating the suggested changes by the reviewers. Thanks.

2020-12-30 15:29 UTC, closed without merging