Fix incorrect link references
MicrosoftDocs/windows-powershell-docs pull request #2106
Opened 2020-09-06 22:47 UTC by e0i

Fixes part of the build warnings in #2078.

cc @JohanFreelancer9 for copy review
cc @get-itips @dariomws @tseward 
cc @traya1

2020-09-06 23:11 UTC, opbld31 commented
Docs Build status updates of commit _[09c7472](https://github.com/e0i/windows-powershell-docs/commits/09c747291fb68453df28123bcb4335be54b3c1ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Remove-AdfsFarmNode.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Disable-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Disable-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Enable-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Enable-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Get-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Get-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Get-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Get-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Remove-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Remove-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Set-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Set-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/applocker/Get-AppLockerFileInformation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/applocker/Get-AppLockerFileInformation.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/clusterawareupdating/Test-CauSetup.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/clusterawareupdating/Test-CauSetup.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/dcbqos/Get-NetQosTrafficClass.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/dcbqos/Get-NetQosTrafficClass.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiConnection.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiConnection.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiSession.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiSession.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiTarget.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiTarget.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Update-IscsiTarget.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Update-IscsiTarget.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsitarget/Expand-IscsiVirtualDisk.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsitarget/Expand-IscsiVirtualDisk.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netadapter/Enable-NetAdapterQos.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netadapter/Enable-NetAdapterQos.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netadapter/Get-NetAdapterRsc.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netadapter/Get-NetAdapterRsc.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeCryptoSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeCryptoSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase1AuthSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase1AuthSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase2AuthSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase2AuthSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecQuickModeCryptoSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecQuickModeCryptoSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetFirewallRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetFirewallRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetFirewallRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetFirewallRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Get-NetFirewallAddressFilter.md](https://github.com/e0i/windows-powershell-docs/blob/in [...]

2020-09-07 13:17 UTC, get-itips approved these changes

2020-09-07 13:31 UTC, JohanFreelancer9 approved these changes

2020-09-07 15:29 UTC, dariomws requested changes
I'm not sure about Install-WindowsFeature and Uninstall-WindowsFeature... 

I think someone moved these cmdlets to the Server Manager Migration folder because he didn't know where to put them.
The problem with them is that they are available in 2016/2019, not in Windows 10. But I think that the best option here is to have these cmdlets under ServerManager folder in the same way that they are in 2012 and 2012 R2, and we can add a note about that they are not available on Windows 10. Also, I think that Microsoft.Windows.ServerManager.Migration folder should be renamed to MigrationTools. 

These tasks are complimentary, I think. For this PR we can leave these links as @e0i is proposing or point them to the 2012 R2 version.

What do you think @get-itips @tseward?

2020-09-07 15:29 UTC, dariomws commented on docset/winserver2012-ps/netsecurity/Rename-NetFirewallRule.md
> +[New-GPO](../winserver2012-ps/grouppolicy/New-GPO.md)
```suggestion
[New-GPO](../grouppolicy/New-GPO.md)
```

2020-09-07 15:29 UTC, dariomws commented on docset/winserver2012-ps/iscsi/Get-IscsiConnection.md
> +[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```suggestion
[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```

2020-09-07 15:29 UTC, dariomws commented on docset/winserver2012-ps/iscsi/Get-IscsiSession.md
> +[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```suggestion
[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```

2020-09-07 15:29 UTC, dariomws commented on docset/winserver2012-ps/iscsi/Get-IscsiTarget.md
> +[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```suggestion
[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```

2020-09-07 15:29 UTC, dariomws commented on docset/winserver2012-ps/iscsi/Update-IscsiTarget.md
> +[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```suggestion
[Get-InitiatorPort](../storage/Get-InitiatorPort.md)
```

2020-09-09 12:36 UTC, opbld31 commented
Docs Build status updates of commit _[d38275a](https://github.com/e0i/windows-powershell-docs/commits/d38275a97ce86f8daa85f67c8cee6aff06a2f503)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Remove-AdfsFarmNode.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Disable-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Disable-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Enable-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Enable-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Get-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Get-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Get-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Get-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Remove-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Remove-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Set-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Set-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/applocker/Get-AppLockerFileInformation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/applocker/Get-AppLockerFileInformation.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/clusterawareupdating/Test-CauSetup.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/clusterawareupdating/Test-CauSetup.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/dcbqos/Get-NetQosTrafficClass.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/dcbqos/Get-NetQosTrafficClass.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiConnection.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiConnection.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiSession.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiSession.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiTarget.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiTarget.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Update-IscsiTarget.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Update-IscsiTarget.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsitarget/Expand-IscsiVirtualDisk.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsitarget/Expand-IscsiVirtualDisk.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netadapter/Enable-NetAdapterQos.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netadapter/Enable-NetAdapterQos.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netadapter/Get-NetAdapterRsc.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netadapter/Get-NetAdapterRsc.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeCryptoSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeCryptoSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase1AuthSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase1AuthSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase2AuthSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase2AuthSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecQuickModeCryptoSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecQuickModeCryptoSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetFirewallRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetFirewallRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetFirewallRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetFirewallRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Get-NetFirewallAddressFilter.md](https://github.com/e0i/windows-powershell-docs/blob/in [...]

2020-09-09 12:52 UTC, dariomws approved these changes

2020-09-09 13:01 UTC, opbld32 commented
Docs Build status updates of commit _[3aa9701](https://github.com/e0i/windows-powershell-docs/commits/3aa9701129b05774b11aa5eca54323b65d9d200a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Remove-AdfsFarmNode.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Disable-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Disable-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Enable-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Enable-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Get-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Get-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Get-SmbDelegation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Get-SmbDelegation.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Remove-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Remove-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/windows/smbshare/Set-SmbBandwidthLimit.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/windows/smbshare/Set-SmbBandwidthLimit.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/applocker/Get-AppLockerFileInformation.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/applocker/Get-AppLockerFileInformation.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/applocker/Test-AppLockerPolicy.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/clusterawareupdating/Test-CauSetup.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/clusterawareupdating/Test-CauSetup.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/dcbqos/Get-NetQosTrafficClass.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/dcbqos/Get-NetQosTrafficClass.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiConnection.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiConnection.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiSession.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiSession.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Get-IscsiTarget.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Get-IscsiTarget.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsi/Update-IscsiTarget.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsi/Update-IscsiTarget.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/iscsitarget/Expand-IscsiVirtualDisk.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/iscsitarget/Expand-IscsiVirtualDisk.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netadapter/Enable-NetAdapterQos.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netadapter/Enable-NetAdapterQos.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netadapter/Get-NetAdapterRsc.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netadapter/Get-NetAdapterRsc.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeCryptoSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeCryptoSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase1AuthSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase1AuthSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase2AuthSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecPhase2AuthSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecQuickModeCryptoSet.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecQuickModeCryptoSet.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Copy-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Copy-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetFirewallRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetFirewallRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Disable-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Disable-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetFirewallRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetFirewallRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetIPsecMainModeRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetIPsecMainModeRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Enable-NetIPsecRule.md](https://github.com/e0i/windows-powershell-docs/blob/invalid-link-references/docset/winserver2012-ps/netsecurity/Enable-NetIPsecRule.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/netsecurity/Get-NetFirewallAddressFilter.md](https://github.com/e0i/windows-powershell-docs/blob/in [...]

2020-09-09 15:50 UTC, merged