Rpm  reset appx package
MicrosoftDocs/windows-powershell-docs pull request #2123
Opened 2020-09-17 19:52 UTC by RDMacLachlan

2020-09-17 19:56 UTC, opbld31 commented
Docs Build status updates of commit _[0d24ea9](https://github.com/RDMacLachlan/windows-powershell-docs/commits/0d24ea9b6b3e6a375f0477ea5cd1530a70009f79)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009171952387767-2123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tFYFrpzx%2BVPibWkEf3h6Xzl%2B7DrbtwuOeUHnhe7FbN4%3D&st=2020-09-17T19%3A51%3A05Z&se=2020-10-18T19%3A56%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 13:45 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR.

cc @JohanFreelancer9 for copy editing.

Thank you.

2020-09-23 14:36 UTC, get-itips approved these changes
I think this needs to be added here also https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/appx/Appx.md

2020-09-23 14:37 UTC, get-itips commented
Also the build is currently failing for this file, please check the format of the markdown with PlatyPS.

2020-09-23 17:49 UTC, dariomws requested changes
Agree with @get-itips.

Error is "Expect Heading, please try to use PlatyPS validate the content".

2020-09-24 02:44 UTC, JohanFreelancer9 commented on docset/windows/appx/Reset-AppxPackage.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```

2020-09-24 02:49 UTC, JohanFreelancer9 requested changes
Copy review - please see @get-itips' comments.

2020-09-29 19:39 UTC, opbld30 commented
Docs Build status updates of commit _[df20e67](https://github.com/RDMacLachlan/windows-powershell-docs/commits/df20e677658b7715d428d898c173f5271023f8c4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :x:Error | | [Details](#user-content-f0af4870-6c586aaf)
[docset/windows/adfs/Remove-AdfsFarmNode.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-ae38266e-6c586aaf)
[docset/windows/bitstransfer/Get-BitsTransfer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitstransfer/Get-BitsTransfer.yml) | :warning:Warning | | [Details](#user-content-f8a95909-6c586aaf)
[docset/windows/booteventcollector/Set-SbecLogSession.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/booteventcollector/Set-SbecLogSession.yml) | :warning:Warning | | [Details](#user-content-0d31055f-6c586aaf)
[docset/windows/booteventcollector/Save-SbecLogSession.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/booteventcollector/Save-SbecLogSession.yml) | :warning:Warning | | [Details](#user-content-15bf087f-6c586aaf)
[docset/windows/bitstransfer/Remove-BitsTransfer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitstransfer/Remove-BitsTransfer.yml) | :warning:Warning | | [Details](#user-content-bfcd3e94-6c586aaf)
[docset/windows/branchcache/Export-BCSecretKey.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/branchcache/Export-BCSecretKey.yml) | :warning:Warning | | [Details](#user-content-46a46005-6c586aaf)
[docset/windows/branchcache/Set-BCMinSMBLatency.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/branchcache/Set-BCMinSMBLatency.yml) | :warning:Warning | | [Details](#user-content-1034783c-6c586aaf)
[docset/windows/appx/index.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/index.yml) | :warning:Warning | | [Details](#user-content-18f65446-6c586aaf)
[docset/windows/deduplication/Disable-DedupVolume.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/deduplication/Disable-DedupVolume.yml) | :warning:Warning | | [Details](#user-content-ad400b58-6c586aaf)
[docset/windows/branchcache/Publish-BCWebContent.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/branchcache/Publish-BCWebContent.yml) | :warning:Warning | | [Details](#user-content-765a4d6e-6c586aaf)
[docset/windows/deduplication/Get-DedupStatus.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/deduplication/Get-DedupStatus.yml) | :warning:Warning | | [Details](#user-content-ba22406e-6c586aaf)
[docset/windows/booteventcollector/index.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/booteventcollector/index.yml) | :warning:Warning | | [Details](#user-content-a51361b4-6c586aaf)
[docset/windows/dfsn/Get-DfsnAccess.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/dfsn/Get-DfsnAccess.yml) | :warning:Warning | | [Details](#user-content-2feb9b48-6c586aaf)
[docset/windows/branchcache/Get-BCHostedCacheServerConfiguration.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/branchcache/Get-BCHostedCacheServerConfiguration.yml) | :warning:Warning | | [Details](#user-content-21e436bd-6c586aaf)
[docset/windows/clusterawareupdating/Get-CauClusterRole.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/clusterawareupdating/Get-CauClusterRole.yml) | :warning:Warning | | [Details](#user-content-de3bbad1-6c586aaf)
[docset/windows/bitstransfer/Complete-BitsTransfer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitstransfer/Complete-BitsTransfer.yml) | :warning:Warning | | [Details](#user-content-f343cd21-6c586aaf)
[docset/windows/clusterawareupdating/Get-CauReport.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/clusterawareupdating/Get-CauReport.yml) | :warning:Warning | | [Details](#user-content-13f2587e-6c586aaf)
[docset/windows/booteventcollector/Stop-SbecLogSession.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/booteventcollector/Stop-SbecLogSession.yml) | :warning:Warning | | [Details](#user-content-054cd54b-6c586aaf)
[docset/windows/bitstransfer/Add-BitsFile.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitstransfer/Add-BitsFile.yml) | :warning:Warning | | [Details](#user-content-34d98ad7-6c586aaf)
[docset/windows/dcbqos/Get-NetQosTrafficClass.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/dcbqos/Get-NetQosTrafficClass.yml) | :warning:Warning | | [Details](#user-content-de1c4e75-6c586aaf)
[docset/windows/branchcache/Get-BCHashCache.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/branchcache/Get-BCHashCache.yml) | :warning:Warning | | [Details](#user-content-1a0f1774-6c586aaf)
[docset/windows/bitstransfer/Resume-BitsTransfer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitstransfer/Resume-BitsTransfer.yml) | :warning:Warning | | [Details](#user-content-bd2da671-6c586aaf)
[docset/windows/devicehealthattestation/Get-DHASActiveEncryptionCertificate.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/devicehealthattestation/Get-DHASActiveEncryptionCertificate.yml) | :warning:Warning | | [Details](#user-content-4a0c1b5c-6c586aaf)
[docset/windows/bitlocker/Suspend-BitLocker.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitlocker/Suspend-BitLocker.yml) | :warning:Warning | | [Details](#user-content-23c11707-6c586aaf)
[docset/windows/bitstransfer/Suspend-BitsTransfer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/bitstransfer/Suspend-BitsTransfer.yml) | :warning:Warning | | [Details](#user-content-12cee673-6c586aaf)
[docset/windows/dcbqos/Enable-NetQosFlowControl.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/dcbqos/Enable-NetQosFlowControl.yml) | :warning:Warning | | [Details](#user-content-db2ca793-6c586aaf)
[docset/windows/branchcache/Get-BCClientConfiguration.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/branchcache/Get-BCClientConfiguration.yml) | :warning:Warning | | [Details](#user-content-f56000ca-6c586aaf)
[docset/windows/devicehealthattestation/Get-DHASActiveSigningCertificate.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/devicehealthattestation/Get-DHASActiveSigningCertificate.yml) | :warning:Warning | | [Details](#user-content-de0072c8-6c586aaf)
[docset/windows/appx/Get-AppxDefaultVolume.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RP [...]

2020-09-29 19:43 UTC, opbld31 commented
Docs Build status updates of commit _[836b1d2](https://github.com/RDMacLachlan/windows-powershell-docs/commits/836b1d2bc630b3c9d957161c3c1b83c9ff582019)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :x:Error | | [Details](#user-content-f0af4870-f1cef390)
[docset/windows/appvclient/Unpublish-AppvClientPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Unpublish-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-6e07b68b-f1cef390)
[docset/windows/appvclient/Get-AppvClientPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-128c2707-f1cef390)
[docset/windows/appvsequencer/index.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/index.yml) | :warning:Warning | | [Details](#user-content-9aa80669-f1cef390)
[docset/windows/appvsequencer/Expand-AppvSequencerPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/Expand-AppvSequencerPackage.yml) | :warning:Warning | | [Details](#user-content-a0426e85-f1cef390)
[docset/windows/appvsequencer/New-AppvSequencerPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvSequencerPackage.yml) | :warning:Warning | | [Details](#user-content-d8d91fe1-f1cef390)
[docset/windows/appvclient/Get-AppvPublishingServer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvPublishingServer.yml) | :warning:Warning | | [Details](#user-content-f45127e3-f1cef390)
[docset/windows/appvclient/Get-AppvClientMode.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvClientMode.yml) | :warning:Warning | | [Details](#user-content-b7fe3790-f1cef390)
[docset/windows/adfs/Disable-AdfsApplicationGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Disable-AdfsApplicationGroup.yml) | :warning:Warning | | [Details](#user-content-f8ccc0c9-f1cef390)
[docset/windows/adfs/Get-AdfsSyncProperties.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Get-AdfsSyncProperties.yml) | :warning:Warning | | [Details](#user-content-26e53341-f1cef390)
[docset/windows/adfs/Disable-AdfsEndpoint.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-5b0f7ac7-f1cef390)
[docset/windows/adfs/Get-AdfsFarmInformation.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Get-AdfsFarmInformation.yml) | :warning:Warning | | [Details](#user-content-c807312f-f1cef390)
[docset/windows/adfs/Disable-AdfsLocalClaimsProviderTrust.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Disable-AdfsLocalClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-853e65fb-f1cef390)
[docset/windows/adfs/Add-AdfsNativeClientApplication.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Add-AdfsNativeClientApplication.yml) | :warning:Warning | | [Details](#user-content-6340661c-f1cef390)
[docset/windows/adfs/Get-AdfsApplicationGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Get-AdfsApplicationGroup.yml) | :warning:Warning | | [Details](#user-content-0c6cdbd2-f1cef390)
[docset/windows/adfs/Enable-AdfsApplicationGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Enable-AdfsApplicationGroup.yml) | :warning:Warning | | [Details](#user-content-fc398f2c-f1cef390)
[docset/windows/adfs/Get-AdfsLocalClaimsProviderTrust.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Get-AdfsLocalClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-392dc73d-f1cef390)
[docset/windows/adfs/Add-AdfsLocalClaimsProviderTrust.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Add-AdfsLocalClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-1a54abe1-f1cef390)
[docset/windows/adfs/Get-AdfsWebConfig.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Get-AdfsWebConfig.yml) | :warning:Warning | | [Details](#user-content-081e2ff9-f1cef390)
[docset/windows/adfs/Remove-AdfsFarmNode.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-ae38266e-f1cef390)
[docset/windows/adfs/Get-AdfsNativeClientApplication.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Get-AdfsNativeClientApplication.yml) | :warning:Warning | | [Details](#user-content-9e640236-f1cef390)
[docset/windows/adfs/Set-AdfsGlobalWebContent.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Set-AdfsGlobalWebContent.yml) | :warning:Warning | | [Details](#user-content-76910ac4-f1cef390)
[docset/windows/adfs/Enable-AdfsLocalClaimsProviderTrust.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Enable-AdfsLocalClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-c80e8180-f1cef390)
[docset/windows/adfs/Remove-AdfsApplicationGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Remove-AdfsApplicationGroup.yml) | :warning:Warning | | [Details](#user-content-1cd754a9-f1cef390)
[docset/windows/adfs/New-AdfsApplicationGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/New-AdfsApplicationGroup.yml) | :warning:Warning | | [Details](#user-content-cf9e4754-f1cef390)
[docset/windows/appbackgroundtask/Get-AppBackgroundTask.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appbackgroundtask/Get-AppBackgroundTask.yml) | :warning:Warning | | [Details](#user-content-7b178c5b-f1cef390)
[docset/windows/adfs/Enable-AdfsEndpoint.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-c0b731aa-f1cef390)
[docset/windows/adrmsadmin/Uninstall-RmsMfgEnrollment.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adrmsadmin/Uninstall-RmsMfgEnrollment.yml) | :warning:Warning | | [Details](#user-content-267db0e7-f1cef390)
[docset/windows/adrmsadmin/Export-RmsTPD.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/adrmsadmin/Export-RmsTPD.yml) | :warning:Warning | | [Details](#user-content-dbb41ba6-f1cef390)
[docset/windows/appvclient/Repair-AppvClientPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/app [...]

2020-09-30 01:15 UTC, JohanFreelancer9 commented on docset/windows/appx/Reset-AppxPackage.md
> +Starting at Windows 10 Insider Preview Build 20215 you get access to the `Rest-AppxPackage` PowerShell Cmdlet for use in resetting your installed Windows Apps.
```suggestion
Starting at Windows 10 Insider Preview Build 20215 you get access to the `Rest-AppxPackage` PowerShell Cmdlet for use in resetting your installed Windows apps.
```

2020-10-21 16:57 UTC, e0i commented
Re-opening to regenerate build.

2020-10-21 17:00 UTC, opbld32 commented
Docs Build status updates of commit _[836b1d2](https://github.com/RDMacLachlan/windows-powershell-docs/commits/836b1d2bc630b3c9d957161c3c1b83c9ff582019)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :x:Error | | [Details](#user-content-f0af4870-38677928)
[docset/mdop/mbam/get-mbamtpmownerpassword.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamtpmownerpassword.md) | :warning:Warning | | [Details](#user-content-724a1b80-38677928)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvPackageAccelerator.yml) | :warning:Warning | | [Details](#user-content-b5b1c41d-38677928)
[docset/mdop/mbam/get-mbambitlockerrecoverykey.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbambitlockerrecoverykey.md) | :warning:Warning | | [Details](#user-content-1a2741fb-38677928)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-38677928)
[docset/mdop/mbam/test-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/test-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-a1afc1d1-38677928)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-38677928)
[docset/mdop/mbam/get-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamreport.md) | :warning:Warning | | [Details](#user-content-e9525729-38677928)
[docset/mdop/appvserver/grant-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/grant-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-0b27961f-38677928)
[docset/windows/appvclient/Unpublish-AppvClientPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Unpublish-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-6e07b68b-38677928)
[docset/mdop/appvserver/new-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/new-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-899a17da-38677928)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-38677928)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-38677928)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-38677928)
[docset/windows/appvsequencer/Update-AppvSequencerPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/Update-AppvSequencerPackage.yml) | :warning:Warning | | [Details](#user-content-52ac2567-38677928)
[docset/mdop/agpm/unlock-controlledgpo.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/agpm/unlock-controlledgpo.md) | :warning:Warning | | [Details](#user-content-0f6d474a-38677928)
[docset/mdop/mbam/disable-mbamwebapplication.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/disable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-121c5d3d-38677928)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-38677928)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-38677928)
[docset/mdop/mbam/write-mbamrecoveryinformation.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/write-mbamrecoveryinformation.md) | :warning:Warning | | [Details](#user-content-e43a9859-38677928)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-38677928)
[docset/mdop/medv/export-medvconfiguration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/medv/export-medvconfiguration.md) | :warning:Warning | | [Details](#user-content-1167a531-38677928)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-38677928)
[docset/mdop/mbam/enable-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/enable-mbamreport.md) | :warning:Warning | | [Details](#user-content-2a4312c1-38677928)
[docset/mdop/mbam/test-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/test-mbamreport.md) | :warning:Warning | | [Details](#user-content-835b6b92-38677928)
[docset/windows/appvsequencer/New-AppvSequencerPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvSequencerPackage.yml) | :warning:Warning | | [Details](#user-content-d8d91fe1-38677928)
[docset/mdop/mbam/disable-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/disable-mbamreport.md) | :warning:Warning | | [Details](#user-content-1757a059-38677928)
[docset/mdop/mbam/get-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-1b2b6a55-38677928)
[docset/mdop/mbam/enable-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/enable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-b1bb4167-38677928)
[docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md) | :warning:War [...]

2020-10-21 17:51 UTC, opbld31 commented
Docs Build status updates of commit _[8ee472b](https://github.com/RDMacLachlan/windows-powershell-docs/commits/8ee472b21c3c50022fa796192fc1c3ef9aa7def8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :x:Error | | [Details](#user-content-f0af4870-c54eb8a8)
[docset/mdop/appvserver/get-appvserverpackagedeploymentconfiguration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverpackagedeploymentconfiguration.md) | :warning:Warning | | [Details](#user-content-31105460-c54eb8a8)
[docset/mdop/mbam/write-mbamrecoveryinformation.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/write-mbamrecoveryinformation.md) | :warning:Warning | | [Details](#user-content-e43a9859-c54eb8a8)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-c54eb8a8)
[docset/windows/appvclient/Get-AppvClientConnectionGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvClientConnectionGroup.yml) | :warning:Warning | | [Details](#user-content-18012200-c54eb8a8)
[docset/mdop/agpm/unlock-controlledgpo.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/agpm/unlock-controlledgpo.md) | :warning:Warning | | [Details](#user-content-0f6d474a-c54eb8a8)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-c54eb8a8)
[docset/mdop/mbam/enable-mbamwebapplication.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/enable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-39983848-c54eb8a8)
[docset/mdop/mbam/get-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-1b2b6a55-c54eb8a8)
[docset/mdop/mbam/get-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamreport.md) | :warning:Warning | | [Details](#user-content-e9525729-c54eb8a8)
[docset/mdop/uev/enable-uevtemplate.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/uev/enable-uevtemplate.md) | :warning:Warning | | [Details](#user-content-bfc75929-c54eb8a8)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-c54eb8a8)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvPackageAccelerator.yml) | :warning:Warning | | [Details](#user-content-b5b1c41d-c54eb8a8)
[docset/mdop/medv/export-medvconfiguration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/medv/export-medvconfiguration.md) | :warning:Warning | | [Details](#user-content-1167a531-c54eb8a8)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-c54eb8a8)
[docset/mdop/mbam/get-mbambitlockerrecoverykey.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbambitlockerrecoverykey.md) | :warning:Warning | | [Details](#user-content-1a2741fb-c54eb8a8)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-c54eb8a8)
[docset/mdop/appvserver/grant-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/grant-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-d5ff5896-c54eb8a8)
[docset/mdop/mbam/write-mbamcomputeruser.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/write-mbamcomputeruser.md) | :warning:Warning | | [Details](#user-content-d5e1fb42-c54eb8a8)
[docset/mdop/uev/import-uevconfiguration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/uev/import-uevconfiguration.md) | :warning:Warning | | [Details](#user-content-3cfeecd7-c54eb8a8)
[docset/mdop/mbam/get-mbamwebapplication.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-36901c15-c54eb8a8)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/import-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ae2d5b45-c54eb8a8)
[docset/mdop/appvclient/get-appvclientconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-88c6e250-c54eb8a8)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-c54eb8a8)
[docset/mdop/mbam/read-adtpminformation.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/read-adtpminformation.md) | :warning:Warning | | [Details](#user-content-db054964-c54eb8a8)
[docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-22c33323-c54eb8a8)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-c54eb8a8)
[docset/mdop/mbam/test-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/test-mbamreport.md) | :warning:Warning | | [Details](#user-content-835b6b92-c54eb8a8)
[docset/windows/appvclient/Unpublish-AppvClientPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Unpublish-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-6e07b68b-c54eb8a8)
[docset/mdop/uev/disable-uevtemplate.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/uev/disable-uevtemplate.md) | :warning:Warning | [...]

2020-10-21 18:03 UTC, opbld32 commented
Docs Build status updates of commit _[017640c](https://github.com/RDMacLachlan/windows-powershell-docs/commits/017640c19c9fa3291ef0f4a7f9ffc08de2ad57ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :x:Error | | [Details](#user-content-f0af4870-a239b82b)
[docset/mdop/appvclient/stop-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/stop-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-b800b10e-a239b82b)
[docset/mdop/appvclient/get-appvclientconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-88c6e250-a239b82b)
[docset/windows/appvclient/Get-AppvPublishingServer.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvPublishingServer.yml) | :warning:Warning | | [Details](#user-content-f45127e3-a239b82b)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-a239b82b)
[docset/mdop/appvclient/get-appvvirtualprocess.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvvirtualprocess.md) | :warning:Warning | | [Details](#user-content-7b156128-a239b82b)
[docset/windows/appvclient/Set-AppvClientConfiguration.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Set-AppvClientConfiguration.yml) | :warning:Warning | | [Details](#user-content-106afec2-a239b82b)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-a239b82b)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-a239b82b)
[docset/mdop/appvclient/remove-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/remove-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-9db775ad-a239b82b)
[docset/mdop/appvclient/set-appvpublishingserver.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/set-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-85260d09-a239b82b)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/import-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ae2d5b45-a239b82b)
[docset/windows/appvclient/Get-AppvVirtualProcess.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvVirtualProcess.yml) | :warning:Warning | | [Details](#user-content-af7f020e-a239b82b)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvPackageAccelerator.yml) | :warning:Warning | | [Details](#user-content-b5b1c41d-a239b82b)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-a239b82b)
[docset/windows/appvclient/Mount-AppvClientConnectionGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Mount-AppvClientConnectionGroup.yml) | :warning:Warning | | [Details](#user-content-9ead9401-a239b82b)
[docset/mdop/agpm/publish-controlledgpo.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/agpm/publish-controlledgpo.md) | :warning:Warning | | [Details](#user-content-f266a5c0-a239b82b)
[docset/mdop/appv/convertfrom-appvlegacypackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appv/convertfrom-appvlegacypackage.md) | :warning:Warning | | [Details](#user-content-40104fbc-a239b82b)
[docset/windows/appvclient/Get-AppvClientConnectionGroup.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvClientConnectionGroup.yml) | :warning:Warning | | [Details](#user-content-18012200-a239b82b)
[docset/windows/appvclient/Stop-AppvClientPackage.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Stop-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-4644f30f-a239b82b)
[docset/mdop/appvclient/send-appvclientreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/send-appvclientreport.md) | :warning:Warning | | [Details](#user-content-b8a57e87-a239b82b)
[docset/mdop/appvclient/sync-appvpublishingserver.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/sync-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-10723e77-a239b82b)
[docset/mdop/appvserver/remove-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-a88eaaf8-a239b82b)
[docset/mdop/appvserver/grant-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/grant-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-0b27961f-a239b82b)
[docset/windows/appvclient/Send-AppvClientReport.yml](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Send-AppvClientReport.yml) | :warning:Warning | | [Details](#user-content-8b38f455-a239b82b)
[docset/mdop/appvclient/get-appvclientconfiguration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvclientconfiguration.md) | :warning:Warning | | [Details](#user-content-9ae7de48-a239b82b)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-a239b82b)
[docset/mdop/mbam/read-adrecoveryinformation.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/read-adrecoveryinformation.md) | :warning:Warning | | [Details](#user-content-6d1d1686-a239b82b)
[docset/mdop/mbam/get-mbamtpmownerpassword.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamtpmownerpassword.md) | :warning:Warning | | [Details](#user-content-724a1b80-a239b82b)
[docset/mdop/mbam/test-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPa [...]

2020-10-21 18:24 UTC, opbld31 commented
Docs Build status updates of commit _[40a546a](https://github.com/RDMacLachlan/windows-powershell-docs/commits/40a546aa47478d4d40553fbf0bfa89c59c447cc9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :warning:Warning | | [Details](#user-content-f0af4870-39341bb7)
[docset/mdop/appvserver/set-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/set-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-d1fd1e49-39341bb7)
[docset/mdop/appvclient/get-appvclientmode.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvclientmode.md) | :warning:Warning | | [Details](#user-content-5aa92fd3-39341bb7)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-39341bb7)
[docset/mdop/mbam/get-mbamwebapplication.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-36901c15-39341bb7)
[docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-6a8cd355-39341bb7)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-39341bb7)
[docset/mdop/appv/convertfrom-appvlegacypackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appv/convertfrom-appvlegacypackage.md) | :warning:Warning | | [Details](#user-content-40104fbc-39341bb7)
[docset/mdop/mbam/read-adrecoveryinformation.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/read-adrecoveryinformation.md) | :warning:Warning | | [Details](#user-content-6d1d1686-39341bb7)
[docset/windows/appvclient/Stop-AppvClientPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Stop-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-f7ffc343-39341bb7)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-39341bb7)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-39341bb7)
[docset/mdop/mbam/enable-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/enable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-b1bb4167-39341bb7)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-39341bb7)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-39341bb7)
[docset/windows/appvclient/Unpublish-AppvClientPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Unpublish-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-4dbcd802-39341bb7)
[docset/windows/appvsequencer/Expand-AppvSequencerPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/Expand-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-93a1ef35-39341bb7)
[docset/windows/appvsequencer/New-AppvSequencerPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-76bddda7-39341bb7)
[docset/mdop/mbam/get-mbamreport.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamreport.md) | :warning:Warning | | [Details](#user-content-e9525729-39341bb7)
[docset/mdop/uev/clear-uevappxpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/uev/clear-uevappxpackage.md) | :warning:Warning | | [Details](#user-content-706a39a5-39341bb7)
[docset/mdop/uev/enable-uevtemplate.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/uev/enable-uevtemplate.md) | :warning:Warning | | [Details](#user-content-bfc75929-39341bb7)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-39341bb7)
[docset/mdop/appvclient/get-appvclientapplication.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvclientapplication.md) | :warning:Warning | | [Details](#user-content-936eb549-39341bb7)
[docset/windows/appvclient/Get-AppvClientMode.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvClientMode.md) | :warning:Warning | | [Details](#user-content-93f5a75b-39341bb7)
[docset/windows/uev/Enable-UevTemplate.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/uev/Enable-UevTemplate.md) | :warning:Warning | | [Details](#user-content-3e1bd6c6-39341bb7)
[docset/mdop/mbam/read-adtpminformation.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/read-adtpminformation.md) | :warning:Warning | | [Details](#user-content-db054964-39341bb7)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-39341bb7)
[docset/mdop/mbam/test-mbamdatabase.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/test-mbamdatabase.md) | :warning:Warning | | [Details](#user-content-b11bdd91-39341bb7)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-39341bb7)
[docset/windows/uev/Clear-UevAppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/uev/Clear-UevAppxPackage.md) | :warning:Warning | | [Details](#user-content-5aefabb7-39341bb7)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/impor [...]

2020-10-21 18:25 UTC, RDMacLachlan commented
Resolved error in the article.

2020-10-21 18:30 UTC, opbld33 commented
Docs Build status updates of commit _[34b57d7](https://github.com/RDMacLachlan/windows-powershell-docs/commits/34b57d739ff94f82be5d58ced54ee976dd1cb449)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :warning:Warning | | [Details](#user-content-f0af4870-b7988a6c)
[docset/mdop/appvclient/stop-appvclientconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/stop-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-72e2c169-b7988a6c)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/import-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ae2d5b45-b7988a6c)
[docset/windows/appvsequencer/New-AppvSequencerPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-76bddda7-b7988a6c)
[docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md) | :warning:Warning | | [Details](#user-content-96de03ef-b7988a6c)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-b7988a6c)
[docset/mdop/appvserver/remove-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-a88eaaf8-b7988a6c)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-b7988a6c)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-b7988a6c)
[docset/windows/appvclient/Remove-AppvClientConnectionGroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Remove-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-404478c9-b7988a6c)
[docset/mdop/appvclient/get-appvpublishingserver.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-aff0e31e-b7988a6c)
[docset/windows/appvclient/Sync-AppvPublishingServer.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Sync-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-4b9a6faf-b7988a6c)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-b7988a6c)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-b7988a6c)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/New-AppvPackageAccelerator.md) | :warning:Warning | | [Details](#user-content-ff826ff1-b7988a6c)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-b7988a6c)
[docset/mdop/appvserver/new-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/new-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-899a17da-b7988a6c)
[docset/mdop/agpm/get-controlledgpo.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/agpm/get-controlledgpo.md) | :warning:Warning | | [Details](#user-content-8529f522-b7988a6c)
[docset/mdop/appvclient/get-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/get-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-0b6ba1b7-b7988a6c)
[docset/mdop/appvserver/set-appvserverconnectiongroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/set-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-0219beb2-b7988a6c)
[docset/mdop/appvclient/mount-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/mount-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-46fdce12-b7988a6c)
[docset/windows/appvclient/Get-AppvPublishingServer.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Get-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-bf6c58c7-b7988a6c)
[docset/mdop/mbam/test-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/test-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-a1afc1d1-b7988a6c)
[docset/mdop/appvserver/set-appvserverpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvserver/set-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-d1fd1e49-b7988a6c)
[docset/mdop/mbam/write-mbamcomputeruser.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/write-mbamcomputeruser.md) | :warning:Warning | | [Details](#user-content-d5e1fb42-b7988a6c)
[docset/windows/appvsequencer/Update-AppvSequencerPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvsequencer/Update-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-abffa8f3-b7988a6c)
[docset/windows/appvclient/Remove-AppvClientPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Remove-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-72400978-b7988a6c)
[docset/mdop/appvclient/remove-appvclientpackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/appvclient/remove-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-9db775ad-b7988a6c)
[docset/mdop/mbam/get-mbamcmintegration.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/mdop/mbam/get-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-1b2b6a55-b7988a6c)
[docset/windows/appvclient/Stop-AppvClientConnectionGroup.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appvclient/Stop-AppvClientConnectionGroup.md) | :warning:Warning  [...]

2020-11-17 17:20 UTC, e0i commented
Closing and re-opening to refresh validation checks.

2020-11-17 17:25 UTC, opbld31 commented
Docs Build status updates of commit _[34b57d7](https://github.com/RDMacLachlan/windows-powershell-docs/commits/34b57d739ff94f82be5d58ced54ee976dd1cb449)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :warning:Warning | | [Details](#user-content-f0af4870-108dc90c)

<a id="f0af4870-108dc90c"></a>
### [docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md)
 - **Line 0, Column 0**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.technology': 'powershell-windows' is not valid with 'ms.prod' value 'w10'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171721075210-2123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2n5eRL%2B0NIj4DsYRG03Npyh9yz2Z8M4VKokoA5dJ53Y%3D&st=2020-11-17T17%3A20%3A31Z&se=2020-12-18T17%3A25%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 15:39 UTC, tseward approved these changes

2020-12-30 15:35 UTC, opbld30 commented
Docs Build status updates of commit _[34b57d7](https://github.com/RDMacLachlan/windows-powershell-docs/commits/34b57d739ff94f82be5d58ced54ee976dd1cb449)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/appx/reset-appxpackage?view=win10-ps&branch=pr-en-us-2123) (win10-ps) | [Details](#user-content-f0af4870-3bd232d6)

<a id="f0af4870-3bd232d6"></a>
### [docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md)
 - **Line 0, Column 0**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.technology': 'powershell-windows' is not valid with 'ms.prod' value 'w10'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012301531265742-2123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ErS2LHJJMn8c8P%2F4rmakGTUcf6NNn5EYTOcnbUnpL3c%3D&st=2020-12-30T15%3A30%3A22Z&se=2021-01-30T15%3A35%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-07 19:26 UTC, RDMacLachlan commented
Following the reference guide I have updated the ms.technology from "powershell-windows" to "windows". Should this change be made to all current articles in this repository?

2021-02-10 10:11 UTC, dariomws commented
@RDMacLachlan thank you for your contribution.

Yes, I think it must be changed in all current articles in this repository, but give me some time to discuss it with mi colleagues.

2021-02-10 12:35 UTC, get-itips commented on docset/windows/appx/Reset-AppxPackage.md
> +Starting at Windows 10 Insider Preview Build 20215 you get access to the `Rest-AppxPackage` PowerShell Cmdlet for use in resetting your installed Windows Apps.
```suggestion
Starting at Windows 10 Insider Preview Build 20215 you get access to the `Reset-AppxPackage` PowerShell Cmdlet for use in resetting your installed Windows Apps.
```

2021-02-10 16:07 UTC, tseward approved these changes
Approved pending @get-itips suggestion.

2021-02-10 17:14 UTC, opbld33 commented
Docs Build status updates of commit _[fe43735](https://github.com/RDMacLachlan/windows-powershell-docs/commits/fe43735a663fb062ab8ee6668bb2ed8592b1987d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/appx/reset-appxpackage?view=win10-ps&branch=pr-en-us-2123) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102101711055324-2123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9xvR28TFkk2iaI6e%2F%2FCb0zkBCtQ4GyZdRATSoLQvJtA%3D&st=2021-02-10T17%3A09%3A56Z&se=2021-03-13T17%3A14%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 17:58 UTC, dariomws approved these changes

2021-02-10 18:30 UTC, opbld33 commented
Docs Build status updates of commit _[09d8664](https://github.com/RDMacLachlan/windows-powershell-docs/commits/09d8664690b8321c93ba90bc20426c61655e558c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Reset-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/RPM--Reset-AppxPackage/docset/windows/appx/Reset-AppxPackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/appx/reset-appxpackage?view=win10-ps&branch=pr-en-us-2123) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102101826196160-2123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ykL31LMHcUmIFPQTkhuasHWDv3pqK8QTPBMds0t%2BOss%3D&st=2021-02-10T18%3A25%3A02Z&se=2021-03-13T18%3A30%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:30 UTC, merged