Resolves #2063
MicrosoftDocs/windows-powershell-docs pull request #2130
Opened 2020-09-18 18:41 UTC by velkovb

Add ssl example.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2063

2020-09-18 18:47 UTC, opbld32 commented
Docs Build status updates of commit _[9119a73](https://github.com/velkovb/windows-powershell-docs/commits/9119a73c7db52138ed70b796154eb4306180e367)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009181841193398-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tMQ%2FiXC74fO8M%2FYGIfKxdf1GrwWDPP5h2l0iflDLrrE%3D&st=2020-09-18T18%3A42%3A56Z&se=2020-10-19T18%3A47%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-18 18:54 UTC, opbld33 commented
Docs Build status updates of commit _[3ed1e1a](https://github.com/velkovb/windows-powershell-docs/commits/3ed1e1a3cc0854c121f3974bad57c70e077f2808)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009181843436885-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gc5xmQcx%2B1gG7hRP%2F8eh4Vt3ALyA4EKgGBxp2jBHX4g%3D&st=2020-09-18T18%3A49%3A40Z&se=2020-10-19T18%3A54%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 13:45 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR.

cc @JohanFreelancer9 for copy editing.

Thank you.

2020-09-23 14:27 UTC, dariomws requested changes

2020-09-23 14:27 UTC, dariomws commented on docset/winserver2012-ps/webadminstration/New-WebBinding.md
> +This command creates an SSL binding on the default website.s
```suggestion
This command creates an SSL binding on the default website.
```

2020-09-23 14:40 UTC, get-itips reviewed
i am ok once suggestions are applied

2020-09-23 16:17 UTC, tseward commented
Also OK once the changes are applied.

2020-09-23 19:04 UTC, opbld32 commented
Docs Build status updates of commit _[3b17eb6](https://github.com/velkovb/windows-powershell-docs/commits/3b17eb64e734d9edcb36937d8a2cc9f4b40581a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009231857453251-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=86uhX1mY5vsjCyjOHvBssTm1CrNuL%2BLaFbxjGC52mNM%3D&st=2020-09-23T18%3A59%3A16Z&se=2020-10-24T19%3A04%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 19:10 UTC, opbld33 commented
Docs Build status updates of commit _[3b17eb6](https://github.com/velkovb/windows-powershell-docs/commits/3b17eb64e734d9edcb36937d8a2cc9f4b40581a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C23%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009231857554588-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fMkVDjkoMIvha9rSiyVr9%2FHUKO4mG0aZFbXouESDeaw%3D&st=2020-09-23T19%3A05%3A55Z&se=2020-10-24T19%3A10%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-23 19:21 UTC, dariomws approved these changes

2020-09-24 01:18 UTC, get-itips approved these changes

2020-09-24 01:35 UTC, tseward commented
Actually, revisiting this -- the cmdlet examples don't show how to get into the IIS drive. Should we instead just use PS C:\> for the examples?

2020-09-24 02:31 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/webadministration/New-WebBinding.md
> +### Example 2: Add a new ssl site binding
```suggestion
### Example 2: Add a new SSL site binding
```

2020-09-24 02:32 UTC, JohanFreelancer9 commented on docset/windows/webadministration/New-WebBinding.md
> +### Example 2: Add a new ssl site binding
```suggestion
### Example 2: Add a new SSL site binding
```

2020-09-24 02:34 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/webadminstration/New-WebBinding.md
> +### Example 2: Add a new ssl site binding
```suggestion
### Example 2: Add a new SSL site binding
```

2020-09-24 02:38 UTC, JohanFreelancer9 requested changes
Copy review - please also see Trevor's comment.

2020-09-24 05:59 UTC, opbld30 commented
Docs Build status updates of commit _[2f40f1b](https://github.com/velkovb/windows-powershell-docs/commits/2f40f1b6939f0cf7310ef5cde25df36589d4ecb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009240552078807-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2XSYMAzBl47EVwd3YSrfbmaXpNmITPaYsSNj1%2B26Yos%3D&st=2020-09-24T05%3A54%3A05Z&se=2020-10-25T05%3A59%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[2f40f1b](https://github.com/velkovb/windows-powershell-docs/commits/2f40f1b6939f0cf7310ef5cde25df36589d4ecb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009240552186762-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BxwjPemr8L9UvwGJpuf3xxYKJVIj7JjK5IUZqhEnXV8%3D&st=2020-09-24T06%3A00%3A12Z&se=2020-10-25T06%3A05%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-24 06:20 UTC, JohanFreelancer9 approved these changes

2020-09-29 18:03 UTC, opbld31 commented
Docs Build status updates of commit _[cdb1325](https://github.com/velkovb/windows-powershell-docs/commits/cdb1325877320066f5d6442e739e0e20c9d8a93e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291758516724-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RQRU5wXNL78C%2F58lXdZgPRCDEbfOh4bcjOcqf%2Bu5Djg%3D&st=2020-09-29T17%3A58%3A02Z&se=2020-10-30T18%3A03%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 18:08 UTC, opbld33 commented
Docs Build status updates of commit _[ee97c80](https://github.com/velkovb/windows-powershell-docs/commits/ee97c80287f97092a070267d0c5e2d9e8dbf3e62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/windows/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012-ps/webadminstration/New-WebBinding.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebBinding.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2063-add-example/docset/winserver2012r2-ps/webadministration/New-WebBinding.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291803357936-2130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4ZSHyy2TSNnic4Kj53npavWxY5N2alNi5IE8mg6KpDc%3D&st=2020-09-29T18%3A03%3A10Z&se=2020-10-30T18%3A08%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 18:08 UTC, merged