Update Get-ADUser.md
MicrosoftDocs/windows-powershell-docs pull request #2145
Opened 2020-09-24 18:53 UTC by doctordns

1. Added an example using an LDAP Filter to get all enabled users.
2. Added PowerShell to the example's code fencing
3. Removed figure tense to improve readability
4. added a space between the prompt and the command in all examples

2020-09-24 19:00 UTC, opbld31 commented
Docs Build status updates of commit _[9a9227e](https://github.com/doctordns/windows-powershell-docs/commits/9a9227e57c7d0b962c7ae6fb2dc23e92bbb293e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/doctordns/windows-powershell-docs/blob/patch-12/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009241853356903-2145%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CPO7CSPlPfN6yhibfBxeoz6Cx63dobL0r7iWg4tKhAY%3D&st=2020-09-24T18%3A55%3A04Z&se=2020-10-25T19%3A00%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 17:31 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-29 17:31 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-09-29 19:24 UTC, dariomws requested changes
Thank you @doctordns for this contribution!

I think we should add the same example to 2012 R2 and 2016 versions.

2020-09-29 19:24 UTC, dariomws commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +-----------
```suggestion
```
Thank you @doctordns for this contribution!

Let's remove these lines in the examples.

2020-09-29 19:24 UTC, dariomws commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +- If none of the previous cases apply, the Partition parameter does not take any default value.
```suggestion
- If none of the previous cases applies, the Partition parameter does not take any default value.
```

2020-09-29 19:24 UTC, dariomws commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +Note that rules listed first are evaluated first and once a default value can be determined, no further rules is evaluated.
```suggestion
Note that rules listed first are evaluated first, and once a default value can be determined, no further rules are evaluated.
```

2020-09-29 19:24 UTC, dariomws commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +- If none of the previous cases apply, the default value of Partition is set to the default partition or naming context of the target domain.
```suggestion
- If none of the previous cases applies, the default value of Partition is set to the default partition or naming context of the target domain.
```

2020-09-29 20:09 UTC, get-itips reviewed
I am ok once suggestions are applied.

2020-09-29 20:15 UTC, tseward commented
Also approved once changes are implemented.

2020-09-30 00:37 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +- If the target AD LDS instance has a default naming context, the default value of Partition is set to the default naming context.  To specify a default naming context for an AD LDS environment, set
```suggestion
- If the target AD LDS instance has a default naming context, the default value of Partition is set to the default naming context. To specify a default naming context for an AD LDS environment, set the msDS-defaultNamingContext property of the Active Directory directory service agent (DSA) object (nTDSDSA) for the AD LDS instance.
```

2020-09-30 00:46 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +Get all user accounts in AD that are enabled, using an LDAP filter.
```suggestion
Get all user accounts in Active Directory that are enabled, using an LDAP filter.
```

2020-09-30 00:51 UTC, JohanFreelancer9 approved these changes
Approved with changes implemented.

2020-10-21 16:56 UTC, e0i commented
Please feel free to re-open this PR by implementing the changes suggested above, and resolving the merge conflicts and and the review is going to continue. Thank you.

2020-10-21 16:56 UTC, closed without merging