Update Set-ADReplicationSite.md
MicrosoftDocs/windows-powershell-docs pull request #2147
Opened 2020-09-24 21:05 UTC by msbemba

Corrected KCC from   Kerberos consistency checker to  Knowledge Consistency Checker.

2020-09-24 21:05 UTC, msbemba commented
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2126

2020-09-24 21:12 UTC, opbld33 commented
Docs Build status updates of commit _[b833ba1](https://github.com/msbemba/windows-powershell-docs/commits/b833ba1d0da1c97fcfdc7db83a5d22284f90ac61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-121/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009242105448877-2147%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kqFNx0I%2Bw4AqN0OqCwMSSmmnsCTtyddQ8jHUsluAGeg%3D&st=2020-09-24T21%3A07%3A09Z&se=2020-10-25T21%3A12%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 12:53 UTC, msbemba commented
@JohanFreelancer9  Please copy review

2020-09-29 15:13 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +When enabled,  this optional parameter prevents the Knowledge consistency checker (KCC) from removing connection objects that it does not need.
```suggestion
When enabled,  this optional parameter prevents the Knowledge Consistency Checker (KCC) from removing connection objects that it does not need.
```

2020-09-29 15:14 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +This parameter option prevents the Knowledge consistency checker (KCC) from excluding servers that are unreachable from the topology; that is, the KCC does use an alternate server to reroute replicat
```suggestion
This parameter option prevents the Knowledge Consistency Checker (KCC) from excluding servers that are unreachable from the topology; that is, the KCC does use an alternate server to reroute replication.
```

2020-09-29 15:16 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +When enabled, this parameter prevents the Knowledge consistency checker (KCC) from generating optimizing connections in the ring topology of intrasite replication.
```suggestion
When enabled, this parameter prevents the Knowledge Consistency Checker (KCC) from generating optimizing connections in the ring topology of intrasite replication.
```

2020-09-29 15:16 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +Implements Knowledge consistency checker (KCC) operation that is consistent with Windows Server 2003 forest functional level.
```suggestion
Implements Knowledge Consistency Checker (KCC) operation that is consistent with Windows Server 2003 forest functional level.
```

2020-09-29 15:17 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +When the forest functional level Windows Server 2003 or Windows Server 2003 interim is in effect, provides Knowledge consistency checker (KCC) control of the ability to enable or disable site link br
```suggestion
When the forest functional level Windows Server 2003 or Windows Server 2003 interim is in effect, provides Knowledge Consistency Checker (KCC) control with the ability to enable or disable site link bridging.
```

2020-09-29 15:18 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-29 17:32 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-09-29 18:55 UTC, opbld32 commented
Docs Build status updates of commit _[52cb448](https://github.com/msbemba/windows-powershell-docs/commits/52cb448a7b261bc8048304a4c9a77e1bd302dac7)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:55 UTC, opbld33 commented
Docs Build status updates of commit _[74ca004](https://github.com/msbemba/windows-powershell-docs/commits/74ca00403ac4d4857355f02f231596c8ab924deb)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[e5fcc52](https://github.com/msbemba/windows-powershell-docs/commits/e5fcc521c5e16fa0ed5d3a2c4eb8b30fc5cb68e8)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:56 UTC, opbld30 commented
Docs Build status updates of commit _[9f75c41](https://github.com/msbemba/windows-powershell-docs/commits/9f75c412db06b5439584f19b814b17a21a9db2c8)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 18:56 UTC, opbld30 commented
Docs Build status updates of commit _[3195423](https://github.com/msbemba/windows-powershell-docs/commits/31954238ec87d87939fd5c44de7dcbf2778c9eed)_: 

:clock10: **Pending**: waiting for processors ([8](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 8 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-09-29 19:00 UTC, opbld31 commented
Docs Build status updates of commit _[52cb448](https://github.com/msbemba/windows-powershell-docs/commits/52cb448a7b261bc8048304a4c9a77e1bd302dac7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-121/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291855423822-2147%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CXIrEBQV2WiL6Yx4u8b0mFdzCH6X1poBL5cryQf%2F0bg%3D&st=2020-09-29T18%3A55%3A18Z&se=2020-10-30T19%3A00%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 19:04 UTC, opbld32 commented
Docs Build status updates of commit _[e5fcc52](https://github.com/msbemba/windows-powershell-docs/commits/e5fcc521c5e16fa0ed5d3a2c4eb8b30fc5cb68e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-121/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291855552497-2147%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sx%2BRHP09e3Jt5XPW2p0h2mkFKumIZSEWviusEgehmBk%3D&st=2020-09-29T18%3A59%3A42Z&se=2020-10-30T19%3A04%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 19:25 UTC, dariomws approved these changes

2020-09-29 20:10 UTC, get-itips approved these changes

2020-09-29 20:15 UTC, tseward approved these changes

2020-09-30 00:25 UTC, JohanFreelancer9 approved these changes

2020-10-05 15:26 UTC, opbld32 commented
Docs Build status updates of commit _[37bc6de](https://github.com/msbemba/windows-powershell-docs/commits/37bc6de1fad724246236d2d6d17efed446da3d59)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-121/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010051522120912-2147%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0m0hwTieoVieHIGJ6ivMsPUhfLYmTxUrfVHEWcuteYg%3D&st=2020-10-05T15%3A21%3A41Z&se=2020-11-05T15%3A26%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 15:27 UTC, merged