Update Set-ADReplicationSite.md
MicrosoftDocs/windows-powershell-docs pull request #2153
Opened 2020-09-29 13:00 UTC by msbemba

Corrected Kerberos consistency checker  to Knowledge Consistency Checker

2020-09-29 13:00 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2020-09-29 13:04 UTC, opbld33 commented
Docs Build status updates of commit _[5215002](https://github.com/msbemba/windows-powershell-docs/commits/5215002717bd20050dd5b5b15c3c8d5c940616a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291300322042-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JiqY8ggFkYr81hCO0kVeJEfVmqifRCQfK65vCuKubOA%3D&st=2020-09-29T12%3A59%3A49Z&se=2020-10-30T13%3A04%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 13:09 UTC, opbld33 commented
Docs Build status updates of commit _[31de3d8](https://github.com/msbemba/windows-powershell-docs/commits/31de3d8c1259a6e03ce8642873da59f179b5842e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291305055426-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jsW%2BaV37s0Hcyctud%2BhSJeF4pfkDnr1WGuMkXPuAu34%3D&st=2020-09-29T13%3A04%3A13Z&se=2020-10-30T13%3A09%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 13:13 UTC, opbld33 commented
Docs Build status updates of commit _[eb6bcb4](https://github.com/msbemba/windows-powershell-docs/commits/eb6bcb4091ca2362db82ca64eded9475c6846022)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291306032613-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pywv937%2BYaZvxBCiY7c6iCE4eZ9iJClFFjcfF69pPCo%3D&st=2020-09-29T13%3A08%3A23Z&se=2020-10-30T13%3A13%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 14:56 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +When enabled,  this optional parameter prevents the Knowledge consistency checker (KCC) from removing connection objects that it does not need.
```suggestion
When enabled,  this optional parameter prevents the Knowledge Consistency Checker (KCC) from removing connection objects that it does not need.
```

2020-09-29 14:57 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +This parameter option prevents the Knowledge consistency checker (KCC) from excluding servers that are unreachable from the topology; that is, the KCC does use an alternate server to reroute replicat
```suggestion
This parameter option prevents the Knowledge Consistency Checker (KCC) from excluding servers that are unreachable from the topology; that is, the KCC does use an alternate server to reroute replication.
```

2020-09-29 14:58 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +When enabled, this parameter prevents the Knowledge consistency checker (KCC) from generating optimizing connections in the ring topology of intrasite replication.
```suggestion
When enabled, this parameter prevents the Knowledge Consistency Checker (KCC) from generating optimizing connections in the ring topology of intrasite replication.
```

2020-09-29 14:59 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +Implements Knowledge consistency checker (KCC) operation that is consistent with Windows Server 2003 forest functional level.
```suggestion
Implements Knowledge Consistency Checker (KCC) operation that is consistent with Windows Server 2003 forest functional level.
```

2020-09-29 15:00 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md
> +When the forest functional level Windows Server 2003 or Windows Server 2003 interim is in effect, provides Knowledge consistency checker (KCC) control of the ability to enable or disable site link br
```suggestion
When the forest functional level Windows Server 2003 or Windows Server 2003 interim is in effect, provides Knowledge Consistency Checker (KCC) control of the ability to enable or disable site link bridging.
```

2020-09-29 15:00 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
> +Indicates whether the cmdlet prevents the Knowledge consistency checker (KCC) that functions as the intersite topology generator (ISTG) from generating connections for intersite replication.
```suggestion
Indicates whether the cmdlet prevents the Knowledge Consistency Checker (KCC) that functions as the intersite topology generator (ISTG) from generating connections for intersite replication.
```

2020-09-29 15:01 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
> +When enabled,  this optional parameter prevents the Knowledge consistency checker (KCC) from removing connection objects that it does not need.
```suggestion
When enabled,  this optional parameter prevents the Knowledge Consistency Checker (KCC) from removing connection objects that it does not need.
```

2020-09-29 15:02 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
> +This parameter option prevents the Knowledge consistency checker (KCC) from excluding servers that are unreachable from the topology; that is, the KCC does use an alternate server to reroute replicat
```suggestion
This parameter option prevents the Knowledge Consistency Checker (KCC) from excluding servers that are unreachable from the topology; that is, the KCC does use an alternate server to reroute replication.
```

2020-09-29 15:02 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
> +When enabled, this parameter prevents the Knowledge consistency checker (KCC) from generating optimizing connections in the ring topology of intrasite replication.
```suggestion
When enabled, this parameter prevents the Knowledge Consistency Checker (KCC) from generating optimizing connections in the ring topology of intrasite replication.
```

2020-09-29 15:03 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
> +Indicates whether the cmdlet implements Knowledge consistency checker (KCC) operation that is consistent with Windows Server 2003 forest functional level.
```suggestion
Indicates whether the cmdlet implements Knowledge Consistency Checker (KCC) operation that is consistent with Windows Server 2003 forest functional level.
```

2020-09-29 15:04 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md
> +When the forest functional level Windows Server 2003 or Windows Server 2003 interim is in effect, provides Knowledge consistency checker (KCC) control of the ability to enable or disable site link br
```suggestion
When the forest functional level Windows Server 2003 or Windows Server 2003 interim is in effect, provides Knowledge Consistency Checker (KCC) control of the ability to enable or disable site link bridging.
```

2020-09-29 15:05 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-29 16:24 UTC, opbld32 commented
Docs Build status updates of commit _[b5bdb9b](https://github.com/msbemba/windows-powershell-docs/commits/b5bdb9b8487e56bb74fbf3d40eecb7fec67f57ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291619454515-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P3JdUEDw7GPKN4aINnv4217M%2Bu7zuTPIXtD5BtCSPqk%3D&st=2020-09-29T16%3A19%3A17Z&se=2020-10-30T16%3A24%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 16:28 UTC, opbld32 commented
Docs Build status updates of commit _[644ae59](https://github.com/msbemba/windows-powershell-docs/commits/644ae598bee6e4caf73cf834b12b412f0dc002ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291620465557-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lHhIgaHZzspq0%2FicdXNGLcIu3q0jzr%2FC1wyvACWVK2c%3D&st=2020-09-29T16%3A23%3A25Z&se=2020-10-30T16%3A28%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 16:33 UTC, opbld32 commented
Docs Build status updates of commit _[9814eec](https://github.com/msbemba/windows-powershell-docs/commits/9814eec51faaaae8340f90ad46ba5aabd31c9014)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291624564261-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e3NxwyH8prVHF9NU%2FWkHGlzUivV1ZqbToJC7RKHXrm0%3D&st=2020-09-29T16%3A28%3A08Z&se=2020-10-30T16%3A33%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 16:37 UTC, opbld31 commented
Docs Build status updates of commit _[cdf97f9](https://github.com/msbemba/windows-powershell-docs/commits/cdf97f9336949e6f92a61a818327bddfda2a9d79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291631301898-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CpHd808lvDgO1nK9sOu%2BRKIc010KzNHb8ixw5sD7FK8%3D&st=2020-09-29T16%3A32%3A27Z&se=2020-10-30T16%3A37%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 16:42 UTC, opbld32 commented
Docs Build status updates of commit _[644ae59](https://github.com/msbemba/windows-powershell-docs/commits/644ae598bee6e4caf73cf834b12b412f0dc002ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291620357485-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HLvEAHjTjxCtNwuC%2Bg09Jb5zwfuJgneC7IQAxfcsfzU%3D&st=2020-09-29T16%3A37%3A12Z&se=2020-10-30T16%3A42%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 16:46 UTC, opbld31 commented
Docs Build status updates of commit _[4aeab0e](https://github.com/msbemba/windows-powershell-docs/commits/4aeab0e2f2ee26273026bfbdbb798ba76508625d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202009291620206449-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5bb1vJ4bJQeK9My4xKZ%2Fhu78XFjzi2vPMiNLFysUmwE%3D&st=2020-09-29T16%3A41%3A43Z&se=2020-10-30T16%3A46%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-29 17:28 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-09-29 19:10 UTC, dariomws approved these changes

2020-09-29 20:03 UTC, get-itips approved these changes

2020-09-29 20:12 UTC, tseward approved these changes

2020-09-30 01:10 UTC, JohanFreelancer9 approved these changes

2020-10-05 15:52 UTC, opbld32 commented
Docs Build status updates of commit _[0e931d2](https://github.com/msbemba/windows-powershell-docs/commits/0e931d2cb5991fe0219e9762019b9d71b7abc525)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/windows/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012-ps/activedirectory/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-122/docset/winserver2012r2-ps/addsadministration/Set-ADReplicationSite.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010051548241061-2153%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NULznJYkXvJuYDIqPotOlcMx60VIjiHFvsJY78dzUsY%3D&st=2020-10-05T15%3A47%3A38Z&se=2020-11-05T15%3A52%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 15:53 UTC, merged