Update-Set-MpPreference-4519186
MicrosoftDocs/windows-powershell-docs pull request #2158
Opened 2020-10-01 03:49 UTC by Lovina-Saldanha

Updated information for the parameter "DisableCpuThrottleOnIdleScans"

2020-10-01 03:54 UTC, opbld32 commented
Docs Build status updates of commit _[6142c5e](https://github.com/Lovina-Saldanha/windows-powershell-docs/commits/6142c5ecf6a9aee28ef10f123655f2dbb7bd6476)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/defender/Set-MpPreference.md](https://github.com/Lovina-Saldanha/windows-powershell-docs/blob/patch-1/docset/windows/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010010349386334-2158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CFOKowesSQv6el%2FJCVBbuah%2FLgkynUDWMJ10yehovjk%3D&st=2020-10-01T03%3A49%3A19Z&se=2020-11-01T03%3A54%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 07:57 UTC, opbld32 commented
Docs Build status updates of commit _[32e5150](https://github.com/Lovina-Saldanha/windows-powershell-docs/commits/32e51504b306ad6891dd14b117bda51d06520a12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/defender/Set-MpPreference.md](https://github.com/Lovina-Saldanha/windows-powershell-docs/blob/patch-1/docset/windows/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010010753179070-2158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tb%2FDW6obk6q8y4DQQw5pyDjDgKOqXnIceGVm0HHn7ts%3D&st=2020-10-01T07%3A52%3A32Z&se=2020-11-01T07%3A57%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-01 15:56 UTC, opbld30 commented
Docs Build status updates of commit _[ed7341a](https://github.com/Lovina-Saldanha/windows-powershell-docs/commits/ed7341a6cb82b1a6e4146bbaa2a242bc678c95a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/defender/Set-MpPreference.md](https://github.com/Lovina-Saldanha/windows-powershell-docs/blob/patch-1/docset/windows/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010011551591539-2158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IpyU0NPa89SA%2BHh6PKCi8pG%2F40sR%2FYvdqSojSFowQKU%3D&st=2020-10-01T15%3A51%3A14Z&se=2020-11-01T15%3A56%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-03 15:36 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-03 15:36 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-10-03 19:31 UTC, tseward approved these changes

2020-10-04 03:15 UTC, JohanFreelancer9 commented on docset/windows/defender/Set-MpPreference.md
> +Indicates whether the CPU will be throttled for scheduled scans while the device is idle. This parameter is enabled by default, thus ensuring that the CPU will not throttle for scheduled scans perfor
```suggestion
Indicates whether the CPU will be throttled for scheduled scans while the device is idle. This parameter is enabled by default, thus ensuring that the CPU will not be throttled for scheduled scans performed when the device is idle, regardless of what **ScanAvgCPULoadFactor** is set to. For all other scheduled scans, this flag does not have any impact and normal throttling will occur.
```

2020-10-04 03:19 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-04 22:21 UTC, get-itips approved these changes

2020-10-05 04:12 UTC, opbld31 commented
Docs Build status updates of commit _[209cd25](https://github.com/Lovina-Saldanha/windows-powershell-docs/commits/209cd25cc07cfdb7148bb20f7c2947a99740ebc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/defender/Set-MpPreference.md](https://github.com/Lovina-Saldanha/windows-powershell-docs/blob/patch-1/docset/windows/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010050408284370-2158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VmoKc0uuQZjmSeI6pbwm23aUrlAManN5eJ1d3PbpMgA%3D&st=2020-10-05T04%3A07%3A50Z&se=2020-11-05T04%3A12%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 04:17 UTC, opbld31 commented
Docs Build status updates of commit _[de70739](https://github.com/Lovina-Saldanha/windows-powershell-docs/commits/de7073902c5000e3127015ac1d8baacd15952a87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/defender/Set-MpPreference.md](https://github.com/Lovina-Saldanha/windows-powershell-docs/blob/patch-1/docset/windows/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010050413234357-2158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n0z%2BFlmWWA1V5kW3CmgG%2B%2F06isvMLgrPkWt565n9roc%3D&st=2020-10-05T04%3A12%3A53Z&se=2020-11-05T04%3A17%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 09:45 UTC, JohanFreelancer9 approved these changes

2020-10-05 12:51 UTC, dariomws approved these changes

2020-10-05 16:53 UTC, opbld33 commented
Docs Build status updates of commit _[c29abbf](https://github.com/Lovina-Saldanha/windows-powershell-docs/commits/c29abbfe166640c8911b46f7b2bb2565192c2153)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/defender/Set-MpPreference.md](https://github.com/Lovina-Saldanha/windows-powershell-docs/blob/patch-1/docset/windows/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010051648386617-2158%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v8MLogz2F1m1NUpqFZSQyCOcbysuWFC2jk0eORscT0g%3D&st=2020-10-05T16%3A48%3A09Z&se=2020-11-05T16%3A53%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-12 16:16 UTC, merged