New Parameter DeferRegistrationWhenPackagesAreInUse
MicrosoftDocs/windows-powershell-docs pull request #2160
Opened 2020-10-02 01:08 UTC by RDMacLachlan

Included examples and description for the new parameter "-DeferRegistrationWhenPackagesAreInUse"

2020-10-02 01:12 UTC, opbld33 commented
Docs Build status updates of commit _[c0751c6](https://github.com/RDMacLachlan/windows-powershell-docs/commits/c0751c6f7895c9b4800e7b250060afad25e6462b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Add-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/rpm-23009447-Add_DeferRegistrationWhenPackagesAreInUse_to_PowerShell/docset/windows/appx/Add-AppxPackage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010020108429215-2160%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=69Usaq0D0vk5imsfZXnpKrgz6pz%2Bhl7ZxlHBpLQMeuY%3D&st=2020-10-02T01%3A07%3A49Z&se=2020-11-02T01%3A12%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-03 15:34 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-10-03 15:35 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-03 19:26 UTC, tseward approved these changes

2020-10-04 03:23 UTC, JohanFreelancer9 commented on docset/windows/appx/Add-AppxPackage.md
> +### Example 2: Update an app, but defer registration until app has closed.
```suggestion
### Example 2: Update an app, but defer registration until the app has closed

```

2020-10-04 03:25 UTC, JohanFreelancer9 commented on docset/windows/appx/Add-AppxPackage.md
> +Specifies that the app will not register for a user if currently in use. The app will update on next launch.
```suggestion
Specifies that the app will not register for a user if currently in use. The app will update on the next launch.

```

2020-10-04 03:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-04 22:18 UTC, get-itips approved these changes

2020-10-05 12:54 UTC, dariomws approved these changes
I'm ok after this minor detail is fixed. Thanks!

2020-10-05 12:54 UTC, dariomws commented on docset/windows/appx/Add-AppxPackage.md
> + [DeferRegistrationWhenPackagesAreInUse] [-OptionalPackages <String[]>] [-RelatedPackages <String[]>]
```suggestion
 [-DeferRegistrationWhenPackagesAreInUse] [-OptionalPackages <String[]>] [-RelatedPackages <String[]>] 

```

2020-10-05 16:21 UTC, opbld31 commented
Docs Build status updates of commit _[aef36ae](https://github.com/RDMacLachlan/windows-powershell-docs/commits/aef36ae98d429c9c00885b1823fc890577bb2a14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Add-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/rpm-23009447-Add_DeferRegistrationWhenPackagesAreInUse_to_PowerShell/docset/windows/appx/Add-AppxPackage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010051617108614-2160%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FODZLHfcfe6QRT77Fl%2B%2Fe1qN%2B0jgGNu2xN%2F%2FiZvwiFg%3D&st=2020-10-05T16%3A16%3A26Z&se=2020-11-05T16%3A21%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 16:25 UTC, opbld33 commented
Docs Build status updates of commit _[9fa7c6c](https://github.com/RDMacLachlan/windows-powershell-docs/commits/9fa7c6c2ec66118a195502b8820db182aa03cd78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Add-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/rpm-23009447-Add_DeferRegistrationWhenPackagesAreInUse_to_PowerShell/docset/windows/appx/Add-AppxPackage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010051618349434-2160%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2sUMMX8Y5kVqiewfh6WCnCOTHJ%2BDpQuwoovb8dGFqNQ%3D&st=2020-10-05T16%3A20%3A52Z&se=2020-11-05T16%3A25%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-05 16:31 UTC, RDMacLachlan commented
All changes have been applied to the Doc. Thank you for reviewing, and providing your comments.

2020-10-06 04:56 UTC, JohanFreelancer9 approved these changes

2020-10-06 16:14 UTC, RDMacLachlan commented
I'm unable to press the **Merge pull request** button as I'm not authorized. Can someone please merge this request or provide me with access to. Thanks!

2020-10-12 16:24 UTC, opbld32 commented
Docs Build status updates of commit _[4daa7c1](https://github.com/RDMacLachlan/windows-powershell-docs/commits/4daa7c1b1c792027761b2aeb8dca751d7a9ed93b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/appx/Add-AppxPackage.md](https://github.com/RDMacLachlan/windows-powershell-docs/blob/rpm-23009447-Add_DeferRegistrationWhenPackagesAreInUse_to_PowerShell/docset/windows/appx/Add-AppxPackage.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202010121620216423-2160%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VRQRh9nAOg8HbNnE7VOxmjuUySZVxrpIFfaImnXBVRs%3D&st=2020-10-12T16%3A19%3A31Z&se=2020-11-12T16%3A24%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-12 16:26 UTC, merged