Resolves #2157
MicrosoftDocs/windows-powershell-docs pull request #2169
Opened 2020-10-20 10:37 UTC by velkovb

Typo.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2157

2020-10-20 10:42 UTC, opbld30 commented
Docs Build status updates of commit _[db7e8f7](https://github.com/velkovb/windows-powershell-docs/commits/db7e8f783959507ed4e765f8e24fd85f3c679e4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :warning:Warning | | [Details](#user-content-a1213b74-d3def326)
[docset/mdop/uev/clear-uevconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/uev/clear-uevconfiguration.md) | :warning:Warning | | [Details](#user-content-dac628ae-d3def326)
[docset/mdop/mbam/test-mbamwebapplication.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/test-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-e7e63682-d3def326)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-d3def326)
[docset/mdop/mbam/write-mbamtpminformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/write-mbamtpminformation.md) | :warning:Warning | | [Details](#user-content-85ebd0e1-d3def326)
[docset/mdop/appvserver/set-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/set-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-d1fd1e49-d3def326)
[docset/mdop/appvclient/get-appvclientconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/get-appvclientconfiguration.md) | :warning:Warning | | [Details](#user-content-9ae7de48-d3def326)
[docset/mdop/mbam/enable-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-b1bb4167-d3def326)
[docset/mdop/mbam/test-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/test-mbamreport.md) | :warning:Warning | | [Details](#user-content-835b6b92-d3def326)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-d3def326)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-d3def326)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-d3def326)
[docset/windows/appvclient/Get-AppvClientConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Get-AppvClientConfiguration.md) | :warning:Warning | | [Details](#user-content-9ae6f7f1-d3def326)
[docset/mdop/mbam/get-mbambitlockerrecoverykey.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/get-mbambitlockerrecoverykey.md) | :warning:Warning | | [Details](#user-content-1a2741fb-d3def326)
[docset/mdop/mbam/disable-mbamwebapplication.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/disable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-121c5d3d-d3def326)
[docset/mdop/appvserver/new-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/new-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-899a17da-d3def326)
[docset/mdop/mbam/get-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/get-mbamreport.md) | :warning:Warning | | [Details](#user-content-e9525729-d3def326)
[docset/mdop/mbam/test-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/test-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-a1afc1d1-d3def326)
[docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md) | :warning:Warning | | [Details](#user-content-96de03ef-d3def326)
[docset/mdop/uev/disable-uevtemplate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/uev/disable-uevtemplate.md) | :warning:Warning | | [Details](#user-content-d676abb8-d3def326)
[docset/mdop/mbam/disable-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/disable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-ee596be7-d3def326)
[docset/mdop/uev/disable-uevappxpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/uev/disable-uevappxpackage.md) | :warning:Warning | | [Details](#user-content-b6c02e42-d3def326)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-d3def326)
[docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/new-medvworkspace.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/new-medvworkspace.md) | :warning:Warning | | [Details](#user-content-a895583e-d3def326)
[docset/windows/uev/Clear-UevConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/uev/Clear-UevConfiguration.md) | :warning:Warning | | [Details](#user-content-2d84a63f-d3def326)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-d3def326)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-d3def326)
[docset/mdop/appvserver/grant-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/grant-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-d5ff5896-d3def326)
[docset/windows/uev/Disable-UevTemplate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/uev/Disable-UevTemplate.md) | :warning:Warning | | [Details](#user-content-19f35351-d3def326)
[docset/windows/uev/Disable-UevAppxPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/uev/Disable-UevAppxPackage.md) | :warning:Warning | | [Details](#user-content-629bd9c5-d3def326)
[docset/mdop/mbam/enable-mbamdatabase.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamdatabase.md) | :warning:Warning | | [Details](#user-content-5165bc7f-d3def326)
[docset/mdop/appvserver/unpublish-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/unpublish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-b1029600-d3def326)
[docset/mdop/mbam/get-mbamtpmownerpass [...]

2020-10-20 10:46 UTC, opbld33 commented
Docs Build status updates of commit _[174aae0](https://github.com/velkovb/windows-powershell-docs/commits/174aae0b80f4409a9694afe359e30c55360c7d1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :warning:Warning | | [Details](#user-content-a1213b74-e8d12f4a)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-e8d12f4a)
[docset/mdop/mbam/disable-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/disable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-ee596be7-e8d12f4a)
[docset/mdop/appvclient/sync-appvpublishingserver.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/sync-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-10723e77-e8d12f4a)
[docset/mdop/mbam/disable-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/disable-mbamreport.md) | :warning:Warning | | [Details](#user-content-1757a059-e8d12f4a)
[docset/mdop/mbam/get-mbambitlockerrecoverykey.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/get-mbambitlockerrecoverykey.md) | :warning:Warning | | [Details](#user-content-1a2741fb-e8d12f4a)
[docset/mdop/appvserver/remove-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/remove-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-a88eaaf8-e8d12f4a)
[docset/mdop/mbam/enable-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamreport.md) | :warning:Warning | | [Details](#user-content-2a4312c1-e8d12f4a)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-e8d12f4a)
[docset/mdop/mbam/enable-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-b1bb4167-e8d12f4a)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-e8d12f4a)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-e8d12f4a)
[docset/mdop/mbam/test-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/test-mbamreport.md) | :warning:Warning | | [Details](#user-content-835b6b92-e8d12f4a)
[docset/mdop/mbam/write-mbamcomputeruser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/write-mbamcomputeruser.md) | :warning:Warning | | [Details](#user-content-d5e1fb42-e8d12f4a)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-e8d12f4a)
[docset/mdop/mbam/get-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/get-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-1b2b6a55-e8d12f4a)
[docset/windows/appvclient/Sync-AppvPublishingServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Sync-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-4b9a6faf-e8d12f4a)
[docset/windows/appvsequencer/Update-AppvSequencerPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvsequencer/Update-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-abffa8f3-e8d12f4a)
[docset/mdop/mbam/disable-mbamwebapplication.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/disable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-121c5d3d-e8d12f4a)
[docset/mdop/mbam/write-mbamtpminformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/write-mbamtpminformation.md) | :warning:Warning | | [Details](#user-content-85ebd0e1-e8d12f4a)
[docset/mdop/mbam/write-mbamrecoveryinformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/write-mbamrecoveryinformation.md) | :warning:Warning | | [Details](#user-content-e43a9859-e8d12f4a)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-e8d12f4a)
[docset/mdop/mbam/enable-mbamwebapplication.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-39983848-e8d12f4a)
[docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/export-medvworkspace.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/export-medvworkspace.md) | :warning:Warning | | [Details](#user-content-d05b6eee-e8d12f4a)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-e8d12f4a)
[docset/mdop/uev/repair-uevtemplateindex.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/uev/repair-uevtemplateindex.md) | :warning:Warning | | [Details](#user-content-cebb92c5-e8d12f4a)
[docset/mdop/appvclient/get-appvclientconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/get-appvclientconfiguration.md) | :warning:Warning | | [Details](#user-content-9ae7de48-e8d12f4a)
[docset/mdop/mbam/read-adtpminformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/read-adtpminformation.md) | :warning:Warning | | [Details](#user-content-db054964-e8d12f4a)
[docset/windows/appvsequencer/Expand-AppvSequencerPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvsequencer/Expand-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-93a1ef35-e8d12f4a)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-e8d12f4a)
[docset/windows/uev/Repair-UevTemplateIndex.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/uev/Repair-UevTemplateIndex.md) | :warning:Warning | | [Details](#user-content-8e8006c3-e8d12f4a)
[docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/new-medvworkspace.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager/new-me [...]

2020-10-20 16:22 UTC, e0i commented
Closing and re-opening to refresh checks

2020-10-20 16:27 UTC, opbld30 commented
Docs Build status updates of commit _[174aae0](https://github.com/velkovb/windows-powershell-docs/commits/174aae0b80f4409a9694afe359e30c55360c7d1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :warning:Warning | | [Details](#user-content-a1213b74-b0a068d3)
[docset/mdop/appvserver/grant-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/grant-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-d5ff5896-b0a068d3)
[docset/mdop/mbam/get-mbambitlockerrecoverykey.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/get-mbambitlockerrecoverykey.md) | :warning:Warning | | [Details](#user-content-1a2741fb-b0a068d3)
[docset/mdop/appvclient/start-appvvirtualprocess.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/start-appvvirtualprocess.md) | :warning:Warning | | [Details](#user-content-ee3d70b3-b0a068d3)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-b0a068d3)
[docset/mdop/appvclient/repair-appvclientpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/repair-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-8f3897f3-b0a068d3)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-b0a068d3)
[docset/mdop/appvclient/send-appvclientreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/send-appvclientreport.md) | :warning:Warning | | [Details](#user-content-b8a57e87-b0a068d3)
[docset/windows/appvsequencer/New-AppvSequencerPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvsequencer/New-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-76bddda7-b0a068d3)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-b0a068d3)
[docset/mdop/mbam/enable-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-b1bb4167-b0a068d3)
[docset/mdop/appvclient/set-appvclientpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/set-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-63b02c3f-b0a068d3)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-b0a068d3)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-b0a068d3)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-b0a068d3)
[docset/mdop/mbam/read-adtpminformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/read-adtpminformation.md) | :warning:Warning | | [Details](#user-content-db054964-b0a068d3)
[docset/mdop/appvclient/add-appvclientpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/add-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-36cd6076-b0a068d3)
[docset/windows/appvclient/Add-AppvClientPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Add-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-9818d699-b0a068d3)
[docset/windows/appvsequencer/Expand-AppvSequencerPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvsequencer/Expand-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-93a1ef35-b0a068d3)
[docset/windows/appvclient/Start-AppvVirtualProcess.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Start-AppvVirtualProcess.md) | :warning:Warning | | [Details](#user-content-65e3cb88-b0a068d3)
[docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md) | :warning:Warning | | [Details](#user-content-96de03ef-b0a068d3)
[docset/windows/appvclient/Set-AppvClientPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Set-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-176b49b4-b0a068d3)
[docset/mdop/mbam/get-mbamcmintegration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/get-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-1b2b6a55-b0a068d3)
[docset/windows/appvclient/Send-AppvClientReport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Send-AppvClientReport.md) | :warning:Warning | | [Details](#user-content-7b27e2e1-b0a068d3)
[docset/mdop/appvclient/remove-appvpublishingserver.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/remove-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-394de290-b0a068d3)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvsequencer/New-AppvPackageAccelerator.md) | :warning:Warning | | [Details](#user-content-ff826ff1-b0a068d3)
[docset/mdop/mbam/enable-mbamdatabase.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamdatabase.md) | :warning:Warning | | [Details](#user-content-5165bc7f-b0a068d3)
[docset/windows/appvclient/Remove-AppvPublishingServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Remove-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-e41ca0ca-b0a068d3)
[docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-6a8cd355-b0a068d3)
[docset/mdop/mbam/enable-mbamwebapplication.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/enable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-39983848-b0a068d3)
[docset/mdop/mbam/write-mbamrecoveryinformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/write-mbamrecoveryinformation.md) | :warning:Warning | | [Details](#user-content-e43a9859-b0a068d3)
[docset/mdop/mbam/test-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/test-mbamreport.md) | :warning:Warning | | [ [...]

2020-10-21 17:30 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-21 17:30 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-10-21 17:54 UTC, get-itips approved these changes

2020-10-21 19:02 UTC, dariomws approved these changes

2020-10-22 02:10 UTC, JohanFreelancer9 approved these changes

2020-10-22 03:23 UTC, tseward requested changes

2020-10-22 03:23 UTC, tseward commented on docset/windows/dnsserver/Add-DnsServerZoneScope.md
> +When a scope is created, its data is persisted in a file named `%Systemroot%\system32\dns\\\<zone name\>\\\<scope name\>.dns`.
You can remove the escape characters since you're using ticks around the path.

2020-10-22 06:31 UTC, opbld33 commented
Docs Build status updates of commit _[4497715](https://github.com/velkovb/windows-powershell-docs/commits/449771513cc6437cd7dae5221bc173652b67b21d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :warning:Warning | | [Details](#user-content-a1213b74-6705b53f)
[docset/windows/appvclient/Unpublish-AppvClientPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Unpublish-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-4dbcd802-6705b53f)
[docset/mdop/medv/export-medvconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/medv/export-medvconfiguration.md) | :warning:Warning | | [Details](#user-content-1167a531-6705b53f)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-6705b53f)
[docset/mdop/appvserver/new-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/new-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-899a17da-6705b53f)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-6705b53f)
[docset/windows/appvclient/Add-AppvClientPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Add-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-9818d699-6705b53f)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-6705b53f)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-6705b53f)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-6705b53f)
[docset/mdop/mbam/read-adtpminformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/read-adtpminformation.md) | :warning:Warning | | [Details](#user-content-db054964-6705b53f)
[docset/windows/appvclient/Sync-AppvPublishingServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Sync-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-4b9a6faf-6705b53f)
[docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-22c33323-6705b53f)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-6705b53f)
[docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md) | :warning:Warning | | [Details](#user-content-96de03ef-6705b53f)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-6705b53f)
[docset/mdop/agpm/publish-controlledgpo.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/agpm/publish-controlledgpo.md) | :warning:Warning | | [Details](#user-content-f266a5c0-6705b53f)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-6705b53f)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/import-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ae2d5b45-6705b53f)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-6705b53f)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-6705b53f)
[docset/mdop/appvclient/get-appvclientconfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/get-appvclientconfiguration.md) | :warning:Warning | | [Details](#user-content-9ae7de48-6705b53f)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvsequencer/New-AppvPackageAccelerator.md) | :warning:Warning | | [Details](#user-content-ff826ff1-6705b53f)
[docset/mdop/uev/clear-uevappxpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/uev/clear-uevappxpackage.md) | :warning:Warning | | [Details](#user-content-706a39a5-6705b53f)
[docset/windows/appvclient/Get-AppvClientConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/appvclient/Get-AppvClientConfiguration.md) | :warning:Warning | | [Details](#user-content-9ae6f7f1-6705b53f)
[docset/mdop/appvserver/grant-appvserverconnectiongroup.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvserver/grant-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-d5ff5896-6705b53f)
[docset/mdop/mbam/disable-mbamreport.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/disable-mbamreport.md) | :warning:Warning | | [Details](#user-content-1757a059-6705b53f)
[docset/mdop/mbam/write-mbamtpminformation.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/mbam/write-mbamtpminformation.md) | :warning:Warning | | [Details](#user-content-85ebd0e1-6705b53f)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-6705b53f)
[docset/mdop/agpm/lock-controlledgpo.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/agpm/lock-controlledgpo.md) | :warning:Warning | | [Details](#user-content-17829822-6705b53f)
[docset/mdop/appvclient/sync-appvpublishingserver.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/mdop/appvclient/sync-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-10723e77-6705b53f)
[docset/windows/appvsequencer/New-AppvSequencerPackage.md](https://github.com/velkovb/windows-powershell-docs/blob/ [...]

2020-11-05 19:29 UTC, opbld31 commented
Docs Build status updates of commit _[2348ea6](https://github.com/velkovb/windows-powershell-docs/commits/2348ea6f0109de3c0153cfe95b07d145b9fd02ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011051925321582-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rdd%2Fss9Xl9KNzppvTw263qtPE7TlGAK8qeleuWHx0pA%3D&st=2020-11-05T19%3A24%3A36Z&se=2020-12-06T19%3A29%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-12 18:59 UTC, opbld33 commented
Docs Build status updates of commit _[a28f126](https://github.com/velkovb/windows-powershell-docs/commits/a28f1263251e349b7e75a195b73ec2e9da76fc7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011121855239874-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5l7dF0vPvOXfaNHyTFBKwuo36HOiCOEukeE5kBXBBew%3D&st=2020-11-12T18%3A54%3A38Z&se=2020-12-13T18%3A59%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:33 UTC, opbld33 commented
Docs Build status updates of commit _[945aa6b](https://github.com/velkovb/windows-powershell-docs/commits/945aa6b623563dd84e45132a7fa8a15172ee0e77)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171728504378-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PgrKKMfWAdGtmEvQnaUOpMsiMVaIs%2BTqVc1bUhBaFRk%3D&st=2020-11-17T17%3A28%3A04Z&se=2020-12-18T17%3A33%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:40 UTC, opbld30 commented
Docs Build status updates of commit _[8f634d6](https://github.com/velkovb/windows-powershell-docs/commits/8f634d604f9658e9b8cfeca052442365e227bdd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171735387505-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qa9CJO4TspzLOSh%2Fev1gA9n%2BBOQ3NLKYwxct3e7WJS8%3D&st=2020-11-17T17%3A34%3A59Z&se=2020-12-18T17%3A39%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:54 UTC, opbld31 commented
Docs Build status updates of commit _[e4b4c97](https://github.com/velkovb/windows-powershell-docs/commits/e4b4c97503721db6fdf21240aa66d5be403c20e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171750161189-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EcGcDNogHIa5hDr44u%2FD%2FiQjJT3AuRBfDBNGQJ%2FUJ9s%3D&st=2020-11-17T17%3A49%3A53Z&se=2020-12-18T17%3A54%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:59 UTC, opbld33 commented
Docs Build status updates of commit _[b9dc8d7](https://github.com/velkovb/windows-powershell-docs/commits/b9dc8d774e95809d3de7521beb165bbbbec5b488)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171755341758-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=42UZe9oCBI4UrJ7fki7HCRb12ZHJyT6WmMTudNngEGA%3D&st=2020-11-17T17%3A54%3A40Z&se=2020-12-18T17%3A59%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 18:06 UTC, opbld32 commented
Docs Build status updates of commit _[45bc3ee](https://github.com/velkovb/windows-powershell-docs/commits/45bc3ee8ef9b2f17df64f08cdd0a88d5490f5383)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Add-DnsServerZoneScope.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2157-typo/docset/windows/dnsserver/Add-DnsServerZoneScope.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171800535600-2169%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YRRrwoqJi42H%2FUSHhSkvpsrCwKAjlbD8Vi%2FvapxRngc%3D&st=2020-11-17T18%3A01%3A12Z&se=2020-12-18T18%3A06%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 18:08 UTC, merged