Update Remove-ADGroupMember.md
MicrosoftDocs/windows-powershell-docs pull request #2175
Opened 2020-10-23 12:03 UTC by HerbertMauerer

As a result of windows bug "24359250: [RS1] Using Permissive Modify causes extra event 5136 to be written for Group membership changes" a new parameter was added to this cmdlet. It already appears in the online help in Powershell ISE.

2020-10-23 12:08 UTC, opbld32 commented
Docs Build status updates of commit _[a4b11b0](https://github.com/HerbertMauerer/windows-powershell-docs/commits/a4b11b049b23199b523495d1ae50c47cb93c56f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Remove-ADGroupMember.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/addsadministration/Remove-ADGroupMember.md) | :warning:Warning | | [Details](#user-content-1504efb8-f0d89768)
[docset/mdop/appvclient/set-appvpublishingserver.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvclient/set-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-85260d09-f0d89768)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-f0d89768)
[docset/windows/appvclient/Unpublish-AppvClientPackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/appvclient/Unpublish-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-4dbcd802-f0d89768)
[docset/windows/appvclient/Set-AppvPublishingServer.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/appvclient/Set-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-49b32784-f0d89768)
[docset/mdop/appvclient/start-appvvirtualprocess.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvclient/start-appvvirtualprocess.md) | :warning:Warning | | [Details](#user-content-ee3d70b3-f0d89768)
[docset/mdop/appvclient/enable-appvclientconnectiongroup.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvclient/enable-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-67d6484d-f0d89768)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-f0d89768)
[docset/mdop/appvserver/set-appvserverpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/set-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-d1fd1e49-f0d89768)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-f0d89768)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-f0d89768)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/import-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ae2d5b45-f0d89768)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-f0d89768)
[docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-22c33323-f0d89768)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/appvsequencer/New-AppvPackageAccelerator.md) | :warning:Warning | | [Details](#user-content-ff826ff1-f0d89768)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-f0d89768)
[docset/mdop/mbam/get-mbamcmintegration.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/get-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-1b2b6a55-f0d89768)
[docset/windows/appvclient/Start-AppvVirtualProcess.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/appvclient/Start-AppvVirtualProcess.md) | :warning:Warning | | [Details](#user-content-65e3cb88-f0d89768)
[docset/mdop/mbam/enable-mbamwebapplication.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/enable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-39983848-f0d89768)
[docset/mdop/mbam/test-mbamdatabase.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/test-mbamdatabase.md) | :warning:Warning | | [Details](#user-content-b11bdd91-f0d89768)
[docset/windows/appvclient/Enable-AppvClientConnectionGroup.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/appvclient/Enable-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-6c1563ac-f0d89768)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-f0d89768)
[docset/mdop/mbam/enable-mbamcmintegration.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/enable-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-b1bb4167-f0d89768)
[docset/mdop/appv/test-appvlegacypackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appv/test-appvlegacypackage.md) | :warning:Warning | | [Details](#user-content-d19775fa-f0d89768)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-f0d89768)
[docset/mdop/mbam/test-mbamcmintegration.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/test-mbamcmintegration.md) | :warning:Warning | | [Details](#user-content-a1afc1d1-f0d89768)
[docset/mdop/mbam/write-mbamcomputeruser.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/write-mbamcomputeruser.md) | :warning:Warning | | [Details](#user-content-d5e1fb42-f0d89768)
[docset/mdop/uev/disable-uevappxpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/uev/disable-uevappxpackage.md) | :warning:Warning | | [Details](#user-content-b6c02e42-f0d89768)
[docset/mdop/mbam/disable-mbamreport.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/disable-mbamreport.md) | :warning:Warning | | [Details](#user-content-1757a059-f0d89768)
[docset/mdop/agpm/get-controlledgpo.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/agpm/get-controlledgpo.md) | :warning:Warning | | [Details](#user-content-8529f522-f0d89768)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-f0d89768)
[docset/mdop/mbam/write-mbamtpminformation.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/mdop/mbam/write-mbamtpminformation.md) | :warning:Warning | | [Details [...]

2020-11-13 08:23 UTC, HerbertMauerer commented
Hello,

I think this is stuck. Is there a ETA of this being released?
I have a customer waiting for it.

Herbert Mauerer
[cid:image001.png@01D6B99E.AA0872A0]<https://campus.partners.extranet.microsoft.com/sites/campus/Pages/wwcommunities.aspx>
Senior Escalation Engineer
Customer Services and Support EMEA
WW Communities Debugging<http://aka.ms/wwcomdebug>, SME
Which WW Community should you join? Click here<https://microsoft.sharepoint.com/teams/campusWWCs/Pages/Landing.aspx>
[cid:image002.jpg@01D6B99E.AA0872A0]
Do you have feedback for me? Please ask me for a connect survey.

From: opbld32 <notifications@github.com>
Sent: Freitag, 23. Oktober 2020 14:09
To: MicrosoftDocs/windows-powershell-docs <windows-powershell-docs@noreply.github.com>
Cc: Herbert Mauerer (BULL FIGHTER) <Herbert.Mauerer@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [MicrosoftDocs/windows-powershell-docs] Update Remove-ADGroupMember.md (#2175)


Docs Build status updates of commit a4b11b0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fcommits%2Fa4b11b049b23199b523495d1ae50c47cb93c56f1&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198451105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mGY3d1lSTq%2Bfr2YZ4%2FmBosAllGz8WlNfzfqqGzp0LNk%3D&reserved=0>:

⚠️ Validation status: warnings
File
Status
Preview URL
Details
docset/windows/addsadministration/Remove-ADGroupMember.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fwindows%2Faddsadministration%2FRemove-ADGroupMember.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198461107%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yNnEXeSMiXytnJGYq5Y%2BiHw6gZRblA5O9heDvEsbZzg%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvclient/set-appvpublishingserver.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvclient%2Fset-appvpublishingserver.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198471097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WunsN%2FpVoAit7kK1oOD88MgmEgwNrm3%2FhOQ8dB51uJc%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvserver/get-appvserverconnectiongroup.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvserver%2Fget-appvserverconnectiongroup.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198471097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8GXPnnLEISaQ7lNQC34Fk0Bh4njhENR8SR0Gn%2BScPFY%3D&reserved=0>
⚠️Warning
Details
docset/windows/appvclient/Unpublish-AppvClientPackage.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fwindows%2Fappvclient%2FUnpublish-AppvClientPackage.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198471097%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F3Rv5tlXQlkNL5ZWG2L9LFqh3PCueYtzDqFLnG7lqjE%3D&reserved=0>
⚠️Warning
Details
docset/windows/appvclient/Set-AppvPublishingServer.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fwindows%2Fappvclient%2FSet-AppvPublishingServer.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198481094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E1W4dHOIGBf2EkuQJ5MactgQILxV%2B4Oop3no3eHvX70%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvclient/start-appvvirtualprocess.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvclient%2Fstart-appvvirtualprocess.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198491082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xWcjQZABl%2F5njlqL1f5bA2ovQ2IvhO4QCjNF%2FzDB0nc%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvclient/enable-appvclientconnectiongroup.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvclient%2Fenable-appvclientconnectiongroup.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198491082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EObhtYEKflWLev0voyFZSRcOoCUTioyd9jU4QIOq3HA%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvserver/remove-appvserverconnectiongroup.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvserver%2Fremove-appvserverconnectiongroup.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198501086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QMntI9QnAODs9WC4uuk4DVH1cmlQYXqUEuuCQWqFQsg%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvserver/set-appvserverpackage.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvserver%2Fset-appvserverpackage.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198501086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XtxlrHHqFNHntLd198yhzeJWZNV96F9AC3X8ZCEWbH8%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvclient/unpublish-appvclientpackage.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvclient%2Funpublish-appvclientpackage.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198501086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cWvmrUKKTZMFlakg3jW8tZ6d7c4jomp91U39qG4HCls%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvsequencer/expand-appvsequencerpackage.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHerbertMauerer%2Fwindows-powershell-docs%2Fblob%2Fpatch-2%2Fdocset%2Fmdop%2Fappvsequencer%2Fexpand-appvsequencerpackage.md&data=04%7C01%7CHerbert.Mauerer%40microsoft.com%7Cf6a473f7f64e4c1b487808d8774c5eea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637390517198511076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3dwgUTrQ4YFW7mSlCiNLXNp2rn7qyOYrNiZ2reA7lTs%3D&reserved=0>
⚠️Warning
Details
docset/mdop/appvserver/import-appvserverpack [...]

2020-11-17 17:17 UTC, e0i commented
Closing and re-opening to refresh validation checks.

2020-11-17 17:21 UTC, opbld30 commented
Docs Build status updates of commit _[a4b11b0](https://github.com/HerbertMauerer/windows-powershell-docs/commits/a4b11b049b23199b523495d1ae50c47cb93c56f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Remove-ADGroupMember.md](https://github.com/HerbertMauerer/windows-powershell-docs/blob/patch-2/docset/windows/addsadministration/Remove-ADGroupMember.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171717192238-2175%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5c1t%2FCu7%2BPN5RHCzXqWRpvbvj%2BS0LKiprNZ2DefvdwU%3D&st=2020-11-17T17%3A16%3A47Z&se=2020-12-18T17%3A21%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-25 13:08 UTC, opbld31 commented
Docs Build status updates of commit _[5f2cf33](https://github.com/HerbertMauerer/windows-powershell-docs/commits/5f2cf33b22011945547a2dd67dc326541142d544)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1befb6d7)

<a id="1befb6d7"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C25%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011251308106287-2175%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yPZe1OecTCvkE4zv5VE8%2BY4IzyGwCvxG8Ggi0fMTSs0%3D&st=2020-11-25T13%3A03%3A38Z&se=2020-12-26T13%3A08%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-26 15:14 UTC, opbld33 commented
Docs Build status updates of commit _[a52a799](https://github.com/HerbertMauerer/windows-powershell-docs/commits/a52a799ccf994d9940a09f2e9f800a906b0b34c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-deae2091)

<a id="deae2091"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011261514155042-2175%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MBNMZuhKNOfkUcIMPuFOkyOVP8AK5KViHSWCZYSG4GE%3D&st=2020-11-26T15%3A09%3A43Z&se=2020-12-27T15%3A14%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 15:54 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-15 15:54 UTC, opbld31 commented
Docs Build status updates of commit _[a52a799](https://github.com/HerbertMauerer/windows-powershell-docs/commits/a52a799ccf994d9940a09f2e9f800a906b0b34c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-289dd63d)

<a id="289dd63d"></a>
###
 - **[Error-[CannotMergeCommit](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot merge commit a52a799ccf994d9940a09f2e9f800a906b0b34c7 in branch patch-2 of repository https://github.com/HerbertMauerer/windows-powershell-docs into branch master (commit b5fca77bbd96411069209cfabee7b40cf8fa05e3). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012151554446147-2175%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iY5b3WpL10ZRO5BR%2B0%2BD2gYgHQOjDdhkTgWgG3UwQxc%3D&st=2020-12-15T15%3A49%3A53Z&se=2021-01-15T15%3A54%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 16:36 UTC, get-itips requested changes
The file was updated after this PR was created so it is currently resulting in a merge conflict.
Please review the conflicts, thanks @HerbertMauerer !

2020-12-16 07:28 UTC, HerbertMauerer commented
Please excuse me, this is one of my first and until now biggest changes I make in github directly. I made a few mistakes, and I have created new pull requests and the one where I seem to have gotten things right are 2228 and 2229.

So I think we should cancel this one. You can check the other PRs and edit review them. Thank you.

Herbert Mauerer

2020-12-16 10:20 UTC, JohanFreelancer9 commented on docset/windows/addsadministration/Remove-ADGroupMember.md
> +Group membership updates use permissive modify by default. This suppresses an error when removing a member that is not member of the group.
```suggestion
Group membership updates use permissive modify by default. This suppresses an error when removing a member that is not a member of the group.
```

2020-12-16 10:23 UTC, JohanFreelancer9 requested changes
If this PR is not closed, please include the one minor copy edit.

2020-12-16 16:01 UTC, tseward approved these changes

2020-12-30 15:35 UTC, closed without merging

2020-12-30 15:35 UTC, e0i commented
Closing based on the PR authors’ comments.