Add note about ports range format
MicrosoftDocs/windows-powershell-docs pull request #2179
Opened 2020-10-26 18:00 UTC by dhmhd

* Add note for LocalPort and RemotePort options that ports range format can be used for specifying a continuous sequence of ports in one single ACL rule;
* Add usage example for this feature.

2020-10-26 18:06 UTC, opbld31 commented
Docs Build status updates of commit _[771e70f](https://github.com/dhmhd/windows-powershell-docs/commits/771e70f46f6f51501e6ed9dcc6ad0362d7759d4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :warning:Warning | | [Details](#user-content-3355afd5-72eb15be)
[docset/mdop/appvclient/set-appvclientpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/set-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-63b02c3f-72eb15be)
[docset/mdop/appvclient/set-appvclientmode.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/set-appvclientmode.md) | :warning:Warning | | [Details](#user-content-2a4e3610-72eb15be)
[docset/mdop/appvclient/sync-appvpublishingserver.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/sync-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-10723e77-72eb15be)
[docset/mdop/appvclient/mount-appvclientpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/mount-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-46fdce12-72eb15be)
[docset/windows/appvclient/Remove-AppvPublishingServer.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Remove-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-e41ca0ca-72eb15be)
[docset/mdop/agpm/add-controlledgpo.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/agpm/add-controlledgpo.md) | :warning:Warning | | [Details](#user-content-ffd49bec-72eb15be)
[docset/mdop/appvclient/repair-appvclientconnectiongroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/repair-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-c2c08fc0-72eb15be)
[docset/mdop/appvclient/remove-appvpublishingserver.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/remove-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-394de290-72eb15be)
[docset/mdop/appvclient/remove-appvclientpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/remove-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-9db775ad-72eb15be)
[docset/windows/appvclient/Set-AppvClientConfiguration.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Set-AppvClientConfiguration.md) | :warning:Warning | | [Details](#user-content-6523cc1b-72eb15be)
[docset/mdop/appvclient/stop-appvclientconnectiongroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/stop-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-72e2c169-72eb15be)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-72eb15be)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-72eb15be)
[docset/mdop/appvserver/get-appvserverpackagedeploymentconfiguration.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/get-appvserverpackagedeploymentconfiguration.md) | :warning:Warning | | [Details](#user-content-31105460-72eb15be)
[docset/windows/appvclient/Get-AppvClientPackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Get-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-c7bca43d-72eb15be)
[docset/mdop/appvserver/publish-appvserverconnectiongroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/publish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-ab61575b-72eb15be)
[docset/windows/appvclient/Mount-AppvClientPackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Mount-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-d4633ee0-72eb15be)
[docset/windows/appvsequencer/Update-AppvSequencerPackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvsequencer/Update-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-abffa8f3-72eb15be)
[docset/windows/appvclient/Sync-AppvPublishingServer.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Sync-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-4b9a6faf-72eb15be)
[docset/windows/appvclient/Repair-AppvClientConnectionGroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Repair-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-c1ccc2cf-72eb15be)
[docset/mdop/appvclient/set-appvclientconfiguration.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/set-appvclientconfiguration.md) | :warning:Warning | | [Details](#user-content-e8612c98-72eb15be)
[docset/mdop/appvserver/grant-appvserverconnectiongroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/grant-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-d5ff5896-72eb15be)
[docset/mdop/appvserver/remove-appvserverpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/remove-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-a88eaaf8-72eb15be)
[docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-6a8cd355-72eb15be)
[docset/windows/appvclient/Get-AppvClientConnectionGroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Get-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-27565059-72eb15be)
[docset/mdop/appvserver/unpublish-appvserverpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/unpublish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-b1029600-72eb15be)
[docset/windows/appvclient/Get-AppvClientApplication.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Get-AppvClientApplication.md) | :warning:Warning | | [Details](#user-content-8e28c3ce-72eb15be)
[docset/mdop/appvclient/set-appvpublishingserver.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/set-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-85260d09-72eb15be)
[docset/mdop/mbam/get-mbambitlockerrecoverykey.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/mbam/get-mbambitlockerrecoverykey.md) | :warning:Warning | | [Details](#user-content-1a2741fb-72eb15be)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-72eb15be)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-72eb15be)
[doc [...]

2020-11-17 16:43 UTC, e0i commented
Reopening to run checks

2020-11-17 16:47 UTC, opbld31 commented
Docs Build status updates of commit _[771e70f](https://github.com/dhmhd/windows-powershell-docs/commits/771e70f46f6f51501e6ed9dcc6ad0362d7759d4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171643256302-2179%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kfqRdNDilzvzGhwo96ArNQosjo33yqrBDS5OuZ4LCpU%3D&st=2020-11-17T16%3A42%3A51Z&se=2020-12-18T16%3A47%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 13:12 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-18 13:48 UTC, get-itips commented on docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md
> +Specifies the local port for the ACL. Also a ports range format can be used (i.e. "49152-49182", for example).
```suggestion
Specifies the local port for the ACL. A port range format can be used also (i.e. "49152-49182", for example).
```

2020-11-18 13:49 UTC, get-itips commented on docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md
> +Specifies the remote port for the ACL. Also a ports range format can be used (i.e. "49152-49182", for example).
```suggestion
Specifies the remote port for the ACL. A port range format can be used also  (i.e. "49152-49182", for example).
```

2020-11-18 13:50 UTC, get-itips reviewed
Thanks for the contribution

2020-11-18 13:51 UTC, dariomws requested changes

2020-11-18 13:51 UTC, dariomws commented on docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md
> +Specifies the remote port for the ACL. Also a ports range format can be used (i.e. "49152-49182", for example).
```suggestion
Specifies the local port for the ACL. A port range format can also be used (i.e. "49152-49182", for example).
```

2020-11-18 13:51 UTC, dariomws commented on docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md
> +Specifies the local port for the ACL. Also a ports range format can be used (i.e. "49152-49182", for example).
```suggestion
Specifies the local port for the ACL. A port range format can also be used (i.e. "49152-49182", for example).
```

2020-11-18 14:30 UTC, dariomws commented
The same information can also be added to W2016 article.

2020-11-18 15:01 UTC, JohanFreelancer9 requested changes
Sorry Andres, have to go with Dario on this one.

2020-12-16 16:14 UTC, tseward approved these changes
Approved pending dariomws' changes.

2020-12-17 15:06 UTC, e0i commented
@dhmhd This PR is good to go once the suggested changes have been applied. Thank you.

2021-01-14 17:23 UTC, opbld32 commented
Docs Build status updates of commit _[49f3ba2](https://github.com/dhmhd/windows-powershell-docs/commits/49f3ba20a86a3230cd2956e9b1cc4f4c5cef9f46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=win10-ps&branch=pr-en-us-2179) (win10-ps) |
[docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=winserver2012r2-ps&branch=pr-en-us-2179) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101141719322152-2179%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qa%2FcVG9VGoInTqQ9U3NiYfkGiKWuWgSGGTkPBFgvk7U%3D&st=2021-01-14T17%3A18%3A20Z&se=2021-02-14T17%3A23%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 04:13 UTC, JohanFreelancer9 approved these changes

2021-02-09 19:19 UTC, opbld30 commented
Docs Build status updates of commit _[dcdd981](https://github.com/dhmhd/windows-powershell-docs/commits/dcdd98116d100997f46952a66232484949bf1a10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=win10-ps&branch=pr-en-us-2179) (win10-ps) |
[docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=winserver2012r2-ps&branch=pr-en-us-2179) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102091915300709-2179%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8bjT%2FkG%2BW6Yb%2BjyYE2rekji6YxI%2FW1OpDgvYlgjtn%2BU%3D&st=2021-02-09T19%3A14%3A55Z&se=2021-03-12T19%3A19%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 19:24 UTC, tiburd commented
close > reopen

2021-02-09 19:24 UTC, opbld31 commented
Docs Build status updates of commit _[27d2094](https://github.com/dhmhd/windows-powershell-docs/commits/27d2094dca94691a02d00847758831f032772c1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=win10-ps&branch=pr-en-us-2179) (win10-ps) |
[docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=winserver2012r2-ps&branch=pr-en-us-2179) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102091917135165-2179%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Bn19C1KIV3qXftn2kysZmX6fdUx7cMNJoriET9fNdDI%3D&st=2021-02-09T19%3A19%3A43Z&se=2021-03-12T19%3A24%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 19:25 UTC, merged

2021-02-09 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[27d2094](https://github.com/dhmhd/windows-powershell-docs/commits/27d2094dca94691a02d00847758831f032772c1e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=win10-ps&branch=pr-en-us-2179) (win10-ps) |
[docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md](https://github.com/dhmhd/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Add-VMNetworkAdapterExtendedAcl.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/add-vmnetworkadapterextendedacl?view=winserver2012r2-ps&branch=pr-en-us-2179) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102091925287315-2179%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FDrci8bkn%2FZYTr766QYhL2IP71VJD01wRBMJUxXD2b0%3D&st=2021-02-09T19%3A24%3A10Z&se=2021-03-12T19%3A29%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>