Update Set-VMHost: accurate info on default folders
MicrosoftDocs/windows-powershell-docs pull request #2182
Opened 2020-10-28 18:32 UTC by skycommand

Areas of change:
- Example 4
    - Fix one typo
    - Give more accurate info about what's stored where
- -VirtualHardDiskPath
    - Explain that it is not a functional setting
- -VirtualMachinePath
    - Explain that it is a functional setting and Hyper-V creates a "Virtual Machines" sub-folder

2020-10-28 18:37 UTC, opbld30 commented
Docs Build status updates of commit _[e78644f](https://github.com/skycommand/windows-powershell-docs/commits/e78644f81e02853ec087c1e35a12494df571aa08)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :warning:Warning | | [Details](#user-content-1f3b574a-09730dcd)
[docset/windows/appvclient/Set-AppvPublishingServer.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Set-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-49b32784-09730dcd)
[docset/mdop/appvclient/mount-appvclientconnectiongroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/mount-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-7312a5c5-09730dcd)
[docset/windows/appvclient/Stop-AppvClientConnectionGroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Stop-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-b73e720d-09730dcd)
[docset/mdop/appvclient/get-appvclientpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/get-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-0b6ba1b7-09730dcd)
[docset/windows/appvclient/Remove-AppvClientPackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Remove-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-72400978-09730dcd)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-09730dcd)
[docset/mdop/appvsequencer/update-appvsequencerpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvsequencer/update-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-7eb4d3d1-09730dcd)
[docset/mdop/appvserver/new-appvserverconnectiongroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/new-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-899a17da-09730dcd)
[docset/windows/appvclient/Sync-AppvPublishingServer.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Sync-AppvPublishingServer.md) | :warning:Warning | | [Details](#user-content-4b9a6faf-09730dcd)
[docset/windows/appvclient/Stop-AppvClientPackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Stop-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-f7ffc343-09730dcd)
[docset/windows/appvclient/Start-AppvVirtualProcess.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Start-AppvVirtualProcess.md) | :warning:Warning | | [Details](#user-content-65e3cb88-09730dcd)
[docset/mdop/appvserver/grant-appvserverpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/grant-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-0b27961f-09730dcd)
[docset/mdop/appvclient/stop-appvclientconnectiongroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/stop-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-72e2c169-09730dcd)
[docset/mdop/appvsequencer/new-appvsequencerpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvsequencer/new-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-668f4784-09730dcd)
[docset/windows/appvsequencer/Update-AppvSequencerPackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvsequencer/Update-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-abffa8f3-09730dcd)
[docset/mdop/appvsequencer/new-appvpackageaccelerator.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvsequencer/new-appvpackageaccelerator.md) | :warning:Warning | | [Details](#user-content-6d66a49a-09730dcd)
[docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/unpublish-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-36bc4373-09730dcd)
[docset/mdop/agpm/get-controlledgpo.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/agpm/get-controlledgpo.md) | :warning:Warning | | [Details](#user-content-8529f522-09730dcd)
[docset/mdop/appvclient/unpublish-appvclientpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/unpublish-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-038bfac8-09730dcd)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-09730dcd)
[docset/mdop/appvserver/remove-appvserverconnectiongroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/remove-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-494ada64-09730dcd)
[docset/windows/appvclient/Get-AppvClientPackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Get-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-c7bca43d-09730dcd)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-09730dcd)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-09730dcd)
[docset/mdop/appvclient/start-appvvirtualprocess.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/start-appvvirtualprocess.md) | :warning:Warning | | [Details](#user-content-ee3d70b3-09730dcd)
[docset/windows/appvclient/Mount-AppvClientConnectionGroup.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvclient/Mount-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-f6dc7c62-09730dcd)
[docset/mdop/appvclient/sync-appvpublishingserver.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvclient/sync-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-10723e77-09730dcd)
[docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/get-appvserverpackageuserconfiguration.md) | :warning:Warning | | [Details](#user-content-96de03ef-09730dcd)
[docset/mdop/appvserver/import-appvserverpackage.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/mdop/appvserver/import-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ae2d5b45-09730dcd)
[docset/windows/appvsequencer/New-AppvPackageAccelerator.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/appvsequencer/New-AppvPackageAccelerator.md) | :warning:Warning | | [Details](#user-content-ff826ff1-09730dcd)
[docset/mdop/appvclient/remove-appvpublishingserver.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/ [...]

2020-11-17 16:52 UTC, opbld31 commented
Docs Build status updates of commit _[e78644f](https://github.com/skycommand/windows-powershell-docs/commits/e78644f81e02853ec087c1e35a12494df571aa08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171648118545-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UixR2MyJoHlfS6KRA26rAy2P45J5lVxH50kCpxYMjJc%3D&st=2020-11-17T16%3A47%3A45Z&se=2020-12-18T16%3A52%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 13:14 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-18 14:22 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/Set-VMHost.md
> +Specifies the default folder to store virtual hard disks on the Hyper-V host. This is not a functional setting. The Hyper-V Manager snap-in and Windows Admin Center query it to offer you a default pa
```suggestion
Specifies the default folder to store virtual hard disks on the Hyper-V host. This is not a functional setting. The Hyper-V Manager snap-in and Windows Admin Center query it to offer you a default path, but the Hyper-V API (for example `CreateFixedVirtualHardDisk`) and `New-VHD` don't use it.
```

2020-11-18 14:23 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/Set-VMHost.md
> +Specifies the default folder to store virtual machine configuration files on the Hyper-V host. This is a functional setting, meaning that if you do not supply a path to VM creations tools (e.g. `New-
```suggestion
Specifies the default folder to store virtual machine configuration files on the Hyper-V host. This is a functional setting, meaning that if you do not supply a path to VM creation tools (for example `New-VM`), Hyper-V will use this path. Hyper-V will create at least one subfolder in this path, called "Virtual Machines".
```

2020-11-18 14:26 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-18 14:57 UTC, opbld33 commented
Docs Build status updates of commit _[6ee4a9b](https://github.com/skycommand/windows-powershell-docs/commits/6ee4a9bb1eb8593b6ac04fd75d7965b2ece8aab1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181453163656-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ac%2Fxv4y4RKA8cOE0gck6ZA0lOjscSnjFGWvhOOUWMTA%3D&st=2020-11-18T14%3A52%3A56Z&se=2020-12-19T14%3A57%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 15:01 UTC, opbld30 commented
Docs Build status updates of commit _[3957b1f](https://github.com/skycommand/windows-powershell-docs/commits/3957b1f3c5f1a4764f70c9ed16ecd6284f658b40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181453240336-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KV9nl5YlRpWzlZ84liScOuqGgRTMgk%2Bl8krtNGX2Wr8%3D&st=2020-11-18T14%3A56%3A56Z&se=2020-12-19T15%3A01%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 15:13 UTC, JohanFreelancer9 approved these changes

2020-11-18 15:15 UTC, dariomws approved these changes
Thanks @skycommand!

2020-11-18 15:16 UTC, dariomws commented
I think the same information could be added to 2012 and 2012 R2 articles.

2020-11-18 15:29 UTC, skycommand commented
@dariomws Done.

2020-11-18 15:30 UTC, dariomws commented
Thanks @skycommand!

2020-11-18 15:32 UTC, opbld33 commented
Docs Build status updates of commit _[8e550c2](https://github.com/skycommand/windows-powershell-docs/commits/8e550c2ed611596ce5eeea163d756f105f7b5b39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181528260435-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vaoi%2B6Mo7ciHYUMy%2BH5bgRAw1zcggLJbjn3AHi9K%2BEg%3D&st=2020-11-18T15%3A27%3A58Z&se=2020-12-19T15%3A32%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 15:33 UTC, tseward approved these changes

2020-11-18 15:37 UTC, opbld33 commented
Docs Build status updates of commit _[9afb40f](https://github.com/skycommand/windows-powershell-docs/commits/9afb40f0c77db2886c754d88513826398a79a6a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181528381936-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JvpHno6T0rUJURYERlITQ2QcyaHTQSfNinvxVhjeuqU%3D&st=2020-11-18T15%3A32%3A32Z&se=2020-12-19T15%3A37%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 15:57 UTC, opbld33 commented
Docs Build status updates of commit _[0c2b5ee](https://github.com/skycommand/windows-powershell-docs/commits/0c2b5ee9aace5b589e0c94a7f6d1ad13947d5606)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181553154089-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wQY41lLivGuZ5Sad3byshTgWxetq7Urlngu0h2zcdn8%3D&st=2020-11-18T15%3A52%3A39Z&se=2020-12-19T15%3A57%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 16:51 UTC, get-itips approved these changes

2020-12-09 02:14 UTC, opbld30 commented
Docs Build status updates of commit _[4d17b67](https://github.com/skycommand/windows-powershell-docs/commits/4d17b6742973670a716c0edf937cc4b554acc2c4)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-09 02:18 UTC, opbld31 commented
Docs Build status updates of commit _[4d17b67](https://github.com/skycommand/windows-powershell-docs/commits/4d17b6742973670a716c0edf937cc4b554acc2c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=win10-ps&branch=pr-en-us-2182) (win10-ps) |
[docset/winserver2012-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=winserver2012-ps&branch=pr-en-us-2182) (winserver2012-ps) |
[docset/winserver2012r2-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=winserver2012r2-ps&branch=pr-en-us-2182) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012090214278445-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HwEkl0kflfQiPSXSg6FQScSj9jtbwojxFnfGAh9cqD4%3D&st=2020-12-09T02%3A13%3A49Z&se=2021-01-09T02%3A18%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 16:21 UTC, opbld30 commented
Docs Build status updates of commit _[f83e7c5](https://github.com/skycommand/windows-powershell-docs/commits/f83e7c58ae2c014aa125e037b41fe7ce93c5ca15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=win10-ps&branch=pr-en-us-2182) (win10-ps) |
[docset/winserver2012-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=winserver2012-ps&branch=pr-en-us-2182) (winserver2012-ps) |
[docset/winserver2012r2-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=winserver2012r2-ps&branch=pr-en-us-2182) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012151616487980-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iL4ho7cEoliero2%2B8pOx6%2Bfwv9DkkcT%2Fu8cmJtsANcw%3D&st=2020-12-15T16%3A16%3A22Z&se=2021-01-15T16%3A21%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 16:31 UTC, opbld30 commented
Docs Build status updates of commit _[12b461a](https://github.com/skycommand/windows-powershell-docs/commits/12b461a7e91af6bf5e5d4589b2351453e58a5c6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/windows/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=win10-ps&branch=pr-en-us-2182) (win10-ps) |
[docset/winserver2012-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=winserver2012-ps&branch=pr-en-us-2182) (winserver2012-ps) |
[docset/winserver2012r2-ps/hyper-v/Set-VMHost.md](https://github.com/skycommand/windows-powershell-docs/blob/patch-1/docset/winserver2012r2-ps/hyper-v/Set-VMHost.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmhost?view=winserver2012r2-ps&branch=pr-en-us-2182) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012151626419359-2182%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GapDK33Uk6wxFJ%2BnY0BK3Qg35YPuwluppHoKS2gQkfY%3D&st=2020-12-15T16%3A26%3A05Z&se=2021-01-15T16%3A31%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 16:31 UTC, merged