added several examples
MicrosoftDocs/windows-powershell-docs pull request #2197
Opened 2020-11-05 17:22 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/300

2020-11-05 17:22 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-11-05 17:26 UTC, opbld33 commented
Docs Build status updates of commit _[8dd638d](https://github.com/MaratMussabekov/windows-powershell-docs/commits/8dd638dc0e8de07489209cad5a35270f97f02b0a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :warning:Warning | | [Details](#user-content-76439e95-d527f99d)
[docset/mdop/appvclient/set-appvclientmode.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/set-appvclientmode.md) | :warning:Warning | | [Details](#user-content-2a4e3610-d527f99d)
[docset/mdop/appvclient/remove-appvclientconnectiongroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/remove-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-c3a07c83-d527f99d)
[docset/mdop/appvclient/set-appvclientconfiguration.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/set-appvclientconfiguration.md) | :warning:Warning | | [Details](#user-content-e8612c98-d527f99d)
[docset/mdop/agpm/unlock-controlledgpo.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/agpm/unlock-controlledgpo.md) | :warning:Warning | | [Details](#user-content-0f6d474a-d527f99d)
[docset/windows/appvclient/Start-AppvVirtualProcess.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Start-AppvVirtualProcess.md) | :warning:Warning | | [Details](#user-content-65e3cb88-d527f99d)
[docset/windows/appvclient/Set-AppvClientPackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Set-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-176b49b4-d527f99d)
[docset/mdop/appvsequencer/expand-appvsequencerpackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvsequencer/expand-appvsequencerpackage.md) | :warning:Warning | | [Details](#user-content-85aad0ce-d527f99d)
[docset/windows/appvclient/Add-AppvClientPackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Add-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-9818d699-d527f99d)
[docset/mdop/appvclient/add-appvclientpackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/add-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-36cd6076-d527f99d)
[docset/windows/appvclient/Remove-AppvClientPackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Remove-AppvClientPackage.md) | :warning:Warning | | [Details](#user-content-72400978-d527f99d)
[docset/windows/appvclient/Stop-AppvClientConnectionGroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Stop-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-b73e720d-d527f99d)
[docset/windows/appvsequencer/Expand-AppvSequencerPackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvsequencer/Expand-AppvSequencerPackage.md) | :warning:Warning | | [Details](#user-content-93a1ef35-d527f99d)
[docset/windows/appvclient/Mount-AppvClientConnectionGroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Mount-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-f6dc7c62-d527f99d)
[docset/mdop/appvserver/publish-appvserverpackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/publish-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-ca8570a2-d527f99d)
[docset/mdop/appvclient/get-appvvirtualprocess.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/get-appvvirtualprocess.md) | :warning:Warning | | [Details](#user-content-7b156128-d527f99d)
[docset/windows/appvclient/Set-AppvClientMode.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Set-AppvClientMode.md) | :warning:Warning | | [Details](#user-content-002817af-d527f99d)
[docset/windows/appvclient/Set-AppvClientConfiguration.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Set-AppvClientConfiguration.md) | :warning:Warning | | [Details](#user-content-6523cc1b-d527f99d)
[docset/mdop/appvclient/get-appvpublishingserver.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/get-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-aff0e31e-d527f99d)
[docset/mdop/appvclient/sync-appvpublishingserver.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/sync-appvpublishingserver.md) | :warning:Warning | | [Details](#user-content-10723e77-d527f99d)
[docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/remove-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-22c33323-d527f99d)
[docset/windows/appvclient/Remove-AppvClientConnectionGroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Remove-AppvClientConnectionGroup.md) | :warning:Warning | | [Details](#user-content-404478c9-d527f99d)
[docset/mdop/appvclient/mount-appvclientpackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/mount-appvclientpackage.md) | :warning:Warning | | [Details](#user-content-46fdce12-d527f99d)
[docset/mdop/appvserver/get-appvserverpackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/get-appvserverpackage.md) | :warning:Warning | | [Details](#user-content-9ec4b047-d527f99d)
[docset/mdop/appvclient/stop-appvclientconnectiongroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvclient/stop-appvclientconnectiongroup.md) | :warning:Warning | | [Details](#user-content-72e2c169-d527f99d)
[docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/add-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-e20248ea-d527f99d)
[docset/mdop/appvserver/get-appvserverconnectiongroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/get-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-33cb0490-d527f99d)
[docset/windows/appvclient/Get-AppvVirtualProcess.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/appvclient/Get-AppvVirtualProcess.md) | :warning:Warning | | [Details](#user-content-689bc065-d527f99d)
[docset/mdop/appvserver/update-appvserverconnectiongroup.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/update-appvserverconnectiongroup.md) | :warning:Warning | | [Details](#user-content-5e65d59f-d527f99d)
[docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/appvserver/set-appvserverconnectiongrouppackage.md) | :warning:Warning | | [Details](#user-content-6a8cd355-d527f99d)
[docset/mdop/mbam/disable-mbamwebapplication.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/mdop/mbam/disable-mbamwebapplication.md) | :warning:Warning | | [Details](#user-content-121c5d3d-d527f99d [...]

2020-11-06 04:05 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/New-VM.md
> +This example creates a virtual machine named new 5. The machine doesn't have any VHD disk and set to boot from CD.
```suggestion
This example creates a virtual machine named new 5. The machine doesn't have any VHD disk and is set to boot from CD. 
```

2020-11-06 04:06 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/New-VM.md
> +This example creates a virtual machine named new 6. The machine has the same generation and amount of assigned memory as existing machine named old 1, and connected to the same network switch.
```suggestion
This example creates a virtual machine named new 6. The machine has the same generation and amount of assigned memory as the existing machine named old 1 and connects to the same network switch.
```

2020-11-06 04:12 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/New-VM.md
> +This example asks for credentials, then creates a virtual machine named new 4 that has 2 GB of memory on the server named HostServer01.
```suggestion
This example asks for credentials, then creates a virtual machine named new 4, which has 2 GB of memory, on the server named HostServer01.
```

2020-11-06 04:13 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-08 02:56 UTC, opbld31 commented
Docs Build status updates of commit _[fd6f02a](https://github.com/MaratMussabekov/windows-powershell-docs/commits/fd6f02a2addf4e904ebd53c45e52e59b3e692bfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011080251502272-2197%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8JvxA%2FLUvRlINlMzehxrwaCDoTE1zpkEwatxf4kGJv4%3D&st=2020-11-08T02%3A51%3A11Z&se=2020-12-09T02%3A56%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 03:00 UTC, opbld31 commented
Docs Build status updates of commit _[a856df5](https://github.com/MaratMussabekov/windows-powershell-docs/commits/a856df5449adffae9ec39a382baecae5665c708e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011080252135397-2197%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EhkN4GTpbrE1bMmjdoYAq3nu%2FOsH0o3L%2FsBbLV3LCqs%3D&st=2020-11-08T02%3A55%3A38Z&se=2020-12-09T03%3A00%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-08 04:16 UTC, JohanFreelancer9 approved these changes

2020-11-17 17:29 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-17 18:58 UTC, dariomws approved these changes
These updates are good for me.

Anyway, I think the author of the issues is also asking us to fill in the missing descriptions of the parameters. And, we can add/update the same information for the W2012 and W2012 R2 versions.

2020-11-17 20:02 UTC, get-itips approved these changes

2020-11-18 15:42 UTC, tseward approved these changes

2020-11-19 15:54 UTC, opbld31 commented
Docs Build status updates of commit _[c6bb3ab](https://github.com/MaratMussabekov/windows-powershell-docs/commits/c6bb3ab8ce38ba8e1b3c575a826c6ad0147e8ac7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011191550277411-2197%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1apR7hjQ5m7EXCwLeZPDSM6u6xmMDiT8q3PfESz%2BjAM%3D&st=2020-11-19T15%3A49%3A43Z&se=2020-12-20T15%3A54%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 15:57 UTC, MaratMussabekov commented
hello, added for WS2012 and WS2012 R2
Thank you

2020-11-19 15:59 UTC, opbld33 commented
Docs Build status updates of commit _[6e9e73e](https://github.com/MaratMussabekov/windows-powershell-docs/commits/6e9e73ebc4ed29f916cf6b95e196334843684f2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012r2-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011191551121796-2197%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VcLLt19cNAV2Dh3PcJlXMkW6gitE%2FYmNtXPMbDtqi0o%3D&st=2020-11-19T15%3A54%3A12Z&se=2020-12-20T15%3A59%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 16:03 UTC, opbld32 commented
Docs Build status updates of commit _[4336618](https://github.com/MaratMussabekov/windows-powershell-docs/commits/433661895f9c5157befc890568788217d3711231)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012r2-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011191555173696-2197%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jmVVVNiowLcb8RSmj4oQIOVQHzPyNwa1e6yowGuRdVA%3D&st=2020-11-19T15%3A58%3A29Z&se=2020-12-20T16%3A03%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 16:28 UTC, opbld33 commented
Docs Build status updates of commit _[397ccd3](https://github.com/MaratMussabekov/windows-powershell-docs/commits/397ccd377630f6641249b6599d5e5d3b16432019)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/windows/hyper-v/New-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/new-vm?view=win10-ps&branch=pr-en-us-2197) (win10-ps) |
[docset/winserver2012-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/new-vm?view=winserver2012-ps&branch=pr-en-us-2197) (winserver2012-ps) |
[docset/winserver2012r2-ps/hyper-v/New-VM.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-11/docset/winserver2012r2-ps/hyper-v/New-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/new-vm?view=winserver2012r2-ps&branch=pr-en-us-2197) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012091624244275-2197%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ssI6vUXuZyCP7BwMUSCFEETHKoifbtPcCrcxhjpTQtk%3D&st=2020-12-09T16%3A23%3A55Z&se=2021-01-09T16%3A28%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 16:35 UTC, merged