Update Set-VpnConnectionProxy.md
MicrosoftDocs/windows-powershell-docs pull request #2201
Opened 2020-11-10 15:12 UTC by msarcletti

Adding additional information for the scope / limitation of the VPN proxy settings configuration

2020-11-10 15:16 UTC, opbld32 commented
Docs Build status updates of commit _[9f6f365](https://github.com/msarcletti/windows-powershell-docs/commits/9f6f3656ded89aa9598a55c3817b342f83a38948)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Set-VpnConnectionProxy.md](https://github.com/msarcletti/windows-powershell-docs/blob/patch-1/docset/windows/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011101512248857-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vX%2FI5ClG3LdGMfNanbCrnGeU3Ok4BTe9vd9FsnrZHN0%3D&st=2020-11-10T15%3A11%3A44Z&se=2020-12-11T15%3A16%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 07:57 UTC, opbld32 commented
Docs Build status updates of commit _[81aef52](https://github.com/msarcletti/windows-powershell-docs/commits/81aef52a94b625c8a7b691541b3cea67dedc0ef6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Set-VpnConnectionProxy.md](https://github.com/msarcletti/windows-powershell-docs/blob/patch-1/docset/windows/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011130753464997-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VmFZ0hLA2z5shXgR2DSuD2q4uvCUgqAuJz8QWOcNZDM%3D&st=2020-11-13T07%3A52%3A42Z&se=2020-12-14T07%3A57%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-13 08:02 UTC, opbld30 commented
Docs Build status updates of commit _[be39b3a](https://github.com/msarcletti/windows-powershell-docs/commits/be39b3a04fe72f5ffe8cd79d2b0b0c15c1705138)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Set-VpnConnectionProxy.md](https://github.com/msarcletti/windows-powershell-docs/blob/patch-1/docset/windows/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C13%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011130755389970-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AfJ7UDMQ94pjCbtbR312z9M2gH8meRNY7K7GEFZhdRc%3D&st=2020-11-13T07%3A57%3A20Z&se=2020-12-14T08%3A02%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:29 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-17 17:29 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-17 18:36 UTC, dariomws approved these changes
I think the same note should be added to W2012 and W2012 R2 articles.

2020-11-17 20:00 UTC, get-itips requested changes
We can not use the [!NOTE] tag on cmdlet's articles, it will not render ok on Get-Help output.
Thanks for the contribution!

2020-11-18 04:34 UTC, JohanFreelancer9 commented on docset/windows/vpnclient/Set-VpnConnectionProxy.md
> +>[!NOTE]
```suggestion
```

2020-11-18 04:41 UTC, JohanFreelancer9 commented on docset/windows/vpnclient/Set-VpnConnectionProxy.md
> +> VPN proxy settings are only used on Force Tunnel Connections. On Split Tunnel Connections, the general proxy settings are used.
```suggestion
Note that VPN proxy settings are only used on forced tunnel connections. On split tunnel connections, the general proxy settings are used.
```

2020-11-18 04:41 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-18 16:04 UTC, tseward approved these changes

2020-11-20 07:38 UTC, opbld31 commented
Docs Build status updates of commit _[2171162](https://github.com/msarcletti/windows-powershell-docs/commits/217116258fec091eababa4c16f12c951746c7328)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Set-VpnConnectionProxy.md](https://github.com/msarcletti/windows-powershell-docs/blob/patch-1/docset/windows/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011200734390833-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mdVWg76VzXW%2F3m7ntyBXYjlNNWf7F94C%2FjDFTTPx15k%3D&st=2020-11-20T07%3A33%3A56Z&se=2020-12-21T07%3A38%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 07:43 UTC, opbld33 commented
Docs Build status updates of commit _[f052791](https://github.com/msarcletti/windows-powershell-docs/commits/f052791fa0d1b667e0dc11c8f289f2cba68a2bff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Set-VpnConnectionProxy.md](https://github.com/msarcletti/windows-powershell-docs/blob/patch-1/docset/windows/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011200735440384-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CQ0n2HG9Pv%2BPsQ4IHiaArA1ULvFTzje4hnB2qjPl16Y%3D&st=2020-11-20T07%3A38%3A09Z&se=2020-12-21T07%3A43%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 08:22 UTC, JohanFreelancer9 approved these changes

2020-11-20 13:18 UTC, get-itips approved these changes

2020-12-15 17:09 UTC, opbld31 commented
Docs Build status updates of commit _[5aff68d](https://github.com/msarcletti/windows-powershell-docs/commits/5aff68dbec2f38738bf2e35800a7ea01aa2930c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Set-VpnConnectionProxy.md](https://github.com/msarcletti/windows-powershell-docs/blob/patch-1/docset/windows/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionproxy?view=win10-ps&branch=pr-en-us-2201) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012151705063429-2201%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CGESBIm5X4iXZzKR6m9flJ0nBnZgULixKJuY3rENG%2FE%3D&st=2020-12-15T17%3A04%3A30Z&se=2021-01-15T17%3A09%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 17:10 UTC, merged