added note about elevation
MicrosoftDocs/windows-powershell-docs pull request #2203
Opened 2020-11-14 15:35 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2015

2020-11-14 15:35 UTC, opbld30 commented
Docs Build status updates of commit _[832c45f](https://github.com/MaratMussabekov/windows-powershell-docs/commits/832c45f26c003399123ec974842880553cd8992d)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-14 15:36 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-11-15 01:39 UTC, JohanFreelancer9 approved these changes

2020-11-15 03:23 UTC, opbld32 commented
Docs Build status updates of commit _[832c45f](https://github.com/MaratMussabekov/windows-powershell-docs/commits/832c45f26c003399123ec974842880553cd8992d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Install-ADServiceAccount.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-12/docset/windows/addsadministration/Install-ADServiceAccount.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011141535174295-2203%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kcoTi%2BhtMbjYjZLP1wvqOvAAfzMpBP4MQsPknfmCdRw%3D&st=2020-11-15T03%3A18%3A18Z&se=2020-12-16T03%3A23%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-15 14:49 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-15 14:54 UTC, get-itips approved these changes

2020-11-15 18:13 UTC, tseward requested changes

2020-11-15 18:13 UTC, tseward commented on docset/windows/addsadministration/Install-ADServiceAccount.md
> +* This cmdlet must be run from elevated PowerShell session.
This cmdlet must be run from an elevated PowerShell session.

2020-11-16 13:30 UTC, dariomws approved these changes

2020-11-16 13:30 UTC, dariomws commented on docset/windows/addsadministration/Install-ADServiceAccount.md
> +* This cmdlet must be run from elevated PowerShell session.
```suggestion
* This cmdlet must be run from an elevated PowerShell session.
```

Agree with @tseward.

2020-11-16 13:35 UTC, dariomws commented
@MaratMussabekov I think we should also add this information to the W2012 R2 article.

2020-11-16 14:12 UTC, MaratMussabekov commented
Hello, done, please have a look at #2211 
Thank you!

2020-11-16 14:14 UTC, opbld30 commented
Docs Build status updates of commit _[108f98b](https://github.com/MaratMussabekov/windows-powershell-docs/commits/108f98b4f909c584cb0e7da692a27a41fa24e226)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Install-ADServiceAccount.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-12/docset/windows/addsadministration/Install-ADServiceAccount.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011161409384885-2203%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OGn4xAG9wBCm0wmRdnfS8OSiug%2BDfV8ZhDOSXwABasA%3D&st=2020-11-16T14%3A09%3A00Z&se=2020-12-17T14%3A14%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 20:18 UTC, tseward commented
Is this universal? I suspect it isn't when running from a client machine.

2020-11-27 03:22 UTC, MaratMussabekov commented
Hello @tseward ,
could you please clarify?
Thank you

2020-11-27 18:29 UTC, tseward commented
> Hello @tseward ,
> could you please clarify?
> Thank you

Does this require elevation when running from a client machine?

2020-11-28 21:39 UTC, MaratMussabekov commented
Hello,
yes, for remote sessions, including sessions from client computers, elevation is required too.
Thank you

2021-02-09 19:16 UTC, opbld32 commented
Docs Build status updates of commit _[fe0cfbd](https://github.com/MaratMussabekov/windows-powershell-docs/commits/fe0cfbd3897096d9eb2685f3852a7770a4e91f6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/Install-ADServiceAccount.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-12/docset/windows/addsadministration/Install-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/install-adserviceaccount?view=win10-ps&branch=pr-en-us-2203) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102091911586351-2203%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TuGfqdL1l%2FIgYAhxVcaaa1MVKoSyWpJpIykitgu7NhM%3D&st=2021-02-09T19%3A10%3A58Z&se=2021-03-12T19%3A15%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 19:16 UTC, merged