Resolves #1812
MicrosoftDocs/windows-powershell-docs pull request #2207
Opened 2020-11-15 14:52 UTC by velkovb

Provide more info on setting Application pool properties
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1812

2020-11-15 14:56 UTC, opbld32 commented
Docs Build status updates of commit _[95582b5](https://github.com/velkovb/windows-powershell-docs/commits/95582b50d3ffb8768d0a933ff8603763cd244ea7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011151452174176-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3ASOL4OPnz2%2BPeLW8LakdUkv5XSZPvv%2FwRkHWw6rDC0%3D&st=2020-11-15T14%3A51%3A49Z&se=2020-12-16T14%3A56%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-15 15:01 UTC, opbld32 commented
Docs Build status updates of commit _[8a78db8](https://github.com/velkovb/windows-powershell-docs/commits/8a78db83a3e28fd324402f1675d2654d9fd3a92d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011151453457313-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4LSFnQ5GO9qAWG3zSjDslFjAspQI3R9Q1Oe%2FOWuKeJU%3D&st=2020-11-15T14%3A56%3A31Z&se=2020-12-16T15%3A01%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:24 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-17 17:24 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-17 19:06 UTC, dariomws approved these changes
Just a small suggestion.

2020-11-17 19:06 UTC, dariomws commented on docset/windows/webadministration/New-WebAppPool.md
> +The **New-WebAppPool** cmdlet creates an Internet Information Services (IIS) application pool. For changing different properties of the application pool after creation check the following article - [
```suggestion
The **New-WebAppPool** cmdlet creates an Internet Information Services (IIS) application pool. For changing different properties of the application pool after creation, see [PowerShell Snap-in: Making Configuration Changes to Websites and App Pools](https://docs.microsoft.com/iis/manage/powershell/powershell-snap-in-making-simple-configuration-changes-to-web-sites-and-application-pools).
```

2020-11-17 19:51 UTC, get-itips reviewed
Agree when @dariomws suggestions are applied.

2020-11-17 20:00 UTC, opbld32 commented
Docs Build status updates of commit _[fe3635c](https://github.com/velkovb/windows-powershell-docs/commits/fe3635c9300d0decf2d9b55cd58e389e189be7d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171956037800-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sbRq2Y3v%2FYLEMlxsGLcp%2FVO7MsLx4vabxZPTtWOqjqQ%3D&st=2020-11-17T19%3A55%3A23Z&se=2020-12-18T20%3A00%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 20:03 UTC, get-itips approved these changes

2020-11-17 20:38 UTC, opbld33 commented
Docs Build status updates of commit _[c950958](https://github.com/velkovb/windows-powershell-docs/commits/c9509582f8b7d5083fc77b4a8fdd4331d544e5a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011172033571755-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YE7GMoj4cDQsRGZMniU3THI5X1qewDXk7%2FBTf1WOWtk%3D&st=2020-11-17T20%3A33%3A21Z&se=2020-12-18T20%3A38%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 04:14 UTC, JohanFreelancer9 commented on docset/windows/webadministration/New-WebAppPool.md
> +### Example 2: Create an IIS application pool and set managedRuntimeVersion
```suggestion
### Example 3: Create an IIS application pool and set managedRuntimeVersion
```

2020-11-18 04:14 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/webadminstration/New-WebAppPool.md
> +The **New-WebAppPool** cmdlet creates an Internet Information Services (IIS) application pool. For changing different properties of the application pool after creation check, see [PowerShell Snap-in:
```suggestion
The **New-WebAppPool** cmdlet creates an Internet Information Services (IIS) application pool. For changing different properties of the application pool after creation, see [PowerShell Snap-in: Making Configuration Changes to Websites and App Pools](https://docs.microsoft.com/iis/manage/powershell/powershell-snap-in-making-simple-configuration-changes-to-web-sites-and-application-pools).
```

2020-11-18 04:14 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/webadminstration/New-WebAppPool.md
> +### Example 2: Create an IIS application pool and set managedRuntimeVersion
```suggestion
### Example 3: Create an IIS application pool and set managedRuntimeVersion
```

2020-11-18 04:15 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/webadministration/New-WebAppPool.md
> +### Example 2: Create an IIS application pool and set managedRuntimeVersion
```suggestion
### Example 3: Create an IIS application pool and set managedRuntimeVersion
```

2020-11-18 04:15 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-18 07:06 UTC, opbld33 commented
Docs Build status updates of commit _[c36bbe6](https://github.com/velkovb/windows-powershell-docs/commits/c36bbe681d4505fb7edc429e945d886d2b67c027)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011180702374629-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DJYsYGYqGChMlEtTWxZcvwV1MaydQ%2B8LV9zbXqFlF3E%3D&st=2020-11-18T07%3A01%3A50Z&se=2020-12-19T07%3A06%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 07:40 UTC, JohanFreelancer9 approved these changes

2020-11-18 16:02 UTC, tseward approved these changes
Approve pending changes

2020-11-24 15:46 UTC, opbld33 commented
Docs Build status updates of commit _[481269d](https://github.com/velkovb/windows-powershell-docs/commits/481269d7ac9a77871c11c8373f8c7cb1f2d12ccc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011241541485444-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hUnsHpHxfNg1NcSqnwIHQkxfiYgzKLriSDTFzqTiLBA%3D&st=2020-11-24T15%3A41%3A09Z&se=2020-12-25T15%3A46%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 18:13 UTC, opbld30 commented
Docs Build status updates of commit _[2997647](https://github.com/velkovb/windows-powershell-docs/commits/29976471b45a679462561ead7d173af8af3a12f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/windows/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/webadminstration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012-ps/webadminstration/New-WebAppPool.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/webadministration/New-WebAppPool.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1812-property-description/docset/winserver2012r2-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011301808563839-2207%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tXwWOwgitbnU%2Fg3bgTVH5a%2Fb0giddRRZv9jWy%2FpKZM4%3D&st=2020-11-30T18%3A08%3A14Z&se=2020-12-31T18%3A13%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 18:24 UTC, merged