Resolver #2024
MicrosoftDocs/windows-powershell-docs pull request #2210
Opened 2020-11-16 07:41 UTC by velkovb

Add note in description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2024

2020-11-16 07:45 UTC, opbld32 commented
Docs Build status updates of commit _[fa41e68](https://github.com/velkovb/windows-powershell-docs/commits/fa41e689842365c739e82eec7fbeca4e04a387f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011160741193145-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TLLkQANU4B1AvELOwuQOIpxSsV3%2BIyFZs2O11bKj%2FOQ%3D&st=2020-11-16T07%3A40%3A51Z&se=2020-12-17T07%3A45%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-16 07:59 UTC, opbld31 commented
Docs Build status updates of commit _[b736fe4](https://github.com/velkovb/windows-powershell-docs/commits/b736fe42fc478d9a8f07d46d0e1a01a78f1019e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011160755018032-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z4DFZyq8yM0NrEa45NP8LK5QpJVsoHTYQsmK8kyu75c%3D&st=2020-11-16T07%3A54%3A28Z&se=2020-12-17T07%3A59%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 17:22 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-17 17:22 UTC, e0i commented
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-17 19:19 UTC, dariomws commented on docset/windows/hyper-v/Get-VHD.md
> +> When the VHD is in use (e.g by a VM or mounted in OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. All others will get and error that it is
Same here, I think we cannot use standard note format because of Get-Help.

2020-11-17 19:37 UTC, get-itips reviewed
what is "all others" here?
agree with @dariomws

2020-11-17 19:57 UTC, velkovb commented
@get-itips Every other server trying to run **Get-VHD** against the file. Really not sure who to say it appropriately.

2020-11-17 20:06 UTC, get-itips commented
> @get-itips Every other server trying to run **Get-VHD** against the file. Really not sure who to say it appropriately.

Ok probably @JohanFreelancer9 will figure it out :)

2020-11-17 20:38 UTC, opbld33 commented
Docs Build status updates of commit _[6c2c90d](https://github.com/velkovb/windows-powershell-docs/commits/6c2c90dee659fdbe30915b77cb1d0e86e4d4bca8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011172033438558-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1dyhqaI5zBDG3icqQuBN2PDVp7FxOWYP1a7xtbXabbo%3D&st=2020-11-17T20%3A33%3A07Z&se=2020-12-18T20%3A38%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 07:54 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/Get-VHD.md
> +> [!Note]
```suggestion
```

2020-11-18 08:03 UTC, JohanFreelancer9 commented on docset/windows/hyper-v/Get-VHD.md
> +> When the VHD is in use (e.g by a VM or mounted in OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. All others will get and error that it is
```suggestion
Note that when the VHD is in use (for example by a VM or mounted in the OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. Any other server trying to run the Get-VHD cmdlet will get an error that it is in use. 
```

2020-11-18 08:04 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/hyper-v/Get-VHD.md
> +> [!Note]
```suggestion
```

2020-11-18 08:04 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/hyper-v/Get-VHD.md
> +> When the VHD is in use (e.g by a VM or mounted in OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. All others will get and error that it is
```suggestion
Note that when the VHD is in use (for example by a VM or mounted in the OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. Any other server trying to run the Get-VHD cmdlet will get an error that it is in use.  
```

2020-11-18 08:06 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/hyper-v/Get-VHD.md
> +> [!Note]
```suggestion
```

2020-11-18 08:06 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/hyper-v/Get-VHD.md
> +> When the VHD is in use (e.g by a VM or mounted in OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. All others will get and error that it is
```suggestion
Note that when the VHD is in use (for example by a VM or mounted in the OS) and it is on shared storage, the **Get-VHD** cmdlet can only access it from the host that is using it. Any other server trying to run the Get-VHD cmdlet will get an error that it is in use. 
```

2020-11-18 08:07 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-18 09:42 UTC, opbld31 commented
Docs Build status updates of commit _[f2ca8fb](https://github.com/velkovb/windows-powershell-docs/commits/f2ca8fbc6e951996772ef09145e0ff6d2a1454bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011180937510590-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F9RbAWT%2BGclvRGzN44Cy%2B%2BfgOL1bqAwuHhU4JiF20Ag%3D&st=2020-11-18T09%3A37%3A08Z&se=2020-12-19T09%3A42%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 14:12 UTC, JohanFreelancer9 approved these changes

2020-11-24 15:44 UTC, opbld33 commented
Docs Build status updates of commit _[0258d10](https://github.com/velkovb/windows-powershell-docs/commits/0258d102176fb4debe52224a952683a30366b6ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011241540281580-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eVR75XNEs89W%2B0kHTTGVV4F4ktdoSly0LYtaz4q5qNw%3D&st=2020-11-24T15%3A39%3A41Z&se=2020-12-25T15%3A44%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-25 18:03 UTC, tseward approved these changes

2020-11-30 17:56 UTC, opbld31 commented
Docs Build status updates of commit _[3f4cfce](https://github.com/velkovb/windows-powershell-docs/commits/3f4cfceb389abe209e2b0ba7497aa0b3773faa11)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011301752400988-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6sv1VDvnUCzbNJLATT0wv%2F1p6%2Fe1zHJzjGBDOuW5oXE%3D&st=2020-11-30T17%3A51%3A49Z&se=2020-12-31T17%3A56%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 18:02 UTC, opbld32 commented
Docs Build status updates of commit _[894633f](https://github.com/velkovb/windows-powershell-docs/commits/894633f746830c67230722f1e97b3c26a2f0a3b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011301757554892-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hINIO7jkX2yHvKz4kuZ77X2ZWjB7n3xUWZSpHT%2FiLtk%3D&st=2020-11-30T17%3A57%3A23Z&se=2020-12-31T18%3A02%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 18:13 UTC, opbld31 commented
Docs Build status updates of commit _[ef7ed0d](https://github.com/velkovb/windows-powershell-docs/commits/ef7ed0d98c60cf574e21d08734513082c5330944)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011301808461594-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NgHUBozZF%2FPzcCgnVhjKJOKKqlDT5XIuw%2Fq9LjXaUOI%3D&st=2020-11-30T18%3A08%3A11Z&se=2020-12-31T18%3A13%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 18:29 UTC, opbld30 commented
Docs Build status updates of commit _[c934454](https://github.com/velkovb/windows-powershell-docs/commits/c9344541d28fe2a59c3b6393c8edfcd838b0d064)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/windows/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/hyper-v/Get-VHD.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2024-add-note/docset/winserver2012r2-ps/hyper-v/Get-VHD.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011301825355026-2210%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=72D1tMVhVc8UCZLJgxVuLzWNzjRO3ruYH8j%2BB8YSgFg%3D&st=2020-11-30T18%3A24%3A57Z&se=2020-12-31T18%3A29%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-30 18:30 UTC, merged