revert changes
MicrosoftDocs/windows-powershell-docs pull request #2214
Opened 2020-11-17 12:10 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2183
revert changes https://github.com/MicrosoftDocs/windows-powershell-docs/commit/de9804871db683335c9e846d18eb920d4cd45ea9#diff-e8fa4151e0a760501051972a6a346a4eb82006ef1308d959ad0998b0704921c7 and https://github.com/MicrosoftDocs/windows-powershell-docs/commit/92773b22ea7bc498e910b1c74f883a8bced06598#diff-e8fa4151e0a760501051972a6a346a4eb82006ef1308d959ad0998b0704921c7

2020-11-17 12:11 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2020-11-17 12:15 UTC, opbld31 commented
Docs Build status updates of commit _[ab01e98](https://github.com/MaratMussabekov/windows-powershell-docs/commits/ab01e9848917cfbf025aff569e5678313743a9e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/failoverclusters/Set-ClusterLog.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-18/docset/windows/failoverclusters/Set-ClusterLog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011171210525424-2214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3qB2H74rU%2FOaCXgfATwg4OhLhT88JCUO3lthjml%2B5zc%3D&st=2020-11-17T12%3A10%3A07Z&se=2020-12-18T12%3A15%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 13:19 UTC, e0i commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

2020-11-18 14:35 UTC, dariomws requested changes
I agree with @carlosmayol.

The difference between 2016 and 2019 must be specified.

2020-11-18 14:35 UTC, dariomws commented on docset/windows/failoverclusters/Set-ClusterLog.md
> +The acceptable values for this parameter are:`8` MB to `1024` MB.
```suggestion
The acceptable values for this parameter in Windows 2016 are:`8` MB to `1024` MB.
The acceptable values for this parameter in Windows 2019 are:`8` MB to `2048` MB.
```

2020-11-18 14:36 UTC, JohanFreelancer9 approved these changes

2020-11-19 16:48 UTC, opbld31 commented
Docs Build status updates of commit _[6b169cc](https://github.com/MaratMussabekov/windows-powershell-docs/commits/6b169cc05aca81cdc08beaf036190b278ad04705)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/failoverclusters/Set-ClusterLog.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-18/docset/windows/failoverclusters/Set-ClusterLog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011191644427356-2214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Is4Zwr7RcwQESc4cpZ1RRR%2FumyFaxiM%2FX4TAXX8lQCc%3D&st=2020-11-19T16%3A43%3A49Z&se=2020-12-20T16%3A48%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 17:43 UTC, tseward approved these changes

2020-11-19 21:11 UTC, get-itips approved these changes

2020-11-20 11:54 UTC, dariomws approved these changes

2020-12-09 16:22 UTC, opbld33 commented
Docs Build status updates of commit _[f77d6a9](https://github.com/MaratMussabekov/windows-powershell-docs/commits/f77d6a9cebff868923e4dafb69f1d16f32f568f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/failoverclusters/Set-ClusterLog.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-18/docset/windows/failoverclusters/Set-ClusterLog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterlog?view=win10-ps&branch=pr-en-us-2214) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012091618347024-2214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ctk%2BkIOnowxYrTJRIQPA5dCOSKlo5wJlwZeMwT2fcIc%3D&st=2020-12-09T16%3A17%3A47Z&se=2021-01-09T16%3A22%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 16:23 UTC, merged