Resolves #1289
MicrosoftDocs/windows-powershell-docs pull request #2218
Opened 2020-11-18 15:36 UTC by velkovb

Provide source for SMB information
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1289

2020-11-18 15:40 UTC, opbld32 commented
Docs Build status updates of commit _[e5c083c](https://github.com/velkovb/windows-powershell-docs/commits/e5c083ccd04931e5aa5daeacc96bdc5824a3eb61)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/smbshare/Set-SmbServerConfiguration.md) | :x:Error | | [Details](#user-content-e162777c-728bec8b)
[docset/windows/remoteaccess/Get-BgpCustomRoute.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Get-BgpCustomRoute.yml) | :warning:Warning | | [Details](#user-content-22e4c07c-728bec8b)
[docset/windows/remoteaccess/New-VpnTrafficSelector.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/New-VpnTrafficSelector.yml) | :warning:Warning | | [Details](#user-content-8aa0f15a-728bec8b)
[docset/windows/remoteaccess/Remove-BgpRouter.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Remove-BgpRouter.yml) | :warning:Warning | | [Details](#user-content-52c8f773-728bec8b)
[docset/windows/remoteaccess/Add-VpnS2SInterface.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Add-VpnS2SInterface.yml) | :warning:Warning | | [Details](#user-content-919be279-728bec8b)
[docset/windows/remoteaccess/Enable-BgpRouteFlapDampening.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Enable-BgpRouteFlapDampening.yml) | :warning:Warning | | [Details](#user-content-dc3e5143-728bec8b)
[docset/windows/remoteaccess/New-VpnSstpProxyRule.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/New-VpnSstpProxyRule.yml) | :warning:Warning | | [Details](#user-content-199ab3d9-728bec8b)
[docset/windows/webadministration/New-WebAppPool.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/webadministration/New-WebAppPool.yml) | :warning:Warning | | [Details](#user-content-f5cb4c1f-728bec8b)
[docset/windows/storage/Format-Volume.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/storage/Format-Volume.yml) | :warning:Warning | | [Details](#user-content-e5c97959-728bec8b)
[docset/windows/remoteaccess/Remove-BgpCustomRoute.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Remove-BgpCustomRoute.yml) | :warning:Warning | | [Details](#user-content-1030c1ee-728bec8b)
[docset/windows/storage/Grant-FileShareAccess.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/storage/Grant-FileShareAccess.yml) | :warning:Warning | | [Details](#user-content-20837cae-728bec8b)
[docset/windows/webadministration/Set-WebConfiguration.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/webadministration/Set-WebConfiguration.yml) | :warning:Warning | | [Details](#user-content-dc75c67d-728bec8b)
[docset/windows/wdac/Set-OdbcDriver.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/wdac/Set-OdbcDriver.yml) | :warning:Warning | | [Details](#user-content-32632a97-728bec8b)
[docset/windows/remoteaccess/Stop-BgpPeer.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Stop-BgpPeer.yml) | :warning:Warning | | [Details](#user-content-7168af6f-728bec8b)
[docset/windows/remoteaccess/Add-VpnSstpProxyRule.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Add-VpnSstpProxyRule.yml) | :warning:Warning | | [Details](#user-content-14857c8e-728bec8b)
[docset/windows/remoteaccess/Get-BgpPeer.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Get-BgpPeer.yml) | :warning:Warning | | [Details](#user-content-2ba0b335-728bec8b)
[docset/windows/storagereplica/Sync-SRGroup.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/storagereplica/Sync-SRGroup.yml) | :warning:Warning | | [Details](#user-content-eb07f0d9-728bec8b)
[docset/windows/remoteaccess/Start-BgpPeer.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Start-BgpPeer.yml) | :warning:Warning | | [Details](#user-content-6ec2ee8b-728bec8b)
[docset/windows/vpnclient/Add-VpnConnectionTriggerTrustedNetwork.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/vpnclient/Add-VpnConnectionTriggerTrustedNetwork.yml) | :warning:Warning | | [Details](#user-content-4f749717-728bec8b)
[docset/windows/storage/Resize-StorageTier.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/storage/Resize-StorageTier.yml) | :warning:Warning | | [Details](#user-content-a0fd1291-728bec8b)
[docset/windows/storage/New-StoragePool.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/storage/New-StoragePool.yml) | :warning:Warning | | [Details](#user-content-7447f37c-728bec8b)
[docset/windows/wdac/Remove-OdbcDsn.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/wdac/Remove-OdbcDsn.yml) | :warning:Warning | | [Details](#user-content-44a7a6b3-728bec8b)
[docset/windows/wds/Approve-WdsClient.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/wds/Approve-WdsClient.yml) | :warning:Warning | | [Details](#user-content-617c1118-728bec8b)
[docset/windows/wdac/Set-OdbcDsn.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/wdac/Set-OdbcDsn.yml) | :warning:Warning | | [Details](#user-content-4ff95c71-728bec8b)
[docset/windows/webadministration/Remove-WebAppPool.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/webadministration/Remove-WebAppPool.yml) | :warning:Warning | | [Details](#user-content-d9f38dfc-728bec8b)
[docset/windows/webadministration/Get-WebManagedModule.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/webadministration/Get-WebManagedModule.yml) | :warning:Warning | | [Details](#user-content-a6ab5236-728bec8b)
[docset/windows/remoteaccess/Set-VpnS2SInterface.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Set-VpnS2SInterface.yml) | :warning:Warning | | [Details](#user-content-88f21759-728bec8b)
[docset/windows/remoteaccess/Set-BgpPeer.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/remoteaccess/Set-BgpPeer.yml) | :warning:Warning | | [Details](#user-content-21b89afd-728bec8b)
[docset/windows/storage/Resize-VirtualDisk.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/storage/Resize-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-37db8e1f-728bec8b)
[docset/windows/wds/Disable-WdsBootImage.yml](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/wds/Disable-WdsBootImage.yml) | :warning:Warning | | [Details](#user-content-cec19c4c-728bec8b)
[docset/windows/webadministration/Get-WebGlobalMo [...]

2020-11-18 16:12 UTC, opbld30 commented
Docs Build status updates of commit _[6e5d15b](https://github.com/velkovb/windows-powershell-docs/commits/6e5d15b13eef4c62fc598b48a97b6d08ad215f88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181608255796-2218%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZduzkJgSiedVJ48ec%2B1zG0aJBbT24YS1rhcr5Z5ZLlg%3D&st=2020-11-18T16%3A07%3A43Z&se=2020-12-19T16%3A12%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 18:59 UTC, opbld32 commented
Docs Build status updates of commit _[9470347](https://github.com/velkovb/windows-powershell-docs/commits/947034769bec27cd75866e40ef29a8098b12c7d4)_: 

:clock10: **Pending**: waiting for processors ([23](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 23 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-18 19:04 UTC, opbld30 commented
Docs Build status updates of commit _[9470347](https://github.com/velkovb/windows-powershell-docs/commits/947034769bec27cd75866e40ef29a8098b12c7d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011181858587136-2218%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sZZRYz2Qy05000VxzGIFAzPBx65xWPC6gzDI0%2FSpyZ0%3D&st=2020-11-18T18%3A59%3A50Z&se=2020-12-19T19%3A04%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-28 00:20 UTC, e0i commented
cc @dariomws @get-itips @tseward @JohanFreelancer9

2020-11-28 06:24 UTC, JohanFreelancer9 commented on docset/windows/smbshare/Set-SmbServerConfiguration.md
> +The **Set-SmbServerConfiguration** cmdlet sets the Server Message Block (SMB) Service configuration. For get more information on SMB server and protocol specification, see [Overview of file sharing u
```suggestion
The **Set-SmbServerConfiguration** cmdlet sets the Server Message Block (SMB) Service configuration. For more information on SMB server and protocol specification, see [Overview of file sharing using the SMB 3 protocol in Windows Server](https://docs.microsoft.com/windows-server/storage/file-server/file-server-smb-overview) and [[MS-SMB2]: Server Message Block (SMB) Protocol Versions 2 and 3](https://docs.microsoft.com/openspecs/windows_protocols/ms-smb2/5606ad47-5ee0-437a-817e-70c366052962).
```

2020-11-28 06:29 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md
> +The **Set-SmbServerConfiguration** cmdlet sets the Server Message Block (SMB) server configuration. For get more information on SMB server and protocol specification, see [Server Message Block Overvi
```suggestion
The **Set-SmbServerConfiguration** cmdlet sets the Server Message Block (SMB) server configuration. For more information on SMB server and protocol specifications, see [Server Message Block Overview](https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831795(v=ws.11)). For protocol specification, see [[MS-SMB2]: Server Message Block (SMB) Protocol Versions 2 and 3](https://docs.microsoft.com/openspecs/windows_protocols/ms-smb2/5606ad47-5ee0-437a-817e-70c366052962).
```

2020-11-28 06:29 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md
> +The **Set-SmbServerConfiguration** cmdlet sets the Server Message Block (SMB) server configuration. For get more information on SMB server and protocol specification, see [Server Message Block Overvi
```suggestion
The **Set-SmbServerConfiguration** cmdlet sets the Server Message Block (SMB) server configuration. For more information on SMB server and protocol specifications, see [Server Message Block Overview](https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831795(v=ws.11)). For protocol specification, see [[MS-SMB2]: Server Message Block (SMB) Protocol Versions 2 and 3](https://docs.microsoft.com/openspecs/windows_protocols/ms-smb2/5606ad47-5ee0-437a-817e-70c366052962).
```

2020-11-28 06:30 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-28 07:35 UTC, opbld32 commented
Docs Build status updates of commit _[0a129f9](https://github.com/velkovb/windows-powershell-docs/commits/0a129f9e3e8f4e767e05db81263e7ac52620d0e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C28%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202011280731313823-2218%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1bwtSdkdbaZXdYuAUjNzuJBSr5RVkCc7NvOzIujBTfI%3D&st=2020-11-28T07%3A30%3A38Z&se=2020-12-29T07%3A35%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-28 08:15 UTC, JohanFreelancer9 approved these changes

2020-11-28 12:23 UTC, get-itips approved these changes

2020-11-28 14:19 UTC, dariomws approved these changes

2020-11-29 21:22 UTC, tseward approved these changes

2020-11-30 11:36 UTC, JohanFreelancer9 approved these changes

2020-12-02 12:40 UTC, opbld30 commented
Docs Build status updates of commit _[0f5a1cb](https://github.com/velkovb/windows-powershell-docs/commits/0f5a1cb37693f0a9e55709a0a64b28111bf7c3e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |
[docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012021236003297-2218%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bheLfs9pxuCu9GEoO4zaO%2Fzb5j3c165WFOvdhM%2Baz1g%3D&st=2020-12-02T12%3A35%3A32Z&se=2021-01-02T12%3A40%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 16:14 UTC, opbld31 commented
Docs Build status updates of commit _[1b51762](https://github.com/velkovb/windows-powershell-docs/commits/1b51762c025281c61df5ae1d8c0a1c29c0c80f67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/windows/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=win10-ps&branch=pr-en-us-2218) (win10-ps) |
[docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=winserver2012-ps&branch=pr-en-us-2218) (winserver2012-ps) |
[docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/1289-provide-info-links/docset/winserver2012r2-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=winserver2012r2-ps&branch=pr-en-us-2218) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012091610052313-2218%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CE%2FmJob5Ez51sRjsTOOtK8bk9fdYm9TgIkdg9ocJGmQ%3D&st=2020-12-09T16%3A09%3A25Z&se=2021-01-09T16%3A14%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 16:17 UTC, merged