Resolves #2196
MicrosoftDocs/windows-powershell-docs pull request #2238
Opened 2020-12-13 13:10 UTC by velkovb

Fix SamAccountName description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2196

2020-12-13 13:15 UTC, opbld30 commented
Docs Build status updates of commit _[b427b55](https://github.com/velkovb/windows-powershell-docs/commits/b427b5501405c4006e58231ae362cae9b41e1c82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/windows/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps&branch=pr-en-us-2238) (win10-ps) |
[docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps&branch=pr-en-us-2238) (winserver2012-ps) |
[docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=winserver2012r2-ps&branch=pr-en-us-2238) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C13%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012131310361554-2238%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EU5TFlYWtd8D1iDuuKuJTpYemeDyE3xVawnpQhfrbNo%3D&st=2020-12-13T13%3A10%3A08Z&se=2021-01-13T13%3A15%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-13 13:36 UTC, opbld30 commented
Docs Build status updates of commit _[6c904ce](https://github.com/velkovb/windows-powershell-docs/commits/6c904ce00866e3643fe6496f54626f5846a551b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/windows/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps&branch=pr-en-us-2238) (win10-ps) |
[docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps&branch=pr-en-us-2238) (winserver2012-ps) |
[docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=winserver2012r2-ps&branch=pr-en-us-2238) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C13%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012131332154650-2238%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4trcryf0klDBF6zAXjJu5G9Pt%2FnyC6AB1u3MnaJOpQE%3D&st=2020-12-13T13%3A31%3A51Z&se=2021-01-13T13%3A36%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-27 18:12 UTC, opbld33 commented
Docs Build status updates of commit _[d2ae332](https://github.com/velkovb/windows-powershell-docs/commits/d2ae3326e4c0dbd92d02aae187d0973c744c238a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/windows/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps&branch=pr-en-us-2238) (win10-ps) |
[docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps&branch=pr-en-us-2238) (winserver2012-ps) |
[docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=winserver2012r2-ps&branch=pr-en-us-2238) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C27%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012271808543854-2238%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F6f2VariHcmiNb%2BKxQh3ykro9FJ0fs1LXqisQFb5bWM%3D&st=2020-12-27T18%3A07%3A40Z&se=2021-01-27T18%3A12%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-30 14:00 UTC, get-itips approved these changes

2020-12-30 14:25 UTC, dariomws requested changes

2020-12-30 14:25 UTC, dariomws commented on docset/windows/addsadministration/New-ADServiceAccount.md
> +### Example 5: Create a new maanged service accoutn and register multiple service principal names
```suggestion
### Example 5: Create a new managed service account and register multiple service principal names
```

2020-12-30 14:25 UTC, dariomws commented on docset/windows/addsadministration/New-ADServiceAccount.md
> +C:\PS>New-ADServiceAccount service1 -ServicePrincipalNames "HTTP/Machine3.corp.contoso.com,HTTP/Machine3.corp.contoso.com/contoso" -DNSHostName service1.contoso.com
```suggestion
PS C:\> New-ADServiceAccount service1 -ServicePrincipalNames "HTTP/Machine3.corp.contoso.com,HTTP/Machine3.corp.contoso.com/contoso" -DNSHostName service1.contoso.com
```

2020-12-30 14:25 UTC, dariomws commented on docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md
> +### Example 5: Create a new maanged service accoutn and register multiple service principal names
```suggestion
### Example 5: Create a new managed service account and register multiple service principal names
```

2020-12-30 14:25 UTC, dariomws commented on docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md
>  C:\PS>New-ADServiceAccount service1 -ServicePrincipalNames "HTTP/Machine3.corp.contoso.com,HTTP/Machine3.corp.contoso.com/contoso" -DNSHostName service1.contoso.com
```suggestion
PS C:\> New-ADServiceAccount service1 -ServicePrincipalNames "HTTP/Machine3.corp.contoso.com,HTTP/Machine3.corp.contoso.com/contoso" -DNSHostName service1.contoso.com
```

2020-12-30 14:25 UTC, dariomws commented on docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md
> +### Example 5: Create a new maanged service accoutn and register multiple service principal names
```suggestion
### Example 5: Create a new managed service account and register multiple service principal names
```

2020-12-30 14:25 UTC, dariomws commented on docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md
> +C:\PS>New-ADServiceAccount service1 -ServicePrincipalNames "HTTP/Machine3.corp.contoso.com,HTTP/Machine3.corp.contoso.com/contoso" -DNSHostName service1.contoso.com
```suggestion
PS C:\> New-ADServiceAccount service1 -ServicePrincipalNames "HTTP/Machine3.corp.contoso.com,HTTP/Machine3.corp.contoso.com/contoso" -DNSHostName service1.contoso.com
```

2020-12-30 14:34 UTC, opbld32 commented
Docs Build status updates of commit _[a0bef56](https://github.com/velkovb/windows-powershell-docs/commits/a0bef566ad9012479531ac8fef9db56576d902c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/windows/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps&branch=pr-en-us-2238) (win10-ps) |
[docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps&branch=pr-en-us-2238) (winserver2012-ps) |
[docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=winserver2012r2-ps&branch=pr-en-us-2238) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012301430271427-2238%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3niBvSsNqBnD0C%2F0Vsoaoog5%2F4hE7pct1YjvxY%2BYI8U%3D&st=2020-12-30T14%3A29%3A29Z&se=2021-01-30T14%3A34%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-30 14:52 UTC, dariomws approved these changes

2020-12-30 19:51 UTC, tseward approved these changes

2020-12-31 16:28 UTC, opbld30 commented
Docs Build status updates of commit _[f73b164](https://github.com/velkovb/windows-powershell-docs/commits/f73b16405088282091260d186f48fd5a31926330)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/windows/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=win10-ps&branch=pr-en-us-2238) (win10-ps) |
[docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps&branch=pr-en-us-2238) (winserver2012-ps) |
[docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2196-sam-description/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/addsadministration/new-adserviceaccount?view=winserver2012r2-ps&branch=pr-en-us-2238) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C31%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202012311624304223-2238%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s6TC2zBme5vXPT6z0%2BEZbN3hVTKkFue0R%2F0HPyPq1es%3D&st=2020-12-31T16%3A23%3A14Z&se=2021-01-31T16%3A28%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-31 16:30 UTC, merged