Resolves #2235
MicrosoftDocs/windows-powershell-docs pull request #2254
Opened 2021-01-04 18:40 UTC by velkovb

Fix example 1
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2235

2021-01-04 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[021e3ae](https://github.com/velkovb/windows-powershell-docs/commits/021e3ae04e3196028a271fa1639cc544f04650f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Get-AdfsClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/windows/adfs/Get-AdfsClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=win10-ps&branch=pr-en-us-2254) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101041840519089-2254%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YQGUvb2iiEefhG%2B%2BT%2F4ReYlBqz4U0KoSzSs9dcbjHTU%3D&st=2021-01-04T18%3A39%3A58Z&se=2021-02-04T18%3A44%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 18:48 UTC, opbld32 commented
Docs Build status updates of commit _[290ba3d](https://github.com/velkovb/windows-powershell-docs/commits/290ba3d86492a19d86d986e1c219eacccf3a49be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Get-AdfsClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/windows/adfs/Get-AdfsClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=win10-ps&branch=pr-en-us-2254) (win10-ps) |
[docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=winserver2012-ps&branch=pr-en-us-2254) (winserver2012-ps) |
[docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=winserver2012r2-ps&branch=pr-en-us-2254) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101041843312018-2254%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ACISRA1QyV7t09fngvuTAU4HG3fwkbSXm1YEqAvWDjI%3D&st=2021-01-04T18%3A43%3A50Z&se=2021-02-04T18%3A48%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 13:37 UTC, e0i commented
cc @JohanFreelancer9

2021-01-05 14:29 UTC, JohanFreelancer9 commented on docset/windows/adfs/Get-AdfsClaimDescription.md
> +This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`, `-Verbose`, `-
```suggestion
This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`, `-Verbose`, `-WarningAction`, and `-WarningVariable`. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-01-05 14:30 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md
> +This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`, `-Verbose`, `-
```suggestion
This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`, `-Verbose`, `-WarningAction`, and `-WarningVariable`. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-01-05 14:30 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md
> +This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`, `-Verbose`, `-
```suggestion
This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`, `-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`, `-Verbose`, `-WarningAction`, and `-WarningVariable`. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-01-05 14:31 UTC, JohanFreelancer9 requested changes
Copy review - minor edits.

2021-01-05 15:48 UTC, opbld31 commented
Docs Build status updates of commit _[2ca5fda](https://github.com/velkovb/windows-powershell-docs/commits/2ca5fdaead731889719a530fc6100ba367c89a30)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Get-AdfsClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/windows/adfs/Get-AdfsClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=win10-ps&branch=pr-en-us-2254) (win10-ps) |
[docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/winserver2012-ps/adfs/Get-ADFSClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=winserver2012-ps&branch=pr-en-us-2254) (winserver2012-ps) |
[docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2235-example-fix/docset/winserver2012r2-ps/adfs/Get-AdfsClaimDescription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/get-adfsclaimdescription?view=winserver2012r2-ps&branch=pr-en-us-2254) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101051544369146-2254%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LQ0euOzFIaWlne74RVqlbieIRCgl3ZI8S7sNbuC5F6Y%3D&st=2021-01-05T15%3A43%3A37Z&se=2021-02-05T15%3A48%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 17:07 UTC, tseward approved these changes

2021-01-06 03:30 UTC, JohanFreelancer9 approved these changes

2021-01-07 17:01 UTC, merged