Improves New-StoragePool
MicrosoftDocs/windows-powershell-docs pull request #2257
Opened 2021-01-04 20:51 UTC by exchange12rocks

1. Improves formatting in examples.
2. Some parameters in reality have default values, but the documentation misses it. Not anymore.

2021-01-04 20:55 UTC, opbld33 commented
Docs Build status updates of commit _[69f277a](https://github.com/exchange12rocks/windows-powershell-docs/commits/69f277a2e56c269e8ab5271859ff5dd7a93fe067)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :x:Error | | [Details](#user-content-838d0396-3e08c7e2)
[docset/windows/storage/Disconnect-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Disconnect-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-48422143-3e08c7e2)
[docset/windows/storage/Get-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-36eac960-3e08c7e2)
[docset/windows/storage/Get-PhysicalDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-PhysicalDisk.yml) | :warning:Warning | | [Details](#user-content-5564362f-3e08c7e2)
[docset/windows/smbshare/Get-SmbServerConfiguration.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/smbshare/Get-SmbServerConfiguration.yml) | :warning:Warning | | [Details](#user-content-93451834-3e08c7e2)
[docset/windows/storage/Set-StorageProvider.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Set-StorageProvider.yml) | :warning:Warning | | [Details](#user-content-2d12361d-3e08c7e2)
[docset/windows/storage/Update-StoragePool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Update-StoragePool.yml) | :warning:Warning | | [Details](#user-content-d7630f35-3e08c7e2)
[docset/windows/storage/Set-StorageTier.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Set-StorageTier.yml) | :warning:Warning | | [Details](#user-content-186d9648-3e08c7e2)
[docset/windows/storage/Get-VirtualDiskSupportedSize.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-VirtualDiskSupportedSize.yml) | :warning:Warning | | [Details](#user-content-dead73c3-3e08c7e2)
[docset/windows/storage/Remove-StorageTier.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Remove-StorageTier.yml) | :warning:Warning | | [Details](#user-content-401be78c-3e08c7e2)
[docset/windows/storage/Remove-StoragePool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Remove-StoragePool.yml) | :warning:Warning | | [Details](#user-content-91928c99-3e08c7e2)
[docset/windows/storage/Get-ResiliencySetting.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-ResiliencySetting.yml) | :warning:Warning | | [Details](#user-content-4b58a01f-3e08c7e2)
[docset/windows/wdac/Get-WdacBidTrace.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/wdac/Get-WdacBidTrace.yml) | :warning:Warning | | [Details](#user-content-d6d22424-3e08c7e2)
[docset/windows/wdac/Set-OdbcDriver.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/wdac/Set-OdbcDriver.yml) | :warning:Warning | | [Details](#user-content-32632a97-3e08c7e2)
[docset/windows/storage/Resize-StorageTier.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Resize-StorageTier.yml) | :warning:Warning | | [Details](#user-content-a0fd1291-3e08c7e2)
[docset/windows/storage/Remove-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Remove-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-f77899d7-3e08c7e2)
[docset/windows/storage/Hide-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Hide-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-721e12e0-3e08c7e2)
[docset/windows/storage/Set-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Set-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-45fe793a-3e08c7e2)
[docset/windows/storage/Connect-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Connect-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-7975b4aa-3e08c7e2)
[docset/windows/storage/Get-StoragePool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-StoragePool.yml) | :warning:Warning | | [Details](#user-content-8ee4352b-3e08c7e2)
[docset/windows/storage/Resize-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Resize-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-37db8e1f-3e08c7e2)
[docset/windows/storage/Show-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Show-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-face61ea-3e08c7e2)
[docset/windows/storage/Optimize-StoragePool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Optimize-StoragePool.yml) | :warning:Warning | | [Details](#user-content-39696cda-3e08c7e2)
[docset/windows/storage/Debug-Volume.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Debug-Volume.yml) | :warning:Warning | | [Details](#user-content-e9ca42c4-3e08c7e2)
[docset/windows/storage/Set-StoragePool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Set-StoragePool.yml) | :warning:Warning | | [Details](#user-content-76d08b8f-3e08c7e2)
[docset/windows/wdac/Disable-WdacBidTrace.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/wdac/Disable-WdacBidTrace.yml) | :warning:Warning | | [Details](#user-content-ce4faa24-3e08c7e2)
[docset/windows/storage/Repair-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Repair-VirtualDisk.yml) | :warning:Warning | | [Details](#user-content-7d4249a8-3e08c7e2)
[docset/windows/storage/Get-StorageTier.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-StorageTier.yml) | :warning:Warning | | [Details](#user-content-a8e42be6-3e08c7e2)

<a id="838d0396-3e08c7e2"></a>
### [docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/q1uf-s/docset/windows/storage/New-StoragePool.md:60:(189) '```
PS C:\> New-StoragePool -FriendlyName Company...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="48422143-3e08c7e2"></a>
### [docset/windows/storage/Disconnect-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Disconnect-VirtualDisk.yml)
 - **Line 23, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './New-VirtualDisk.yml'.`````

<a id="36eac960-3e08c7e2"></a>
### [docset/windows/storage/Get-VirtualDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-VirtualDisk.yml)
 - **Lin [...]

2021-01-04 22:46 UTC, opbld33 commented
Docs Build status updates of commit _[782919b](https://github.com/exchange12rocks/windows-powershell-docs/commits/782919ba69830eb6ef8b16f3a6f3d2dd7478575c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101042243031003-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sm9fPQBFBEIvgtQl6xfnN2AOmsk4TsOUOFEJCk4T7ac%3D&st=2021-01-04T22%3A41%3A42Z&se=2021-02-04T22%3A46%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 22:53 UTC, opbld30 commented
Docs Build status updates of commit _[0af7e21](https://github.com/exchange12rocks/windows-powershell-docs/commits/0af7e21978483978bee7adaf4ff8bf407b8feaec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101042250116967-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CfcAyGrsP4CbBIKM6keMIJOk1Oe%2BRLpV%2BQFAbc8cHeg%3D&st=2021-01-04T22%3A48%3A49Z&se=2021-02-04T22%3A53%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 23:02 UTC, opbld32 commented
Docs Build status updates of commit _[a690159](https://github.com/exchange12rocks/windows-powershell-docs/commits/a690159718c29b2a47553a50c3cb2eb475d964c2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :x:Error | | [Details](#user-content-838d0396-b005e92c)
[docset/windows/uev/Update-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Update-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-e069a5ce-b005e92c)
[docset/windows/uev/Unregister-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Unregister-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-5b9b5d45-b005e92c)
[docset/windows/uev/Set-UevConfiguration.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Set-UevConfiguration.yml) | :warning:Warning | | [Details](#user-content-34abdef7-b005e92c)
[docset/windows/uev/Restore-UevUserSetting.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Restore-UevUserSetting.yml) | :warning:Warning | | [Details](#user-content-fc19224f-b005e92c)
[docset/windows/uev/Set-UevTemplateProfile.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Set-UevTemplateProfile.yml) | :warning:Warning | | [Details](#user-content-50364c9c-b005e92c)
[docset/windows/uev/Test-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Test-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-a924dcce-b005e92c)
[docset/windows/iisadministration/Get-IISAppPool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/iisadministration/Get-IISAppPool.yml) | :warning:Warning | | [Details](#user-content-a5ba9443-b005e92c)
[docset/windows/failoverclusters/Add-ClusterDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/failoverclusters/Add-ClusterDisk.yml) | :warning:Warning | | [Details](#user-content-0f75dc63-b005e92c)
[docset/windows/netsecurity/New-NetIPsecQuickModeCryptoSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecQuickModeCryptoSet.yml) | :warning:Warning | | [Details](#user-content-03dac4d7-b005e92c)
[docset/windows/netsecurity/New-NetIPsecPhase1AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecPhase1AuthSet.yml) | :warning:Warning | | [Details](#user-content-33d20fdb-b005e92c)
[docset/windows/storage/Get-StorageSetting.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-StorageSetting.yml) | :warning:Warning | | [Details](#user-content-68a2f2d0-b005e92c)
[docset/windows/remoteaccess/Add-BgpRouteAggregate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remoteaccess/Add-BgpRouteAggregate.yml) | :warning:Warning | | [Details](#user-content-f7e2fed2-b005e92c)
[docset/windows/netsecurity/New-NetIPsecMainModeCryptoSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecMainModeCryptoSet.yml) | :warning:Warning | | [Details](#user-content-d8fe7ad4-b005e92c)
[docset/windows/remotedesktop/Get-RDRemoteApp.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remotedesktop/Get-RDRemoteApp.yml) | :warning:Warning | | [Details](#user-content-26b49a41-b005e92c)
[docset/windows/storage/Disable-StorageHighAvailability.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Disable-StorageHighAvailability.yml) | :warning:Warning | | [Details](#user-content-d77d07a3-b005e92c)
[docset/windows/storage/Disable-StorageMaintenanceMode.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Disable-StorageMaintenanceMode.yml) | :warning:Warning | | [Details](#user-content-ac20a7cd-b005e92c)
[docset/windows/remoteaccess/Add-BgpPeer.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remoteaccess/Add-BgpPeer.yml) | :warning:Warning | | [Details](#user-content-d320fa9c-b005e92c)
[docset/windows/remoteaccess/Add-BgpRouter.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remoteaccess/Add-BgpRouter.yml) | :warning:Warning | | [Details](#user-content-95af5b4f-b005e92c)
[docset/windows/remotedesktop/Add-RDServer.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remotedesktop/Add-RDServer.yml) | :warning:Warning | | [Details](#user-content-ed6b0046-b005e92c)
[docset/windows/netsecurity/New-NetIPsecPhase2AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecPhase2AuthSet.yml) | :warning:Warning | | [Details](#user-content-06ef23df-b005e92c)
[docset/windows/remoteaccess/Add-VpnSstpProxyRule.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remoteaccess/Add-VpnSstpProxyRule.yml) | :warning:Warning | | [Details](#user-content-14857c8e-b005e92c)
[docset/windows/shieldedvmprovisioning/Test-ShieldingDataApplicability.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/shieldedvmprovisioning/Test-ShieldingDataApplicability.yml) | :warning:Warning | | [Details](#user-content-585126c2-b005e92c)
[docset/windows/remoteaccess/Add-BgpRoutingPolicy.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remoteaccess/Add-BgpRoutingPolicy.yml) | :warning:Warning | | [Details](#user-content-1824334e-b005e92c)
[docset/windows/storage/Remove-FileShare.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Remove-FileShare.yml) | :warning:Warning | | [Details](#user-content-8a2f557c-b005e92c)
[docset/windows/storage/Get-StorageSubSystem.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Get-StorageSubSystem.yml) | :warning:Warning | | [Details](#user-content-490f208a-b005e92c)
[docset/windows/storage/Unblock-FileShareAccess.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Unblock-FileShareAccess.yml) | :warning:Warning | | [Details](#user-content-3d0e2e7c-b005e92c)
[docset/windows/remotedesktop/Set-RDWorkspace.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remotedesktop/Set-RDWorkspace.yml) | :warning:Warning | | [Details](#user-content-b4f1cb1c-b005e92c)
[docset/windows/storage/Set-StorageHealthSetting.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Set-StorageHealthSetting.yml) | :warning:Warning | | [Details](#user-content-ab89a992-b005e92c)
[docset/windows/remotedesktop/Set-RDVirtualDesktopIdleCount.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/remotedesktop/Set-RDVirtualDesktopIdleCount.yml) | :warning:Warning | | [Details](#user-content-8da7a802-b005e92c)
[docset/windows/storage/Enable-StorageHighAvailability.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/Enable-StorageHighAvailability.yml) | :warning:Warning | | [Details](#user-content-78d5b762-b005e92c)
[docset/windows/storag [...]

2021-01-04 23:14 UTC, opbld31 commented
Docs Build status updates of commit _[5e48496](https://github.com/exchange12rocks/windows-powershell-docs/commits/5e484964bf353f24dba41e53047d25f16b353475)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :x:Error | | [Details](#user-content-838d0396-f6d18e31)
[docset/windows/uev/Clear-UevConfiguration.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Clear-UevConfiguration.yml) | :warning:Warning | | [Details](#user-content-ca1a2c4c-f6d18e31)
[docset/windows/uev/Test-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Test-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-a924dcce-f6d18e31)
[docset/windows/uev/Enable-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Enable-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-71ead9a9-f6d18e31)
[docset/windows/uev/Disable-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Disable-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-667c8667-f6d18e31)
[docset/windows/uev/Set-UevConfiguration.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Set-UevConfiguration.yml) | :warning:Warning | | [Details](#user-content-34abdef7-f6d18e31)
[docset/windows/uev/Export-UevConfiguration.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Export-UevConfiguration.yml) | :warning:Warning | | [Details](#user-content-b0dbbb35-f6d18e31)
[docset/windows/uev/Unregister-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Unregister-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-5b9b5d45-f6d18e31)
[docset/windows/uev/Update-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Update-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-e069a5ce-f6d18e31)
[docset/windows/uev/Get-UevConfiguration.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Get-UevConfiguration.yml) | :warning:Warning | | [Details](#user-content-8aa17274-f6d18e31)
[docset/windows/uev/Get-UevTemplate.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/uev/Get-UevTemplate.yml) | :warning:Warning | | [Details](#user-content-aedb1b8c-f6d18e31)
[docset/windows/failoverclusters/Add-ClusterDisk.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/failoverclusters/Add-ClusterDisk.yml) | :warning:Warning | | [Details](#user-content-0f75dc63-f6d18e31)
[docset/windows/iisadministration/Get-IISAppPool.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/iisadministration/Get-IISAppPool.yml) | :warning:Warning | | [Details](#user-content-a5ba9443-f6d18e31)
[docset/windows/netsecurity/Rename-NetIPsecPhase2AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Rename-NetIPsecPhase2AuthSet.yml) | :warning:Warning | | [Details](#user-content-a9b5c39d-f6d18e31)
[docset/windows/netsecurity/Get-NetIPsecQuickModeCryptoSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Get-NetIPsecQuickModeCryptoSet.yml) | :warning:Warning | | [Details](#user-content-aaea4108-f6d18e31)
[docset/windows/netsecurity/Enable-NetIPsecMainModeRule.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Enable-NetIPsecMainModeRule.yml) | :warning:Warning | | [Details](#user-content-43c3fbab-f6d18e31)
[docset/windows/netsecurity/Remove-NetIPsecPhase2AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Remove-NetIPsecPhase2AuthSet.yml) | :warning:Warning | | [Details](#user-content-0612c4e9-f6d18e31)
[docset/windows/netsecurity/Copy-NetIPsecMainModeRule.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Copy-NetIPsecMainModeRule.yml) | :warning:Warning | | [Details](#user-content-aa8cfedd-f6d18e31)
[docset/windows/netsecurity/Get-NetIPsecPhase1AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Get-NetIPsecPhase1AuthSet.yml) | :warning:Warning | | [Details](#user-content-65bdfaac-f6d18e31)
[docset/windows/netsecurity/New-NetIPsecMainModeCryptoProposal.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecMainModeCryptoProposal.yml) | :warning:Warning | | [Details](#user-content-441705c7-f6d18e31)
[docset/windows/netsecurity/Get-NetFirewallInterfaceTypeFilter.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Get-NetFirewallInterfaceTypeFilter.yml) | :warning:Warning | | [Details](#user-content-fa11c834-f6d18e31)
[docset/windows/netsecurity/Copy-NetIPsecPhase1AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Copy-NetIPsecPhase1AuthSet.yml) | :warning:Warning | | [Details](#user-content-1c59e552-f6d18e31)
[docset/windows/netsecurity/Get-NetFirewallAddressFilter.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Get-NetFirewallAddressFilter.yml) | :warning:Warning | | [Details](#user-content-579b4d6f-f6d18e31)
[docset/windows/netsecurity/Get-NetIPsecPhase2AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Get-NetIPsecPhase2AuthSet.yml) | :warning:Warning | | [Details](#user-content-2fc617fa-f6d18e31)
[docset/windows/netsecurity/New-NetIPsecMainModeCryptoSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecMainModeCryptoSet.yml) | :warning:Warning | | [Details](#user-content-d8fe7ad4-f6d18e31)
[docset/windows/netsecurity/New-NetIPsecRule.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecRule.yml) | :warning:Warning | | [Details](#user-content-9fa40781-f6d18e31)
[docset/windows/netsecurity/New-NetIPsecAuthProposal.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/New-NetIPsecAuthProposal.yml) | :warning:Warning | | [Details](#user-content-4da83722-f6d18e31)
[docset/windows/netsecurity/Get-NetFirewallInterfaceFilter.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Get-NetFirewallInterfaceFilter.yml) | :warning:Warning | | [Details](#user-content-a1990677-f6d18e31)
[docset/windows/netsecurity/Rename-NetIPsecMainModeRule.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Rename-NetIPsecMainModeRule.yml) | :warning:Warning | | [Details](#user-content-430402b7-f6d18e31)
[docset/windows/netsecurity/Rename-NetIPsecPhase1AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Rename-NetIPsecPhase1AuthSet.yml) | :warning:Warning | | [Details](#user-content-26150a53-f6d18e31)
[docset/windows/netsecurity/Copy-NetIPsecPhase2AuthSet.yml](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/netsecurity/Copy-NetIPsecPhase [...]

2021-01-04 23:34 UTC, opbld31 commented
Docs Build status updates of commit _[39f7717](https://github.com/exchange12rocks/windows-powershell-docs/commits/39f77177851c20a3ef7d92343ec76b6049b16625)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101042330430784-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KNBwR7a58IOrTdNLS3VEJGM%2BM98Izd%2FhwFk2ztYjUII%3D&st=2021-01-04T23%3A29%3A22Z&se=2021-02-04T23%3A34%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 23:45 UTC, opbld30 commented
Docs Build status updates of commit _[deb4ef9](https://github.com/exchange12rocks/windows-powershell-docs/commits/deb4ef99655ca43c18f4bfe72823edaabee5dfcc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101042342024688-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DSHZFJ%2FBuX0MQzT9dKo87arNNcUQFElPJ%2B2RvNIPubc%3D&st=2021-01-04T23%3A40%3A55Z&se=2021-02-04T23%3A45%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 23:55 UTC, opbld30 commented
Docs Build status updates of commit _[d8bfd46](https://github.com/exchange12rocks/windows-powershell-docs/commits/d8bfd463e9025a684b0532bdab09534d96f294ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101042352033107-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pbg%2BfmRDV5kozEvXIemQZXMj8G%2FR7%2BofVjUcQFEiyrI%3D&st=2021-01-04T23%3A50%3A50Z&se=2021-02-04T23%3A55%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-07 13:11 UTC, e0i commented
CC @JohanFreelancer9

2021-01-07 14:24 UTC, get-itips approved these changes

2021-01-07 15:55 UTC, JohanFreelancer9 commented on docset/windows/storage/New-StoragePool.md
> +The first line uses the **Get-PhysicalDisk** cmdlet to get all PhysicalDisk objects than are not yet in a (concrete) storage pool, and assigns the array of objects to the $PhysicalDisks variable.
```suggestion
The first line uses the **Get-PhysicalDisk** cmdlet to get all PhysicalDisk objects that are not yet in a (concrete) storage pool and assigns the array of objects to the $PhysicalDisks variable.
```

2021-01-07 15:58 UTC, JohanFreelancer9 commented on docset/windows/storage/New-StoragePool.md
> +The first part (`New-StoragePool …`) creates a new storage pool using the physical disks in the $PhysicalDisks variable, and then passes the new storage pool down the pipeline. All of the following c
```suggestion
The first part (`New-StoragePool …`) creates a new storage pool using the physical disks in the $PhysicalDisks variable and then passes the new storage pool down the pipeline. All of the following commands are logically part of one command and should be entered as such.
```

2021-01-07 15:59 UTC, JohanFreelancer9 commented on docset/windows/storage/New-StoragePool.md
> +The third part (`Initialize-Disk …`) initializes the disk that was passed in, and then passes the disk down the pipeline.
```suggestion
The third part (`Initialize-Disk …`) initializes the disk that was passed in and then passes the disk down the pipeline.
```

2021-01-07 16:03 UTC, JohanFreelancer9 commented on docset/windows/storage/New-StoragePool.md
> +For the Windows Storage subsystem acceptable values are Mirror, Parity, and Simple. "Mirror" is the default value.
```suggestion
For the Windows Storage subsystem, acceptable values are Mirror, Parity, and Simple. "Mirror" is the default value.
```

2021-01-07 16:09 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-07 17:48 UTC, opbld30 commented
Docs Build status updates of commit _[de65d1d](https://github.com/exchange12rocks/windows-powershell-docs/commits/de65d1de96972da8ec2d6e567fcef8b82a150d14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C7%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101071744234471-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o6UBUDnPMrHqNq4R%2B9jWXtNCpLlrk6e9C7132dOUkHI%3D&st=2021-01-07T17%3A43%3A12Z&se=2021-02-07T17%3A48%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-07 18:56 UTC, tseward requested changes

2021-01-07 18:56 UTC, tseward commented on docset/windows/storage/New-StoragePool.md
> +The second line creates a new storage pool using the $PhysicalDisks variable to specify the disks to include from the WindowsStorage subsystem (specified with a wildcard * to remove the need to modif
Please back tick `$PhysicalDisks`.

2021-01-07 20:07 UTC, dariomws approved these changes
I think you can also leave the acceptable values here.

2021-01-08 02:16 UTC, JohanFreelancer9 approved these changes
Approved with @tseward's and @dariomws's suggestions.

2021-01-09 19:58 UTC, opbld31 commented
Docs Build status updates of commit _[59041d8](https://github.com/exchange12rocks/windows-powershell-docs/commits/59041d8eafe6ea274646d45c43aa53f01ff36767)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101091954269011-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fd9tnJSD%2FMkaJ6OJfFiUP3FdN2wMVIA93u4z%2B9VvNS4%3D&st=2021-01-09T19%3A53%3A10Z&se=2021-02-09T19%3A58%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 20:02 UTC, opbld32 commented
Docs Build status updates of commit _[84d52ed](https://github.com/exchange12rocks/windows-powershell-docs/commits/84d52ed214dda7ec213c570398b50b550b47ae38)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101091958459800-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U7ZRhyzp5hld42Ty%2BEE044ambNCEBlmdjxbLOaAgXqY%3D&st=2021-01-09T19%3A57%3A41Z&se=2021-02-09T20%3A02%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 20:06 UTC, opbld31 commented
Docs Build status updates of commit _[d0e9197](https://github.com/exchange12rocks/windows-powershell-docs/commits/d0e9197bf388871e1ba8257367522af7ae9ce3d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101092001367646-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IxVd47s80gRnB42IKtXeC5npax2K9CYGX9rYU4WnGeI%3D&st=2021-01-09T20%3A01%3A48Z&se=2021-02-09T20%3A06%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 20:10 UTC, opbld30 commented
Docs Build status updates of commit _[95225dc](https://github.com/exchange12rocks/windows-powershell-docs/commits/95225dc0d3769b4b67aca4f5dae3050a6feb2823)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101092004109840-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3MeuZrGWkcaN6C0%2B2b2Fy4jq4H0a7jwQzcyn5MkJTqo%3D&st=2021-01-09T20%3A05%3A46Z&se=2021-02-09T20%3A10%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 20:23 UTC, exchange12rocks commented
I reverted back the acceptable values changes, so as I understand, this PR is ready for merging now.

2021-01-10 15:07 UTC, JohanFreelancer9 approved these changes

2021-01-12 17:31 UTC, opbld30 commented
Docs Build status updates of commit _[9da97a0](https://github.com/exchange12rocks/windows-powershell-docs/commits/9da97a0311ef5148739a4aca61ff232a3d56d74f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101121727168436-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XWLgudtGFr0MPBV5l9THRfy7O1P8kpRMFjv5UQo9OyY%3D&st=2021-01-12T17%3A26%3A07Z&se=2021-02-12T17%3A31%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 17:37 UTC, opbld32 commented
Docs Build status updates of commit _[8e09e94](https://github.com/exchange12rocks/windows-powershell-docs/commits/8e09e94f25c82ec779ecc687183852c1926125d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/New-StoragePool.md](https://github.com/exchange12rocks/windows-powershell-docs/blob/patch-2/docset/windows/storage/New-StoragePool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/new-storagepool?view=win10-ps&branch=pr-en-us-2257) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101121733534335-2257%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1JquZWvktWxxMPqYl7Pbgbx3wCXWnCzU50kFxxpKpLU%3D&st=2021-01-12T17%3A32%3A35Z&se=2021-02-12T17%3A37%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 17:40 UTC, merged