Update Set-AdfsAlternateTlsClientBinding.md
MicrosoftDocs/windows-powershell-docs pull request #2282
Opened 2021-01-22 17:31 UTC by zhvolosh

2021-01-22 17:35 UTC, opbld30 commented
Docs Build status updates of commit _[db473d9](https://github.com/zhvolosh/windows-powershell-docs/commits/db473d9401ec991d547b83031b62199ad51d89ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Set-AdfsAlternateTlsClientBinding.md](https://github.com/zhvolosh/windows-powershell-docs/blob/patch-1/docset/windows/adfs/Set-AdfsAlternateTlsClientBinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsalternatetlsclientbinding?view=win10-ps&branch=pr-en-us-2282) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202101221731593864-2282%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0ycCyP1dAupxJIcj%2BreM31cQmhTRUUWxl9N7lWENkRE%3D&st=2021-01-22T17%3A30%3A38Z&se=2021-02-22T17%3A35%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 00:18 UTC, get-itips approved these changes
Thanks for your contribution @zhvolosh 
Can you kindly also add a description for the Member parameter to align to the other ADFS cmdlets? `Specifies an array of members.` [example](https://docs.microsoft.com/en-us/powershell/module/adfs/test-adfsfarmbehaviorlevelraise?view=win10-ps)

2021-02-10 04:24 UTC, tseward requested changes
It also looks like `-Thumbprint` needs a description.

2021-02-10 05:49 UTC, JohanFreelancer9 approved these changes

2021-02-10 10:27 UTC, dariomws approved these changes
Agree with @tseward and @get-itips.

2021-03-11 16:54 UTC, opbld33 commented
Docs Build status updates of commit _[40e1553](https://github.com/zhvolosh/windows-powershell-docs/commits/40e15534cdcddb7a37aa29fbf40c931ed504391e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/adfs/Set-AdfsAlternateTlsClientBinding.md](https://github.com/zhvolosh/windows-powershell-docs/blob/patch-1/docset/windows/adfs/Set-AdfsAlternateTlsClientBinding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsalternatetlsclientbinding?view=win10-ps&branch=pr-en-us-2282) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103111650520593-2282%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=utdW%2BuwxXyXFKdkNAVeBelphCNx9FYrmRgRGAQ7pEqk%3D&st=2021-03-11T16%3A49%3A57Z&se=2021-04-11T16%3A54%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-11 16:55 UTC, merged