Update New-NetIPsecPhase1AuthSet.md
MicrosoftDocs/windows-powershell-docs pull request #2298
Opened 2021-02-09 15:42 UTC by K-razy

Hello

In the Example 1, it should be "-Phase1AuthSet" insteadOf "-Phase2AuthSet".
If not the certificate verification is not correctly implemented.

Kind Regards

KCS

2021-02-09 15:46 UTC, opbld31 commented
Docs Build status updates of commit _[6904f58](https://github.com/K-razy/windows-powershell-docs/commits/6904f58bc6b733326021a7186e3ec9d8adbced34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/netsecurity/New-NetIPsecPhase1AuthSet.md](https://github.com/K-razy/windows-powershell-docs/blob/patch-1/docset/windows/netsecurity/New-NetIPsecPhase1AuthSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netipsecphase1authset?view=win10-ps&branch=pr-en-us-2298) (win10-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202102091542413305-2298%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1t407%2FIPhHh4y1m4cbLKGEEmd6Y4hABhvUekVRjFMaY%3D&st=2021-02-09T15%3A41%3A28Z&se=2021-03-12T15%3A46%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 23:32 UTC, get-itips approved these changes
Hello @K-razy 
Thanks for your contribution.
Correct, the object created in the line before references a NetIPsecPhase1AuthSet

2021-02-10 02:38 UTC, JohanFreelancer9 approved these changes

2021-02-10 04:23 UTC, tseward requested changes
Can you remove all of the newlines in the Examples? This should shorten up the article and make it easier to read.

2021-02-10 10:34 UTC, dariomws approved these changes

2021-02-11 20:33 UTC, e0i commented
@K-razy Thank you for the contribution. The PR is good to go once the newlines have been removed as suggested.

2021-03-11 16:48 UTC, opbld30 commented
Docs Build status updates of commit _[378a99d](https://github.com/K-razy/windows-powershell-docs/commits/378a99dbe9a5f2524bea0ad496237eb2c85a5add)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/netsecurity/New-NetIPsecPhase1AuthSet.md](https://github.com/K-razy/windows-powershell-docs/blob/patch-1/docset/windows/netsecurity/New-NetIPsecPhase1AuthSet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netipsecphase1authset?view=win10-ps&branch=pr-en-us-2298) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103111644427758-2298%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WKG91%2FnTdN17OkToMWaoM8Y%2BOjUK2i62M2k9l0eQ1MQ%3D&st=2021-03-11T16%3A43%3A46Z&se=2021-04-11T16%3A48%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-11 16:48 UTC, merged