Correction to markdown syntax for list format
MicrosoftDocs/windows-powershell-docs pull request #2308
Opened 2021-02-21 00:25 UTC by chris18890

I noticed that a few list items on https://docs.microsoft.com/en-us/powershell/module/remoteaccess/install-remoteaccess?view=win10-ps weren't rendering correctly, this should make them consistent with the other items in the respective lists.

2021-02-21 03:54 UTC, JohanFreelancer9 commented on docset/windows/remoteaccess/Install-RemoteAccess.md
>  - Vpn.
```suggestion
- Vpn
```

2021-02-21 03:54 UTC, JohanFreelancer9 commented on docset/windows/remoteaccess/Install-RemoteAccess.md
> +- VpnS2S.
```suggestion
- VpnS2S
```

2021-02-21 03:55 UTC, JohanFreelancer9 requested changes
Copy review - please also remove the two periods as indicated.

2021-02-22 04:56 UTC, JohanFreelancer9 approved these changes

2021-02-22 20:42 UTC, get-itips approved these changes
Thanks for your contribution!

2021-02-22 21:10 UTC, dariomws approved these changes

2021-02-23 16:07 UTC, tseward approved these changes

2021-03-11 16:55 UTC, tiburd commented
close > reopen

2021-03-11 17:00 UTC, opbld32 commented
Docs Build status updates of commit _[37976cb](https://github.com/chris18890/windows-powershell-docs/commits/37976cb5caac654a457c1cead62faab738d06548)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/remoteaccess/Install-RemoteAccess.md](https://github.com/chris18890/windows-powershell-docs/blob/patch-1/docset/windows/remoteaccess/Install-RemoteAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/remoteaccess/install-remoteaccess?view=win10-ps&branch=pr-en-us-2308) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103111656211535-2308%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1xljmAVolFkn1AMhDZ8yvrjRVFYYdQmqyVJ3Jtydl7s%3D&st=2021-03-11T16%3A55%3A11Z&se=2021-04-11T17%3A00%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-11 17:11 UTC, opbld33 commented
Docs Build status updates of commit _[cebda23](https://github.com/chris18890/windows-powershell-docs/commits/cebda236a8da3c4da856c2980931e2c31b1eaeca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/remoteaccess/Install-RemoteAccess.md](https://github.com/chris18890/windows-powershell-docs/blob/patch-1/docset/windows/remoteaccess/Install-RemoteAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/remoteaccess/install-remoteaccess?view=win10-ps&branch=pr-en-us-2308) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103111708291647-2308%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uOe6p0%2BIa3PivxUhEPPdLd3gsXQmrbCXgu%2BMbKpdJIw%3D&st=2021-03-11T17%3A06%3A38Z&se=2021-04-11T17%3A11%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-11 17:12 UTC, merged