Resolve #2301
MicrosoftDocs/windows-powershell-docs pull request #2309
Opened 2021-02-21 15:27 UTC by velkovb

Remove Server 2008 R2
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2301

2021-02-22 09:37 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/dnsserver/Get-DnsServer.md
> +For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://technet.microsoft.com/en-us/library/ee176824.aspx).
```suggestion
For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://technet.microsoft.com/library/ee176824.aspx).
```

2021-02-22 09:39 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md
> +For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://technet.microsoft.com/en-us/library/ee176824.aspx).
```suggestion
For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://technet.microsoft.com/library/ee176824.aspx).
```

2021-02-22 09:42 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-22 20:40 UTC, get-itips approved these changes

2021-02-22 21:12 UTC, dariomws approved these changes

2021-02-23 06:42 UTC, JohanFreelancer9 approved these changes

2021-02-23 16:11 UTC, tseward commented on docset/winserver2012-ps/dnsserver/Get-DnsServer.md
> +For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://technet.microsoft.com/library/ee176824.aspx).
Please update the URL to https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/export-clixml

2021-02-24 03:59 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/dnsserver/Get-DnsServer.md
> +For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/export-clixml).
```suggestion
For more information about **Export-Clixml**, see [Using the Export-Clixml cmdlet](https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/export-clixml).
```

2021-02-25 13:09 UTC, tseward approved these changes

2021-02-25 14:40 UTC, JohanFreelancer9 approved these changes

2021-03-03 12:04 UTC, opbld31 commented
Docs Build status updates of commit _[190bd2f](https://github.com/velkovb/windows-powershell-docs/commits/190bd2f2a0b21a735c0f73ed8ea84f9d7a2e42b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/windows/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=win10-ps&branch=pr-en-us-2309) (win10-ps) |
[docset/winserver2012-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012-ps&branch=pr-en-us-2309) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012r2-ps&branch=pr-en-us-2309) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103031200427306-2309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ggTOvAjwzLL%2FT0i%2FgkXI8WR7sA3t5ErclBcnFh5yRZY%3D&st=2021-03-03T11%3A59%3A49Z&se=2021-04-03T12%3A04%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 12:08 UTC, opbld33 commented
Docs Build status updates of commit _[c0c9954](https://github.com/velkovb/windows-powershell-docs/commits/c0c995448243a001ae813ee4a52362e9e2cd6617)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/windows/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=win10-ps&branch=pr-en-us-2309) (win10-ps) |
[docset/winserver2012-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012-ps&branch=pr-en-us-2309) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012r2-ps&branch=pr-en-us-2309) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103031204455046-2309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OlcM2lm4g4eLEUw2EEk22Eqo6paWeIHNrIrWJtpR5n0%3D&st=2021-03-03T12%3A03%3A47Z&se=2021-04-03T12%3A08%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 16:24 UTC, tseward approved these changes

2021-03-09 17:55 UTC, opbld33 commented
Docs Build status updates of commit _[f3b724a](https://github.com/velkovb/windows-powershell-docs/commits/f3b724acf640989010082e8c7cdd5446bf891d2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/windows/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=win10-ps&branch=pr-en-us-2309) (win10-ps) |
[docset/winserver2012-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012-ps&branch=pr-en-us-2309) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012r2-ps&branch=pr-en-us-2309) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103091751309706-2309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ay4WYDA0YASlC7og16ChlKU8mDaLnhRKhfSXLvhCdh4%3D&st=2021-03-09T17%3A50%3A27Z&se=2021-04-09T17%3A55%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 17:59 UTC, opbld33 commented
Docs Build status updates of commit _[8bf1aa2](https://github.com/velkovb/windows-powershell-docs/commits/8bf1aa2ca35f807c6bb37a421219f3fcab4a9de2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/windows/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=win10-ps&branch=pr-en-us-2309) (win10-ps) |
[docset/winserver2012-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012-ps&branch=pr-en-us-2309) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2301-remove-2008-r2/docset/winserver2012r2-ps/dnsserver/Get-DnsServer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserver?view=winserver2012r2-ps&branch=pr-en-us-2309) (winserver2012r2-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103091754464335-2309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7M6ycYQbCQQ0AmIiG%2BoAGJsmgVlS1%2FgdhM4GIzshhmU%3D&st=2021-03-09T17%3A54%3A34Z&se=2021-04-09T17%3A59%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 17:59 UTC, merged