Update Disable-PhysicalDiskIdentification Ex1 Cmds
MicrosoftDocs/windows-powershell-docs pull request #2327
Opened 2021-03-08 23:54 UTC by katy-pan

Update command as discovered by partner Bug 31760701. Change by ecosystem PM (Katy Pan) and approval by feature team software engineer (Taylor Hope)

2021-03-08 23:58 UTC, opbld31 commented
Docs Build status updates of commit _[7689308](https://github.com/katy-pan/windows-powershell-docs/commits/7689308bd0aee9a54914c8a58b534aee55aa63ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/Disable-PhysicalDiskIdentification.md](https://github.com/katy-pan/windows-powershell-docs/blob/patch-1/docset/windows/storage/Disable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/disable-physicaldiskidentification?view=win10-ps&branch=pr-en-us-2327) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103082354210958-2327%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fPh06JJP1l9DYSL0KHnlkfSoypekGgqSqrEfBwfjMCo%3D&st=2021-03-08T23%3A53%3A21Z&se=2021-04-08T23%3A58%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 10:52 UTC, JohanFreelancer9 commented on docset/windows/storage/Disable-PhysicalDiskIdentification.md
>  The first command gets the storage poll named SpacePool by using the Get-StoragePool cmdlet.
```suggestion
```

2021-03-09 10:58 UTC, JohanFreelancer9 commented on docset/windows/storage/Disable-PhysicalDiskIdentification.md
>  The first command gets the storage poll named SpacePool by using the Get-StoragePool cmdlet.
@katy-pan - please confirm whether this line should be deleted, and if necessary, please commit the deletion.

2021-03-09 10:58 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-09 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[a0072d8](https://github.com/katy-pan/windows-powershell-docs/commits/a0072d8f255078281a2e33b2ff80cd4ffb81739b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/Disable-PhysicalDiskIdentification.md](https://github.com/katy-pan/windows-powershell-docs/blob/patch-1/docset/windows/storage/Disable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/disable-physicaldiskidentification?view=win10-ps&branch=pr-en-us-2327) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103091934358458-2327%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FNVJGahiG8pjrFu%2FQLYX16f6UHx5YRCeQUsX4v7uRpU%3D&st=2021-03-09T19%3A33%3A20Z&se=2021-04-09T19%3A38%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-10 01:27 UTC, JohanFreelancer9 approved these changes

2021-03-11 17:15 UTC, tseward requested changes

2021-03-11 17:15 UTC, tseward commented on docset/windows/storage/Disable-PhysicalDiskIdentification.md
> +PGet-PhysicalDisk -StoragePool $pool | Disable-PhysicalDiskIdentification
This should be in the format of:

```
PS C:\> Get-PhysicalDisk -StoragePool $pool | Disable-PhysicalDiskIdentification
```

I'm assuming the "P" in front of "Get-" was a typo.

Where is $pool being initialized?

2021-03-11 17:15 UTC, tseward commented on docset/windows/storage/Disable-PhysicalDiskIdentification.md
>  The command stores the pool in the $StPool variable.
Did you mean to modify this to indicate the variable "$pool"?

2021-03-11 20:57 UTC, get-itips reviewed
I am ok once @tseward suggestions are applied

2021-03-11 21:44 UTC, dariomws requested changes

2021-03-11 21:44 UTC, dariomws commented on docset/windows/storage/Disable-PhysicalDiskIdentification.md
>  The command stores the pool in the $StPool variable.
This example disables the identification LED on all physical disks associated with the storage pool named "SpacePool".

2021-03-13 00:51 UTC, opbld30 commented
Docs Build status updates of commit _[3c1eb73](https://github.com/katy-pan/windows-powershell-docs/commits/3c1eb73b4304a965d333042897db455b7b731d52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/Disable-PhysicalDiskIdentification.md](https://github.com/katy-pan/windows-powershell-docs/blob/patch-1/docset/windows/storage/Disable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/disable-physicaldiskidentification?view=win10-ps&branch=pr-en-us-2327) (win10-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C13%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103130048033230-2327%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hwXqnfZd2n263e%2BmVxwgXFH8uh62zVsF5HxL2wYcKlo%3D&st=2021-03-13T00%3A46%3A33Z&se=2021-04-13T00%3A51%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-17 13:01 UTC, e0i commented
Hello, @katy-pan This PR is good to go once the formatting fixes have been applied. Thank you for this contribution.

2021-03-17 17:52 UTC, tseward requested changes

2021-03-17 17:52 UTC, tseward commented on docset/windows/storage/Disable-PhysicalDiskIdentification.md
> +Get-PhysicalDisk -StoragePool $pool | Disable-PhysicalDiskIdentification
This should be prefixed with `PS C:\>`.

2021-03-17 18:46 UTC, opbld33 commented
Docs Build status updates of commit _[068ca37](https://github.com/katy-pan/windows-powershell-docs/commits/068ca37e112f590a2b14c681af07742c879f7e26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/Disable-PhysicalDiskIdentification.md](https://github.com/katy-pan/windows-powershell-docs/blob/patch-1/docset/windows/storage/Disable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/disable-physicaldiskidentification?view=windowsserver2019-ps&branch=pr-en-us-2327) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103171841446455-2327%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u%2FldYXX3ZqyG%2Fv7CLIEeQi%2FupWCinJ%2FC9BIwNptA8%2FM%3D&st=2021-03-17T18%3A41%3A40Z&se=2021-04-17T18%3A46%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 15:28 UTC, opbld30 commented
Docs Build status updates of commit _[e419005](https://github.com/katy-pan/windows-powershell-docs/commits/e419005bedfc54a99e75915920c462d3380df7ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/storage/Disable-PhysicalDiskIdentification.md](https://github.com/katy-pan/windows-powershell-docs/blob/patch-1/docset/windows/storage/Disable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/disable-physicaldiskidentification?view=windowsserver2016-ps&branch=pr-en-us-2327) (WindowsServer2016-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103221522559088-2327%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CDov8DxL7e%2F%2BPeOa4VQbQegBXSbq8nT5gIlhIleUKnA%3D&st=2021-03-22T15%3A22%3A59Z&se=2021-04-22T15%3A27%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 15:28 UTC, merged