Resolves #2303
MicrosoftDocs/windows-powershell-docs pull request #2348
Opened 2021-03-26 14:10 UTC by velkovb

Add Example
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2303

2021-03-26 14:15 UTC, opbld33 commented
Docs Build status updates of commit _[b183530](https://github.com/velkovb/windows-powershell-docs/commits/b1835304ca28a1512d5b0c71d4577545a5a79ef9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/windows/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-2348) (WindowsServer2016-ps) |
[docset/winserver2012-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2012-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=winserver2012-ps&branch=pr-en-us-2348) (winserver2012-ps) |
[docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=winserver2012r2-ps&branch=pr-en-us-2348) (winserver2012r2-ps) |
[docset/winserver2019-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2019-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2019-ps&branch=pr-en-us-2348) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103261410352047-2348%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gCxMVuHllOzkVYsAzOStDHFMqWOmOYLQrUvDfqqzGmA%3D&st=2021-03-26T14%3A10%3A46Z&se=2021-04-26T14%3A15%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 15:10 UTC, JohanFreelancer9 commented on docset/windows/vpnclient/Add-VpnConnection.md
> +The pre-shared key for the connection is specified by the **L2tpPsk** parameter Additional parameters specify that the connection:
```suggestion
The pre-shared key for the connection is specified by the **L2tpPsk** parameter. Additional parameters specify that the connection: 
```

2021-03-26 15:14 UTC, JohanFreelancer9 commented on docset/windows/vpnclient/Add-VpnConnection.md
> +This set of commands adds a VPN connection using already generated EAP XML configuration. For more information how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.co
```suggestion
This set of commands adds a VPN connection using an already generated EAP XML configuration. For more information about how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.com/windows/client-management/mdm/eap-configuration)
```

2021-03-26 15:18 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/vpnclient/Add-VpnConnection.md
> +The pre-shared key for the connection is specified by the **L2tpPsk** parameter Additional parameters specify that the connection:
```suggestion
The pre-shared key for the connection is specified by the **L2tpPsk** parameter. Additional parameters specify that the connection: 
```

2021-03-26 15:20 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/vpnclient/Add-VpnConnection.md
> +This set of commands adds a VPN connection using already generated EAP XML configuration. For more information how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.co
```suggestion
This set of commands adds a VPN connection using an already generated EAP XML configuration. For more information about how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.com/windows/client-management/mdm/eap-configuration)
```

2021-03-26 15:23 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md
>  The pre-shared key for the connection is specified by the **L2tpPsk** parameter Additional parameters specify that the connection:
```suggestion
The pre-shared key for the connection is specified by the **L2tpPsk** parameter. Additional parameters specify that the connection: 
```

2021-03-26 15:27 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md
> +This set of commands adds a VPN connection using already generated EAP XML configuration. For more information how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.co
```suggestion
This set of commands adds a VPN connection using already generated EAP XML configuration. For more information about how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.com/windows/client-management/mdm/eap-configuration).
```

2021-03-26 15:31 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/vpnclient/Add-VpnConnection.md
> +The pre-shared key for the connection is specified by the **L2tpPsk** parameter Additional parameters specify that the connection:
```suggestion
The pre-shared key for the connection is specified by the **L2tpPsk** parameter. Additional parameters specify that the connection: 
```

2021-03-26 15:33 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/vpnclient/Add-VpnConnection.md
> +This set of commands adds a VPN connection using already generated EAP XML configuration. For more information how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.co
```suggestion
This set of commands adds a VPN connection using already generated EAP XML configuration. For more information about how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.com/windows/client-management/mdm/eap-configuration).
```

2021-03-26 15:40 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: `-Debug`, `-ErrorAction`, `-ErrorVariable`,
`-InformationAction`, `-InformationVariable`, `-OutVariable`, `-OutBuffer`, `-PipelineVariable`,
`-Verbose`, `-WarningAction`, and `-WarningVariable`. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-03-26 15:51 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-26 16:43 UTC, opbld31 commented
Docs Build status updates of commit _[ef53549](https://github.com/velkovb/windows-powershell-docs/commits/ef53549726157b7da765e7a612c689d86b377731)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/windows/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-2348) (WindowsServer2016-ps) |
[docset/winserver2012-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2012-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=winserver2012-ps&branch=pr-en-us-2348) (winserver2012-ps) |
[docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=winserver2012r2-ps&branch=pr-en-us-2348) (winserver2012r2-ps) |
[docset/winserver2019-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2019-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2019-ps&branch=pr-en-us-2348) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103261638381222-2348%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FLkkvbn6RVTk5SHS2z6MAqV9YYJab8Ocgzo3lRqo1uE%3D&st=2021-03-26T16%3A38%3A35Z&se=2021-04-26T16%3A43%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-27 03:27 UTC, JohanFreelancer9 approved these changes

2021-03-27 22:49 UTC, tseward approved these changes

2021-03-28 14:31 UTC, get-itips commented on docset/windows/vpnclient/Add-VpnConnection.md
> +PS C:\> Add-VpnConnection -Name "Test6" -ServerAddress "10.1.1.1" -TunnelType "L2tp" -EncryptionLevel "Required" -AuthenticationMethod Eap -SplitTunneling -AllUserConnection -RememberCredential -EapC
```suggestion
PS C:\> Add-VpnConnection -Name "Test6" -ServerAddress "10.1.1.1" -TunnelType "L2tp" -EncryptionLevel "Required" -AuthenticationMethod Eap -SplitTunneling -AllUserConnection -RememberCredential -EapConfigXmlStream $EAPXml
```

2021-03-28 14:32 UTC, get-itips commented on docset/windows/vpnclient/Add-VpnConnection.md
> +PS C:\> Add-VpnConnection -Name "Test6" -ServerAddress "10.1.1.1" -TunnelType "L2tp" -EncryptionLevel "Required" -AuthenticationMethod Eap -SplitTunneling -AllUserConnection -RememberCredential -EapC
Small typo, please kindly fix the other occurrences.

2021-03-29 07:05 UTC, dariomws approved these changes

2021-03-29 07:05 UTC, dariomws commented on docset/windows/vpnclient/Add-VpnConnection.md
> +This set of commands adds a VPN connection using already generated EAP XML configuration. For more information about how to generate EAP XML configuration, see [EAP Configuration](https://docs.micros
```suggestion
This set of commands adds a VPN connection using an already generated EAP XML configuration. For more information about how to generate EAP XML configuration, see [EAP Configuration](https://docs.microsoft.com/windows/client-management/mdm/eap-configuration).
```
Just a small suggestion. I approve after @get-itips and @JohanFreelancer9 details.

2021-03-29 07:32 UTC, opbld30 commented
Docs Build status updates of commit _[f92a93a](https://github.com/velkovb/windows-powershell-docs/commits/f92a93a18834251b1389b12fba9aea40437b7885)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/windows/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/windows/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-2348) (WindowsServer2016-ps) |
[docset/winserver2012-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2012-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=winserver2012-ps&branch=pr-en-us-2348) (winserver2012-ps) |
[docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2012r2-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=winserver2012r2-ps&branch=pr-en-us-2348) (winserver2012r2-ps) |
[docset/winserver2019-ps/vpnclient/Add-VpnConnection.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2303-add-example/docset/winserver2019-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2019-ps&branch=pr-en-us-2348) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C29%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103290727374859-2348%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=03QBtrFGoRmr1kuUkR3vmuVa%2BEXRJFUCLY%2BC2SbfTMw%3D&st=2021-03-29T07%3A27%3A36Z&se=2021-04-29T07%3A32%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-29 21:39 UTC, get-itips approved these changes

2021-03-30 13:00 UTC, merged