Fixed Close-SmbOpenFile examples
MicrosoftDocs/windows-powershell-docs pull request #2362
Opened 2021-03-31 21:26 UTC by dariomws

Related to https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2360.

2021-03-31 21:34 UTC, opbld30 commented
Docs Build status updates of commit _[f3f5919](https://github.com/dariomws/windows-powershell-docs/commits/f3f5919fcc9936e627d69505ce55250c94cc5b3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2012-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=winserver2012-ps&branch=pr-en-us-2362) (winserver2012-ps) |
[docset/winserver2012r2-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2012r2-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=winserver2012r2-ps&branch=pr-en-us-2362) (winserver2012r2-ps) |
[docset/winserver2016-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2016-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=windowsserver2016-ps&branch=pr-en-us-2362) (WindowsServer2016-ps) |
[docset/winserver2019-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2019-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=windowsserver2019-ps&branch=pr-en-us-2362) (WindowsServer2019-ps) |
[docset/winserver2022-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2022-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=windowsserver2022-ps&branch=pr-en-us-2362) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C31%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202103312126241426-2362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oo0jKBhrZfK1SJS8NmyNc1%2FKj%2B9TBnwYZGF2hzFUHSk%3D&st=2021-03-31T21%3A29%3A39Z&se=2021-05-01T21%3A34%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 03:02 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/smbshare/Close-SmbOpenFile.md
>  This command closes one or more files that are open by one of the client identified with the session ID 4415226380393 of the SMB server.
```suggestion
This command closes one or more files that are open by one of the clients identified with the session ID 4415226380393 of the SMB server.
```

2021-04-01 03:03 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/smbshare/Close-SmbOpenFile.md
>  This command closes one or more files that are open by one of the client identified with the session ID 4415226380393 of the SMB server.
Not related to this PR, but please also commit this minor typo.

2021-04-01 03:04 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/smbshare/Close-SmbOpenFile.md
>  This command closes one or more files that are open by one of the client identified with the session ID 4415226380393 of the SMB server.
```suggestion
This command closes one or more files that are open by one of the clients identified with the session ID 4415226380393 of the SMB server.
```

2021-04-01 03:05 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-01 07:51 UTC, opbld32 commented
Docs Build status updates of commit _[a9be707](https://github.com/dariomws/windows-powershell-docs/commits/a9be70797ce568968f9f01eb8c3e0f85480d81d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2012-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=winserver2012-ps&branch=pr-en-us-2362) (winserver2012-ps) |
[docset/winserver2012r2-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2012r2-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=winserver2012r2-ps&branch=pr-en-us-2362) (winserver2012r2-ps) |
[docset/winserver2016-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2016-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=windowsserver2016-ps&branch=pr-en-us-2362) (WindowsServer2016-ps) |
[docset/winserver2019-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2019-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=windowsserver2019-ps&branch=pr-en-us-2362) (WindowsServer2019-ps) |
[docset/winserver2022-ps/smbshare/Close-SmbOpenFile.md](https://github.com/dariomws/windows-powershell-docs/blob/patch-9/docset/winserver2022-ps/smbshare/Close-SmbOpenFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/close-smbopenfile?view=windowsserver2022-ps&branch=pr-en-us-2362) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104010745015092-2362%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9btzUtQpesbL8YrXzMcl2uRYRdL3mqhmT658Sz%2FBItE%3D&st=2021-04-01T07%3A46%3A24Z&se=2021-05-02T07%3A51%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 08:18 UTC, JohanFreelancer9 approved these changes

2021-04-05 14:08 UTC, sdwheeler approved these changes

2021-04-05 14:08 UTC, merged