Added WDAC exceptions creation ps HOW TO
MicrosoftDocs/windows-powershell-docs pull request #2365
Opened 2021-04-01 23:49 UTC by jgeurten

- Provided comprehensive PS cmds resulting in a WDAC rule exception and WDAC CI policy
- Verified the PS cmds successfully build a policy locally and converted the policy to binary
- Added description of the steps below the PS example

Open Items: 
- Do we need a topic in the WDAC docs about exceptions?

2021-04-01 23:52 UTC, jgeurten commented
Can I please have @jsuther1974 and @isbrahm added as optional reviewers

2021-04-01 23:55 UTC, opbld31 commented
Docs Build status updates of commit _[23fd68d](https://github.com/jgeurten/windows-powershell-docs/commits/23fd68d58d73d9af6e5315e08636b39b1be1fc3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/configci/New-CIPolicy.md](https://github.com/jgeurten/windows-powershell-docs/blob/jogeurte-wdac-exceptions/docset/winserver2019-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps&branch=pr-en-us-2365) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104012349271506-2365%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9kse027l%2F2EHwREbbpCmlLWjyMwNu9gToNeUTXZk2UM%3D&st=2021-04-01T23%3A50%3A48Z&se=2021-05-02T23%3A55%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 08:10 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/configci/New-CIPolicy.md
> +The first set of commands create an allow file rule based on the CA certificate used to sign the test application as well as a deny exception rule based on the original file name of the application t
```suggestion
The first set of commands creates an allow file rule based on the CA certificate used to sign the test application as well as a deny exception rule based on the original file name of the application to block. The deny rule has a user mode and kernel mode component which requires both sections' file exception boolean fields to be set to '1'. 
```

2021-04-02 08:11 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/configci/New-CIPolicy.md
> +The second set of commands set the exceptions field of the allow file rule to the identifier of the exception rule. If the allow rule has both a user mode and kernel mode component, the exception fie
```suggestion
The second set of commands sets the exceptions field of the allow file rule to the identifier of the exception rule. If the allow rule has both a user mode and kernel mode component, the exception fields of both components must have the identifier of the exception rule set. 
```

2021-04-02 08:12 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/configci/New-CIPolicy.md
> +File rule exceptions cannot use the PCA Certificate, Publisher, Signed Version or File Publisher rule levels.
```suggestion
File rule exceptions cannot use the PCA Certificate, Publisher, Signed Version, or File Publisher rule levels. 
```

2021-04-02 08:13 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-02 16:38 UTC, opbld33 commented
Docs Build status updates of commit _[dba04ce](https://github.com/jgeurten/windows-powershell-docs/commits/dba04ceec9e3801bc40dbe67cc803e8cb072ce7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/configci/New-CIPolicy.md](https://github.com/jgeurten/windows-powershell-docs/blob/jogeurte-wdac-exceptions/docset/winserver2019-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps&branch=pr-en-us-2365) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104021631298311-2365%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BGvEhN%2FKwhaGokSVr6G8YgJ52t9LY90BBFdOG3Esj9c%3D&st=2021-04-02T16%3A33%3A01Z&se=2021-05-03T16%3A38%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 16:44 UTC, opbld30 commented
Docs Build status updates of commit _[644d754](https://github.com/jgeurten/windows-powershell-docs/commits/644d754a36510937daf294df46553d881586bdb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/configci/New-CIPolicy.md](https://github.com/jgeurten/windows-powershell-docs/blob/jogeurte-wdac-exceptions/docset/winserver2019-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps&branch=pr-en-us-2365) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104021632235392-2365%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3Zh2%2B%2FHSrgTKaSdI4wyglvBfkIgrfKqDX8eSMs9XixE%3D&st=2021-04-02T16%3A39%3A14Z&se=2021-05-03T16%3A44%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 16:53 UTC, opbld32 commented
Docs Build status updates of commit _[4bca68f](https://github.com/jgeurten/windows-powershell-docs/commits/4bca68f363336e09a94e2a5dfddfd6c863361d9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/configci/New-CIPolicy.md](https://github.com/jgeurten/windows-powershell-docs/blob/jogeurte-wdac-exceptions/docset/winserver2019-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps&branch=pr-en-us-2365) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104021632081082-2365%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=trpDAc%2BI0tJ%2F78PlDXTgZF2xfpJGlSGPp7nlWskmYz4%3D&st=2021-04-02T16%3A48%3A16Z&se=2021-05-03T16%3A53%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 16:55 UTC, JohanFreelancer9 approved these changes

2021-04-05 14:06 UTC, sdwheeler requested changes
Please make the same changes to the 2022 content.

2021-04-05 16:58 UTC, jgeurten commented
> Please make the same changes to the 2022 content.

I have made the changes to the 2022 content as well, @sdwheeler. In the future, is the expectation to make the changes to only 2022 content or both 2019, 2022? Thanks. 

Good to merge the PR from my side.

2021-04-05 17:02 UTC, sdwheeler commented
@jgeurten You need to make changes to all versions that the change applies to. This can include the previous versions if the change is appropriate to those versions.

2021-04-05 17:02 UTC, opbld32 commented
Docs Build status updates of commit _[25b84fa](https://github.com/jgeurten/windows-powershell-docs/commits/25b84fa86768679c037c73ae2c59ffd067e5f155)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/configci/New-CIPolicy.md](https://github.com/jgeurten/windows-powershell-docs/blob/jogeurte-wdac-exceptions/docset/winserver2019-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2019-ps&branch=pr-en-us-2365) (WindowsServer2019-ps) |
[docset/winserver2022-ps/configci/New-CIPolicy.md](https://github.com/jgeurten/windows-powershell-docs/blob/jogeurte-wdac-exceptions/docset/winserver2022-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2022-ps&branch=pr-en-us-2365) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104051656519873-2365%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jwelJKLTodCrZpZfIjUq3RH9sWQl00SqU1EC%2FGTB5f4%3D&st=2021-04-05T16%3A57%3A50Z&se=2021-05-06T17%3A02%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 14:36 UTC, sdwheeler approved these changes

2021-04-06 14:36 UTC, merged