update New-NetFirewallRule.md
MicrosoftDocs/windows-powershell-docs pull request #2409
Opened 2021-04-11 10:52 UTC by MaratMussabekov

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2377

2021-04-11 10:52 UTC, MaratMussabekov commented
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

2021-04-11 10:58 UTC, opbld33 commented
Docs Build status updates of commit _[05dd0cb](https://github.com/MaratMussabekov/windows-powershell-docs/commits/05dd0cb6dd4885d3f09923c390484c424f5d572c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C11%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104111052264762-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FCcGhTo4fpmcqy2sYAS5nu4ISSieIzHVK7ywkqBB9Ms%3D&st=2021-04-11T10%3A53%3A41Z&se=2021-05-12T10%3A58%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-11 15:04 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
> +Note: The DeferToApp and DeferToUser options are only valid for computers running Windows 7, Windows Server 2008 R2, and Windows Server® 2012.
```suggestion
> [!NOTE]
> The DeferToApp and DeferToUser options are only valid for computers running Windows 7, Windows Server 2008 R2, and Windows Server 2012.
```

2021-04-11 15:05 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md
> +The acceptable values for this parameter are: Block or Allow.
```suggestion
The acceptable values for this parameter are Block and Allow.
```

2021-04-11 15:06 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md
> +The acceptable values for this parameter are: Block or Allow.
```suggestion
The acceptable values for this parameter are Block and Allow.
```

2021-04-11 15:08 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md
> +The acceptable values for this parameter are: Block or Allow.
```suggestion
The acceptable values for this parameter are Block and Allow.
```

2021-04-11 15:15 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md
> +The acceptable values for this parameter are: Block or Allow.
```suggestion
The acceptable values for this parameter are Block and Allow.
```

2021-04-11 15:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-12 17:58 UTC, opbld33 commented
Docs Build status updates of commit _[3355fb2](https://github.com/MaratMussabekov/windows-powershell-docs/commits/3355fb25e0dc440bf984e8dd7b01aae2accde628)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104121752235387-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FtKAe71RyQCGrwuT3wZsdqktFW8eINorDOrirIE1tX0%3D&st=2021-04-12T17%3A53%3A44Z&se=2021-05-13T17%3A58%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 18:05 UTC, opbld33 commented
Docs Build status updates of commit _[eeba1cf](https://github.com/MaratMussabekov/windows-powershell-docs/commits/eeba1cf53b278db5d9a76bbd5da3d49f2f5832db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104121752371582-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7mZeBZRWSmB9qKTBiGzgaPRLmPLoweaQ3vJuSYO0iBk%3D&st=2021-04-12T18%3A00%3A06Z&se=2021-05-13T18%3A05%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 18:11 UTC, opbld33 commented
Docs Build status updates of commit _[09a8747](https://github.com/MaratMussabekov/windows-powershell-docs/commits/09a874711d1fd294587920a4795864b039ede51e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104121752310007-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gZWZyBaadYcZcERUIImpJVVrrVblv2nmH0mCZK41vqQ%3D&st=2021-04-12T18%3A06%3A32Z&se=2021-05-13T18%3A11%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 18:18 UTC, opbld31 commented
Docs Build status updates of commit _[bfbd2be](https://github.com/MaratMussabekov/windows-powershell-docs/commits/bfbd2beee5a5dd0eccc0f6f7717a64dbf1db2552)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104121753494434-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rsMG6w%2F7VJEf7kjHWk2XJFz5Po1fTnArxqKb0yVGgyM%3D&st=2021-04-12T18%3A13%3A06Z&se=2021-05-13T18%3A18%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[2f504df](https://github.com/MaratMussabekov/windows-powershell-docs/commits/2f504df52c3d0cc57aa50aff27cbd088aa95c0bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104121753439526-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u2okgfLR7A4RePUCckugUCxK2Z8tyk7PRryEmYJoLX8%3D&st=2021-04-12T18%3A19%3A28Z&se=2021-05-13T18%3A24%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-13 05:28 UTC, JohanFreelancer9 approved these changes

2021-04-15 23:53 UTC, get-itips commented on docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md
> +The acceptable values for this parameter are Block and Allow.
I was able to use "DeferToApp" and "DeferToUser" in WinServ2012R2 (the article you are editing belongs to that version), can you kindly detail what is the reason to remove those values from acceptable list? thanks

2021-04-16 00:02 UTC, get-itips commented on docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md
> +The acceptable values for this parameter are Block and Allow.
I was also able to specify DeferToUser and DeferToApp in Server 2016

2021-04-16 00:03 UTC, get-itips requested changes
@MaratMussabekov Marat, please review my comments, 2012r2 and 2016 still have those parameters, currently on my lab do not have 2019 and 2022 can you please test those versions? probably the parameters are still there.

2021-04-16 06:59 UTC, dariomws requested changes
Agree with @get-itips. I tested both in W2012 R2, 2016 and 2019.

This note/sentence should be removed from all articles of each version.

2021-04-16 12:17 UTC, get-itips commented on docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
> +> [!NOTE]
Please use a regular Note: as the NOTE tag can't be rendered in get-help output thanks

2021-04-16 14:49 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
> +> [!NOTE]
Note: The DeferToApp and DeferToUser options are only valid for computers running Windows 7, Windows Server 2008 R2, and Windows Server 2012.

2021-04-16 14:50 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
> +> [!NOTE]
```suggestion
Note: The DeferToApp and DeferToUser options are only valid for computers running Windows 7, Windows Server 2008 R2, and Windows Server 2012.
```

2021-04-16 14:50 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md
> +> The DeferToApp and DeferToUser options are only valid for computers running Windows 7, Windows Server 2008 R2, and Windows Server 2012.
```suggestion
```

2021-04-20 16:09 UTC, opbld33 commented
Docs Build status updates of commit _[12fb1a7](https://github.com/MaratMussabekov/windows-powershell-docs/commits/12fb1a75ee2d632eec05ac22cad6fb559161b4c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104201603281835-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zruHFauzdXS7r2k%2FEPa0Gykd5ZxTXECDkO0kUjQ7%2FBg%3D&st=2021-04-20T16%3A04%3A35Z&se=2021-05-21T16%3A09%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 16:15 UTC, opbld31 commented
Docs Build status updates of commit _[474a539](https://github.com/MaratMussabekov/windows-powershell-docs/commits/474a539c691aad8e65e0f5d013fc3dd9fb9a40fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104201603555372-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BAvKCqSLxRCV1btYyQLLPhuNcj1uAgJbC7tneW3NPuY%3D&st=2021-04-20T16%3A10%3A49Z&se=2021-05-21T16%3A15%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 16:22 UTC, opbld31 commented
Docs Build status updates of commit _[5ed10dc](https://github.com/MaratMussabekov/windows-powershell-docs/commits/5ed10dce47637e899bc141582037482d9aebdde6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |
[docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104201612577415-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FwAAl3gozHJ%2Bv%2FwftO5g3jYMAFLHA79dtbkKTnV8hIM%3D&st=2021-04-20T16%3A17%3A18Z&se=2021-05-21T16%3A22%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 16:25 UTC, MaratMussabekov commented
Dear @JohanFreelancer9 ,
can you please have another look? I applied recommendations from other contributors and also fixed the same error on Set-NetFirewallRule article.
Thank you!

2021-04-20 16:28 UTC, opbld30 commented
Docs Build status updates of commit _[bc6c921](https://github.com/MaratMussabekov/windows-powershell-docs/commits/bc6c921a9a3bf5b17baeab6e495cc0baff28f91e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |
[docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104201621351520-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hx%2Bmat940vy9pHzzhoLGpB%2Fa3y7MoEzhnljef6FH%2BBA%3D&st=2021-04-20T16%3A23%3A54Z&se=2021-05-21T16%3A28%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 16:35 UTC, opbld32 commented
Docs Build status updates of commit _[474a539](https://github.com/MaratMussabekov/windows-powershell-docs/commits/474a539c691aad8e65e0f5d013fc3dd9fb9a40fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |
[docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104201603451622-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LbkfoVVl4%2B1v0us0pLjGCYdxQGIOTQL22XFGobGUJYc%3D&st=2021-04-20T16%3A30%3A38Z&se=2021-05-21T16%3A35%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-21 04:31 UTC, JohanFreelancer9 approved these changes

2021-04-21 04:32 UTC, JohanFreelancer9 commented
@MaratMussabekov - looks good.

2021-04-21 07:10 UTC, dariomws approved these changes

2021-04-21 14:00 UTC, get-itips approved these changes

2021-04-21 15:02 UTC, tseward approved these changes

2021-04-21 20:32 UTC, opbld30 commented
Docs Build status updates of commit _[dde9fa3](https://github.com/MaratMussabekov/windows-powershell-docs/commits/dde9fa37a0f761b4b9896869763347895ac765a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012-ps&branch=pr-en-us-2409) (winserver2012-ps) |
[docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2012r2-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=winserver2012r2-ps&branch=pr-en-us-2409) (winserver2012r2-ps) |
[docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2016-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2016-ps&branch=pr-en-us-2409) (WindowsServer2016-ps) |
[docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2019-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2019-ps&branch=pr-en-us-2409) (WindowsServer2019-ps) |
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |
[docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md](https://github.com/MaratMussabekov/windows-powershell-docs/blob/patch-22/docset/winserver2022-ps/netsecurity/Set-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/netsecurity/set-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-2409) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C21%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104212026141329-2409%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C6OZpOqW4BrmWejEnko%2FX0FFVoOcdWiwTW5iYrGSK2Q%3D&st=2021-04-21T20%3A27%3A36Z&se=2021-05-22T20%3A32%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-21 20:39 UTC, merged