Resolves #2340
MicrosoftDocs/windows-powershell-docs pull request #2419
Opened 2021-04-15 18:42 UTC by velkovb

Add missing parameter
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2340

2021-04-15 18:49 UTC, opbld32 commented
Docs Build status updates of commit _[33efc0f](https://github.com/velkovb/windows-powershell-docs/commits/33efc0f4dbed98e6cd2bb1ea7559d38527cf4497)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2016-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2016-ps&branch=pr-en-us-2419) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2019-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2019-ps&branch=pr-en-us-2419) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2022-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2022-ps&branch=pr-en-us-2419) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104151842518649-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4hQQY5VUXefZv6Af%2FIeMSja02EO9BfwHTXuxGInx1sM%3D&st=2021-04-15T18%3A44%3A08Z&se=2021-05-16T18%3A49%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 02:32 UTC, JohanFreelancer9 approved these changes

2021-04-16 12:23 UTC, get-itips requested changes
Please also add the parameter to the parameters section

2021-04-16 14:06 UTC, opbld32 commented
Docs Build status updates of commit _[2e13426](https://github.com/velkovb/windows-powershell-docs/commits/2e13426e0cccae373c033236b01b824403661e0c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2016-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2016-ps&branch=pr-en-us-2419) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2019-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2019-ps&branch=pr-en-us-2419) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2022-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2022-ps&branch=pr-en-us-2419) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104161359453421-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PA5MPUE5bg%2BxaxQOutpr9jr%2BI5FuOd%2FPAy3L3E9o2lI%3D&st=2021-04-16T14%3A01%3A11Z&se=2021-05-17T14%3A06%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 14:12 UTC, opbld31 commented
Docs Build status updates of commit _[9d8fa86](https://github.com/velkovb/windows-powershell-docs/commits/9d8fa861433e6630f12410d3dba2c965518d0d02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2016-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2016-ps&branch=pr-en-us-2419) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2019-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2019-ps&branch=pr-en-us-2419) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2022-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2022-ps&branch=pr-en-us-2419) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104161401447571-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cG33OXWegR01wSoqKX2UpOXcmGtv09pZEKpAUYpgHL8%3D&st=2021-04-16T14%3A07%3A38Z&se=2021-05-17T14%3A12%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 14:14 UTC, get-itips approved these changes

2021-04-16 18:57 UTC, tseward approved these changes

2021-04-17 09:28 UTC, dariomws approved these changes

2021-04-17 09:28 UTC, dariomws commented on docset/winserver2016-ps/adfs/Set-AdfsProperties.md
> +Specifies Extranet Smart Lockout mode
```suggestion
Specifies Extranet Smart Lockout mode.
```

2021-04-17 09:28 UTC, dariomws commented on docset/winserver2019-ps/adfs/Set-AdfsProperties.md
> +Specifies Extranet Smart Lockout mode
```suggestion
Specifies Extranet Smart Lockout mode.
```

2021-04-17 09:28 UTC, dariomws commented on docset/winserver2022-ps/adfs/Set-AdfsProperties.md
> +Specifies Extranet Smart Lockout mode
```suggestion
Specifies Extranet Smart Lockout mode.
```

2021-04-17 12:41 UTC, opbld33 commented
Docs Build status updates of commit _[17fa055](https://github.com/velkovb/windows-powershell-docs/commits/17fa055a3df7c36ab6ee88e4766fb440718f7232)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2016-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2016-ps&branch=pr-en-us-2419) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2019-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2019-ps&branch=pr-en-us-2419) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2022-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2022-ps&branch=pr-en-us-2419) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104171235217967-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2sbvXaq2RBxm1j1TzgxqWJGTSl9zUc5%2BgSSfzs6RR34%3D&st=2021-04-17T12%3A36%3A44Z&se=2021-05-18T12%3A41%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 17:01 UTC, opbld30 commented
Docs Build status updates of commit _[28ab8de](https://github.com/velkovb/windows-powershell-docs/commits/28ab8de875965fddc73921903bcfcfa2a3923f6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2016-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2016-ps&branch=pr-en-us-2419) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2019-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2019-ps&branch=pr-en-us-2419) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsProperties.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2340-missing-parameter/docset/winserver2022-ps/adfs/Set-AdfsProperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsproperties?view=windowsserver2022-ps&branch=pr-en-us-2419) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104191655261931-2419%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LqMEo%2B66F7CnWNPBS81jsxu3mn4V9MsQZqCuQoUEq6Q%3D&st=2021-04-19T16%3A56%3A48Z&se=2021-05-20T17%3A01%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 17:02 UTC, merged