Resolves #2364
MicrosoftDocs/windows-powershell-docs pull request #2424
Opened 2021-04-16 18:34 UTC by velkovb

Fix parameter description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2364

2021-04-16 18:41 UTC, opbld32 commented
Docs Build status updates of commit _[38bf792](https://github.com/velkovb/windows-powershell-docs/commits/38bf792ef141474dc31010cfa20bcf2412efad4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2012-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=winserver2012-ps&branch=pr-en-us-2424) (winserver2012-ps) |
[docset/winserver2012r2-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2012r2-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=winserver2012r2-ps&branch=pr-en-us-2424) (winserver2012r2-ps) |
[docset/winserver2016-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2016-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2016-ps&branch=pr-en-us-2424) (WindowsServer2016-ps) |
[docset/winserver2019-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2019-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2019-ps&branch=pr-en-us-2424) (WindowsServer2019-ps) |
[docset/winserver2022-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2022-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2022-ps&branch=pr-en-us-2424) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104161834349271-2424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pw8X0uanMFhYFwlZrFCHyNDEY0hhnG4cC%2FYBYr77mDM%3D&st=2021-04-16T18%3A36%3A09Z&se=2021-05-17T18%3A41%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 23:41 UTC, get-itips approved these changes

2021-04-17 08:52 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/pki/Export-Certificate.md
> +Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute is set.
```suggestion
Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute set.
```

2021-04-17 08:53 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/pki/Export-Certificate.md
> +Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute is set.
```suggestion
Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute set.
```

2021-04-17 08:53 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/pki/Export-Certificate.md
> +Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute is set.
```suggestion
Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute set.
```

2021-04-17 08:54 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/pki/Export-Certificate.md
> +Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute is set.
```suggestion
Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute set.
```

2021-04-17 08:54 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/pki/Export-Certificate.md
> +Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute is set.
```suggestion
Specifies that the exported certificate file will overwrite an existing certificate file, even if it has the Read-only attribute set.
```

2021-04-17 08:55 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-17 09:45 UTC, dariomws approved these changes

2021-04-17 12:45 UTC, opbld33 commented
Docs Build status updates of commit _[f311e31](https://github.com/velkovb/windows-powershell-docs/commits/f311e31efb5ec7764f0a9b681c2517f577212b23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2012-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=winserver2012-ps&branch=pr-en-us-2424) (winserver2012-ps) |
[docset/winserver2012r2-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2012r2-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=winserver2012r2-ps&branch=pr-en-us-2424) (winserver2012r2-ps) |
[docset/winserver2016-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2016-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2016-ps&branch=pr-en-us-2424) (WindowsServer2016-ps) |
[docset/winserver2019-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2019-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2019-ps&branch=pr-en-us-2424) (WindowsServer2019-ps) |
[docset/winserver2022-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2022-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2022-ps&branch=pr-en-us-2424) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104171239211391-2424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XpAoYZgi0wQizpfJjuh3kMFmWc5WGxSJqr1nyaVM4aM%3D&st=2021-04-17T12%3A40%3A42Z&se=2021-05-18T12%3A45%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 12:51 UTC, opbld31 commented
Docs Build status updates of commit _[f311e31](https://github.com/velkovb/windows-powershell-docs/commits/f311e31efb5ec7764f0a9b681c2517f577212b23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2012-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=winserver2012-ps&branch=pr-en-us-2424) (winserver2012-ps) |
[docset/winserver2012r2-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2012r2-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=winserver2012r2-ps&branch=pr-en-us-2424) (winserver2012r2-ps) |
[docset/winserver2016-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2016-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2016-ps&branch=pr-en-us-2424) (WindowsServer2016-ps) |
[docset/winserver2019-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2019-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2019-ps&branch=pr-en-us-2424) (WindowsServer2019-ps) |
[docset/winserver2022-ps/pki/Export-Certificate.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2364-parameter-descriptio/docset/winserver2022-ps/pki/Export-Certificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/pki/export-certificate?view=windowsserver2022-ps&branch=pr-en-us-2424) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202104171239313502-2424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rN2SZKqx5uE9i1fl80JvMUn2JHT9%2B5EjWBEUFuWBYCo%3D&st=2021-04-17T12%3A46%3A40Z&se=2021-05-18T12%3A51%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 13:27 UTC, JohanFreelancer9 approved these changes

2021-04-17 14:45 UTC, tseward approved these changes

2021-04-19 15:06 UTC, merged