Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #2487
Opened 2021-06-07 16:43 UTC by marysiakam9889

Adding new update control commands for SDP scenario

2021-06-07 16:50 UTC, opbld33 commented
Docs Build status updates of commit _[bbe9456](https://github.com/marysiakam9889/windows-powershell-docs/commits/bbe9456bff013f6e036be07a5c27aa768bb452ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/marysiakam9889/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-2487) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106071643391727-2487%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QmmvkWfbpvP6oLNupYJuHwHDqUVl6gd9JWiotIAwrWY%3D&st=2021-06-07T16%3A45%3A34Z&se=2021-07-08T16%3A50%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 21:15 UTC, pahuijbr approved these changes
Please approve this PR, marysiakam9889 is also MSFT internal.

2021-06-08 07:19 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Current Channel (Staged): Devices will be offered updates after the release cycle. Suggested to apply to a small, representative part of production population (~10%)
```suggestion
Current Channel (Staged): Devices will be offered updates after the release cycle. Suggested to apply to a small, representative part of production population (~10%).
```

2021-06-08 07:22 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Note: This setting applies to both monthly as well as daily Defender updates and will override any previously configured channel selections for platform and engine updates.
```suggestion
> [!NOTE]
> This setting applies to both monthly as well as daily Defender updates and will override any previously configured channel selections for platform and engine updates. 
```

2021-06-08 07:23 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +
```suggestion
```

2021-06-08 07:27 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +
```suggestion
```

2021-06-08 07:28 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +
```suggestion
```

2021-06-08 07:29 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +
```suggestion
```

2021-06-08 07:31 UTC, JohanFreelancer9 requested changes
Copy review - @marysiakam9889, please commit the few minor suggested changes. Many thanks.

2021-06-08 15:45 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Aliases:
```suggestion
Aliases:

```

2021-06-08 15:45 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Aliases:
```suggestion
Aliases:

```

2021-06-08 15:46 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +
```suggestion
Aliases:

Accepted values:Beta|Preview|Staged|Broad|NotConfigured 
```

2021-06-08 15:47 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Aliases:
```suggestion
Aliases:

```

2021-06-08 19:02 UTC, opbld31 commented
Docs Build status updates of commit _[54db164](https://github.com/marysiakam9889/windows-powershell-docs/commits/54db16408829b910de9bcdf25b2bf1e3799f1e52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/marysiakam9889/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-2487) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106081855215029-2487%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qwl5hkktFg5EurEv77wr2fjtYJ9NZxOMeXmzjmO3hjU%3D&st=2021-06-08T18%3A57%3A01Z&se=2021-07-09T19%3A02%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 19:15 UTC, opbld30 commented
Docs Build status updates of commit _[463e1ef](https://github.com/marysiakam9889/windows-powershell-docs/commits/463e1efe3c9a59107ad7e364eba5858017a97c39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/marysiakam9889/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-2487) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106081855427598-2487%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FaZrw0%2Fm8eqVGkXf95au15ZlMfXO2SFevt9SvWyYUBI%3D&st=2021-06-08T19%3A10%3A23Z&se=2021-07-09T19%3A15%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 19:21 UTC, merged

2021-06-08 19:22 UTC, opbld30 commented
Docs Build status updates of commit _[7c4b50a](https://github.com/marysiakam9889/windows-powershell-docs/commits/7c4b50a357e8bf241bf3fabcbbfcb4686cee45d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/marysiakam9889/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-2487) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106081855270510-2487%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SdYKafLPpwKBMLjQ9rYSo3iAEv9oG5wUOhoFGVZ5E0A%3D&st=2021-06-08T19%3A17%3A10Z&se=2021-07-09T19%3A22%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>