Resolves #2448
MicrosoftDocs/windows-powershell-docs pull request #2493
Opened 2021-06-08 18:42 UTC by velkovb

Add description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2448

2021-06-08 18:48 UTC, opbld33 commented
Docs Build status updates of commit _[0488848](https://github.com/velkovb/windows-powershell-docs/commits/0488848e3a7ad5c4b5e79d8a4e2a49433d948a79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2016-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2016-ps&branch=pr-en-us-2493) (WindowsServer2016-ps) |
[docset/winserver2019-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2019-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2019-ps&branch=pr-en-us-2493) (WindowsServer2019-ps) |
[docset/winserver2022-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2022-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2022-ps&branch=pr-en-us-2493) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106081842071605-2493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZDdYuzmzULwjpW0hvga%2FlbPGOFh%2FF8qiGauTuIU%2FPZI%3D&st=2021-06-08T18%3A43%3A52Z&se=2021-07-09T18%3A48%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 08:05 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +This reference cmdlet descriptions and syntax for all Provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```suggestion
This reference cmdlet provides descriptions and syntax for all Provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```

2021-06-09 08:09 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +List all installed trusted provisioning certificates; use this cmdlet to get the certificate thumbprint to use with the Uninstall-TrustedProvisioningCertificate cmdlet
```suggestion
List all installed trusted provisioning certificates; use this cmdlet to get the certificate thumbprint to use with the Uninstall-TrustedProvisioningCertificate cmdlet.
```

2021-06-09 08:12 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Adds a certificate to the Trusted Certificate store
```suggestion
Add a certificate to the Trusted Certificate Store.
```

2021-06-09 08:12 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Remove a previously installed provisioning certificate
```suggestion
Remove a previously installed provisioning certificate.
```

2021-06-09 08:12 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +This reference cmdlet descriptions and syntax for all Provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```suggestion
This reference cmdlet provides descriptions and syntax for all provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```

2021-06-09 08:14 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Extract the contents of a provisioning package.
```suggestion
Extracts the contents of a provisioning package.
```

2021-06-09 08:14 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Export trace events.
```suggestion
Exports trace events.
```

2021-06-09 08:15 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Install .PPKG package onto the local machine.
```suggestion
Installs .PPKG package onto the local machine.
```

2021-06-09 08:16 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Uninstall .PPKG package from the local machine.
```suggestion
Uninstalls .PPKG package from the local machine.
```

2021-06-09 08:17 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +Extract the contents of a provisioning package.
```suggestion
Extracts the contents of a provisioning package.
```

2021-06-09 08:18 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +List all installed trusted provisioning certificates; use this cmdlet to get the certificate thumbprint to use with the Uninstall-TrustedProvisioningCertificate cmdlet
```suggestion
Lists all installed trusted provisioning certificates; use this cmdlet to get the certificate thumbprint to use with the Uninstall-TrustedProvisioningCertificate cmdlet.
```

2021-06-09 08:18 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +Install .PPKG package onto the local machine.
```suggestion
Installs .PPKG package onto the local machine.
```

2021-06-09 08:19 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +Adds a certificate to the Trusted Certificate store
```suggestion
Adds a certificate to the Trusted Certificate Store.
```

2021-06-09 08:19 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +Uninstall .PPKG package from the local machine.
```suggestion
Uninstalls .PPKG package from the local machine.
```

2021-06-09 08:19 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/provisioning/Provisioning.md
> +Remove a previously installed provisioning certificate
```suggestion
Removes a previously installed provisioning certificate
```

2021-06-09 08:20 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +This reference cmdlet descriptions and syntax for all Provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```suggestion
This reference cmdlet provides descriptions and syntax for all provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```

2021-06-09 08:20 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +Extract the contents of a provisioning package.
```suggestion
Extracts the contents of a provisioning package.
```

2021-06-09 08:21 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +Export trace events.
```suggestion
Exports trace events.
```

2021-06-09 08:21 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +List all installed trusted provisioning certificates; use this cmdlet to get the certificate thumbprint to use with the Uninstall-TrustedProvisioningCertificate cmdlet
```suggestion
Lists all installed trusted provisioning certificates; use this cmdlet to get the certificate thumbprint to use with the Uninstall-TrustedProvisioningCertificate cmdlet.
```

2021-06-09 08:21 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +Install .PPKG package onto the local machine.
```suggestion
Installs .PPKG package onto the local machine.
```

2021-06-09 08:22 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +Adds a certificate to the Trusted Certificate store
```suggestion
Adds a certificate to the Trusted Certificate Store.
```

2021-06-09 08:22 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +Uninstall .PPKG package from the local machine.
```suggestion
Uninstalls .PPKG package from the local machine.
```

2021-06-09 08:22 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/provisioning/Provisioning.md
> +Remove a previously installed provisioning certificate
```suggestion
Removes a previously-installed provisioning certificate
```

2021-06-09 08:27 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-09 09:43 UTC, opbld32 commented
Docs Build status updates of commit _[776ca4f](https://github.com/velkovb/windows-powershell-docs/commits/776ca4f66bf47c7f9ca16758bc291b43925ef30d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2016-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2016-ps&branch=pr-en-us-2493) (WindowsServer2016-ps) |
[docset/winserver2019-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2019-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2019-ps&branch=pr-en-us-2493) (WindowsServer2019-ps) |
[docset/winserver2022-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2022-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2022-ps&branch=pr-en-us-2493) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106090937350769-2493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D1nudPtY8qMbKF10Gsp0oUR799X7Serye2Y8Q3z1bJQ%3D&st=2021-06-09T09%3A38%3A50Z&se=2021-07-10T09%3A43%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 10:46 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +Removes a previously-installed provisioning certificate.
```suggestion
Removes a previously installed provisioning certificate.
```

2021-06-09 10:47 UTC, JohanFreelancer9 requested changes
Apologies @velkovb, my bad. One more, please.

2021-06-10 21:18 UTC, dariomws reviewed
We can remove the word cmdlet here.

2021-06-10 21:18 UTC, dariomws commented on docset/winserver2016-ps/provisioning/Provisioning.md
> +This reference cmdlet provides descriptions and syntax for all provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```suggestion
This reference provides descriptions and syntax for all provisioning-specific cmdlets. It lists cmdlets in alphabetical order based on the verb at the beginning of the cmdlet.
```

2021-06-11 06:34 UTC, opbld33 commented
Docs Build status updates of commit _[efe58b8](https://github.com/velkovb/windows-powershell-docs/commits/efe58b8fce569c1ae9f2fb51b8da6fadc937e5f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2016-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2016-ps&branch=pr-en-us-2493) (WindowsServer2016-ps) |
[docset/winserver2019-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2019-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2019-ps&branch=pr-en-us-2493) (WindowsServer2019-ps) |
[docset/winserver2022-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2022-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2022-ps&branch=pr-en-us-2493) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106110627204081-2493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hxuxNMHvR4BWrnzIJtcRiFYZOMyWjZJCtXrgN483LgE%3D&st=2021-06-11T06%3A29%3A50Z&se=2021-07-12T06%3A34%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 07:04 UTC, dariomws approved these changes

2021-06-11 07:31 UTC, JohanFreelancer9 approved these changes

2021-06-11 21:09 UTC, tseward approved these changes

2021-06-17 14:39 UTC, get-itips approved these changes

2021-06-28 15:58 UTC, opbld31 commented
Docs Build status updates of commit _[a8e6cae](https://github.com/velkovb/windows-powershell-docs/commits/a8e6caea7a2049414de13c6a833f2c11c5e8d651)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2016-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2016-ps&branch=pr-en-us-2493) (WindowsServer2016-ps) |
[docset/winserver2019-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2019-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2019-ps&branch=pr-en-us-2493) (WindowsServer2019-ps) |
[docset/winserver2022-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2022-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2022-ps&branch=pr-en-us-2493) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C28%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106281551468994-2493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=71z1EtePqi%2F%2FZtqMhkrW5vELWYW%2B6795xrWAOQrLFfg%3D&st=2021-06-28T15%3A53%3A05Z&se=2021-07-29T15%3A58%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 16:10 UTC, v-dihans commented
Hi @velkovb 

**Following are blocking issues that need to be resolved before we can merge:**

All Articles in the PR
- Fix the syntax. Some of the changes result in {{Fill in the Synopsis}} displaying on staging. 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)

**Blocking**
- The content preview must be clean on staging. It cannot contain any obvious formatting issues.

***

Thanks

2021-06-28 16:17 UTC, velkovb commented
@v-dihans @e0i I don't think I understand what the issues is. This PR actually removes all of the {{Fill in the Synopsis}} occurrences. 

Where I can see those syntax errors?

2021-06-28 16:19 UTC, v-dihans commented
@velkovb   

You can see staging for each file by clicking on "view" in the Validation report in the PR. 

Thanks

2021-06-28 16:38 UTC, velkovb commented
@v-dihans I don't have access to open those.

2021-06-28 16:49 UTC, v-dihans commented
@velkovb  

I'll try to help. I'll leave a comment with a screenshot of the staged content for each file.

docset/winserver2016-ps/provisioning/Provisioning.md
[
![image](https://user-images.githubusercontent.com/61994212/123674119-7b959e00-d7fe-11eb-9916-9c51b21f5749.png)
](url)

2021-06-28 16:50 UTC, v-dihans commented
docset/winserver2019-ps/provisioning/Provisioning.md

[
![image](https://user-images.githubusercontent.com/61994212/123674245-a122a780-d7fe-11eb-9ea0-0085aae65ca8.png)
](url)

2021-06-28 16:51 UTC, v-dihans commented
docset/winserver2022-ps/provisioning/Provisioning.md

![image](https://user-images.githubusercontent.com/61994212/123674342-be577600-d7fe-11eb-8965-aee27ad9d9c2.png)

2021-06-28 16:55 UTC, opbld31 commented
Docs Build status updates of commit _[3b8d9b0](https://github.com/velkovb/windows-powershell-docs/commits/3b8d9b03f53106d486f19541556e429883617717)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2016-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2016-ps&branch=pr-en-us-2493) (WindowsServer2016-ps) |
[docset/winserver2019-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2019-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2019-ps&branch=pr-en-us-2493) (WindowsServer2019-ps) |
[docset/winserver2022-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2022-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2022-ps&branch=pr-en-us-2493) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C28%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106281645575791-2493%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DVJ2f%2BqAz5m8AMGDo7%2FzcCPLEgYapHrIMbPGOSa%2BqHU%3D&st=2021-06-28T16%3A50%3A53Z&se=2021-07-29T16%3A55%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-28 17:07 UTC, velkovb commented
That doesn't seem right. This PR is fixing exactly those issues. Not sure why it is not picking up the change properly.

2021-06-28 17:12 UTC, velkovb commented
I guess this is automatically picking up the Synopsis inside the actual cmdlet articles.

2021-07-09 11:37 UTC, e0i commented
@sdwheeler It seems that the synopsis fields that we have provided manually are overridden by the build system with the `{{Fill in the Synopsis}}` fields. Can you take a look as the time permits? Thank you.

2021-07-29 13:08 UTC, sdwheeler commented
@velkovb @e0i The cmdlets files are missing the Synopsis information. Those need to be updated as well.

2021-07-29 13:12 UTC, sdwheeler commented
All of these files need to be updated. All of them are missing Synopsis and other descriptions.

- Export-Trace.md
- Get-TrustedProvisioningCertificate.md
- Install-TrustedProvisioningCertificate.md
- Uninstall-ProvisioningPackage.md
- Uninstall-TrustedProvisioningCertificate.md
-

2021-12-08 08:13 UTC, opbld30 commented
Docs Build status updates of commit _[b170ced](https://github.com/velkovb/windows-powershell-docs/commits/b170cedb9cc0e09ddbba62b406ef3ecfd35abb45)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-09 08:17 UTC, opbld31 commented
Docs Build status updates of commit _[80f1b46](https://github.com/velkovb/windows-powershell-docs/commits/80f1b46e40a48c8638bb842cfdbe1d341faeb464)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2016-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2016-ps&branch=pr-en-us-2493) (WindowsServer2016-ps) |
[docset/winserver2019-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2019-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2019-ps&branch=pr-en-us-2493) (WindowsServer2019-ps) |
[docset/winserver2022-ps/provisioning/Provisioning.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2448-missing-description/docset/winserver2022-ps/provisioning/Provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/provisioning/index?view=windowsserver2022-ps&branch=pr-en-us-2493) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C9%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201090810122755-2493%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-09T08%3A17%3A11Z&sr=b&sp=r&sig=OdWall3XDOyx3Zm%2B0OX8AAhEVSA1rHpgCdfhTk83xe4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 14:07 UTC, e0i commented
@tiburd This PR is finally green and can be merged. Thanks.

2022-01-10 18:36 UTC, merged