Added the location of the export zone file
MicrosoftDocs/windows-powershell-docs pull request #2508
Opened 2021-06-14 11:26 UTC by BWMerlin

Added the location to where the export zone file can be found (C:\Windows\System32\DNS) and that the location is on the DNS server.  Also added a note that -FileName is a filename and not a filepath.  This should clarify how users can use this command and where they can locate the output.

2021-06-14 11:33 UTC, opbld32 commented
Docs Build status updates of commit _[bf90148](https://github.com/BWMerlin/windows-powershell-docs/commits/bf901483333158c8a366fb0e245bf623e787726e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md](https://github.com/BWMerlin/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=windowsserver2019-ps&branch=pr-en-us-2508) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106141126235488-2508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A%2ByX0QmrNTj3Wt073Jiewq2E6%2B1rfN7iul9wUay%2BQgY%3D&st=2021-06-14T11%3A28%3A08Z&se=2021-07-15T11%3A33%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 05:51 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md
> +This command exports the zone named western.contoso.com to a file called exportedcontoso.com located in C:\Windows\System32\DNS on the DNS server.  Note that -FileName is a filename not a filepath.
```suggestion
This command exports the zone named western.contoso.com to a file called exportedcontoso.com located in C:\Windows\System32\DNS on the DNS server. Note that -FileName is a filename, not a file path.
```

2021-06-15 05:52 UTC, JohanFreelancer9 requested changes
Copy review - @BWMerlin, please commit my minor suggested changes. Many thanks.

2021-06-15 09:34 UTC, opbld30 commented
Docs Build status updates of commit _[6086632](https://github.com/BWMerlin/windows-powershell-docs/commits/6086632b1f1393c9e94eb6c50f60b6257c8bb76f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md](https://github.com/BWMerlin/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=windowsserver2019-ps&branch=pr-en-us-2508) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106150928111044-2508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RbWlIq%2Fsb%2FaLlMJpajp32C6pZg%2FWDfqTGS86PWY6E%2F8%3D&st=2021-06-15T09%3A29%3A35Z&se=2021-07-16T09%3A34%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 15:39 UTC, JohanFreelancer9 approved these changes

2021-06-28 11:57 UTC, dariomws approved these changes
I think the same update must be applied to all Windows versions (from 2012 to 2022).

2021-06-28 13:11 UTC, get-itips requested changes
Tested this, ok, can you please also correct the description for `FileName` parameter? Thank you!

2021-06-30 09:18 UTC, tseward approved these changes

2021-07-18 09:28 UTC, BWMerlin commented
> 
> 
> Tested this, ok, can you please also correct the description for `FileName` parameter? Thank you!

I *think* I have made the requested change to -FileName.  Please review.

2021-07-18 09:33 UTC, opbld32 commented
Docs Build status updates of commit _[bec3639](https://github.com/BWMerlin/windows-powershell-docs/commits/bec3639a0ad7eb5a482f6f4c01642672c7b6dd9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md](https://github.com/BWMerlin/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=windowsserver2019-ps&branch=pr-en-us-2508) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C18%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202107180927123523-2508%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A21%3A32Z&ske=2021-07-23T08%3A26%3A32Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-18T09%3A28%3A40Z&se=2021-08-18T09%3A33%3A40Z&sr=b&sp=r&sig=4DuRerQd%2FtgKRJqzh6RIzbS1uiv5G5jrMPB0np1%2Fz5M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 12:19 UTC, get-itips approved these changes

2021-07-19 15:29 UTC, opbld30 commented
Docs Build status updates of commit _[2c42ae9](https://github.com/BWMerlin/windows-powershell-docs/commits/2c42ae93fbb5b01713cb6d99c20c284f53a767e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md](https://github.com/BWMerlin/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dnsserver/Export-DnsServerZone.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/export-dnsserverzone?view=windowsserver2019-ps&branch=pr-en-us-2508) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202107191523512474-2508%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A41%3A46Z&ske=2021-07-26T02%3A46%3A46Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T15%3A24%3A58Z&se=2021-08-19T15%3A29%3A58Z&sr=b&sp=r&sig=gSYSbie9xwbnsIhjzwLVCNH0GwwqpeJsCzpBbrvg%2BBg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 15:31 UTC, merged