Resolves #2423
MicrosoftDocs/windows-powershell-docs pull request #2520
Opened 2021-06-25 07:26 UTC by velkovb

Add info about character limit in TXT records
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2423

2021-06-25 07:33 UTC, opbld32 commented
Docs Build status updates of commit _[8466fb3](https://github.com/velkovb/windows-powershell-docs/commits/8466fb3fd157bbccbf3d811339b1c732f00ed41d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012-ps&branch=pr-en-us-2520) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012r2-ps&branch=pr-en-us-2520) (winserver2012r2-ps) |
[docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2016-ps&branch=pr-en-us-2520) (WindowsServer2016-ps) |
[docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2019-ps&branch=pr-en-us-2520) (WindowsServer2019-ps) |
[docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2022-ps&branch=pr-en-us-2520) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106250727003679-2520%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qsg3ffB7EHJ0XsXTGbGp6UashVbkCOcYMQqTxW3g4Xk%3D&st=2021-06-25T07%3A28%3A25Z&se=2021-07-26T07%3A33%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-25 11:37 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md
> +### Example 8: Add multiline TXT resource record
```suggestion
### Example 8: Add a multiline TXT resource record
```

2021-06-25 11:41 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md
> +This command adds a mutliline TXT resource record. String is split in 252 characters sets and then new line is added in the end which is 2 characters in Windows.
```suggestion
This command adds a multiline TXT resource record. The string is split into 252 character sets and the new line, which is two characters in Windows, is added at the end.
```

2021-06-25 11:43 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md
> +### Example 8: Add multiline TXT resource record
```suggestion
### Example 8: Add a multiline TXT resource record
```

2021-06-25 11:43 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md
> +This command adds a mutliline TXT resource record. String is split in 252 characters sets and then new line is added in the end which is 2 characters in Windows.
```suggestion
This command adds a multiline TXT resource record. The string is split into 252 character sets and the new line, which is two characters in Windows, is added at the end.
```

2021-06-25 11:44 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md
> +### Example 8: Add multiline TXT resource record
```suggestion
### Example 8: Add a multiline TXT resource record
```

2021-06-25 11:45 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md
> +This command adds a mutliline TXT resource record. String is split in 252 characters sets and then new line is added in the end which is 2 characters in Windows.
```suggestion
This command adds a multiline TXT resource record. The string is split into 252 character sets and the new line, which is two characters in Windows, is added at the end.
```

2021-06-25 11:46 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md
> +
```suggestion
```

2021-06-25 11:46 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md
> +
```suggestion
```

2021-06-25 11:47 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md
> +
```suggestion
```

2021-06-25 11:48 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md
> +
```suggestion
```

2021-06-25 11:50 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md
> +### Example 8: Add multiline TXT resource record
```suggestion
### Example 8: Add a multiline TXT resource record
```

2021-06-25 11:51 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md
> +
```suggestion
```

2021-06-25 11:53 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md
> +This command adds a mutliline TXT resource record. String is split in 252 characters sets and then new line is added in the end which is 2 characters in Windows.
```suggestion
This command adds a multiline TXT resource record. The string is split into 252 character sets and the new line, which is two characters in Windows, is added at the end.
```

2021-06-25 11:54 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md
> +### Example 8: Add multiline TXT resource record
```suggestion
### Example 8: Add a multiline TXT resource record
```

2021-06-25 11:57 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md
> +
```suggestion
```

2021-06-25 11:58 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md
> +This command adds a mutliline TXT resource record. String is split in 252 characters sets and then new line is added in the end which is 2 characters in Windows.
```suggestion
This command adds a multiline TXT resource record. The string is split into 252 character sets and the new line, which is two characters in Windows, is added at the end.
```

2021-06-25 12:00 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-25 14:07 UTC, opbld31 commented
Docs Build status updates of commit _[bbe1112](https://github.com/velkovb/windows-powershell-docs/commits/bbe1112044360b7a5a325c7dab282aa519aa4fc0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012-ps&branch=pr-en-us-2520) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012r2-ps&branch=pr-en-us-2520) (winserver2012r2-ps) |
[docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2016-ps&branch=pr-en-us-2520) (WindowsServer2016-ps) |
[docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2019-ps&branch=pr-en-us-2520) (WindowsServer2019-ps) |
[docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2022-ps&branch=pr-en-us-2520) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C25%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202106251400213389-2520%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4akxuni5PNiBojVh8u5wB3bPl%2FlgPGd6FD7dP1qmXcI%3D&st=2021-06-25T14%3A02%3A08Z&se=2021-07-26T14%3A07%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-26 06:25 UTC, JohanFreelancer9 approved these changes

2021-06-28 12:01 UTC, dariomws approved these changes

2021-06-28 12:47 UTC, get-itips approved these changes

2021-06-30 09:19 UTC, tseward approved these changes

2021-07-19 15:28 UTC, opbld32 commented
Docs Build status updates of commit _[1ca2021](https://github.com/velkovb/windows-powershell-docs/commits/1ca2021da01cd79300f7257f87da16a13bceec5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012-ps&branch=pr-en-us-2520) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012r2-ps&branch=pr-en-us-2520) (winserver2012r2-ps) |
[docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2016-ps&branch=pr-en-us-2520) (WindowsServer2016-ps) |
[docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2019-ps&branch=pr-en-us-2520) (WindowsServer2019-ps) |
[docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2022-ps&branch=pr-en-us-2520) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202107191522356812-2520%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A56%3A27Z&ske=2021-07-26T03%3A01%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T15%3A23%3A58Z&se=2021-08-19T15%3A28%3A58Z&sr=b&sp=r&sig=bEuEx0wUCi2sx0onhHNlq3FKczSycPJyzofC7syintA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 15:39 UTC, opbld30 commented
Docs Build status updates of commit _[bbaab96](https://github.com/velkovb/windows-powershell-docs/commits/bbaab96714807aa99be20fbd0e8dcbea6af6986b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012-ps&branch=pr-en-us-2520) (winserver2012-ps) |
[docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=winserver2012r2-ps&branch=pr-en-us-2520) (winserver2012r2-ps) |
[docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2016-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2016-ps&branch=pr-en-us-2520) (WindowsServer2016-ps) |
[docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2019-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2019-ps&branch=pr-en-us-2520) (WindowsServer2019-ps) |
[docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2423-missing-info/docset/winserver2022-ps/dnsserver/Add-DnsServerResourceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverresourcerecord?view=windowsserver2022-ps&branch=pr-en-us-2520) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202107191532056929-2520%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-19T02%3A28%3A27Z&ske=2021-07-26T02%3A33%3A27Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-19T15%3A34%3A07Z&se=2021-08-19T15%3A39%3A07Z&sr=b&sp=r&sig=XL0eVcah6lZ4%2Brphhe0DtjhIJoG1i75S5%2FBqp0G7S6E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-19 16:25 UTC, v-dihans commented
Hi @velkovb  

Merging with non-blocking feedback.

&nbsp;
**Following are non-blocking issues that should be resolved now or within three business days in another PR:**

docset/winserver2012-ps/dnsserver/Add-DnsServerResourceRecord.md
- Line 168: Fix the link. Markdown shows on staging. Also change the "http" to "https" and remove the "en-us" from the link.
I noticed that the link actually redirects to another url. You might want to update the link.

docset/winserver2012r2-ps/dnsserver/Add-DnsServerResourceRecord.md
- Line 170: Fix the link. Markdown shows on staging. Also change the "http" to "https" and remove the "en-us" from the link.
I noticed that the link actually redirects to another url. You might want to update the link.

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)

- The content preview must be clean on staging. It cannot contain any obvious formatting issues.
- With rare exceptions, all instances of "http" are changed to "https" in Microsoft links. 
- Links to pages on docs.microsoft.com sites are coded as locale agnostic, meaning that the URL does not include a locale, such as en-us, en-gb, en-in, or any other locale.

***

Also noticed several existing links in the articles that need to have the "http" changed to "https" and the "en-us" removed. 
Those could be fixed or updated as well.

Thanks

2021-07-19 16:25 UTC, merged