Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #2560
Opened 2021-07-22 10:14 UTC by nivabitbol

This change suggested from customer following a support escelation.
Thanks,
Niv

2021-07-22 10:21 UTC, opbld33 commented
Docs Build status updates of commit _[b4eba12](https://github.com/nivabitbol/windows-powershell-docs/commits/b4eba128f2286d16ed345fbdcb6c79307dc5b668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/nivabitbol/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-2560) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C22%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202107221014540632-2560%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-22T02%3A12%3A16Z&ske=2021-07-29T02%3A17%3A16Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-22T10%3A16%3A50Z&se=2021-08-22T10%3A21%3A50Z&sr=b&sp=r&sig=fBu7Vhi4asPSbAr%2Bd71ejK%2BqeKmwB3YtY9W%2Fd4pOW5g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-23 07:05 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Note: This parameter is specific for Quick and Scheduled scans.
```suggestion
Note: This parameter applies specifically to quick and scheduled scans.
```

2021-07-23 07:06 UTC, JohanFreelancer9 requested changes
Copy review - @nivabitbol, kindly commit the suggested change. Many thanks.

2021-07-29 19:30 UTC, sdwheeler commented
This change needs to be made for all versions, including 2022. Is the statement true for previous versions? If so, you need to update all versions.

2021-08-07 17:41 UTC, e0i commented
@nivabitbol 

Please feel free to reopen the PR by updating all versions as suggested above.

2021-08-07 17:41 UTC, closed without merging