Resolves #2017
MicrosoftDocs/windows-powershell-docs pull request #2574
Opened 2021-08-04 18:46 UTC by velkovb

Add example and incorporate changes from PR 2145.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2017

2021-08-06 04:12 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +This command get all enabled user accounts in AD using an LDAP filter.
```suggestion
This command gets all enabled user accounts in Active Directory using an LDAP filter.
```

2021-08-06 04:15 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions is searched.
```suggestion
When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions are searched.
```

2021-08-06 04:17 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/activedirectory/Get-ADUser.md
> +This command get all enabled user accounts in AD using an LDAP filter.
```suggestion
This command gets all enabled user accounts in Active Directory using an LDAP filter.
```

2021-08-06 04:18 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/activedirectory/Get-ADUser.md
> +When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions is searched.
```suggestion
When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions are searched.
```

2021-08-06 04:19 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/activedirectory/Get-ADUser.md
> +This command get all enabled user accounts in AD using an LDAP filter.
```suggestion
This command gets all enabled user accounts in Active Directory using an LDAP filter.
```

2021-08-06 04:21 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/activedirectory/Get-ADUser.md
> +When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions is searched.
```suggestion
When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions are searched.
```

2021-08-06 04:22 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/activedirectory/Get-ADUser.md
> +This command get all enabled user accounts in AD using an LDAP filter.
```suggestion
This command gets all enabled user accounts in Active Directory using an LDAP filter.
```

2021-08-06 04:24 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/activedirectory/Get-ADUser.md
> +When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions is searched.
```suggestion
When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions are searched.
```

2021-08-06 04:24 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/activedirectory/Get-ADUser.md
> +This command get all enabled user accounts in AD using an LDAP filter.
```suggestion
This command gets all enabled user accounts in Active Directory using an LDAP filter.
```

2021-08-06 04:26 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/activedirectory/Get-ADUser.md
> +When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions is searched.
```suggestion
When the value of the *SearchBase* parameter is set to an empty string and you are connected to a GC port, all partitions are searched.
```

2021-08-06 04:29 UTC, JohanFreelancer9 requested changes
Copy review - @velkovb, kindly commit the suggested changes. Many thanks.

2021-08-06 07:32 UTC, opbld32 commented
Docs Build status updates of commit _[6153b53](https://github.com/velkovb/windows-powershell-docs/commits/6153b53fa4a46cf3807bc95d830d61596eefc3ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2574) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2574) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2574) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2574) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2574) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108060726230536-2574%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zKauIKridJIngftnt%2FCqtn9LZjP%2BA%2B25YrbF5oMZF5Y%3D&st=2021-08-06T07%3A27%3A55Z&se=2021-09-06T07%3A32%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 07:39 UTC, opbld30 commented
Docs Build status updates of commit _[6153b53](https://github.com/velkovb/windows-powershell-docs/commits/6153b53fa4a46cf3807bc95d830d61596eefc3ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2574) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2574) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2574) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2574) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2574) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C6%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108060726333639-2574%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RJdiB3HvkRQMrybKRr9yJlV68OoqSIzxhKTsICsFKdM%3D&st=2021-08-06T07%3A34%3A40Z&se=2021-09-06T07%3A39%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-06 09:39 UTC, JohanFreelancer9 approved these changes

2021-08-07 22:41 UTC, tseward approved these changes

2021-08-09 10:25 UTC, dariomws approved these changes

2021-08-09 14:22 UTC, get-itips approved these changes
@velkovb Borislav, can I kindly ask to return to one specific commit that resolves the issue and all of the other cosmetic changes in another commit? Thank you

2021-08-16 15:17 UTC, opbld30 commented
Docs Build status updates of commit _[9bef546](https://github.com/velkovb/windows-powershell-docs/commits/9bef5467d0d90826c7e08766c66b992dcdd0c310)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2574) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2574) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2574) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2574) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2574) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108161510432035-2574%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zloQzkg5sci5DD9v67wblPdixeuoFtxViyubI2k8joQ%3D&st=2021-08-16T15%3A12%3A47Z&se=2021-09-16T15%3A17%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 15:25 UTC, opbld33 commented
Docs Build status updates of commit _[5f98cfe](https://github.com/velkovb/windows-powershell-docs/commits/5f98cfe02ef7301b761b7f028e5d0ac191d583a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2574) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2574) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2574) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2574) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2574) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108161518475515-2574%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4rWZ41p%2BUpUpnt%2F4Ld2DPuwZ6nIQ4YD9xxIseNc6FGg%3D&st=2021-08-16T15%3A20%3A58Z&se=2021-09-16T15%3A25%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 15:34 UTC, opbld31 commented
Docs Build status updates of commit _[f0faea6](https://github.com/velkovb/windows-powershell-docs/commits/f0faea6066cc79747c973d08fc7ac2390448ccff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2574) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2574) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2574) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2574) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2574) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108161527165631-2574%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=dtQQuyUjSI7kZcNYGLRmZOrz5N3ZLt%2FvQDIOPyW3z5c%3D&st=2021-08-16T15%3A29%3A17Z&se=2021-09-16T15%3A34%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 15:43 UTC, opbld30 commented
Docs Build status updates of commit _[287b372](https://github.com/velkovb/windows-powershell-docs/commits/287b372d8ea55274691f73a562e07c0425333866)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2574) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2574) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2574) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2574) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix/2017-add-example/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2574) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108161535545298-2574%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uPPwA1gLmEhYzZkT2%2F6%2FxW0qhkZS7sgxzYYVFL63QK0%3D&st=2021-08-16T15%3A38%3A17Z&se=2021-09-16T15%3A43%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-16 15:51 UTC, merged