WIP: Windows Server 2022 Update to Bitlocker PowerShell Module
MicrosoftDocs/windows-powershell-docs pull request #2580
Opened 2021-08-10 20:13 UTC by IngridAtMicrosoft

2021-08-10 20:20 UTC, opbld33 commented
Docs Build status updates of commit _[a25cd14](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/a25cd144ce6ed1646910e580807e8cef8821e121)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108102013372505-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ts8cGW4lNaftZqjAVRQNDwIBb0Yi044pR6clbsBZyZE%3D&st=2021-08-10T20%3A15%3A00Z&se=2021-09-10T20%3A20%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-10 20:40 UTC, opbld32 commented
Docs Build status updates of commit _[5cf70a9](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/5cf70a9b2ac5e287e1fd3bee4d3c9612c6e21ad3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C10%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108102034058419-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=5yoBO%2F%2B%2FuQu9frZhy4FahJZVCwKVfTRb1n4SRgSWOB8%3D&st=2021-08-10T20%3A35%3A26Z&se=2021-09-10T20%3A40%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 16:05 UTC, opbld31 commented
Docs Build status updates of commit _[6f3a69b](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/6f3a69b2a6e87a2657ed23cc8064df64a4c97064)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108171558320713-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=PSWAgaCL7KSPXKpPg2jILnZVxf3vvnRFZv2A4IZlCkc%3D&st=2021-08-17T16%3A00%3A18Z&se=2021-09-17T16%3A05%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 18:42 UTC, opbld30 commented
Docs Build status updates of commit _[84d7253](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/84d7253f539700e6c229ca3577378f9d1e4b7f0e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108171836231120-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=KonTc2AGJA8Xw0WtSXtAvurTrwpRuSNMi1173zIC1ag%3D&st=2021-08-17T18%3A37%3A53Z&se=2021-09-17T18%3A42%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-17 18:56 UTC, opbld32 commented
Docs Build status updates of commit _[03fc26d](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/03fc26dbcbbbc8831edbe6730df59c6033fcd367)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108171848592173-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6%2FhWLKlha7ujLWTly4IRD%2F7DzIFapMHFF6Tv1PjvIqs%3D&st=2021-08-17T18%3A51%3A06Z&se=2021-09-17T18%3A56%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-18 17:16 UTC, IngridAtMicrosoft commented
#sign-off

2021-08-20 09:24 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/bitlocker/BitLocker.md
> +Saves a key protectore for a BitLocker volume in AAD.
```suggestion
Saves a key protector for a BitLocker volume in AAD.
```

2021-08-20 09:25 UTC, JohanFreelancer9 requested changes
Copy review - @IngridAtMicrosoft, kindly commit the suggested change to fix the typo. Many thanks.

2021-08-20 17:12 UTC, opbld31 commented
Docs Build status updates of commit _[3d389dc](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/3d389dc2290c2fabae00251e2334b6bfd0a1ea47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108201706129887-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=KxKjUBKc%2F%2FkQCs9Re4aE%2BV%2BcMUfOJ2pXgrPNbU1wzqk%3D&st=2021-08-20T17%3A07%3A32Z&se=2021-09-20T17%3A12%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-21 07:28 UTC, JohanFreelancer9 approved these changes

2021-08-23 17:22 UTC, IngridAtMicrosoft commented
@traya1  This is ready to be merged. Thanks!

Ingrid

2021-09-08 10:08 UTC, dariomws requested changes
Minor suggestions.

2021-09-08 10:08 UTC, dariomws commented on docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md
> +BackupToAAD-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId $BLV.KeyProtector[1].KeyProtectorId
```suggestion
PS C:\> $BLV = Get-BitLockerVolume -MountPoint "C:"
PS C:\> BackupToAAD-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId $BLV.KeyProtector[1].KeyProtectorId
```

2021-09-08 10:08 UTC, dariomws commented on docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md
> +BackupToAAD-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId "{E2611001E-6AD0-4A08-BAAA-C9c031DB2AA6}"
```suggestion
PS C:\> BackupToAAD-BitLockerKeyProtector -MountPoint "C:" -KeyProtectorId "{E2611001E-6AD0-4A08-BAAA-C9c031DB2AA6}"
```

2021-09-08 10:08 UTC, dariomws commented on docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-09-08 10:08 UTC, dariomws commented on docset/winserver2022-ps/bitlocker/BitLocker.md
> +### [BackupToAAD-BitLockerKeyProtector](.BackupToAAD-BitLockerKeyProtector.md)
```suggestion
### [BackupToAAD-BitLockerKeyProtector](./BackupToAAD-BitLockerKeyProtector.md)
```

2021-09-08 12:38 UTC, get-itips approved these changes
I am ok once Dario's suggestions are applied

2021-09-09 01:25 UTC, tseward approved these changes

2021-09-14 17:39 UTC, opbld32 commented
Docs Build status updates of commit _[5fdc53b](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/5fdc53b7efea0e1ed7f476cee8f7a1caa2f18913)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109141732582257-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JmbG4UVlCOm3ZTboDqPedBPvpjhiBW%2B7heelsSf75xA%3D&st=2021-09-14T17%3A34%3A29Z&se=2021-10-15T17%3A39%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 18:05 UTC, opbld31 commented
Docs Build status updates of commit _[17bfad2](https://github.com/IngridAtMicrosoft/windows-powershell-docs/commits/17bfad221c3be7c7693cf06cf75fe29ac80afe6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BackupToAAD-BitLockerKeyProtector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/backuptoaad-bitlockerkeyprotector?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |
[docset/winserver2022-ps/bitlocker/BitLocker.md](https://github.com/IngridAtMicrosoft/windows-powershell-docs/blob/monkey/docset/winserver2022-ps/bitlocker/BitLocker.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/bitlocker/index?view=windowsserver2022-ps&branch=pr-en-us-2580) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109141759171468-2580%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=c%2Bww9mSccA5aynVuvFeNrX8hM94Wwxh%2Fc6cL3bgFkV8%3D&st=2021-09-14T18%3A00%3A54Z&se=2021-10-15T18%3A05%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-14 18:07 UTC, merged