WIP: DnsClient PowerShell reference update
MicrosoftDocs/windows-powershell-docs pull request #2593
Opened 2021-08-24 22:33 UTC by TimShererWithAquent

[1869909](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1869909)

2021-08-24 22:40 UTC, opbld32 commented
Docs Build status updates of commit _[2258058](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/2258058344c3366af1e768c8e5dbd22806387b8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/add-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/DnsClient.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/DnsClient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/index?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/get-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/remove-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C24%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202108242233253762-2593%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ypw4bj7Vaysyfkfbeq1%2BupmjJwQHNuhO1FgeEsO5F5Q%3D&st=2021-08-24T22%3A35%3A07Z&se=2021-09-24T22%3A40%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 20:29 UTC, TimShererWithAquent commented
Per email to Alexandru, this is ready for final review.

2021-09-02 07:39 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md
> +If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the comp
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```

2021-09-02 07:51 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md
> +If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the comp
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```

2021-09-02 07:53 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md
> +If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the comp
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```

2021-09-02 08:03 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md
> +If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the comp
```suggestion
If this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
```

2021-09-02 08:08 UTC, JohanFreelancer9 requested changes
Copy review - @TimShererWithAquent, kindly commit the few minor suggested changes to remove the registered trademark symbol. Many thanks.

2021-09-02 14:50 UTC, opbld30 commented
Docs Build status updates of commit _[f306b16](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/f306b166a4451027189e5323f54dd624d3eabdbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/add-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/DnsClient.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/DnsClient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/index?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/get-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/remove-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109021443313790-2593%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=LsEEm%2FmdBdiMiIxMoQj757n%2BWAfdvdzinNZXBxJMNLk%3D&st=2021-09-02T14%3A45%3A24Z&se=2021-10-03T14%3A50%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 07:18 UTC, JohanFreelancer9 approved these changes

2021-09-08 20:41 UTC, TimShererWithAquent commented
@tiburd Editorial changes accepted. Ready for final review.

2021-09-08 23:36 UTC, get-itips approved these changes

2021-09-09 01:25 UTC, tseward approved these changes

2021-09-09 10:57 UTC, dariomws approved these changes

2021-09-09 14:57 UTC, TimShererWithAquent commented
Hi @tiburd - It looks like this is ready to merge.

2021-09-10 20:40 UTC, opbld33 commented
Docs Build status updates of commit _[d5da044](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/d5da04433a222bcefe4cf72d1380fbb30e21a7d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Add-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/add-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/DnsClient.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/DnsClient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/index?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Get-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/get-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Remove-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/remove-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |
[docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/dnsclient-v-tishe/docset/winserver2022-ps/dnsclient/Set-DnsClientDohServerAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclientdohserveraddress?view=windowsserver2022-ps&branch=pr-en-us-2593) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C10%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109102030020854-2593%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6ieXETVKdvkG0JqG8E0Jt1mGM8NSN%2B6zKDvL73smACU%3D&st=2021-09-10T20%3A35%3A13Z&se=2021-10-11T20%3A40%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-10 20:40 UTC, merged