iisadministration PowerShell reference update
MicrosoftDocs/windows-powershell-docs pull request #2602
Opened 2021-08-27 15:44 UTC by TimShererWithAquent

[1870688](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1870688)

This is generated changes only.

2021-08-28 03:07 UTC, tseward approved these changes

2021-08-28 13:46 UTC, get-itips approved these changes

2021-08-30 07:03 UTC, JohanFreelancer9 approved these changes

2021-08-30 08:38 UTC, dariomws requested changes
Minor suggestions.

I also think that these updates should apply to other versions of Windows (2016 and 2019).

2021-08-30 08:38 UTC, dariomws commented on docset/winserver2022-ps/iisadministration/Get-IISSiteBinding.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-08-30 08:38 UTC, dariomws commented on docset/winserver2022-ps/iisadministration/New-IISSiteBinding.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-08-30 08:38 UTC, dariomws commented on docset/winserver2022-ps/iisadministration/Remove-IISSiteBinding.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2021-08-30 08:38 UTC, dariomws commented on docset/winserver2022-ps/iisadministration/Set-IISCentralCertProviderCredential.md
> +### System.Object
This cmdlet has a string parameter as input.

2021-08-30 14:41 UTC, opbld30 commented
Docs Build status updates of commit _[3c86bb9](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/3c86bb9981b37790f83ba4e6f020a99e2f580eda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/iisadministration/Clear-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Clear-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/clear-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Clear-IISConfigCollection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Clear-IISConfigCollection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/clear-iisconfigcollection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Disable-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Disable-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/disable-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Disable-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Disable-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/disable-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Enable-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Enable-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/enable-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Enable-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Enable-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/enable-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Export-IISConfiguration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Export-IISConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/export-iisconfiguration?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISAppPool.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisapppool?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigAttributeValue.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigAttributeValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigattributevalue?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigCollection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigCollection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigcollection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigCollectionElement.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigCollectionElement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigcollectionelement?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigElement.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigElement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigelement?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigSection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigSection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigsection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISServerManager.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISServerManager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisservermanager?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSite.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iissite?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSiteBinding.md](https://githu [...]

2021-08-30 14:44 UTC, TimShererWithAquent commented
@dariomws - Thanks for your help. As for previous versions, the plan is to move the changes into the previous versions once we get the current version up to date -

2021-08-30 14:46 UTC, TimShererWithAquent commented
@tiburd - I've made the changes and it looks like we have 3 approvals. Let me know if I need to do anything else.

2021-08-30 14:48 UTC, opbld33 commented
Docs Build status updates of commit _[04df2c8](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/04df2c809938a412f65fd701dedeb167b614122e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/iisadministration/Clear-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Clear-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/clear-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Clear-IISConfigCollection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Clear-IISConfigCollection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/clear-iisconfigcollection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Disable-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Disable-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/disable-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Disable-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Disable-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/disable-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Enable-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Enable-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/enable-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Enable-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Enable-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/enable-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Export-IISConfiguration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Export-IISConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/export-iisconfiguration?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISAppPool.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisapppool?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigAttributeValue.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigAttributeValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigattributevalue?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigCollection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigCollection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigcollection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigCollectionElement.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigCollectionElement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigcollectionelement?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigElement.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigElement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigelement?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigSection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigSection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigsection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISServerManager.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISServerManager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisservermanager?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSite.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iissite?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSiteBinding.md](https://githu [...]

2021-08-30 14:55 UTC, opbld32 commented
Docs Build status updates of commit _[4def5ac](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/4def5ac0d2bab4c67a982605dbf47e11e332afde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/iisadministration/Clear-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Clear-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/clear-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Clear-IISConfigCollection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Clear-IISConfigCollection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/clear-iisconfigcollection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Disable-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Disable-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/disable-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Disable-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Disable-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/disable-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Enable-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Enable-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/enable-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Enable-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Enable-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/enable-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Export-IISConfiguration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Export-IISConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/export-iisconfiguration?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISAppPool.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisapppool?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISCentralCertProvider.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISCentralCertProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iiscentralcertprovider?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigAttributeValue.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigAttributeValue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigattributevalue?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigCollection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigCollection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigcollection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigCollectionElement.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigCollectionElement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigcollectionelement?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigElement.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigElement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigelement?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISConfigSection.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISConfigSection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisconfigsection?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISServerManager.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISServerManager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iisservermanager?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSharedConfig.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISSharedConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iissharedconfig?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSite.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/iisadministration-v-tishe-a/docset/winserver2022-ps/iisadministration/Get-IISSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/iisadministration/get-iissite?view=windowsserver2022-ps&branch=pr-en-us-2602) (WindowsServer2022-ps) |
[docset/winserver2022-ps/iisadministration/Get-IISSiteBinding.md](https://githu [...]

2021-08-30 16:36 UTC, dariomws approved these changes

2021-08-30 16:36 UTC, dariomws commented
Thanks @TimShererWithAquent!

2021-08-31 21:15 UTC, merged