Create New-MpPerformanceRecording.md
MicrosoftDocs/windows-powershell-docs pull request #2605
Opened 2021-08-27 17:41 UTC by v-smandalika

2021-08-30 07:11 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Defender.md
> +Collects a performance recording of MDAV scans
```suggestion
Collects a performance recording of MDAV scans.
```

2021-08-30 07:12 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +Analyzes and reports on MDAV performance recording
```suggestion
Analyzes and reports on MDAV performance recording.
```

2021-08-30 07:16 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +Specifies how many top scans for output for each top process for each top file, sorted by "Duration”.
```suggestion
Specifies how many top scans to output for each top process for each top file, sorted by "Duration”.
```

2021-08-30 07:18 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +Specifies how many top scans for output for each top process for each top extension, sorted by "Duration”.
```suggestion
Specifies how many top scans to output for each top process for each top extension, sorted by "Duration”.
```

2021-08-30 07:20 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +Specifies how many top scans for output for each top file for each top extension, sorted by "Duration".
```suggestion
Specifies how many top scans to output for each top file for each top extension, sorted by "Duration".
```

2021-08-30 07:21 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +Specifies how many top scans for output for each top extension for each top process, sorted by "Duration”.
```suggestion
Specifies how many top scans to output for each top extension for each top process, sorted by "Duration”.
```

2021-08-30 07:22 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +Specifies how many top scans for output for each top file for each top process, sorted by "Duration”.
```suggestion
Specifies how many top scans to output for each top file for each top process, sorted by "Duration”.
```

2021-08-30 07:32 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +For more information on the Performance analyzer, see Performance Analyzer docs.
```suggestion
For more information on the Performance analyzer, see the [Windows Performance Analyzer](windows-hardware/test/wpt/windows-performance-analyzer) topic.
```

2021-08-30 07:38 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +> This feature is available starting with platform version 4.18.2108.X and higher.
```suggestion
Note: This feature is available starting with platform version 4.18.2108.X and higher.
```

2021-08-30 07:40 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPerformanceReport.md
> +- Performance Analyzer docs
```suggestion
- [Windows Performance Analyzer](windows-hardware/test/wpt/windows-performance-analyzer)
```

2021-08-30 07:44 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/New-MpPerformanceRecording.md
> +Collects a performance recording of MDAV scans.
```suggestion
Collects a performance recording of Microsoft Defender Antivirus scans.
```

2021-08-30 07:47 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/New-MpPerformanceRecording.md
> +> This cmdlet requires elevated administrator privileges.
```suggestion
**IMPORTANT**: This cmdlet requires elevated administrator privileges.
```

2021-08-30 07:49 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/New-MpPerformanceRecording.md
> +Windows Version 10 and higher.
```suggestion
Windows Version 10 and later.
```

2021-08-30 07:51 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/New-MpPerformanceRecording.md
> +> This feature is available starting with platform version 4.18.2108.X and higher.
```suggestion
Note: This feature is available starting with platform version 4.18.2108.X and higher.
```

2021-08-30 07:53 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/New-MpPerformanceRecording.md
> +- Performance Analyzer docs
```suggestion
- [Windows Performance Analyzer](windows-hardware/test/wpt/windows-performance-analyzer)
```

2021-08-30 07:54 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/New-MpPerformanceRecording.md
> +
```suggestion
```

2021-08-30 07:57 UTC, JohanFreelancer9 requested changes
Copy review - @v-smandalika, kindly commit the suggested changes if you agree with them. For information, PowerShell does not support markdown, so [!NOTE], etc. should be Note: <text>, etc. in PowerShell docs. Many thanks.

2021-08-30 11:51 UTC, opbld33 commented
Docs Build status updates of commit _[2d029cb](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/2d029cb6d244bccd3a1d817ca34c21543e89e41d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1938ddbf)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-1938ddbf)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-1938ddbf)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-1938ddbf)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-1938ddbf)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-1938ddbf)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-1938ddbf)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-1938ddbf)
[docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-b9d59df64f067d461dbb48f9ae6854ee-1938ddbf)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-1938ddbf)
[docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-a09f384d8712fb7f8faff8d660e6493d-1938ddbf)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-1938ddbf)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-1938ddbf)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-1938ddbf)
[docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-81ace7fcbe0feada4ba345969d78a27f-1938ddbf)
[docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-b85158b47619ffe71dc427c10b7cc52a-1938ddbf)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-1938ddbf)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcPool.yml) | :warning:Warning | | [Details](#user-content-fa7e045ed70c0a881e90d5d2879861ec-1938ddbf)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-1938ddbf)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-1938ddbf)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-1938ddbf)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-1938ddbf)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-1938ddbf)
[docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-71915acb96d2fd60bc835350494d85ea-1938ddbf)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-1938ddbf)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-f0a22bfd4a4956e0af0cb5431a34dd99-1938ddbf)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-1938ddbf)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/ [...]

2021-08-30 12:14 UTC, JohanFreelancer9 approved these changes

2021-09-01 07:49 UTC, opbld32 commented
Docs Build status updates of commit _[d9f829d](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/d9f829d4637ee3ff1df1db660aecb8981b708d18)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cffaa294)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-cffaa294)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-cffaa294)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-cffaa294)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-de20542205fa8f158452184fc4e34eed-cffaa294)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-cffaa294)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-cffaa294)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-cffaa294)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcPool.yml) | :warning:Warning | | [Details](#user-content-fa7e045ed70c0a881e90d5d2879861ec-cffaa294)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-cffaa294)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-cffaa294)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-cffaa294)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-cffaa294)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-cffaa294)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-cffaa294)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-cffaa294)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-cffaa294)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-cffaa294)
[docset/winserver2012r2-ps/hpc/Start-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNode.yml) | :warning:Warning | | [Details](#user-content-cc542af00eb4eb194383f1acf2114bfa-cffaa294)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-cffaa294)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-cffaa294)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-cffaa294)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-1173548ae89e31a43c4ddf17d0f83a10-cffaa294)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-cffaa294)
[docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-71915acb96d2fd60bc835350494d85ea-cffaa294)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-cffaa294)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-cffaa294)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warn [...]

2021-09-03 05:44 UTC, opbld30 commented
Docs Build status updates of commit _[b6d0e36](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/b6d0e366a62e47adb4b9d2218c52a1385abc724c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f1857df7)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-f1857df7)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-f1857df7)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-f1857df7)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-f1857df7)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-f1857df7)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-f1857df7)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-de20542205fa8f158452184fc4e34eed-f1857df7)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-f1857df7)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-f1857df7)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-f1857df7)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-f1857df7)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-f1857df7)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-f1857df7)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-f1857df7)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-f1857df7)
[docset/winserver2012r2-ps/hpc/Start-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNode.yml) | :warning:Warning | | [Details](#user-content-cc542af00eb4eb194383f1acf2114bfa-f1857df7)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-f1857df7)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcPool.yml) | :warning:Warning | | [Details](#user-content-fa7e045ed70c0a881e90d5d2879861ec-f1857df7)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-f1857df7)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-f1857df7)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-f1857df7)
[docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-b9d59df64f067d461dbb48f9ae6854ee-f1857df7)
[docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-a09f384d8712fb7f8faff8d660e6493d-f1857df7)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-f0a22bfd4a4956e0af0cb5431a34dd99-f1857df7)
[docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-5c0e78634d8dd3aac77ef85ea413cad9-f1857df7)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-f1857df7)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warn [...]

2021-09-03 05:51 UTC, opbld31 commented
Docs Build status updates of commit _[2a73326](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/2a733268a973dfd123db5f6f3e869c58fd1256de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4fbe3c43)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-4fbe3c43)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-de20542205fa8f158452184fc4e34eed-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-4fbe3c43)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-4fbe3c43)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-e9f6766fd03a4b293cb88ad26045007b-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-4fbe3c43)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-4fbe3c43)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-4fbe3c43)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-1173548ae89e31a43c4ddf17d0f83a10-4fbe3c43)
[docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-81ace7fcbe0feada4ba345969d78a27f-4fbe3c43)
[docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-71915acb96d2fd60bc835350494d85ea-4fbe3c43)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-4fbe3c43)
[docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-b85158b47619ffe71dc427c10b7cc52a-4fbe3c43)
[docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-b9d59df64f067d461dbb48f9ae6854ee-4fbe3c43)
[docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patc [...]

2021-09-03 05:58 UTC, opbld31 commented
Docs Build status updates of commit _[63961f4](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/63961f4be9dc6540c4ba98548c5fe8769ce396e7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-baefd1b8)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-baefd1b8)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-baefd1b8)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-baefd1b8)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-baefd1b8)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-baefd1b8)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-baefd1b8)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-baefd1b8)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-baefd1b8)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-baefd1b8)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-baefd1b8)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-e9f6766fd03a4b293cb88ad26045007b-baefd1b8)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-baefd1b8)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-baefd1b8)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-baefd1b8)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-baefd1b8)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-baefd1b8)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-1173548ae89e31a43c4ddf17d0f83a10-baefd1b8)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-f0a22bfd4a4956e0af0cb5431a34dd99-baefd1b8)
[docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-5c0e78634d8dd3aac77ef85ea413cad9-baefd1b8)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-baefd1b8)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-baefd1b8)
[docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-b9d59df64f067d461dbb48f9ae6854ee-baefd1b8)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-baefd1b8)
[docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-a09f384d8712fb7f8faff8d660e6493d-baefd1b8)
[docset/winserver2012r2-ps/hpc/Start-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNode.yml) | :warning:Warning | | [Details](#user-content-cc542af00eb4eb194383f1acf2114bfa-baefd1b8)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-baefd1b8)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2 [...]

2021-09-03 07:00 UTC, opbld30 commented
Docs Build status updates of commit _[a1cfeda](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/a1cfeda28f5a164540653382ba9b1ace67f833e4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8d9eedb7)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-8d9eedb7)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-8d9eedb7)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcPool.yml) | :warning:Warning | | [Details](#user-content-fa7e045ed70c0a881e90d5d2879861ec-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Start-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNode.yml) | :warning:Warning | | [Details](#user-content-cc542af00eb4eb194383f1acf2114bfa-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-8d9eedb7)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-f0a22bfd4a4956e0af0cb5431a34dd99-8d9eedb7)
[docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-5c0e78634d8dd3aac77ef85ea413cad9-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-8d9eedb7)
[docset/winserver2019-ps/defender/Get-MpPerformanceReport.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2019-ps/defender/Get-MpPerformanceReport.md) | :warning:Warning | | [Details](#user-content-2f8cc84dabeda063617651d80611e997-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-8d9eedb7)
[docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-71915acb96d2fd60bc835350494d85ea-8d9eedb7)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-8d9eedb7)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-8d9eedb7)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-e9f6766fd03a4b293cb88ad26045007b-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-8d9eedb7)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-H [...]

2021-09-03 07:29 UTC, opbld33 commented
Docs Build status updates of commit _[b2d9537](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/b2d9537498aa4dde21d56cec2bac3d35a5818510)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1550d9e7)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-1550d9e7)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-1550d9e7)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-1550d9e7)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-1550d9e7)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-1550d9e7)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcPool.yml) | :warning:Warning | | [Details](#user-content-fa7e045ed70c0a881e90d5d2879861ec-1550d9e7)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-1550d9e7)
[docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-b9d59df64f067d461dbb48f9ae6854ee-1550d9e7)
[docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-a09f384d8712fb7f8faff8d660e6493d-1550d9e7)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-f0a22bfd4a4956e0af0cb5431a34dd99-1550d9e7)
[docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-5c0e78634d8dd3aac77ef85ea413cad9-1550d9e7)
[docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-81ace7fcbe0feada4ba345969d78a27f-1550d9e7)
[docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-b85158b47619ffe71dc427c10b7cc52a-1550d9e7)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-1550d9e7)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-1173548ae89e31a43c4ddf17d0f83a10-1550d9e7)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-1550d9e7)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-e9f6766fd03a4b293cb88ad26045007b-1550d9e7)
[docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-71915acb96d2fd60bc835350494d85ea-1550d9e7)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-1550d9e7)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-1550d9e7)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-1550d9e7)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-1550d9e7)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-de20542205fa8f158452184fc4e34eed-1550d9e7)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-1550d9e7)
[docset/winserver2019-ps/defender/Get-MpPerformanceReport.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2019-ps/defender/Get-MpPerformanceReport.md) | :warning:Warning | | [Details](#user-content-2f8cc84dabeda063617651d80611e997-1550d9e7)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-1550d9e7)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows- [...]

2021-09-03 07:42 UTC, opbld32 commented
Docs Build status updates of commit _[b2d9537](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/b2d9537498aa4dde21d56cec2bac3d35a5818510)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b1f154f)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-7b1f154f)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-7b1f154f)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-7b1f154f)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-7b1f154f)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-7b1f154f)
[docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-3fb4cfefec28b9cfd02cf826c44baa84-7b1f154f)
[docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcJob.yml) | :warning:Warning | | [Details](#user-content-5f7f88d866f0f14ba1129e4b6a0c2733-7b1f154f)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-de20542205fa8f158452184fc4e34eed-7b1f154f)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-7b1f154f)
[docset/winserver2012r2-ps/hpc/Set-HpcPool.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcPool.yml) | :warning:Warning | | [Details](#user-content-fa7e045ed70c0a881e90d5d2879861ec-7b1f154f)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-7b1f154f)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-7b1f154f)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml) | :warning:Warning | | [Details](#user-content-46750f26e677aff1759ec7ea0dfa2cf1-7b1f154f)
[docset/winserver2012r2-ps/hpc/Start-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNode.yml) | :warning:Warning | | [Details](#user-content-cc542af00eb4eb194383f1acf2114bfa-7b1f154f)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-7b1f154f)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-7b1f154f)
[docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNodeState.yml) | :warning:Warning | | [Details](#user-content-52a55d94858ecee2cb7e3d8a1d6bfaa3-7b1f154f)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-7b1f154f)
[docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcTestResult.yml) | :warning:Warning | | [Details](#user-content-b90cc709da74a1582dd1f08bfa32dd27-7b1f154f)
[docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Validate-HpcIScsiStorageArray.yml) | :warning:Warning | | [Details](#user-content-de7ea6e6f52244c1ca275a379e40af54-7b1f154f)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-7b1f154f)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-7b1f154f)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-e9f6766fd03a4b293cb88ad26045007b-7b1f154f)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-7b1f154f)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-1173548ae89e31a43c4ddf17d0f83a10-7b1f154f)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-7b1f154f)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) [...]

2021-09-03 11:04 UTC, opbld33 commented
Docs Build status updates of commit _[d0a2bb1](https://github.com/MicrosoftDocs/windows-powershell-docs/commits/d0a2bb10f97370809996ef10e146499a025c009a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d29ccbda)
[docset/winserver2012r2-ps/hpc/Set-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTask.yml) | :warning:Warning | | [Details](#user-content-3cfc5d63a08dba8954ff48df8e53d263-d29ccbda)
[docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcAzureNode.yml) | :warning:Warning | | [Details](#user-content-de20542205fa8f158452184fc4e34eed-d29ccbda)
[docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcTestCredential.yml) | :warning:Warning | | [Details](#user-content-1176738253d0164d81f8cf7d7b94284c-d29ccbda)
[docset/winserver2012r2-ps/hpc/Start-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNode.yml) | :warning:Warning | | [Details](#user-content-cc542af00eb4eb194383f1acf2114bfa-d29ccbda)
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-01f247659a000f7b7d69c23d664246ae-d29ccbda)
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-d0e9b11fd506fe72c6aeba24d1b13268-d29ccbda)
[docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcSoaCredential.yml) | :warning:Warning | | [Details](#user-content-df0f6cacbb83cb4c0793dd8c7a975275-d29ccbda)
[docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Shutdown-HpcNode.yml) | :warning:Warning | | [Details](#user-content-4fc68a1dc27e870f0c95ce16be284667-d29ccbda)
[docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Start-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-039c7c2593913eb78717b362f82dc75c-d29ccbda)
[docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-b9d59df64f067d461dbb48f9ae6854ee-d29ccbda)
[docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Enable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-a09f384d8712fb7f8faff8d660e6493d-d29ccbda)
[docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-71915acb96d2fd60bc835350494d85ea-d29ccbda)
[docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-54eb21710a6e6ba7bacc1ed072e746e9-d29ccbda)
[docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/New-HpcSoftCard.yml) | :warning:Warning | | [Details](#user-content-5fd7a0b1ff16fd865f767c865ae63af4-d29ccbda)
[docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-ee5003001c0ee5108bc0fccaabd8f20d-d29ccbda)
[docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Set-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-1173548ae89e31a43c4ddf17d0f83a10-d29ccbda)
[docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-549b0e27cb2971dca37a3e42ffd1586f-d29ccbda)
[docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-81ace7fcbe0feada4ba345969d78a27f-d29ccbda)
[docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Remove-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-e9f6766fd03a4b293cb88ad26045007b-d29ccbda)
[docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Get-SmbBandwidthLimit.yml) | :warning:Warning | | [Details](#user-content-b85158b47619ffe71dc427c10b7cc52a-d29ccbda)
[docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2016-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-f0a22bfd4a4956e0af0cb5431a34dd99-d29ccbda)
[docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2022-ps/smbshare/Disable-SmbDelegation.yml) | :warning:Warning | | [Details](#user-content-5c0e78634d8dd3aac77ef85ea413cad9-d29ccbda)
[docset/winserver2012r2-ps/hpc/Set-HpcNode.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Set-HpcNode.yml) | :warning:Warning | | [Details](#user-content-f09c8a2c5a537ecdd6380165c9d06614-d29ccbda)
[docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Stop-HpcNodeSet.yml) | :warning:Warning | | [Details](#user-content-e3cbebfd16fd0cef681001010a8465ad-d29ccbda)
[docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Submit-HpcJob.yml) | :warning:Warning | | [Details](#user-content-0fe9f398fcfd3268f37da9fc07680ec2-d29ccbda)
[docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/v-smandalika-patch-1/docset/winserver2012r2-ps/hpc/Get-HpcJobCredential.yml) | :warning:Warning | | [Details](#user-content-a82d218f6f232c452b1c89ecf410e8f6-d29ccbda)
[docset/winserver2012r2-ps/hpc/Stop-HpcTask.yml](https://github.com/MicrosoftDocs/windows-powershell-docs/b [...]

2023-09-01 15:40 UTC, tiburd commented
Closing due to inactivity.

2023-09-01 15:40 UTC, closed without merging