WIP: ADCSAdministration PowerShell reference update
MicrosoftDocs/windows-powershell-docs pull request #2630
Opened 2021-09-03 17:14 UTC by TimShererWithAquent

[1871153](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1871153)

One new cmdlet. Other changes are Input and Output.

2021-09-03 17:21 UTC, opbld30 commented
Docs Build status updates of commit _[c84bd73](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/c84bd73509d60ec46f42cd7d5784d0de75024801)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/adcsadministration/ADCSAdministration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/ADCSAdministration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/index?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/backup-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caattestationidentitykeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caendorsementkeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/restore-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109031714295731-2630%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HxkpDBCWF3ngJFEDo8qnhIGsi9BZ3eXyPrc8sfrdAJE%3D&st=2021-09-03T17%3A16%3A07Z&se=2021-10-04T17%3A21%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 19:20 UTC, opbld30 commented
Docs Build status updates of commit _[611ce2f](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/611ce2f70d85c28e015e74cdb5161726d68c7b0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/adcsadministration/ADCSAdministration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/ADCSAdministration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/index?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/backup-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caattestationidentitykeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caendorsementkeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/restore-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109031914169811-2630%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Fczy7bS6prTDR7TYpU2NEWW42Shros8%2BOGOIJoWyfho%3D&st=2021-09-03T19%3A15%3A39Z&se=2021-10-04T19%3A20%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-15 23:16 UTC, thirunadh commented on docset/winserver2022-ps/adcsadministration/ADCSAdministration.md
> +Checks whether the local certification authority trusts secure hardware for identity attestation.
can you use CA here to be inline with all other descriptions.

2021-09-22 00:12 UTC, thirunadh requested changes

2021-09-22 00:12 UTC, thirunadh commented on docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md
> +This cmdlet verifies whether the public certificate connects through a certificate chain to an anchor that the CA trusts. Specify an X509 certificate by using the **Certificate** parameter.
Please update it to - "This cmdlet verifies whether the Attestation Identity Key (AIK) public certificate ..."

2021-09-22 00:12 UTC, thirunadh commented on docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md
> +This cmdlet checks whether the attestation identity public key exists as a file in a folder configured at the local CA for key attestation. Specify the public key by using the **PublicKeyHash** param
use capital letters for attestation identity - "... Attestation Identity Key (AIK) public key exists ..."

2021-09-22 14:59 UTC, opbld31 commented
Docs Build status updates of commit _[d290a25](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/d290a25e0000b32816cc31af5c3ece81664f6d7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/adcsadministration/ADCSAdministration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/ADCSAdministration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/index?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/backup-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caattestationidentitykeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caendorsementkeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/restore-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C22%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109221452236830-2630%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-23T14%3A59%3A20Z&sr=b&sp=r&sig=KAkzwB2Npjgs0r8wvv5bWzqhRN694n7Oi%2BMV3bi26B8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-22 17:14 UTC, thirunadh approved these changes
Looks good to me. Thanks.

2021-09-22 17:25 UTC, TimShererWithAquent commented
Hi @tiburd - I got SME approval for this one. Ready for review.

2021-09-22 20:19 UTC, get-itips approved these changes

2021-09-22 21:38 UTC, dariomws approved these changes

2021-09-22 22:59 UTC, tseward approved these changes

2021-09-23 08:18 UTC, JohanFreelancer9 approved these changes

2021-09-23 14:33 UTC, TimShererWithAquent commented
@tiburd It looks like we have three approvals and are ready for merge.

2021-09-23 18:18 UTC, opbld33 commented
Docs Build status updates of commit _[f83e85b](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/f83e85b1b800d835888e57bf5f5b3fb3252df387)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/adcsadministration/ADCSAdministration.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/ADCSAdministration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/index?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Add-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Add-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/add-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Backup-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/backup-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAAttestationIdentityKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caattestationidentitykeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Confirm-CAEndorsementKeyInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/confirm-caendorsementkeyinfo?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CAAuthorityInformationAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-caauthorityinformationaccess?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CACrlDistributionPoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-cacrldistributionpoint?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Remove-CATemplate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/remove-catemplate?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |
[docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/adcsadministration-v-tishe/docset/winserver2022-ps/adcsadministration/Restore-CARoleService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adcsadministration/restore-caroleservice?view=windowsserver2022-ps&branch=pr-en-us-2630) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109231812019551-2630%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T18%3A18%3A57Z&sr=b&sp=r&sig=6dmARCMUOhyUmTeNLztQdZ26I8cd%2FLHZEG2QvGtxQ20%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-23 18:24 UTC, merged