WIP: ConfigCI PowerShell reference update
MicrosoftDocs/windows-powershell-docs pull request #2671
Opened 2021-09-23 17:41 UTC by TimShererWithAquent

2021-09-23 17:48 UTC, opbld31 commented
Docs Build status updates of commit _[da23325](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/da2332538ede28fe55d1fcb34f3d7cccc8dfea14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/configci/Add-SignerRule.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Add-SignerRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/add-signerrule?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/ConfigCI.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/ConfigCI.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/index?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Edit-CIPolicyRule.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Edit-CIPolicyRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/edit-cipolicyrule?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Merge-CIPolicy.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Merge-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/merge-cipolicy?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/New-CIPolicy.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/New-CIPolicyRule.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/New-CIPolicyRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Set-CIPolicyIdInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Set-CIPolicyIdInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/set-cipolicyidinfo?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Set-CIPolicySetting.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Set-CIPolicySetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/set-cipolicysetting?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Set-HVCIOptions.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Set-HVCIOptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/set-hvcioptions?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C23%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109231741409664-2671%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-24T17%3A48%3A37Z&sr=b&sp=r&sig=wyljX%2FaQeY%2BORKNY4LsC%2BKyvUlVT6d02%2Bpxq5XluUVM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-13 00:48 UTC, jgeurten requested changes

2021-10-29 21:11 UTC, get-itips approved these changes

2021-10-30 06:58 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/configci/New-CIPolicy.md
> +Refer to [Create WDAC policies in Multiple Policy Format](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-applicati
```suggestion
Refer to [Create WDAC policies in Multiple Policy Format](/windows/security/threat-protection/windows-defender-application-control/deploy-multiple-windows-defender-application-control-policies#creating-wdac-policies-in-multiple-policy-format) for the difference between the policy formats. 
```

2021-10-30 06:59 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/configci/New-CIPolicy.md
> +Refer to [File Name Rules Info](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#windows-defender-application-c
```suggestion
Refer to [File Name Rules Info](/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#windows-defender-application-control-filename-rules) for a description of the acceptable values.
```

2021-10-30 07:02 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/configci/New-CIPolicyRule.md
> +For more information, see [Use a Windows Defender Application Control policy to control specific plug-ins, add-ins, and modules](https://docs.microsoft.com/windows/security/threat-protection/windows-
```suggestion
For more information, see [Use a Windows Defender Application Control policy to control specific plug-ins, add-ins, and modules](/windows/security/threat-protection/windows-defender-application-control/use-windows-defender-application-control-policy-to-control-specific-plug-ins-add-ins-and-modules).
```

2021-10-30 07:03 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/configci/New-CIPolicyRule.md
>  Specifies the primary level of detail for generated rules. Refer to [WDAC File Rule Levels](https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/select-t
```suggestion
Specifies the primary level of detail for generated rules. Refer to [WDAC File Rule Levels](/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#windows-defender-application-control-file-rule-levels) for acceptable parameter values and descriptions.
```

2021-10-30 07:04 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/configci/New-CIPolicyRule.md
> +Refer to [File Name Rules Info](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#windows-defender-application-c
```suggestion
Refer to [File Name Rules Info](/windows/security/threat-protection/windows-defender-application-control/select-types-of-rules-to-create#windows-defender-application-control-filename-rules) for a description of the acceptable values.
```

2021-10-30 07:20 UTC, JohanFreelancer9 requested changes
Copy looks good. However, I have suggested changing the links to site relative links, unless there is a reason not to. @TimShererWithAquent, @dariomws, @get-itips, @tseward. Many thanks.

2021-11-01 10:06 UTC, dariomws approved these changes
I'm ok after suggestions.

2021-11-01 14:39 UTC, TimShererWithAquent commented
@JohanFreelancer9 Thanks - I rechecked the style guide and site relative links are correct, as you said. Accepted your changes.

2021-11-01 14:39 UTC, JohanFreelancer9 approved these changes

2021-11-01 14:43 UTC, opbld32 commented
Docs Build status updates of commit _[dedf295](https://github.com/TimShererWithAquent/windows-powershell-docs/commits/dedf295ffae3873dcb4fa96ff302caaaac34b1e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/configci/Add-SignerRule.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Add-SignerRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/add-signerrule?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/ConfigCI.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/ConfigCI.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/index?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Edit-CIPolicyRule.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Edit-CIPolicyRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/edit-cipolicyrule?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Merge-CIPolicy.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Merge-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/merge-cipolicy?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/New-CIPolicy.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/New-CIPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicy?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/New-CIPolicyRule.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/New-CIPolicyRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/new-cipolicyrule?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Set-CIPolicyIdInfo.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Set-CIPolicyIdInfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/set-cipolicyidinfo?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Set-CIPolicySetting.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Set-CIPolicySetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/set-cipolicysetting?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |
[docset/winserver2022-ps/configci/Set-HVCIOptions.md](https://github.com/TimShererWithAquent/windows-powershell-docs/blob/configci-v-tishe/docset/winserver2022-ps/configci/Set-HVCIOptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/configci/set-hvcioptions?view=windowsserver2022-ps&branch=pr-en-us-2671) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202111011436258648-2671%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-02T14%3A43%3A33Z&sr=b&sp=r&sig=fMnOtJEQGA5fBWjkUExF9tGyvzDIAYIL5J6zYBc1OmI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-01 14:58 UTC, tseward approved these changes

2021-11-01 17:07 UTC, TimShererWithAquent commented
Hi @tiburd - I've accepted the changes from the review. This one should be ready to merge.

2021-11-01 17:12 UTC, merged