Remove note on no recovery compression support
MicrosoftDocs/windows-powershell-docs pull request #2692
Opened 2021-09-30 16:56 UTC by Suphax

2021-09-30 17:06 UTC, opbld33 commented
Docs Build status updates of commit _[969ea6b](https://github.com/Suphax/windows-powershell-docs/commits/969ea6bd3c33db4498984de92be139609eab3359)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dism/Export-WindowsImage.md](https://github.com/Suphax/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dism/Export-WindowsImage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dism/export-windowsimage?view=windowsserver2019-ps&branch=pr-en-us-2692) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C30%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202109301656360107-2692%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-31T17%3A06%3A28Z&sr=b&sp=r&sig=ZdxlRhlEiEHN9axq4uOhUMsay0QIvPMQmog4RQC43y0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-01 09:47 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/dism/Export-WindowsImage.md
> +The *CompressionType* parameter does not apply when you export an image to an existing .wim file, you can only use this CompressionType when you export an image to a new .wim file.
```suggestion
The *CompressionType* parameter does not apply when you export an image to an existing .wim file; you can only use this CompressionType when you export an image to a new .wim file.
```

2021-10-01 09:48 UTC, JohanFreelancer9 requested changes
Copy review - @Suphax, kindly commit the minor additional suggested change. Many thanks.

2021-10-01 17:16 UTC, opbld31 commented
Docs Build status updates of commit _[132d96b](https://github.com/Suphax/windows-powershell-docs/commits/132d96be9a316b03158a6c8452f9f3b911f4ac5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dism/Export-WindowsImage.md](https://github.com/Suphax/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dism/Export-WindowsImage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dism/export-windowsimage?view=windowsserver2019-ps&branch=pr-en-us-2692) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C1%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202110011709565745-2692%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-01T17%3A16%3A30Z&sr=b&sp=r&sig=AtEz2WKu3wlv3oC2q5sR0tJJ01x%2BXEdcO85X9klF%2FKw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-10-02 04:52 UTC, JohanFreelancer9 approved these changes

2021-10-07 21:00 UTC, dariomws approved these changes

2021-10-07 23:16 UTC, get-itips approved these changes
approving after suggestions applied

2021-10-11 14:45 UTC, ghost approved these changes
Approved pending suggested changes.

2022-07-19 22:03 UTC, opbld31 commented
Docs Build status updates of commit _[ae2c405](https://github.com/Suphax/windows-powershell-docs/commits/ae2c4052c69ed01202bf9152be1e2b320f59d4e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dism/Export-WindowsImage.md](https://github.com/Suphax/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dism/Export-WindowsImage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dism/export-windowsimage?view=windowsserver2019-ps&branch=pr-en-us-2692) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202207192156015999-2692/BuildReport?accessString=e0ea85755744b510d98f49a50bdbdfb615c22a3eb5d6bbf80c435704cb8d0dfa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 20:21 UTC, opbld33 commented
Docs Build status updates of commit _[1e7689e](https://github.com/Suphax/windows-powershell-docs/commits/1e7689ecbd308757db975a2e82b9d3a1bc97c1b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/dism/Export-WindowsImage.md](https://github.com/Suphax/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/dism/Export-WindowsImage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dism/export-windowsimage?view=windowsserver2019-ps&branch=pr-en-us-2692) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208252014273611-2692/BuildReport?accessString=6821a992d1632b4557db9badf3ccebe56cc94c0c7a7529b87700912cf6c2d6c6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2024-02-14 19:35 UTC, Suphax commented
Is there anything extra needed for this to be merged? Unsure if I've missed something.

2024-04-11 17:43 UTC, Suphax commented
Hello?

2024-04-17 07:19 UTC, Suphax commented
Great help thanks

2024-04-17 07:19 UTC, closed without merging