Update Restart-VM.md
MicrosoftDocs/windows-powershell-docs pull request #2802
Opened 2021-12-14 18:34 UTC by msbemba

Added information about wait and timeout parameters.

2021-12-14 18:35 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-14 18:35 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2662

2021-12-14 18:40 UTC, opbld32 commented
Docs Build status updates of commit _[0736c21](https://github.com/msbemba/windows-powershell-docs/commits/0736c21c521707529b475fc3291f1725634f2b5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2019-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2019-ps&branch=pr-en-us-2802) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C14%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112141834431283-2802%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-14T18%3A40%3A48Z&sr=b&sp=r&sig=8WViTGPkMnQSj7Prrc3JY0kIIBthc%2BMHA%2B7oX6qMW1g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 03:25 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/hyper-v/Restart-VM.md
> +Specifies the duration of the wait, in seconds. When the timeout elapses, Restart-VM returns to the command prompt, even if the VM isn't  restarted.
```suggestion
Specifies the duration of the wait, in seconds. When the timeout elapses, **Restart-VM** returns to the command prompt, even if the virtual machine isn't restarted.
```

2021-12-15 03:42 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/hyper-v/Restart-VM.md
> +The Timeout parameter is only valid with the Wait parameter. Timeout overrides the Wait parameter's indefinite waiting period.
```suggestion
This parameter is only valid with the `-Wait` parameter. The `-Timeout` parameter overrides the `-Wait` parameter's indefinite waiting period.
```

2021-12-15 03:44 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/hyper-v/Restart-VM.md
> +Restart-VM suppresses the PowerShell prompt and blocks the pipeline until the VM has restarted. You can use this parameter in a script to restart VM and then continue to process when the restart is f
```suggestion
**Restart-VM** suppresses the PowerShell prompt and blocks the pipeline until the virtual machine has restarted. You can use this parameter in a script to restart the virtual machine and then continue to process when the restart is finished.
```

2021-12-15 03:50 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/hyper-v/Restart-VM.md
> +The Wait parameter waits indefinitely for the VM to restart. You can use Timeout to adjust the timing and the For and Delay parameters to wait for particular services to become available on the resta
```suggestion
The `-Wait` parameter waits indefinitely for the virtual machine to restart. You can use the `-Timeout` parameter to adjust the timing and the `-For` and `-Delay` parameters to wait for particular services to become available on the restarted virtual machine.
```

2021-12-15 03:53 UTC, JohanFreelancer9 requested changes
Copy review - these are only suggestions.

2021-12-15 04:59 UTC, opbld31 commented
Docs Build status updates of commit _[ae684c7](https://github.com/msbemba/windows-powershell-docs/commits/ae684c77b7abd0285f70f8b9f6eb9bb4c00f1505)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2019-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2019-ps&branch=pr-en-us-2802) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112150448483836-2802%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T04%3A59%3A16Z&sr=b&sp=r&sig=ILSi4ceyy%2BCUfeX7Mw0TiDnKuUT0c0Wvw3nNYT%2BgZ1g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-15 08:28 UTC, JohanFreelancer9 commented
@msbemba, you have only committed one suggestion. Kindly commit my other suggestions as well. Thanks.

2021-12-15 13:36 UTC, JohanFreelancer9 approved these changes

2021-12-17 07:07 UTC, tseward approved these changes

2021-12-17 13:35 UTC, get-itips reviewed
Can this information be added to other OS's versions of the article?

2021-12-17 22:30 UTC, dariomws approved these changes

2021-12-19 01:34 UTC, msbemba commented
@get-itips It has been added to the other two versions where the parameter is available .

2021-12-19 01:40 UTC, opbld31 commented
Docs Build status updates of commit _[5539f93](https://github.com/msbemba/windows-powershell-docs/commits/5539f933821405c7a7651cad1f088112fd101329)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2016-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2016-ps&branch=pr-en-us-2802) (WindowsServer2016-ps) |
[docset/winserver2019-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2019-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2019-ps&branch=pr-en-us-2802) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190133433940-2802%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T01%3A40%3A46Z&sr=b&sp=r&sig=DCq8MP6Ybj%2Fw8EpTxynOqLvXmtgGjhYBy9%2FMylsI%2BaA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[cf3b468](https://github.com/msbemba/windows-powershell-docs/commits/cf3b4680afe0d897609c16f3464ba3cca3fed271)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2016-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2016-ps&branch=pr-en-us-2802) (WindowsServer2016-ps) |
[docset/winserver2019-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2019-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2019-ps&branch=pr-en-us-2802) (WindowsServer2019-ps) |
[docset/winserver2022-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2022-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2022-ps&branch=pr-en-us-2802) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190133548840-2802%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T01%3A43%3A33Z&sr=b&sp=r&sig=aacR3vGhPcVdr0TJvQMZA7ZRDNuvXDootV%2Fwwc0%2Ftbg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-31 16:03 UTC, opbld31 commented
Docs Build status updates of commit _[7bdac05](https://github.com/msbemba/windows-powershell-docs/commits/7bdac052ed4dd4f09d67c1941b03bf24ad8c345a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2016-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2016-ps&branch=pr-en-us-2802) (WindowsServer2016-ps) |
[docset/winserver2019-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2019-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2019-ps&branch=pr-en-us-2802) (WindowsServer2019-ps) |
[docset/winserver2022-ps/hyper-v/Restart-VM.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-124/docset/winserver2022-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2022-ps&branch=pr-en-us-2802) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202205311549346596-2802/BuildReport?accessString=9f27939ef1cc34e3ba4e3d60a173f2a07049fb54beff909c837b0b6dcbaa5f0b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-31 16:08 UTC, merged