Clarify note on creating named pipe
MicrosoftDocs/windows-powershell-docs pull request #2806
Opened 2021-12-17 18:40 UTC by zanedp

As it was, it has misled many engineers down an unnecessary and confusing path.

2021-12-17 18:47 UTC, opbld32 commented
Docs Build status updates of commit _[84c3018](https://github.com/zanedp/windows-powershell-docs/commits/84c3018bf5ef427ecf0adcb682bfd33fb85e72b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C17%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112171841020192-2806%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-17T18%3A47%3A37Z&sr=b&sp=r&sig=Z9w3wsLXPcDX%2FwFzUuuxOK9TvullZySom%2BbhYaKuEOw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-18 05:53 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/hyper-v/Set-VMComPort.md
> +> You can write write your own application to access the named pipe, or use an application like PuTTY.
```suggestion
> You can write your own application to access the named pipe, or use an application like PuTTY.
```

2021-12-18 05:54 UTC, JohanFreelancer9 requested changes
Copy review - @zanedp, kindly commit the suggested change to correct the typo. Many thanks.

2021-12-20 16:13 UTC, opbld31 commented
Docs Build status updates of commit _[57953a5](https://github.com/zanedp/windows-powershell-docs/commits/57953a5064e851e9d487e4671c569e0ce5b6616b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112201606153082-2806%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-20T16%3A13%3A28Z&sr=b&sp=r&sig=7ytkiGlINfO%2FSFF6FQdWZGKZkjrXiIOvlcfa8TzF9Fk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-21 03:09 UTC, JohanFreelancer9 approved these changes

2022-08-17 15:57 UTC, dariomws requested changes

2022-08-17 15:57 UTC, dariomws commented on docset/winserver2022-ps/hyper-v/Set-VMComPort.md
> +> You can write your own application to access the named pipe, or use an application like PuTTY.
```suggestion
> This does not create the named pipe on the local computer. You can write your own application to access the named pipe, or use a third-party application.
```

2022-08-18 12:02 UTC, get-itips requested changes

2022-08-18 12:04 UTC, get-itips commented
@zanedp please choose one of the two suggestions to replace actual application names, thank you!

2022-08-22 20:39 UTC, opbld32 commented
Docs Build status updates of commit _[bf5eaf1](https://github.com/zanedp/windows-powershell-docs/commits/bf5eaf167c04572acd303a66af456e491a4754f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208222032133449-2806/BuildReport?accessString=7a90c254ecc98eb6da4db841e4c6fc86a6ef62b1ce31c1e7e55474e03b60aa8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 20:47 UTC, opbld30 commented
Docs Build status updates of commit _[cc47ef2](https://github.com/zanedp/windows-powershell-docs/commits/cc47ef2da4ef9d9929bb9cae78c32eec7ab54030)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208222033156303-2806/BuildReport?accessString=d80204ded54bc7628526453fdec9c592583fa0fe3c2abf8f15b973fab8ce4428).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-23 05:24 UTC, tseward approved these changes

2022-08-23 13:25 UTC, dariomws approved these changes

2022-09-29 21:51 UTC, opbld30 commented
Learn Build status updates of commit _[38283a5](https://github.com/zanedp/windows-powershell-docs/commits/38283a56b4307b1faa4d39ede7123e1075c4388c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202209292143401587-2806/BuildReport?accessString=5f993c2707b5cbfbedbe63bbf18e1c743b20ca29f5266e72f68ef18ee8256bae).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-12 04:48 UTC, opbld30 commented
Learn Build status updates of commit _[871db22](https://github.com/zanedp/windows-powershell-docs/commits/871db2275f872fe04643a493ba203eceb22c9c49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202210120440356869-2806/BuildReport?accessString=09e4d5d7e2afb7b54c8e6e2802d3c039fe9b94c0faea7479ceaa159027ceda85).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-04 03:42 UTC, opbld33 commented
Learn Build status updates of commit _[39060fc](https://github.com/zanedp/windows-powershell-docs/commits/39060fc6d8f14fa93f02737c1db09b39055ff08a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Set-VMComPort.md](https://github.com/zanedp/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Set-VMComPort.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/hyper-v/set-vmcomport?view=windowsserver2022-ps&branch=pr-en-us-2806) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202212040334398657-2806/BuildReport?accessString=851473395c1380f644260451b6655fd2e22193d46fe44a8eb24ccc53fbcefc6a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-10-02 05:25 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 20:59 UTC, merged