Update Get-ADGroup.md
MicrosoftDocs/windows-powershell-docs pull request #2812
Opened 2021-12-19 02:27 UTC by msbemba

Canonical name is not accepted value for identity parameter in get-adgroup

2021-12-19 02:28 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-19 02:29 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2021-12-19 02:29 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2680

2021-12-19 02:36 UTC, opbld30 commented
Docs Build status updates of commit _[47d2074](https://github.com/msbemba/windows-powershell-docs/commits/47d20740aa47f720daafa0e7e960e163947ca0f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190227555888-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T02%3A36%3A09Z&sr=b&sp=r&sig=YWk03G%2F1QhBeGXr6dsBuBjgjZf4Xl9SVk2DGb6hhoJU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 02:42 UTC, opbld33 commented
Docs Build status updates of commit _[2238fe5](https://github.com/msbemba/windows-powershell-docs/commits/2238fe52f486c216b7928648820e0a53bbccaea8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012-ps&branch=pr-en-us-2812) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012r2-ps&branch=pr-en-us-2812) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2016-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2016-ps&branch=pr-en-us-2812) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2022-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps&branch=pr-en-us-2812) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190229278017-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T02%3A42%3A32Z&sr=b&sp=r&sig=HMbkNEuAf0Fa0De%2BqSdyea0F3Zk5ef4ov5vWtTUmSh8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 03:07 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Get-ADGroup.md
> +You can identify a group by its distinguished name (DN), GUID, security identifier (SID), Security Accounts Manager (SAM) account name.
```suggestion
You can identify a group by its distinguished name (DN), GUID, security identifier (SID), or Security Accounts Manager (SAM) account name.
```

2021-12-19 03:07 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md
> +You can identify a group by its distinguished name (DN), GUID, security identifier (SID), Security Accounts Manager (SAM) account name.
```suggestion
You can identify a group by its distinguished name (DN), GUID, security identifier (SID), or Security Accounts Manager (SAM) account name.
```

2021-12-19 03:07 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/activedirectory/Get-ADGroup.md
> +You can identify a group by its distinguished name (DN), GUID, security identifier (SID), Security Accounts Manager (SAM) account name.
```suggestion
You can identify a group by its distinguished name (DN), GUID, security identifier (SID), or Security Accounts Manager (SAM) account name.
```

2021-12-19 03:08 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/activedirectory/Get-ADGroup.md
> +You can identify a group by its distinguished name (DN), GUID, security identifier (SID), Security Accounts Manager (SAM) account name.
```suggestion
You can identify a group by its distinguished name (DN), GUID, security identifier (SID), or Security Accounts Manager (SAM) account name.
```

2021-12-19 03:08 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/activedirectory/Get-ADGroup.md
> +You can identify a group by its distinguished name (DN), GUID, security identifier (SID), Security Accounts Manager (SAM) account name.
```suggestion
You can identify a group by its distinguished name (DN), GUID, security identifier (SID), or Security Accounts Manager (SAM) account name.
```

2021-12-19 03:08 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-19 03:34 UTC, opbld31 commented
Docs Build status updates of commit _[f498351](https://github.com/msbemba/windows-powershell-docs/commits/f498351cfffaa057d0c4cbe39d26ed5bfc2466d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012-ps&branch=pr-en-us-2812) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012r2-ps&branch=pr-en-us-2812) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2016-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2016-ps&branch=pr-en-us-2812) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2022-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps&branch=pr-en-us-2812) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190328215221-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T03%3A34%3A06Z&sr=b&sp=r&sig=Cq3CUxDPbbxPTRLwy7hq4yKCN3qRUm6iPnn%2FWBmIFE8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 03:34 UTC, opbld32 commented
Docs Build status updates of commit _[331f12e](https://github.com/msbemba/windows-powershell-docs/commits/331f12e7d9cca15c3ca03ccdb06053d272666741)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012-ps&branch=pr-en-us-2812) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012r2-ps&branch=pr-en-us-2812) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2016-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2016-ps&branch=pr-en-us-2812) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2022-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps&branch=pr-en-us-2812) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190328171461-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T03%3A34%3A27Z&sr=b&sp=r&sig=uax00IHnbnLtf%2BqZBcnqbt9zxKpwhzOtZXDLLia2jZ0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 03:35 UTC, opbld31 commented
Docs Build status updates of commit _[377e503](https://github.com/msbemba/windows-powershell-docs/commits/377e5037ac1c2bccbc6bcab1c165de81369df59e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012-ps&branch=pr-en-us-2812) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012r2-ps&branch=pr-en-us-2812) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2016-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2016-ps&branch=pr-en-us-2812) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2022-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps&branch=pr-en-us-2812) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190328381955-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T03%3A35%3A33Z&sr=b&sp=r&sig=EnKZZvpErMAuXQB5GqxYEHgz0s7r1k422jYBtTHmHoY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 03:40 UTC, opbld33 commented
Docs Build status updates of commit _[5e1c5af](https://github.com/msbemba/windows-powershell-docs/commits/5e1c5afb4fd10366c2dec2c1da5e4134ea517092)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012-ps&branch=pr-en-us-2812) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012r2-ps&branch=pr-en-us-2812) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2016-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2016-ps&branch=pr-en-us-2812) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2022-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps&branch=pr-en-us-2812) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112190330081052-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-19T03%3A40%3A40Z&sr=b&sp=r&sig=YyIQa%2FBcNOf4oayOXfK43dKuY4cqPFcRiTAjIEEQLIo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-19 05:21 UTC, JohanFreelancer9 approved these changes

2021-12-27 14:53 UTC, get-itips approved these changes

2021-12-27 19:59 UTC, tseward approved these changes

2021-12-27 21:26 UTC, dariomws approved these changes

2022-01-04 17:11 UTC, opbld32 commented
Docs Build status updates of commit _[4e4367b](https://github.com/msbemba/windows-powershell-docs/commits/4e4367b1251e97b9173532dcc8657c738cdcbbbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012-ps&branch=pr-en-us-2812) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2012r2-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=winserver2012r2-ps&branch=pr-en-us-2812) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2016-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2016-ps&branch=pr-en-us-2812) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2019-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2019-ps&branch=pr-en-us-2812) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADGroup.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-129/docset/winserver2022-ps/activedirectory/Get-ADGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adgroup?view=windowsserver2022-ps&branch=pr-en-us-2812) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201041705442521-2812%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T17%3A11%3A54Z&sr=b&sp=r&sig=Wk303NH2PvsIk3OwI7uiz4vXeFlVV%2FIHdsm8vSX9ixU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 17:18 UTC, merged