Update New-AdfsAccessControlPolicy.md
MicrosoftDocs/windows-powershell-docs pull request #2817
Opened 2021-12-19 03:03 UTC by msbemba

added instructions to get the XML file

2021-12-19 03:03 UTC, msbemba commented
issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2784

2021-12-19 03:08 UTC, opbld30 commented
Docs Build status updates of commit _[be83e4b](https://github.com/msbemba/windows-powershell-docs/commits/be83e4b176e13d1d197b209f6ebf988c3c012863)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-b4d4a0b5cbc26638849c6706f0c3ee1e-d800cc2e)
[docset/winserver2019-ps/activedirectory/Get-ADReplicationSite.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/Get-ADReplicationSite.yml) | :warning:Warning | | [Details](#user-content-40c866eab1e0e4374d0c9eb5b765ffdb-d800cc2e)
[docset/winserver2019-ps/activedirectory/Remove-ADReplicationSite.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/Remove-ADReplicationSite.yml) | :warning:Warning | | [Details](#user-content-4b797e3a008aeae9c646e4028dcd12ba-d800cc2e)
[docset/winserver2019-ps/adfs/New-AdfsOrganization.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsOrganization.yml) | :warning:Warning | | [Details](#user-content-862b9d3df6e39fe491b9bd72f04438fe-d800cc2e)
[docset/winserver2019-ps/adfs/Remove-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-0aa02919d3556ed87074a8db3ccff747-d800cc2e)
[docset/winserver2019-ps/adfs/Get-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-080bee8b3ac8538f6f0ca9f963bd99b1-d800cc2e)
[docset/winserver2019-ps/activedirectory/New-ADReplicationSite.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/New-ADReplicationSite.yml) | :warning:Warning | | [Details](#user-content-96c5bddfaeb5c6689dc0ba2ca7838458-d800cc2e)
[docset/winserver2019-ps/adfs/Enable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Enable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-182673a13d09d81e1dfbba7923f9702f-d800cc2e)
[docset/winserver2019-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.yml) | :warning:Warning | | [Details](#user-content-efda79a51b124d9380716c04fe117bf1-d800cc2e)
[docset/winserver2019-ps/adfs/Add-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-cebe478e7b56ce6f4d32cbb1db90c012-d800cc2e)
[docset/winserver2019-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-cab5f028e711d97bc48494b6c18e4c50-d800cc2e)
[docset/winserver2019-ps/adfs/Remove-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-421b2b43a2ca771218f7b8cb07a718d9-d800cc2e)
[docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-374ea99e762f40c3928f7fd69cd1dcba-d800cc2e)
[docset/winserver2019-ps/adfs/Remove-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-d9e03ed17dc499f4b14c762a1ae495e7-d800cc2e)
[docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-4341920a1d99a8af0aff051e0e8fadab-d800cc2e)
[docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-b8b9b62ef36528d5b9d8cbb35c9c51ea-d800cc2e)
[docset/winserver2019-ps/adfs/Enable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-1ae5645ea7cd0b6095fb18ef29ec7ff0-d800cc2e)
[docset/winserver2019-ps/adfs/Add-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-cdcd147d0339d2cb39848c600335a2a8-d800cc2e)
[docset/winserver2019-ps/adfs/Get-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-29157833e561a7c0f37d4f62a0517a86-d800cc2e)
[docset/winserver2019-ps/adfs/Disable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-5939dbac3142e6c6f2496c42710216ec-d800cc2e)
[docset/winserver2019-ps/adfs/Enable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Enable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-9c0259ca397d0a44b080ab37403e25e7-d800cc2e)
[docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-10b4f4014a9773412ee7714e38ad818c-d800cc2e)
[docset/winserver2019-ps/adfs/Add-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-c45de574e1e299a04762e15e18fb4416-d800cc2e)
[docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-b66bcf3a26e755e735f517728756bcbb-d800cc2e)
[docset/winserver2019-ps/adfs/Get-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-33f3811a00a079fa62877e333d75af3b-d800cc2e)
[docset/winserver2019-ps/addsdeployment/Test-ADDSDomainControllerUninstallation.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/addsdeployment/Test-ADDSDomainControllerUninstallation.yml) | :warning:Warning | | [Details](#user-content-6ffdd479f0109f150cd3961db2fff7e2-d800cc2e)
[docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-d6982a5f068ae5e184393875085cef2b-d800cc2e)
[d [...]

2021-12-19 03:12 UTC, opbld33 commented
Docs Build status updates of commit _[174d3b1](https://github.com/msbemba/windows-powershell-docs/commits/174d3b14e13146ab56c619c7cc97cea64a9648c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-13945a4eae92c419115685cdf6a91a17-fe5e8282)
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-b4d4a0b5cbc26638849c6706f0c3ee1e-fe5e8282)
[docset/winserver2019-ps/adfs/Add-AdfsFarmNode.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-abd7670f423c7151ec84f360ce9f1599-fe5e8282)
[docset/winserver2019-ps/adfs/Add-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsAttributeStore.yml) | :warning:Warning | | [Details](#user-content-251f1d9683e6c9b2a0f78767c7470dce-fe5e8282)
[docset/winserver2019-ps/adfs/Add-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-cebe478e7b56ce6f4d32cbb1db90c012-fe5e8282)
[docset/winserver2016-ps/appvclient/Disable-AppvClientConnectionGroup.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/appvclient/Disable-AppvClientConnectionGroup.yml) | :warning:Warning | | [Details](#user-content-32a17a59a5ae3b8d560d208d66d5ed0b-fe5e8282)
[docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-374ea99e762f40c3928f7fd69cd1dcba-fe5e8282)
[docset/winserver2019-ps/adfs/Get-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-33f3811a00a079fa62877e333d75af3b-fe5e8282)
[docset/winserver2016-ps/appvclient/Enable-AppvClientConnectionGroup.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/appvclient/Enable-AppvClientConnectionGroup.yml) | :warning:Warning | | [Details](#user-content-bfe57ed77a694076e2a27fca943b9b02-fe5e8282)
[docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-4341920a1d99a8af0aff051e0e8fadab-fe5e8282)
[docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-b8b9b62ef36528d5b9d8cbb35c9c51ea-fe5e8282)
[docset/winserver2019-ps/adfs/Enable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-1ae5645ea7cd0b6095fb18ef29ec7ff0-fe5e8282)
[docset/winserver2019-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-cab5f028e711d97bc48494b6c18e4c50-fe5e8282)
[docset/winserver2019-ps/adfs/Remove-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-0aa02919d3556ed87074a8db3ccff747-fe5e8282)
[docset/winserver2019-ps/adfs/Get-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-080bee8b3ac8538f6f0ca9f963bd99b1-fe5e8282)
[docset/winserver2016-ps/appx/Add-AppxPackage.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/appx/Add-AppxPackage.yml) | :warning:Warning | | [Details](#user-content-c22a6c97e176342699bc77d67dbff827-fe5e8282)
[docset/winserver2016-ps/branchcache/Get-BCDataCacheExtension.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/branchcache/Get-BCDataCacheExtension.yml) | :warning:Warning | | [Details](#user-content-4047ca792fae36c2a85600ad902f78db-fe5e8282)
[docset/winserver2016-ps/branchcache/Get-BCHostedCacheServerConfiguration.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/branchcache/Get-BCHostedCacheServerConfiguration.yml) | :warning:Warning | | [Details](#user-content-887abd576bea7dd3569ec3938806c2ba-fe5e8282)
[docset/winserver2019-ps/adfs/Disable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-5939dbac3142e6c6f2496c42710216ec-fe5e8282)
[docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-10b4f4014a9773412ee7714e38ad818c-fe5e8282)
[docset/winserver2019-ps/adcsdeployment/Uninstall-AdcsEnrollmentPolicyWebService.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adcsdeployment/Uninstall-AdcsEnrollmentPolicyWebService.yml) | :warning:Warning | | [Details](#user-content-7c45193da21ee1e1b96f57afc300f328-fe5e8282)
[docset/winserver2016-ps/appx/Get-AppxPackage.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/appx/Get-AppxPackage.yml) | :warning:Warning | | [Details](#user-content-7380915215457e6c96e5105529c4f831-fe5e8282)
[docset/winserver2016-ps/bestpractices/Invoke-BpaModel.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/bestpractices/Invoke-BpaModel.yml) | :warning:Warning | | [Details](#user-content-0db40097d41d805f887a3528c1b005c8-fe5e8282)
[docset/winserver2016-ps/bitlocker/Disable-BitLockerAutoUnlock.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/bitlocker/Disable-BitLockerAutoUnlock.yml) | :warning:Warning | | [Details](#user-content-ea7bab5daa786ffc5dc72700204ceb22-fe5e8282)
[docset/winserver2016-ps/bitlocker/Disable-BitLocker.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/bitlocker/Disable-BitLocker.yml) | :warning:Warning | | [Details](#user-content-f93ed3b10e512656cb97e6d49b51bc85-fe5e8282)
[docset/winserver2016-ps/appx/Get-AppxLastError.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/appx/Get-AppxLastError.yml) | :warning:Warning | | [Details](#user-content-32f93ce341db9141f5766fbdd401ba3f-fe5e8282)
[docset/winserver2016-ps/bitlocker/Suspend-BitLocker.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/bitlocker/Suspend-BitLocker.yml) | :warning:Warning | | [Details](#user-content-4d5b9b6b9828a5034cca01168ad97283-fe5e8282)
[docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershe [...]

2021-12-19 06:06 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md
> +## How to create a Federation metadata file?
```suggestion
## How to create a Federation metadata file
```

2021-12-19 06:13 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md
> +The federation metadata document is a XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata).Enter in your federation service name and click
****
```suggestion
The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). Enter your federation service name and select the **Get federation metadata** button to retrieve your document.
```

2021-12-19 06:14 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md
> +## How to create a Federation metadata file?
```suggestion
## How to create a Federation metadata file?
```
```suggestion
## How to create a federation metadata file
```

2021-12-19 06:15 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md
> +The federation metadata document is a XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata).Enter in your federation service name and click
```suggestion
The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). Enter your federation service name and select the **Get federation metadata** button to retrieve your document.
```

2021-12-19 06:15 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md
> +## How to create a Federation metadata file?
```suggestion
## How to create a federation metadata file
```

2021-12-19 06:16 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md
> +The federation metadata document is a XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata).Enter in your federation service name and click
```suggestion
The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). Enter your federation service name and select the **Get federation metadata** button to retrieve your document.
```

2021-12-19 06:17 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-19 06:40 UTC, opbld31 commented
Docs Build status updates of commit _[9c0a1bf](https://github.com/msbemba/windows-powershell-docs/commits/9c0a1bf5d3d898e24987b967637408aeadfa47c0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-13945a4eae92c419115685cdf6a91a17-6dd4ae6d)
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-b4d4a0b5cbc26638849c6706f0c3ee1e-6dd4ae6d)
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-7512a94902e53896e8c46abcc282471e-6dd4ae6d)
[docset/winserver2019-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-08c0047a49fcfd0a16c04c49248fa845-6dd4ae6d)
[docset/winserver2016-ps/adfs/Remove-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Remove-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-8ec9342852b05898db48ae8faefc4a88-6dd4ae6d)
[docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-07e9b0474e1ecfcfab4cb34ee32bdd30-6dd4ae6d)
[docset/winserver2022-ps/adfs/Remove-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-0cc93f31160c08fa9b0e4720f287dce9-6dd4ae6d)
[docset/winserver2016-ps/adfs/Add-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Add-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-706aad643874e46e0087dc4e77add76a-6dd4ae6d)
[docset/winserver2019-ps/adfs/Remove-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-7f12e65456b248a951238104dd6aed72-6dd4ae6d)
[docset/winserver2019-ps/adfs/Remove-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-0aa02919d3556ed87074a8db3ccff747-6dd4ae6d)
[docset/winserver2016-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-9a707e5a5e41a68e1b436441ef65a371-6dd4ae6d)
[docset/winserver2022-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-c733847391702a328bed5e316d1f6463-6dd4ae6d)
[docset/winserver2016-ps/adfs/Remove-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Remove-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-72e0b6076183f1fcf375270cb142c8ad-6dd4ae6d)
[docset/winserver2016-ps/adfs/Get-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Get-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-b884f0f757c50d3cb9e9c83938b57246-6dd4ae6d)
[docset/winserver2019-ps/adfs/Add-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-c45de574e1e299a04762e15e18fb4416-6dd4ae6d)
[docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-d6982a5f068ae5e184393875085cef2b-6dd4ae6d)
[docset/winserver2022-ps/adfs/Remove-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-321e79c40c722e8ca1970c19db0fc23b-6dd4ae6d)
[docset/winserver2022-ps/adfs/Enable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Enable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-257b99ce64759e02bc52b2ffcc261f6c-6dd4ae6d)
[docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-374ea99e762f40c3928f7fd69cd1dcba-6dd4ae6d)
[docset/winserver2022-ps/adfs/Add-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-d23b1488cf35948380322657d16cac41-6dd4ae6d)
[docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-10b4f4014a9773412ee7714e38ad818c-6dd4ae6d)
[docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-4341920a1d99a8af0aff051e0e8fadab-6dd4ae6d)
[docset/winserver2019-ps/adfs/New-AdfsOrganization.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsOrganization.yml) | :warning:Warning | | [Details](#user-content-862b9d3df6e39fe491b9bd72f04438fe-6dd4ae6d)
[docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-b66bcf3a26e755e735f517728756bcbb-6dd4ae6d)
[docset/winserver2022-ps/adfs/Remove-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-2fec4cc1b1e7607095ab46d0fc614992-6dd4ae6d)
[docset/winserver2019-ps/adfs/Add-AdfsFarmNode.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-abd7670f423c7151ec84f360ce9f1599-6dd4ae6d)
[docset/winserver2022-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-28e622191a9d501ecdbd2f0faab8a992-6dd4ae6d)
[docset/winserver2022-ps/adfs/Remove-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsAttributeStore.yml) | [...]

2021-12-19 06:41 UTC, opbld33 commented
Docs Build status updates of commit _[b49cfed](https://github.com/msbemba/windows-powershell-docs/commits/b49cfed9270824f6f070279e3da99f2acbcdffaa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-13945a4eae92c419115685cdf6a91a17-0b378765)
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-b4d4a0b5cbc26638849c6706f0c3ee1e-0b378765)
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-7512a94902e53896e8c46abcc282471e-0b378765)
[docset/winserver2016-ps/adfs/Remove-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Remove-AdfsAttributeStore.yml) | :warning:Warning | | [Details](#user-content-189073a5625cf49ee9d9237d4a34550b-0b378765)
[docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-b8b9b62ef36528d5b9d8cbb35c9c51ea-0b378765)
[docset/winserver2022-ps/adfs/Set-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Set-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-1d180d293992a1ef74d210cdabd8f0a1-0b378765)
[docset/winserver2016-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-c90a2cfc8791962c7d708cd60db99eba-0b378765)
[docset/winserver2016-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-19894852e6467a91a3c2d124b43937f7-0b378765)
[docset/winserver2016-ps/adfs/Enable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-a7d19ef2636bbda2ada89c803803526c-0b378765)
[docset/winserver2016-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-03ba68223bc8bfadd644814b5d240129-0b378765)
[docset/winserver2016-ps/adfs/Get-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Get-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-5ba9ef60f075d0c28f9e1e9b230a5e2c-0b378765)
[docset/winserver2022-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-c369c66f72b94d1d1c6328d8b9312754-0b378765)
[docset/winserver2022-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-d0785d07d7afc8f8e3f7b9000b2db6b1-0b378765)
[docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-07e9b0474e1ecfcfab4cb34ee32bdd30-0b378765)
[docset/winserver2019-ps/adfs/Set-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Set-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-93dfa3380a1d01282b84901e496f0e90-0b378765)
[docset/winserver2022-ps/adfs/Enable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-30d06c713834a9d42cd1b8c09883a3bd-0b378765)
[docset/winserver2022-ps/adfs/Get-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-657213c638da8daf577418d1177a5ca2-0b378765)
[docset/winserver2016-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-9a707e5a5e41a68e1b436441ef65a371-0b378765)
[docset/winserver2022-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-acc57a009f1bb51ca7c311d346fbf91b-0b378765)
[docset/winserver2016-ps/adfs/Get-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Get-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-91ae79e9c7ab3c010b0a7a7ff2e4c8ba-0b378765)
[docset/winserver2016-ps/adfs/Add-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Add-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-7d9928690cb8e6126094fb9e0f3970a3-0b378765)
[docset/winserver2016-ps/adfs/Disable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Disable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-52a9f58755ec0b583e9a0f317db6ca83-0b378765)
[docset/winserver2016-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-22a5ca1fe0a3bf55830ce5997c0d13a7-0b378765)
[docset/winserver2016-ps/adfs/New-AdfsOrganization.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsOrganization.yml) | :warning:Warning | | [Details](#user-content-133d28f180ffd5cf6ead8c8059c0882a-0b378765)
[docset/winserver2022-ps/adfs/Disable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Disable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-6478b9785a480d1d65734ad93b91839c-0b378765)
[docset/winserver2022-ps/adfs/New-AdfsOrganization.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsOrganization.yml) | :warning:Warning | | [Details](#user-content-2c185d949c119b893faf916d037bfc45-0b378765)
[docset/winserver2022-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-c733847391702a328bed5e316d1f6463-0b378765)
[docset/winserver2019-ps/adfs/Add-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-ce [...]

2021-12-19 06:43 UTC, opbld31 commented
Docs Build status updates of commit _[199802f](https://github.com/msbemba/windows-powershell-docs/commits/199802fa7c0bbb2dcfc850b467c0b7e8c622f33a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-13945a4eae92c419115685cdf6a91a17-36d85a7b)
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-b4d4a0b5cbc26638849c6706f0c3ee1e-36d85a7b)
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-7512a94902e53896e8c46abcc282471e-36d85a7b)
[docset/winserver2022-ps/appvclient/Mount-AppvClientPackage.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/appvclient/Mount-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-6f6a31fcabe8971f2e8288dfe77ef19e-36d85a7b)
[docset/winserver2022-ps/appvclient/Mount-AppvClientConnectionGroup.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/appvclient/Mount-AppvClientConnectionGroup.yml) | :warning:Warning | | [Details](#user-content-5fe1b89fd71e92706289062407dd3890-36d85a7b)
[docset/winserver2022-ps/appvclient/Add-AppvClientPackage.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/appvclient/Add-AppvClientPackage.yml) | :warning:Warning | | [Details](#user-content-02f4bceb28751456ff37a9bfcd02a69c-36d85a7b)
[docset/winserver2016-ps/adrmsadmin/Get-RmsCertChain.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adrmsadmin/Get-RmsCertChain.yml) | :warning:Warning | | [Details](#user-content-cffed085797b040bd8048e1de2411dba-36d85a7b)
[docset/winserver2016-ps/adfs/Add-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Add-AdfsAttributeStore.yml) | :warning:Warning | | [Details](#user-content-9d6240f4fa6861202fe3eac750f2cbb3-36d85a7b)
[docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-374ea99e762f40c3928f7fd69cd1dcba-36d85a7b)
[docset/winserver2022-ps/adrmsadmin/Get-RmsEncryptedIL.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Get-RmsEncryptedIL.yml) | :warning:Warning | | [Details](#user-content-ac450d7c13e0d4350d2197d25160e8ab-36d85a7b)
[docset/winserver2019-ps/adfs/Disable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-5939dbac3142e6c6f2496c42710216ec-36d85a7b)
[docset/winserver2019-ps/adfs/New-AdfsOrganization.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsOrganization.yml) | :warning:Warning | | [Details](#user-content-862b9d3df6e39fe491b9bd72f04438fe-36d85a7b)
[docset/winserver2019-ps/adfs/Remove-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Remove-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-d9e03ed17dc499f4b14c762a1ae495e7-36d85a7b)
[docset/winserver2022-ps/appvclient/index.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/appvclient/index.yml) | :warning:Warning | | [Details](#user-content-c531f7447ddf522d1ad39703a0325545-36d85a7b)
[docset/winserver2022-ps/adrmsadmin/Get-RmsChildCert.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Get-RmsChildCert.yml) | :warning:Warning | | [Details](#user-content-7ac764d6c30d18c25f8475852558e883-36d85a7b)
[docset/winserver2016-ps/adfs/Remove-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Remove-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-9f3be5430ea7938c3f4f75062bf29b06-36d85a7b)
[docset/winserver2019-ps/adfs/Enable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-1ae5645ea7cd0b6095fb18ef29ec7ff0-36d85a7b)
[docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-b8b9b62ef36528d5b9d8cbb35c9c51ea-36d85a7b)
[docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-b66bcf3a26e755e735f517728756bcbb-36d85a7b)
[docset/winserver2022-ps/appx/index.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/appx/index.yml) | :warning:Warning | | [Details](#user-content-dd7c41c5a14d04f225206d87f22f9547-36d85a7b)
[docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-4341920a1d99a8af0aff051e0e8fadab-36d85a7b)
[docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-d6982a5f068ae5e184393875085cef2b-36d85a7b)
[docset/winserver2016-ps/adfs/Remove-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Remove-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-8ec9342852b05898db48ae8faefc4a88-36d85a7b)
[docset/winserver2022-ps/adrmsadmin/Get-RmsUserRequestReport.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Get-RmsUserRequestReport.yml) | :warning:Warning | | [Details](#user-content-23b3605ea1e0da64b9135b0a9f175059-36d85a7b)
[docset/winserver2016-ps/adfs/Remove-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Remove-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-fee9c4eb21fa01a72f8e284005ae2e86-36d85a7b)
[docset/winserver2016-ps/adfs/Get-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Get-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-91ae79e9c7ab3c010b0a7a7ff2e4c8ba-36d85a7b)
[docset/winserver2016-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-bc1a6068e7a6b01165fe2aa0d2cf2db3-36d85a7b)
[docset/winserver2019-ps/addsdeployment/Install-ADDSDomainController.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/addsdeployment/Install-ADDSDomainContr [...]

2021-12-20 06:44 UTC, JohanFreelancer9 approved these changes

2021-12-27 14:09 UTC, get-itips approved these changes

2021-12-27 14:10 UTC, get-itips commented
@msbemba Please review build errors, the header is not expected, maybe replace with a note.

2021-12-27 20:02 UTC, tseward approved these changes

2021-12-27 21:48 UTC, dariomws approved these changes
@msbemba, as @get-itips suggested, please move it to a note or just another sentence in the description section.

Thanks!

2021-12-27 22:17 UTC, msbemba commented
> @msbemba, as @get-itips suggested, please move it to a note or just another sentence in the description section.
> 
> Thanks!

Thank you. the changes are completed.

2021-12-27 22:20 UTC, opbld31 commented
Docs Build status updates of commit _[493dc36](https://github.com/msbemba/windows-powershell-docs/commits/493dc36ac0056df912ecd5d32a59fdd49ebf7b6a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-b4d4a0b5cbc26638849c6706f0c3ee1e-6ba8010e)
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-7512a94902e53896e8c46abcc282471e-6ba8010e)
[docset/winserver2019-ps/activedirectory/Get-ADReplicationSiteLink.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/Get-ADReplicationSiteLink.yml) | :warning:Warning | | [Details](#user-content-843c680df2064324ca5eed2566d553ce-6ba8010e)
[docset/winserver2019-ps/activedirectory/Remove-ADReplicationSiteLink.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/Remove-ADReplicationSiteLink.yml) | :warning:Warning | | [Details](#user-content-586a7bedd785c246b1c15096c9ab115a-6ba8010e)
[docset/winserver2019-ps/activedirectory/Remove-ADReplicationSubnet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/Remove-ADReplicationSubnet.yml) | :warning:Warning | | [Details](#user-content-adf60f66a362e98c8a1153b9496ec48d-6ba8010e)
[docset/winserver2019-ps/activedirectory/New-ADReplicationSubnet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/New-ADReplicationSubnet.yml) | :warning:Warning | | [Details](#user-content-59c0799251f6165ed1a0b52c603cfd63-6ba8010e)
[docset/winserver2019-ps/activedirectory/New-ADReplicationSiteLink.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/New-ADReplicationSiteLink.yml) | :warning:Warning | | [Details](#user-content-f56051d2fe2e7ec0cf5699621c8b6558-6ba8010e)
[docset/winserver2019-ps/adfs/Get-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-33f3811a00a079fa62877e333d75af3b-6ba8010e)
[docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-07e9b0474e1ecfcfab4cb34ee32bdd30-6ba8010e)
[docset/winserver2022-ps/adrms/Uninstall-ADRMS.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrms/Uninstall-ADRMS.yml) | :warning:Warning | | [Details](#user-content-903d163de4e7d6cb69ce3bafd22e5afa-6ba8010e)
[docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-10b4f4014a9773412ee7714e38ad818c-6ba8010e)
[docset/winserver2022-ps/adfs/Get-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-108ff9a658c73bd8a0efa9af50a90992-6ba8010e)
[docset/winserver2019-ps/activedirectory/Get-ADReplicationSubnet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/activedirectory/Get-ADReplicationSubnet.yml) | :warning:Warning | | [Details](#user-content-986ffcc7835efe2f1a56aad175bbea8f-6ba8010e)
[docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-4341920a1d99a8af0aff051e0e8fadab-6ba8010e)
[docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-d6982a5f068ae5e184393875085cef2b-6ba8010e)
[docset/winserver2019-ps/adfs/Get-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Get-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-29157833e561a7c0f37d4f62a0517a86-6ba8010e)
[docset/winserver2019-ps/adfs/Add-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Add-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-c45de574e1e299a04762e15e18fb4416-6ba8010e)
[docset/winserver2022-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-acc57a009f1bb51ca7c311d346fbf91b-6ba8010e)
[docset/winserver2022-ps/adfs/Remove-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-0cc93f31160c08fa9b0e4720f287dce9-6ba8010e)
[docset/winserver2019-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-cab5f028e711d97bc48494b6c18e4c50-6ba8010e)
[docset/winserver2022-ps/adrmsadmin/Get-RmsSystemHealthReport.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Get-RmsSystemHealthReport.yml) | :warning:Warning | | [Details](#user-content-3c99d14a9ad031e5db7528407182d4da-6ba8010e)
[docset/winserver2022-ps/adrmsadmin/Export-RmsReportDefinitionLanguage.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Export-RmsReportDefinitionLanguage.yml) | :warning:Warning | | [Details](#user-content-a44c7705c68381d7d8c50d19a6a9438c-6ba8010e)
[docset/winserver2022-ps/adrmsadmin/Export-RmsTPD.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Export-RmsTPD.yml) | :warning:Warning | | [Details](#user-content-15fe75d9502910425e91d99272432fcf-6ba8010e)
[docset/winserver2022-ps/adrmsadmin/Uninstall-RmsMfgEnrollment.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adrmsadmin/Uninstall-RmsMfgEnrollment.yml) | :warning:Warning | | [Details](#user-content-517803cb6939a64f2b8d2b66a872546d-6ba8010e)
[docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-b66bcf3a26e755e735f517728756bcbb-6ba8010e)
[docset/winserver2022-ps/adfs/Update-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Update-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-97693e1b3b00643a84c43c5d5498d53c-6ba8010e)
[docset/winserver2022-ps/adfs/Enable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Enable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-257b99ce64759e0 [...]

2021-12-27 22:27 UTC, opbld31 commented
Docs Build status updates of commit _[ace6789](https://github.com/msbemba/windows-powershell-docs/commits/ace6789d1e248d72168ba282a8a96c6de56fb2d2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :x:Error | | [Details](#user-content-7512a94902e53896e8c46abcc282471e-18305952)
[docset/winserver2022-ps/adfs/Disable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Disable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-c369c66f72b94d1d1c6328d8b9312754-18305952)
[docset/winserver2022-ps/adfs/Add-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsAttributeStore.yml) | :warning:Warning | | [Details](#user-content-3449e973ec4aa64f0214974223a87e85-18305952)
[docset/winserver2022-ps/adfs/Disable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Disable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-2aba2f1f49cf434675dc4b1c900d595e-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsAttributeStore.yml) | :warning:Warning | | [Details](#user-content-f4dd2d0a27c3c1796e3c7c19e8a26418-18305952)
[docset/winserver2022-ps/adfs/New-AdfsContactPerson.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsContactPerson.yml) | :warning:Warning | | [Details](#user-content-c733847391702a328bed5e316d1f6463-18305952)
[docset/winserver2022-ps/adfs/Enable-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Enable-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-335ffd4abc989f8199203f15f9e083f5-18305952)
[docset/winserver2022-ps/adfs/Enable-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Enable-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-257b99ce64759e02bc52b2ffcc261f6c-18305952)
[docset/winserver2022-ps/adfs/Add-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-42220d78cda967c0b896d7c4e04ae9b9-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsClaimDescription.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsClaimDescription.yml) | :warning:Warning | | [Details](#user-content-d0785d07d7afc8f8e3f7b9000b2db6b1-18305952)
[docset/winserver2022-ps/adfs/Enable-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Enable-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-30d06c713834a9d42cd1b8c09883a3bd-18305952)
[docset/winserver2022-ps/adfs/New-AdfsOrganization.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsOrganization.yml) | :warning:Warning | | [Details](#user-content-2c185d949c119b893faf916d037bfc45-18305952)
[docset/winserver2022-ps/adfs/Add-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-28e622191a9d501ecdbd2f0faab8a992-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsEndpoint.yml) | :warning:Warning | | [Details](#user-content-657213c638da8daf577418d1177a5ca2-18305952)
[docset/winserver2022-ps/adfs/Remove-AdfsAttributeStore.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsAttributeStore.yml) | :warning:Warning | | [Details](#user-content-f410ae0424ed758732472457b1a5932a-18305952)
[docset/winserver2022-ps/adfs/Remove-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-0cc93f31160c08fa9b0e4720f287dce9-18305952)
[docset/winserver2022-ps/adfs/Add-AdfsClaimsProviderTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsClaimsProviderTrust.yml) | :warning:Warning | | [Details](#user-content-583e1cee6912fc13beedc972809da504-18305952)
[docset/winserver2022-ps/adfs/Add-AdfsFarmNode.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsFarmNode.yml) | :warning:Warning | | [Details](#user-content-eb0a8adb9090dcf073617e7623b7aa67-18305952)
[docset/winserver2022-ps/adfs/Remove-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-321e79c40c722e8ca1970c19db0fc23b-18305952)
[docset/winserver2022-ps/adfs/New-AdfsSamlEndpoint.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsSamlEndpoint.yml) | :warning:Warning | | [Details](#user-content-acc57a009f1bb51ca7c311d346fbf91b-18305952)
[docset/winserver2022-ps/adfs/Add-AdfsRelyingPartyTrust.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Add-AdfsRelyingPartyTrust.yml) | :warning:Warning | | [Details](#user-content-d23b1488cf35948380322657d16cac41-18305952)
[docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsClaimRuleSet.yml) | :warning:Warning | | [Details](#user-content-07e9b0474e1ecfcfab4cb34ee32bdd30-18305952)
[docset/winserver2022-ps/adfs/Remove-AdfsCertificate.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsCertificate.yml) | :warning:Warning | | [Details](#user-content-4fc8b9d10db99e974f9a08e60e3f363b-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsDeviceRegistration.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsDeviceRegistration.yml) | :warning:Warning | | [Details](#user-content-bf1df16d534298a6f743ca6d3b44cd0a-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsRegistrationHosts.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsRegistrationHosts.yml) | :warning:Warning | | [Details](#user-content-d3b829688ef1fbc27bb7a3ac5b6c6846-18305952)
[docset/winserver2022-ps/adfs/Remove-AdfsGlobalWebContent.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Remove-AdfsGlobalWebContent.yml) | :warning:Warning | | [Details](#user-content-f85c462162c6803f122cbc19383ec8a7-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsAuthenticationProviderWebContent.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/Get-AdfsAuthenticationProviderWebContent.yml) | :warning:Warning | | [Details](#user-content-a4099794fbb1ed7e952b213f44dec42e-18305952)
[docset/winserver2022-ps/adfs/Get-AdfsAdditionalAuthenticationRule.yml](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-p [...]

2021-12-28 06:25 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md
> +**How to create a federation metadata file?**
```suggestion
**How to create a federation metadata file**
```

2021-12-28 06:26 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md
> +**How to create a federation metadata file?**
```suggestion
**How to create a federation metadata file**
```

2021-12-28 06:26 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md
> +**How to create a federation metadata file?**
```suggestion
**How to create a federation metadata file**
```

2021-12-28 06:27 UTC, JohanFreelancer9 requested changes
@msbemba, please commit the changes to remove the question marks again. Thanks.

2021-12-28 06:38 UTC, opbld32 commented
Docs Build status updates of commit _[29f001e](https://github.com/msbemba/windows-powershell-docs/commits/29f001e46607e89278854f982184f1b39b1d55e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2016-ps&branch=pr-en-us-2817) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2019-ps&branch=pr-en-us-2817) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2022-ps&branch=pr-en-us-2817) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112280628431031-2817%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T06%3A38%3A03Z&sr=b&sp=r&sig=5B5vSa%2B3nmikBXJgM0a4QfQbsBNfvhwMNWjJfHrMajw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 06:43 UTC, opbld33 commented
Docs Build status updates of commit _[58c8c51](https://github.com/msbemba/windows-powershell-docs/commits/58c8c51c75dcad70635c060a5674af65694526ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2016-ps&branch=pr-en-us-2817) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2019-ps&branch=pr-en-us-2817) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2022-ps&branch=pr-en-us-2817) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C28%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202112280628493757-2817%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-28T06%3A43%3A36Z&sr=b&sp=r&sig=ePImDEDZNXm1Jo1KH5mXpiskCtH9Xw9H1bVlvl4YMis%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-28 09:02 UTC, JohanFreelancer9 approved these changes

2022-01-04 16:13 UTC, tiburd commented on docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md
> +The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). Enter your federation service name and select
```suggestion
The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). To retrieve your document, enter your federation service name, and then select the **Get federation metadata** button.
```

2022-01-04 16:13 UTC, tiburd commented on docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md
> +The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). Enter your federation service name and select
```suggestion
The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). To retrieve your document, enter your federation service name, and then select the **Get federation metadata** button.
```

2022-01-04 16:13 UTC, tiburd commented on docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md
> +The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). Enter your federation service name and select
```suggestion
The federation metadata document is an XML file that is available for [download](https://adfshelp.microsoft.com/MetadataExplorer/GetFederationMetadata). To retrieve your document, enter your federation service name, and then select the **Get federation metadata** button.
```

2022-01-04 16:23 UTC, opbld33 commented
Docs Build status updates of commit _[bd00ec9](https://github.com/msbemba/windows-powershell-docs/commits/bd00ec9800d955752acddf28d93aba9ab7f8195b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2016-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2016-ps&branch=pr-en-us-2817) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2019-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2019-ps&branch=pr-en-us-2817) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-134/docset/winserver2022-ps/adfs/New-AdfsAccessControlPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/new-adfsaccesscontrolpolicy?view=windowsserver2022-ps&branch=pr-en-us-2817) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201041613503459-2817%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T16%3A23%3A20Z&sr=b&sp=r&sig=zMohNyG%2BGq1Dr9mMyl6rjBlw0pUIWcIU5KcBlX99SFQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-04 16:23 UTC, merged