Resolves #2759
MicrosoftDocs/windows-powershell-docs pull request #2831
Opened 2022-01-11 14:20 UTC by velkovb

Correct description.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2759

2022-01-12 10:04 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Get-ADUser.md
> +You can identify a user by its distinguished name (DN), GUID, security identifier (SID) or Security Account Manager (SAM) account name.
```suggestion
You can identify a user by its distinguished name (DN), GUID, security identifier (SID), or Security Account Manager (SAM) account name.
```

2022-01-12 10:04 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/activedirectory/Get-ADUser.md
> +You can identify a user by its distinguished name (DN), GUID, security identifier (SID) or Security Account Manager (SAM) account name.
```suggestion
You can identify a user by its distinguished name (DN), GUID, security identifier (SID), or Security Account Manager (SAM) account name.
```

2022-01-12 10:05 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/activedirectory/Get-ADUser.md
> +You can identify a user by its distinguished name (DN), GUID, security identifier (SID) or Security Account Manager (SAM) account name.
```suggestion
You can identify a user by its distinguished name (DN), GUID, security identifier (SID), or Security Account Manager (SAM) account name.
```

2022-01-12 10:05 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/activedirectory/Get-ADUser.md
> +You can identify a user by its distinguished name (DN), GUID, security identifier (SID) or Security Account Manager (SAM) account name.
```suggestion
You can identify a user by its distinguished name (DN), GUID, security identifier (SID), or Security Account Manager (SAM) account name.
```

2022-01-12 10:07 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/activedirectory/Get-ADUser.md
> +You can identify a user by its distinguished name (DN), GUID, security identifier (SID), Security Account Manager (SAM) account name.
```suggestion
You can identify a user by its distinguished name (DN), GUID, security identifier (SID), or Security Account Manager (SAM) account name.
```

2022-01-12 10:08 UTC, JohanFreelancer9 requested changes
Copy review - please re-insert the Oxford comma.

2022-01-12 10:53 UTC, opbld30 commented
Docs Build status updates of commit _[4ace4c2](https://github.com/velkovb/windows-powershell-docs/commits/4ace4c2cdee7389068314c4a5e0a98e0e85da7ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2759-name-search/docset/winserver2012-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012-ps&branch=pr-en-us-2831) (winserver2012-ps) |
[docset/winserver2012r2-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2759-name-search/docset/winserver2012r2-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=winserver2012r2-ps&branch=pr-en-us-2831) (winserver2012r2-ps) |
[docset/winserver2016-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2759-name-search/docset/winserver2016-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2016-ps&branch=pr-en-us-2831) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2759-name-search/docset/winserver2019-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2019-ps&branch=pr-en-us-2831) (WindowsServer2019-ps) |
[docset/winserver2022-ps/activedirectory/Get-ADUser.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2759-name-search/docset/winserver2022-ps/activedirectory/Get-ADUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-aduser?view=windowsserver2022-ps&branch=pr-en-us-2831) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201121046553904-2831%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T10%3A53%3A18Z&sr=b&sp=r&sig=uvAM0aGRH9W2awmkcquov8SWsKkixOuSBZl4%2BdbHcFc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 11:28 UTC, JohanFreelancer9 approved these changes

2022-01-12 17:55 UTC, get-itips approved these changes

2022-01-13 08:04 UTC, dariomws approved these changes

2022-01-13 20:36 UTC, merged