Resolves #2735
MicrosoftDocs/windows-powershell-docs pull request #2834
Opened 2022-01-12 08:42 UTC by velkovb

Update parameter description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2735

2022-01-12 08:49 UTC, opbld33 commented
Docs Build status updates of commit _[97c88ac](https://github.com/velkovb/windows-powershell-docs/commits/97c88acf014f8fa368759ef6bfb5d4a0611468ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2016-ps&branch=pr-en-us-2834) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2019-ps&branch=pr-en-us-2834) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2022-ps&branch=pr-en-us-2834) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201120842524187-2834%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T08%3A49%3A37Z&sr=b&sp=r&sig=LH2B3DCFg4%2BnRL5%2B38UiVGLHWPcZbesWToUqnDY%2F%2BA4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 11:09 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md
> +Allows to use device authentication as primary for domain joined devices.
```suggestion
Allows the use of device authentication as primary authentication for domain-joined devices.
```

2022-01-12 11:10 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md
> +Allows to use device authentication as primary for domain joined devices.
```suggestion
Allows the use of device authentication as primary authentication for domain-joined devices.

```

2022-01-12 11:11 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md
> +Allows to use device authentication as primary for domain joined devices.
```suggestion
Allows the use of device authentication as primary authentication for domain-joined devices.

```

2022-01-12 11:12 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-12 11:18 UTC, JohanFreelancer9 commented
Apologies Borislav, I've also added the word "method", could you please update? Many thanks.

2022-01-12 11:23 UTC, opbld31 commented
Docs Build status updates of commit _[cb7e57a](https://github.com/velkovb/windows-powershell-docs/commits/cb7e57a9d8da5e10056be3d26ffcaeeffc40ffa0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2016-ps&branch=pr-en-us-2834) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2019-ps&branch=pr-en-us-2834) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2022-ps&branch=pr-en-us-2834) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201121116143929-2834%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T11%3A23%3A19Z&sr=b&sp=r&sig=C2q1SPwuDgzn%2FVE6V5doUaDa4DeQsi0%2B7u%2BQuL1Dj5A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 11:53 UTC, velkovb commented
Not sure if method is the correct word here as it may create confusion. Both in Client and Device parameter method is used to specify the authentication method. Maybe here it is more appropriate to say type?

2022-01-12 12:03 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md
> +Allows the use of device authentication as primary authentication method for domain-joined devices.
```suggestion
Allows the use of device authentication as the primary type for domain-joined devices.
```

2022-01-12 12:03 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md
> +Allows the use of device authentication as primary authentication for domain-joined devices.
```suggestion
Allows the use of device authentication as the primary type for domain-joined devices.
```

2022-01-12 12:04 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md
> +Allows the use of device authentication as primary authentication for domain-joined devices.
```suggestion
Allows the use of device authentication as the primary type for domain-joined devices.
```

2022-01-12 12:05 UTC, JohanFreelancer9 requested changes
@velkovb, please commit the changes if you agree. Thanks for the explanation.

2022-01-12 17:21 UTC, get-itips approved these changes

2022-01-13 03:10 UTC, tseward approved these changes

2022-01-13 16:12 UTC, dariomws approved these changes

2022-01-19 22:36 UTC, opbld32 commented
Docs Build status updates of commit _[7e36638](https://github.com/velkovb/windows-powershell-docs/commits/7e36638c2a62cafe8bd8fa670a0dfcc8c4110770)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2016-ps&branch=pr-en-us-2834) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2019-ps&branch=pr-en-us-2834) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2022-ps&branch=pr-en-us-2834) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201192229093285-2834%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T22%3A36%3A15Z&sr=b&sp=r&sig=abqk2xd3lkd2kiH5FbelTlV7kRG0cIq84Li3x8tubbY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 22:43 UTC, opbld31 commented
Docs Build status updates of commit _[68c182a](https://github.com/velkovb/windows-powershell-docs/commits/68c182a25b10a37e45ec33e4ea2de30a67ff5f8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2016-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2016-ps&branch=pr-en-us-2834) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2019-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2019-ps&branch=pr-en-us-2834) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2735-parameter-description/docset/winserver2022-ps/adfs/Set-AdfsGlobalAuthenticationPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/set-adfsglobalauthenticationpolicy?view=windowsserver2022-ps&branch=pr-en-us-2834) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201192230440982-2834%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T22%3A43%3A45Z&sr=b&sp=r&sig=j%2FdUK965Nff%2BVEVJuJttNXVqmUS7i57guV9ttfB5wIQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 22:45 UTC, merged