Resolves #2725
MicrosoftDocs/windows-powershell-docs pull request #2837
Opened 2022-01-12 09:05 UTC by velkovb

Add note for proper node cleanup.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2725

2022-01-12 11:00 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-12 11:01 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-12 11:02 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-12 11:03 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-12 11:03 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-12 11:11 UTC, opbld31 commented
Docs Build status updates of commit _[f2c4f5d](https://github.com/velkovb/windows-powershell-docs/commits/f2c4f5dc8cd95f353f7a27c83c759725f8fa0c20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2016-ps&branch=pr-en-us-2837) (WindowsServer2016-ps) | [Details](#user-content-7424b6ef6cbc244ee49997a8f290ec59-0b7b2fd3)
[docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2019-ps&branch=pr-en-us-2837) (WindowsServer2019-ps) | [Details](#user-content-ec768864f176e8a9a372fe3e574fe452-0b7b2fd3)
[docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=winserver2012r2-ps&branch=pr-en-us-2837) (winserver2012r2-ps) |
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2022-ps&branch=pr-en-us-2837) (WindowsServer2022-ps) |

<a id="7424b6ef6cbc244ee49997a8f290ec59-0b7b2fd3"></a>
### [docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2016-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

<a id="ec768864f176e8a9a372fe3e574fe452-0b7b2fd3"></a>
### [docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2019-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201121105380898-2837%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T11%3A11%3A55Z&sr=b&sp=r&sig=Aax8lOFzviJ5SLp9fjOFUgm2FyCSifurUiFRq4cxn6k%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 11:57 UTC, JohanFreelancer9 approved these changes

2022-01-12 17:50 UTC, get-itips reviewed
when you say _However, this cmdlet..._ you refer to _Uninstall-WindowsFeature_, right? I wonder if that is 100% clear in the sentence

2022-01-12 18:17 UTC, velkovb commented
I was a bit hesitant about using 'However' but couldn't think of anything better.

2022-01-12 23:59 UTC, get-itips commented
> I was a bit hesitant about using 'However' but couldn't think of anything better.

@JohanFreelancer9 any ideas to improve the sentence? or leave as is?

2022-01-13 03:05 UTC, tseward approved these changes

2022-01-13 07:42 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. Note that the **Uninstall-WindowsFeature** cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-13 07:42 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. Note that the **Uninstall-WindowsFeature** cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-13 07:43 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. Note that the **Uninstall-WindowsFeature** cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-13 07:44 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md
> +For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. However, this cmdlet removes only the server role but doesn't remove the node from the ADFS
```suggestion
For more information on the **Uninstall-WindowsFeature** cmdlet, type `Get-Help Uninstall-WindowsFeature`. Note that the **Uninstall-WindowsFeature** cmdlet removes only the server role but doesn't remove the node from the ADFS farm. For proper cleanup, use the **Set-AdfsFarmInformation** cmdlet with the `-RemoveNode` parameter.
```

2022-01-13 07:46 UTC, JohanFreelancer9 requested changes
@velkovb, @get-itips, my suggestion to make the sentence more clear.

2022-01-13 08:18 UTC, opbld33 commented
Docs Build status updates of commit _[56581aa](https://github.com/velkovb/windows-powershell-docs/commits/56581aa906ed1c26e42a46b3f4308eda3a40da25)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2016-ps&branch=pr-en-us-2837) (WindowsServer2016-ps) | [Details](#user-content-7424b6ef6cbc244ee49997a8f290ec59-67d5aa93)
[docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2019-ps&branch=pr-en-us-2837) (WindowsServer2019-ps) | [Details](#user-content-ec768864f176e8a9a372fe3e574fe452-67d5aa93)
[docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=winserver2012r2-ps&branch=pr-en-us-2837) (winserver2012r2-ps) |
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2022-ps&branch=pr-en-us-2837) (WindowsServer2022-ps) |

<a id="7424b6ef6cbc244ee49997a8f290ec59-67d5aa93"></a>
### [docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2016-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

<a id="ec768864f176e8a9a372fe3e574fe452-67d5aa93"></a>
### [docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2019-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201130811498469-2837%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T08%3A18%3A31Z&sr=b&sp=r&sig=k2rDWWuCJ1GiVl6FaYYzUwCeNb9mCqy5%2F2O0aXPSlys%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 09:44 UTC, JohanFreelancer9 approved these changes

2022-01-13 16:14 UTC, dariomws approved these changes

2022-01-18 16:08 UTC, e0i commented
Cleared assignees by mistake with this one. The PR is ready to be merged. Thanks. @tiburd

2022-01-19 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[3244081](https://github.com/velkovb/windows-powershell-docs/commits/32440811d0be28c6005a5cef9f1c29f1fd3f81ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2016-ps&branch=pr-en-us-2837) (WindowsServer2016-ps) | [Details](#user-content-7424b6ef6cbc244ee49997a8f290ec59-78da1e18)
[docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2019-ps&branch=pr-en-us-2837) (WindowsServer2019-ps) | [Details](#user-content-ec768864f176e8a9a372fe3e574fe452-78da1e18)
[docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=winserver2012r2-ps&branch=pr-en-us-2837) (winserver2012r2-ps) |
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2022-ps&branch=pr-en-us-2837) (WindowsServer2022-ps) |

<a id="7424b6ef6cbc244ee49997a8f290ec59-78da1e18"></a>
### [docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2016-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

<a id="ec768864f176e8a9a372fe3e574fe452-78da1e18"></a>
### [docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2019-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201192307238477-2837%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T23%3A14%3A18Z&sr=b&sp=r&sig=Da%2BPl6ixhZi0xv7OmNF1GXYAtUstQP0vlWZQH3xricM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 23:56 UTC, opbld30 commented
Docs Build status updates of commit _[67e99d3](https://github.com/velkovb/windows-powershell-docs/commits/67e99d3dcdc231529bd5b510b805a681a5d0063d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2019-ps&branch=pr-en-us-2837) (WindowsServer2019-ps) | [Details](#user-content-ec768864f176e8a9a372fe3e574fe452-fd0e8eed)
[docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=winserver2012r2-ps&branch=pr-en-us-2837) (winserver2012r2-ps) |
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2016-ps&branch=pr-en-us-2837) (WindowsServer2016-ps) |
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2022-ps&branch=pr-en-us-2837) (WindowsServer2022-ps) |

<a id="ec768864f176e8a9a372fe3e574fe452-fd0e8eed"></a>
### [docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'winserver2019-ps/Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' referenced by link '../Microsoft.Windows.ServerManager.Migration/Uninstall-WindowsFeature.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201192349358023-2837%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T23%3A56%3A49Z&sr=b&sp=r&sig=JgQjHqLgmH4fC5tnaOZBAscstPZcrdJwk9Kj6yuhHzQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 00:03 UTC, opbld31 commented
Docs Build status updates of commit _[c22ee4a](https://github.com/velkovb/windows-powershell-docs/commits/c22ee4a74ed9c6806395a0e29cce5cb4bc4f5205)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2012r2-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=winserver2012r2-ps&branch=pr-en-us-2837) (winserver2012r2-ps) |
[docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2016-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2016-ps&branch=pr-en-us-2837) (WindowsServer2016-ps) |
[docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2019-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2019-ps&branch=pr-en-us-2837) (WindowsServer2019-ps) |
[docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2725-add-note/docset/winserver2022-ps/adfs/Remove-AdfsFarmNode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/adfs/remove-adfsfarmnode?view=windowsserver2022-ps&branch=pr-en-us-2837) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202201192350177395-2837%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T00%3A03%3A53Z&sr=b&sp=r&sig=pTqIyduKSw205PnpwsgPuih2hv6IFO3QMckrPi58wx4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 00:05 UTC, merged