Move important note to top of documentation
MicrosoftDocs/windows-powershell-docs pull request #2887
Opened 2022-02-15 21:30 UTC by erik0686

The Copy-UserInternationalSettingsToSystem cmdlet is only available in Windows 11 and later. However, there's currently no folder for Win11 documentation, so back in the day we added it to the folder of winserver2022. This has confused some people about its availability, so we added a note pointing out that this cmdlet is only available in Win11 and later. The problem is that this note was added kind of in the middle of the article, so it is not immediately visible. There has been an issue filed about this, and therefore I'm moving the important note to a more visible area in the documentation.

2022-02-15 21:37 UTC, opbld33 commented
Docs Build status updates of commit _[0ad51c9](https://github.com/erik0686/windows-powershell-docs/commits/0ad51c975f4b5120704387c68b7ea56e1afa878d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md](https://github.com/erik0686/windows-powershell-docs/blob/user/ertorres/move-note/docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=windowsserver2022-ps&branch=pr-en-us-2887) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202202152130175114-2887%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T21%3A37%3A46Z&sr=b&sp=r&sig=DCo83Fs1NoLDA753zjOeXU8fDEAh88k9NSJ7iGoTQyQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 09:00 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md
> +**Important:** Note that this PowerShell cmdlet is only available for Windows 11 and later.
```suggestion
**Important:** Note that this PowerShell cmdlet is only available for Windows 11 and later.

```

2022-02-16 09:02 UTC, JohanFreelancer9 requested changes
Copy review - @erik0686, kindly commit the suggested change. Many thanks.

2022-02-16 18:05 UTC, opbld31 commented
Docs Build status updates of commit _[276cafc](https://github.com/erik0686/windows-powershell-docs/commits/276cafc953840f2bf4bb1fe4e9b312aa27728387)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md](https://github.com/erik0686/windows-powershell-docs/blob/user/ertorres/move-note/docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=windowsserver2022-ps&branch=pr-en-us-2887) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202202161758014090-2887%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T18%3A05%3A05Z&sr=b&sp=r&sig=gkFHak1JNkQN2UlkOJKd5c6v5ThZfaRPsny5wA2pFqU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-17 06:55 UTC, JohanFreelancer9 approved these changes

2022-03-08 16:29 UTC, dariomws approved these changes

2022-03-08 16:32 UTC, get-itips approved these changes

2022-03-08 18:35 UTC, tseward approved these changes

2022-04-06 15:36 UTC, opbld32 commented
Docs Build status updates of commit _[f6b219f](https://github.com/erik0686/windows-powershell-docs/commits/f6b219fadd980b17ca79381f76927a5b4eaf5203)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md](https://github.com/erik0686/windows-powershell-docs/blob/user/ertorres/move-note/docset/winserver2022-ps/international/Copy-UserInternationalSettingsToSystem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/international/copy-userinternationalsettingstosystem?view=windowsserver2022-ps&branch=pr-en-us-2887) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C46a32786-a1f6-1250-e1e1-2a4554025dc9%5CPullRequest%5C202204061529151245-2887%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T15%3A36%3A54Z&sr=b&sp=r&sig=V%2Fekx4r47ec%2BLbLqkXOiVnB8RsY9%2BNTD%2FubO1iXWMrA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 15:37 UTC, merged