Resolves #2825
MicrosoftDocs/windows-powershell-docs pull request #2966
Opened 2022-05-10 13:27 UTC by velkovb

Move WhatIf note in cmdlet description
NOTE: The WhatIf switch does not work with this cmdlet.

2022-05-10 13:34 UTC, opbld33 commented
Docs Build status updates of commit _[54cbd7d](https://github.com/velkovb/windows-powershell-docs/commits/54cbd7d2f7f7c15fb806989aa04e299b78110132)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2012-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012-ps&branch=pr-en-us-2966) (winserver2012-ps) |
[docset/winserver2012r2-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2012r2-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012r2-ps&branch=pr-en-us-2966) (winserver2012r2-ps) |
[docset/winserver2016-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2016-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2016-ps&branch=pr-en-us-2966) (WindowsServer2016-ps) |
[docset/winserver2019-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2019-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2019-ps&branch=pr-en-us-2966) (WindowsServer2019-ps) |
[docset/winserver2022-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2022-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2022-ps&branch=pr-en-us-2966) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202205101327072085-2966/BuildReport?accessString=02d319bb14323e12af04eb5907c7b41ab0844e11ca3fd6471f8338b0ef694b08).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-11 05:19 UTC, JohanFreelancer9 approved these changes

2022-06-08 19:46 UTC, get-itips approved these changes

2022-06-08 19:57 UTC, sdwheeler requested changes
Please use the Alert box format for notes like this.

2022-06-08 19:57 UTC, sdwheeler commented on docset/winserver2012-ps/smbshare/New-SmbShare.md
> +NOTE: The WhatIf switch does not work with this cmdlet.
```suggestion
> [!NOTE]
> The WhatIf switch does not work with this cmdlet.
```

2022-06-08 19:57 UTC, sdwheeler commented on docset/winserver2012r2-ps/smbshare/New-SmbShare.md
> +NOTE: The WhatIf switch does not work with this cmdlet.
```suggestion
> [!NOTE]
> The WhatIf switch does not work with this cmdlet.
```

2022-06-08 19:57 UTC, sdwheeler commented on docset/winserver2016-ps/smbshare/New-SmbShare.md
> +NOTE: The WhatIf switch does not work with this cmdlet.
```suggestion
> [!NOTE]
> The WhatIf switch does not work with this cmdlet.
```

2022-06-08 19:57 UTC, sdwheeler commented on docset/winserver2019-ps/smbshare/New-SmbShare.md
> +NOTE: The WhatIf switch does not work with this cmdlet.
```suggestion
> [!NOTE]
> The WhatIf switch does not work with this cmdlet.
```

2022-06-08 19:57 UTC, sdwheeler commented on docset/winserver2022-ps/smbshare/New-SmbShare.md
> +NOTE: The WhatIf switch does not work with this cmdlet.
```suggestion
> [!NOTE]
> The WhatIf switch does not work with this cmdlet.
```

2022-06-10 05:15 UTC, velkovb commented
> Please use the Alert box format for notes like this.

@sdwheeler I have been advised in the past not to use this syntax as it does not render in PowerShell. Should I start using it?

2022-06-10 13:59 UTC, sdwheeler commented
> Should I start using it?

Yes, the Alert boxes are the preferred format.

2022-06-10 15:14 UTC, opbld31 commented
Docs Build status updates of commit _[a626788](https://github.com/velkovb/windows-powershell-docs/commits/a6267884f6279e9b56d9ecc559f85c44673da77e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2012-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012-ps&branch=pr-en-us-2966) (winserver2012-ps) |
[docset/winserver2012r2-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2012r2-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012r2-ps&branch=pr-en-us-2966) (winserver2012r2-ps) |
[docset/winserver2016-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2016-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2016-ps&branch=pr-en-us-2966) (WindowsServer2016-ps) |
[docset/winserver2019-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2019-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2019-ps&branch=pr-en-us-2966) (WindowsServer2019-ps) |
[docset/winserver2022-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2022-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2022-ps&branch=pr-en-us-2966) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202206101506552042-2966/BuildReport?accessString=a60652417150ef3f62a9e10e5b84cfd84d1808806cbdb2ce9667bade617f3dd3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 15:15 UTC, sdwheeler approved these changes

2022-06-10 15:22 UTC, opbld31 commented
Docs Build status updates of commit _[dd6d4eb](https://github.com/velkovb/windows-powershell-docs/commits/dd6d4eb5c2c0dd270c148ce2abdaabe07abb280f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2012-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2012-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012-ps&branch=pr-en-us-2966) (winserver2012-ps) |
[docset/winserver2012r2-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2012r2-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=winserver2012r2-ps&branch=pr-en-us-2966) (winserver2012r2-ps) |
[docset/winserver2016-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2016-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2016-ps&branch=pr-en-us-2966) (WindowsServer2016-ps) |
[docset/winserver2019-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2019-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2019-ps&branch=pr-en-us-2966) (WindowsServer2019-ps) |
[docset/winserver2022-ps/smbshare/New-SmbShare.md](https://github.com/velkovb/windows-powershell-docs/blob/fix-2825/docset/winserver2022-ps/smbshare/New-SmbShare.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/new-smbshare?view=windowsserver2022-ps&branch=pr-en-us-2966) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202206101515386622-2966/BuildReport?accessString=dcafda9d8d8cacf08c745ec5d95bc7cdb4ecac7320e9155dfa72f246b44eb843).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-11 21:38 UTC, dariomws approved these changes

2023-10-02 05:26 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-03 18:48 UTC, merged