Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #3062
Opened 2022-08-15 14:08 UTC by mabdelmalek22

Add proxy settings to the doc

2022-08-15 14:12 UTC, mabdelmalek22 commented
Add Proxy settings

2022-08-15 14:15 UTC, opbld32 commented
Docs Build status updates of commit _[b28ba9d](https://github.com/mabdelmalek22/windows-powershell-docs/commits/b28ba9d52a71adcfe790ac9d13f0a531675ab13a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/mabdelmalek22/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-3062) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208151408074561-3062/BuildReport?accessString=2e52dff468f1b3b703b5254e6ce5dfca549d8230605e895d8937a29922c5613c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-15 14:22 UTC, opbld33 commented
Docs Build status updates of commit _[b28ba9d](https://github.com/mabdelmalek22/windows-powershell-docs/commits/b28ba9d52a71adcfe790ac9d13f0a531675ab13a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/mabdelmalek22/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-3062) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208151412371131-3062/BuildReport?accessString=18a74116ee503e62d0b3c2fb7098f039e8f57b63a1ab2bb4f1af6ed8a87a1ff2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 10:19 UTC, get-itips commented
Looks like this is still work in progress @e0i

2022-08-24 10:14 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +List Proxy PacUrldesciption and settings
```suggestion
Lists the proxy .pac file URLs and settings.
```

2022-08-24 10:17 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +List Proxy Server desciption and settings
```suggestion
Lists the proxy server descriptions and settings. 
```

2022-08-24 10:23 UTC, JohanFreelancer9 requested changes
Copy review - @mabdelmalek22, kindly commit the suggested changes. Also, include the following information for each of these parameters:

Type: 
Parameter Sets: 
Aliases: 
Required: 
Position: 
Default value: 
Accept pipeline input: 
Accept wildcard characters: 

Please see other parameters for formatting. Many thanks.

2022-08-31 16:59 UTC, opbld32 commented
Docs Build status updates of commit _[052d123](https://github.com/mabdelmalek22/windows-powershell-docs/commits/052d12399eb1701f5d89c45d27d3c056a75dd62f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2019-ps/defender/Set-MpPreference.md](https://github.com/mabdelmalek22/windows-powershell-docs/blob/patch-1/docset/winserver2019-ps/defender/Set-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2019-ps&branch=pr-en-us-3062) (WindowsServer2019-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208311652311436-3062/BuildReport?accessString=5f314fcf2e2543f5de2a54c420ecd313b62328a0e57be1500573324ff5d6ad25).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 16:30 UTC, opbld32 commented
Docs Build status updates of commit _[19bdc41](https://github.com/mabdelmalek22/windows-powershell-docs/commits/19bdc414844c053904306cb41b4a9f26347c7096)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2023-10-02 05:28 UTC, closed without merging