Inserted Example 2
MicrosoftDocs/windows-powershell-docs pull request #3084
Opened 2022-08-30 15:43 UTC by Skatterbrainz

Inserted Example 2 to show using -TitleIncludes parameter usage

2022-08-30 15:45 UTC, Skatterbrainz commented
Oops - I pasted the additional lines in the wrong example. The "Windows 10" lines should be under the new Example 2.

2022-08-30 15:50 UTC, opbld33 commented
Docs Build status updates of commit _[f00e81d](https://github.com/Skatterbrainz/windows-powershell-docs/commits/f00e81dbc24092fa8f612bc147979ff3ffa0dbfc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/updateservices/Get-WsusProduct.md](https://github.com/Skatterbrainz/windows-powershell-docs/blob/patch-2/docset/winserver2022-ps/updateservices/Get-WsusProduct.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/updateservices/get-wsusproduct?view=windowsserver2022-ps&branch=pr-en-us-3084) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208301543350686-3084/BuildReport?accessString=5cee77d82d6d5e41abbc3f44a3805c6698b7429385349458a0fca13dd32aa1c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 15:57 UTC, opbld32 commented
Docs Build status updates of commit _[027f97a](https://github.com/Skatterbrainz/windows-powershell-docs/commits/027f97aa2359ff468fd3d69c8dd59b61947e8b87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/updateservices/Get-WsusProduct.md](https://github.com/Skatterbrainz/windows-powershell-docs/blob/patch-2/docset/winserver2022-ps/updateservices/Get-WsusProduct.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/updateservices/get-wsusproduct?view=windowsserver2022-ps&branch=pr-en-us-3084) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202208301547104846-3084/BuildReport?accessString=9d56b973e35df6f1c8a36faee9b47b542fd09632fbe883a75f20af523565123a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 08:46 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/updateservices/Get-WsusProduct.md
> +This command gets all products where Title includes Windows 10
```suggestion
This command gets all products where the product title includes Windows 10.
```

2022-08-31 08:47 UTC, JohanFreelancer9 requested changes
Copy review - @Skatterbrainz, kindly commit the suggested change. Many thanks.

2023-10-02 05:29 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 05:29 UTC, closed without merging