[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute (part 4)
MicrosoftDocs/windows-powershell-docs pull request #3092
Opened 2022-09-03 16:47 UTC by alexbuckgit

**Global effort to fix build validation errors**

The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

2022-09-03 16:47 UTC, alexbuckgit commented
#docutune-draft

2022-09-03 16:54 UTC, opbld30 commented
Docs Build status updates of commit _[90d5968](https://github.com/alexbuckgit/windows-powershell-docs/commits/90d5968ce3b4d84217e74d3eea947dbac4ccf2b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/measure-dedupfilemetadata?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/New-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/New-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/remove-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupVolume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupVolume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Start-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Start-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Stop-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Stop-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/stop-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Update-DedupStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Update-DedupStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/update-dedupstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Add-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Add-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpComputerStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpComputerStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpThreatDetection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpThreatDetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatdetection?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Remove-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Remove-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4lease?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv6freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docs [...]

2022-09-06 15:17 UTC, jmart1428 commented
#docutune-ready

2022-09-07 02:18 UTC, alexbuckgit commented
@sdwheeler

Please merge the changes in this PR. For more information, see the description at the top of this PR.

Any pre-existing build validation issues or insufficient Acrolinx scores should be addressed in a separate PR.

#docutune-request-approval

2022-09-07 07:27 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/defender/Get-MpPreference.md
> +The **Get-MpPreference** cmdlet gets preferences for the Windows Defender scans and updates. For more information about the preferences that this cmdlet retrieves, see [Windows Defender Preferences C
```suggestion
The **Get-MpPreference** cmdlet gets preferences for the Windows Defender scans and updates. For more information about the preferences that this cmdlet retrieves, see [Windows Defender Preferences Class](/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)).
```

2022-09-07 07:34 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/international/Set-WinDefaultInputMethodOverride.md
> +You can pipe a locale ID and a keyboard language ID (KLID). See [Default Input Profiles (Input Locales) in Windows](/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-pa
```suggestion
You can pipe a locale ID and a keyboard language ID (KLID). See [Default Input Profiles (Input Locales) in Windows](/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs).
```

2022-09-07 07:40 UTC, JohanFreelancer9 requested changes
Copy review - @alexbuckgit, a few minor additional changes, please.

2022-09-07 13:11 UTC, sdwheeler requested changes

2022-09-07 13:11 UTC, sdwheeler commented on docset/winserver2016-ps/remotedesktop/Set-RDCertificate.md
> +The first part of the example uses the **ConvertTo-SecureString** cmdlet to create a secure string based on a string that the user supplies and stores it in the **$Password** variable. For more infor
```suggestion
The first part of the example uses the **ConvertTo-SecureString** cmdlet to create a secure string based on a string that the user supplies and stores it in the **$Password** variable. For more information, see [ConvertTo-SecureString](/powershell/module/microsoft.powershell.security/ConvertTo-SecureString). You can also enter the `Get-Help ConvertTo-SecureString` cmdlet into your PowerShell window.
```

2022-09-07 13:11 UTC, sdwheeler commented on docset/winserver2016-ps/remotedesktop/Set-RDCertificate.md
> +[about_CommonParameters](/powershell/module/microsoft.powershell.core/about/about_commonparameters?view=powershell-6)
```suggestion
[about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216)

```

2022-09-07 13:11 UTC, sdwheeler commented on docset/winserver2016-ps/scheduledtasks/Register-ScheduledTask.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion

This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
-InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose,
-WarningAction, and -WarningVariable. For more information, see
[about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-07 13:16 UTC, opbld31 commented
Docs Build status updates of commit _[1ee5bce](https://github.com/alexbuckgit/windows-powershell-docs/commits/1ee5bce1a992bf17ffb0d19be71f85da23478059)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/measure-dedupfilemetadata?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/New-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/New-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/remove-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupVolume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupVolume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Start-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Start-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Stop-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Stop-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/stop-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Update-DedupStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Update-DedupStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/update-dedupstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Add-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Add-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpComputerStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpComputerStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpThreatDetection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpThreatDetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatdetection?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Remove-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Remove-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4lease?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv6freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docs [...]

2022-09-09 12:04 UTC, alexbuckgit commented
@JohanFreelancer9 @sdwheeler -

The request changes have been accepted. Please merge, thanks!

2022-09-09 12:05 UTC, opbld31 commented
Docs Build status updates of commit _[bb034ee](https://github.com/alexbuckgit/windows-powershell-docs/commits/bb034ee28d0b6393ff3aef809d2ec3efc30a525c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/measure-dedupfilemetadata?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/New-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/New-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/remove-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupVolume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupVolume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Start-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Start-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Stop-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Stop-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/stop-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Update-DedupStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Update-DedupStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/update-dedupstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Add-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Add-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpComputerStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpComputerStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpThreatDetection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpThreatDetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatdetection?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Remove-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Remove-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4lease?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv6freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docs [...]

2022-09-09 12:18 UTC, opbld30 commented
Docs Build status updates of commit _[d7e8b97](https://github.com/alexbuckgit/windows-powershell-docs/commits/d7e8b97c7b5fec666a05b8c0a8aace990bf51064)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Measure-DedupFileMetadata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/measure-dedupfilemetadata?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/New-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/New-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/new-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Remove-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/remove-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupSchedule.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupschedule?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Set-DedupVolume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Set-DedupVolume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/set-dedupvolume?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Start-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Start-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/start-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Stop-DedupJob.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Stop-DedupJob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/stop-dedupjob?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/deduplication/Update-DedupStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/deduplication/Update-DedupStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/deduplication/update-dedupstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Add-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Add-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/add-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpComputerStatus.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpComputerStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpcomputerstatus?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Get-MpThreatDetection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Get-MpThreatDetection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/get-mpthreatdetection?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/defender/Remove-MpPreference.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/defender/Remove-MpPreference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/defender/remove-mppreference?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dfsn/Get-DfsnFolderTarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dfsn/get-dfsnfoldertarget?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv4Lease.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv4lease?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164649-5112650/docset/winserver2016-ps/dhcpserver/Get-DhcpServerv6FreeIPAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/dhcpserver/get-dhcpserverv6freeipaddress?view=windowsserver2016-ps&branch=pr-en-us-3092) (WindowsServer2016-ps) |
[docs [...]

2022-09-09 13:46 UTC, sdwheeler approved these changes

2022-09-09 13:47 UTC, JohanFreelancer9 approved these changes

2022-09-09 13:59 UTC, merged