[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute (part 5)
MicrosoftDocs/windows-powershell-docs pull request #3093
Opened 2022-09-03 16:56 UTC by alexbuckgit

**Global effort to fix build validation errors**

The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

2022-09-03 17:04 UTC, opbld31 commented
Docs Build status updates of commit _[1b84eec](https://github.com/alexbuckgit/windows-powershell-docs/commits/1b84eec32272eeda2164b8d77e7de33ccbedbc02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/grant-smbshareaccess?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/enable-physicaldiskidentification?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Format-Volume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Format-Volume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-Disk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-Disk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-PhysicalDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-PhysicalDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-VirtualDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-VirtualDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-virtualdisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/tls/Get-TlsCipherSuite.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/tls/Get-TlsCipherSuite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/updateservices/add-wsusdynamiccategory?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Add-VpnConnection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/New-EapConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/New-EapConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/new-eapconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionproxy?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/Get-WebApplication.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/Get-WebApplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/get-webapplication?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/New-WebAppPool.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/new-webapppool?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webapplicationproxy/set-webapplicationproxyconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/windowserrorreporting/disable-windowserrorreporting?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADComputer.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2019-ps/activedirectory/Get-ADComputer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=windowsserver2019-p [...]

2022-09-06 16:15 UTC, brittmsantos commented
#docutune-ready

2022-09-07 02:18 UTC, alexbuckgit commented
@sdwheeler

Please merge the changes in this PR. For more information, see the description at the top of this PR.

Any pre-existing build validation issues or insufficient Acrolinx scores should be addressed in a separate PR.

#docutune-request-approval

2022-09-07 07:42 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/storage/Get-VirtualDisk.md
> +This cmdlet outputs an object that represents the specified virtual disk. For more information about output object type, please see [MSFT_VirtualDisk class](/previous-versions/windows/desktop/stormgm
```suggestion
This cmdlet outputs an object that represents the specified virtual disk. For more information about output object type, see [MSFT_VirtualDisk class](/previous-versions/windows/desktop/stormgmt/msft-virtualdisk).
```

2022-09-07 07:43 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/tls/Get-TlsCipherSuite.md
> +For more information about protocol versions , see [BCRYPT_KDF_TLS_PRF (L"TLS_PRF")](/windows/desktop/api/bcrypt/nf-bcrypt-bcryptderivekey#bcrypt_kdf_tls_prf-ltls_prf) .
```suggestion
For more information about protocol versions , see [BCRYPT_KDF_TLS_PRF (L"TLS_PRF")](/windows/desktop/api/bcrypt/nf-bcrypt-bcryptderivekey#bcrypt_kdf_tls_prf-ltls_prf).
```

2022-09-07 07:49 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Get-MpPreference.md
> +The **Get-MpPreference** cmdlet gets preferences for the Windows Defender scans and updates. For more information about the preferences that this cmdlet retrieves, see [Windows Defender Preferences C
```suggestion
The **Get-MpPreference** cmdlet gets preferences for the Windows Defender scans and updates. For more information about the preferences that this cmdlet retrieves, see [Windows Defender Preferences Class](/previous-versions/windows/desktop/legacy/dn455323(v=vs.85)).
```

2022-09-07 07:51 UTC, JohanFreelancer9 requested changes
Copy review - @alexbuckgit, a few minor additional changes, please.

2022-09-09 12:19 UTC, opbld33 commented
Docs Build status updates of commit _[516c313](https://github.com/alexbuckgit/windows-powershell-docs/commits/516c3135676c8f8b1c7ae0525459ec43daaadcee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/grant-smbshareaccess?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/enable-physicaldiskidentification?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Format-Volume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Format-Volume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-Disk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-Disk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-PhysicalDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-PhysicalDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-VirtualDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-VirtualDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-virtualdisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/tls/Get-TlsCipherSuite.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/tls/Get-TlsCipherSuite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/updateservices/add-wsusdynamiccategory?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Add-VpnConnection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/New-EapConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/New-EapConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/new-eapconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionproxy?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/Get-WebApplication.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/Get-WebApplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/get-webapplication?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/New-WebAppPool.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/new-webapppool?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webapplicationproxy/set-webapplicationproxyconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/windowserrorreporting/disable-windowserrorreporting?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADComputer.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2019-ps/activedirectory/Get-ADComputer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=windowsserver2019-p [...]

2022-09-09 12:26 UTC, opbld32 commented
Docs Build status updates of commit _[27e67ae](https://github.com/alexbuckgit/windows-powershell-docs/commits/27e67aeda4d61b3a5795467176351110ed6a5bd7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/grant-smbshareaccess?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/enable-physicaldiskidentification?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Format-Volume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Format-Volume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-Disk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-Disk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-PhysicalDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-PhysicalDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-VirtualDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-VirtualDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-virtualdisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/tls/Get-TlsCipherSuite.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/tls/Get-TlsCipherSuite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/updateservices/add-wsusdynamiccategory?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Add-VpnConnection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/New-EapConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/New-EapConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/new-eapconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionproxy?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/Get-WebApplication.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/Get-WebApplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/get-webapplication?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/New-WebAppPool.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/new-webapppool?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webapplicationproxy/set-webapplicationproxyconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/windowserrorreporting/disable-windowserrorreporting?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADComputer.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2019-ps/activedirectory/Get-ADComputer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=windowsserver2019-p [...]

2022-09-09 13:47 UTC, sdwheeler approved these changes

2022-09-09 14:06 UTC, opbld33 commented
Docs Build status updates of commit _[ca2eca8](https://github.com/alexbuckgit/windows-powershell-docs/commits/ca2eca8fa40a9e48d70fe0d794542b82452fc781)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Grant-SmbShareAccess.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/grant-smbshareaccess?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/smbshare/Set-SmbServerConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/smbshare/set-smbserverconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Enable-PhysicalDiskIdentification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/enable-physicaldiskidentification?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Format-Volume.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Format-Volume.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/format-volume?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-Disk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-Disk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-disk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-PhysicalDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-PhysicalDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-physicaldisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/storage/Get-VirtualDisk.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/storage/Get-VirtualDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/storage/get-virtualdisk?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/tls/Get-TlsCipherSuite.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/tls/Get-TlsCipherSuite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/updateservices/Add-WsusDynamicCategory.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/updateservices/add-wsusdynamiccategory?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Add-VpnConnection.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Add-VpnConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/add-vpnconnection?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/New-EapConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/New-EapConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/new-eapconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/vpnclient/Set-VpnConnectionProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionproxy?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/Get-WebApplication.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/Get-WebApplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/get-webapplication?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webadministration/New-WebAppPool.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webadministration/New-WebAppPool.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webadministration/new-webapppool?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/webapplicationproxy/Set-WebApplicationProxyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/webapplicationproxy/set-webapplicationproxyconfiguration?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2016-ps/windowserrorreporting/Disable-WindowsErrorReporting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/windowserrorreporting/disable-windowserrorreporting?view=windowsserver2016-ps&branch=pr-en-us-3093) (WindowsServer2016-ps) |
[docset/winserver2019-ps/activedirectory/Get-ADComputer.md](https://github.com/alexbuckgit/windows-powershell-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220903-164707-6695009/docset/winserver2019-ps/activedirectory/Get-ADComputer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/activedirectory/get-adcomputer?view=windowsserver2019-p [...]

2022-09-09 14:09 UTC, merged