FailoverClustering Bulk Fixup (1/3) - Line formatting updates
MicrosoftDocs/windows-powershell-docs pull request #3162
Opened 2022-10-21 01:18 UTC by robinharwood

Bulk reflowed text and header formatting update before applying further quality updates.

2022-10-21 01:27 UTC, opbld33 commented
Learn Build status updates of commit _[1c04e6c](https://github.com/robinharwood/windows-powershell-docs/commits/1c04e6cccb86e736675842747a97d8bd3adf53a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustercheckpoint?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterdisk?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericapplicationrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericscriptrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericservicerole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroup?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroupsetdependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergrouptoset?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusteriscsitargetserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusternode?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresource?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcedependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcetype?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterscaleoutfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustersharedvolume?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustervi [...]

2022-10-21 10:22 UTC, opbld31 commented
Learn Build status updates of commit _[034b603](https://github.com/robinharwood/windows-powershell-docs/commits/034b603b38487dbf739754d89cd8d2803f18ccd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustercheckpoint?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterdisk?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericapplicationrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericscriptrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericservicerole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroup?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroupsetdependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergrouptoset?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusteriscsitargetserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusternode?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresource?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcedependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcetype?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterscaleoutfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustersharedvolume?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustervi [...]

2022-10-21 10:33 UTC, opbld31 commented
Learn Build status updates of commit _[5a62e1c](https://github.com/robinharwood/windows-powershell-docs/commits/5a62e1ce20d74a8b7671d433dd9508adb7589025)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustercheckpoint?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterdisk?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericapplicationrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericscriptrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericservicerole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroup?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroupsetdependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergrouptoset?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusteriscsitargetserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusternode?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresource?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcedependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcetype?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterscaleoutfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustersharedvolume?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustervi [...]

2022-10-21 10:41 UTC, opbld31 commented
Learn Build status updates of commit _[a88747a](https://github.com/robinharwood/windows-powershell-docs/commits/a88747a91a5aefa23712293049be2180ce4d637a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterCheckpoint.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustercheckpoint?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterDisk.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterdisk?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericapplicationrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericScriptRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericscriptrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGenericServiceRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergenericservicerole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroup.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroup?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupSetDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergroupsetdependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToSet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustergrouptoset?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusteriSCSITargetServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusteriscsitargetserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusternode?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResource.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresource?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceDependency.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcedependency?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterResourceType.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterresourcetype?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterScaleOutFileServerRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clusterscaleoutfileserverrole?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterSharedVolume.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustersharedvolume?view=windowsserver2022-ps&branch=pr-en-us-3162) (WindowsServer2022-ps) |
[docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md](https://github.com/robinharwood/windows-powershell-docs/blob/roharwoo_failoverclusters_line_formatting/docset/winserver2022-ps/failoverclusters/Add-ClusterVirtualMachineRole.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/failoverclusters/add-clustervi [...]

2022-10-21 11:35 UTC, robinharwood commented
Hi @michaeltlombardi / @sdwheeler,

I believe this PR is release ready if you would be kind enough to review and if appropriate sign-off/merge 😊

The main update was to reflow and fix any line return issues.

Please let me know if you have any questions or if I need to apply any other updates.

Thanks Robin

2022-10-21 21:02 UTC, michaeltlombardi requested changes
I went through for a style/formatting pass, there's a few places where it seems like text got munged and some broken formatting.

That being said, in case you want to focus this PR (and the others) on _only_ cleaning up the line lengths, I'll review the other PRs only for broken formatting and similar issues.

I haven't done a thorough prose editing here, either, but could do in the future. This pass was lightweight, addressing formatting where I thought it would likely also affect line length.

2022-10-22 08:27 UTC, robinharwood commented on docset/winserver2022-ps/failoverclusters/Get-Cluster.md
> + before the cluster will be quarantined. This is set to 3 by default.
Hey @michaeltlombardi - yes, I will address in #3162 and other follow ups.

2022-10-22 08:27 UTC, robinharwood commented on docset/winserver2022-ps/failoverclusters/Get-Cluster.md
> + host will remain quarantined.
Hey @michaeltlombardi - yes, I will address in #3162 and other follow ups.

Edit: Note, that #3162 need to be rebased once this is live :-)

2022-10-22 08:27 UTC, robinharwood commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGenericApplicationRole.md
>  Specifies the Windows PowerShell® command line to use for the highly available generic application.
Hey @michaeltlombardi - yes, I will address in #3162 and other follow ups.

Edit: Note, that #3162 need to be rebased once this is live :-)

2022-10-22 08:31 UTC, robinharwood commented on docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md
> +connected correctly to the networks and storage and that it contains the same software updates.
Hey @michaeltlombardi - I think this is GitHub doing a strange comparison, if I look at the file directly, I think it looks OK. I want to make sure you are happy too though :-)

2022-10-22 11:45 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterNode.md
> +connected correctly to the networks and storage and that it contains the same software updates.
Okay! Happy to merge as-is then, there's going to be a bunch more PRs that will catch anything along the way anyhow.

2022-10-22 11:46 UTC, michaeltlombardi approved these changes

2022-10-22 11:47 UTC, merged