Add descriptions to other parameters.
MicrosoftDocs/windows-powershell-docs pull request #3180
Opened 2022-11-07 01:47 UTC by oasaleh

This change adds descriptions to **Delay** and **For** parameters.

2022-11-07 01:54 UTC, opbld31 commented
Learn Build status updates of commit _[f9e5ce0](https://github.com/oasaleh/windows-powershell-docs/commits/f9e5ce0ded98093923bbba57146d93cd8ef77c6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/hyper-v/Restart-VM.md](https://github.com/oasaleh/windows-powershell-docs/blob/patch-1/docset/winserver2022-ps/hyper-v/Restart-VM.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/hyper-v/restart-vm?view=windowsserver2022-ps&branch=pr-en-us-3180) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202211070147047552-3180/BuildReport?accessString=a24131d09c0467b35534d22932b071da7d49f98c2b40c89b55ea565551590339).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-01-16 08:38 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/hyper-v/Restart-VM.md
> +Specifies the frequency of queries, in seconds. PowerShell queries the service specified by the For parameter to determine whether the service is available after the computer is restarted. This param
```suggestion
Specifies the frequency of queries, in seconds. PowerShell queries the service specified by the `-For` parameter to determine whether the service is available after the computer is restarted. This parameter is valid only with the `-Wait` and `-For` parameters. If the `-Delay` parameter isn't specified, **Restart-VM** uses a five-second delay.
```

2023-01-16 08:42 UTC, JohanFreelancer9 requested changes
Copy review - @oasaleh, kindly commit the minor suggested changes.

2023-03-25 06:42 UTC, JohanFreelancer9 approved these changes

2023-07-28 18:26 UTC, get-itips approved these changes
Can this be added to other OS versions of the article? Thanks

2023-08-06 21:18 UTC, scanum commented
Hi @tiburd hope all is well. Could you please help with this PR? Thanks!

2023-08-07 17:40 UTC, tiburd commented
@oasaleh 
Hi Omar,

To help ensure content health and consistency between operating system versions, please add your proposed changes for all operating system versions.

It looks like these are the other affected operating system versions:
- winserver2012-ps
- winserver2016-ps
- winserver2019-ps
- winserver2012r2-ps

After you finish that, please @ mention me or @scanum so we can have the changes reviewed and approved.

Thank you!

cc: @scanum

2023-10-02 05:33 UTC, scanum commented
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

2023-10-02 05:33 UTC, closed without merging