Update New-NetFirewallRule.md
MicrosoftDocs/windows-powershell-docs pull request #3224
Opened 2022-12-13 15:20 UTC by msbemba

Updated more details for remotedynamickeywordaddress

Fixes#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2984

2022-12-13 15:23 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2022-12-14 07:18 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-14 07:38 UTC, opbld33 commented
Learn Build status updates of commit _[f26e355](https://github.com/msbemba/windows-powershell-docs/commits/f26e355a3d625a2979242be0831557434a109481)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md](https://github.com/msbemba/windows-powershell-docs/blob/patch-147/docset/winserver2022-ps/netsecurity/New-NetFirewallRule.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/netsecurity/new-netfirewallrule?view=windowsserver2022-ps&branch=pr-en-us-3224) (WindowsServer2022-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/46a32786-a1f6-1250-e1e1-2a4554025dc9/202212140731156043-3224/BuildReport?accessString=b102048fbcbf61c230865f5b6d237fa858c3d3aef6b5bc69fb952225960afe97).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/46a32786-a1f6-1250-e1e1-2a4554025dc9?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2023-10-02 18:19 UTC, get-itips approved these changes

2023-10-02 18:59 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-04 16:29 UTC, merged