Update Get-SmbShare.md for scopename and related examples
MicrosoftDocs/windows-powershell-docs pull request #3246
Opened 2023-01-21 00:50 UTC by nedpyle

# PR Summary

Redesigned help to not be misleading about scopename vs cimsession and added a remote server example: previous examples and help were often referring to failover clustering without being explicit, showing output that 99,9% of customers will never see because they are not running clusters. I am going to do this against get-smbshare, new-smbshare, set-smbshare, remove-smbshare as needed.

## PR Checklist

- [X] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [X] **Summary:** This PR's summary describes the scope and intent of the change.
- [X] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [X] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-01-23 08:13 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/smbshare/Get-SmbShare.md
> +### Example 3: Display information about the SMB shares on a remote computer.
```suggestion
### Example 3: Display information about the SMB shares on a remote computer
```

2023-01-23 08:14 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/smbshare/Get-SmbShare.md
> +Specifies the scope of the share by name. For use with Windows Server failover cluster file server resources.
```suggestion
Specifies the scope of the share by name for use with Windows Server failover cluster file server resources.
```

2023-01-23 08:18 UTC, JohanFreelancer9 requested changes
Copy review - @nedpyle, kindly commit the minor suggested change. Many thanks.

2023-01-24 10:19 UTC, JohanFreelancer9 approved these changes

2023-07-28 18:32 UTC, get-itips approved these changes
Can you please check if this change can be applied to other OS versions of the cmdlet's article? Thank you Ned

2023-07-28 20:26 UTC, nedpyle commented
> Can you please check if this change can be applied to other OS versions of the cmdlet's article? Thank you Ned

yes, all previous versions

2023-07-28 20:32 UTC, get-itips commented
Can you please make also those edits in this PR? Thank you

2023-07-28 20:49 UTC, nedpyle commented
> Can you please make also those edits in this PR? Thank you

What edits?

2023-07-28 20:51 UTC, get-itips commented
> > Can you please make also those edits in this PR? Thank you
> 
> What edits?

I am referring to these other files

![image](https://github.com/MicrosoftDocs/windows-powershell-docs/assets/36666927/8d2b273d-4865-45aa-9481-0a6920feac46)

2023-07-28 20:57 UTC, nedpyle commented
> > > Can you please make also those edits in this PR? Thank you
> > 
> > 
> > What edits?
> 
> I am referring to these other files
> 
> ![image](https://user-images.githubusercontent.com/36666927/256930037-8d2b273d-4865-45aa-9481-0a6920feac46.png)

I'm not doing that, there are too many edits in too many files. They should be bulk fixed, not individually edited.

2023-07-31 20:15 UTC, merged