Clarified support & fixed synopsis for global mapping
MicrosoftDocs/windows-powershell-docs pull request #3253
Opened 2023-01-28 00:39 UTC by nedpyle

Fixed the synopsis and updated the supported and unsupported scenarios for use of New-SmbGlobalMapping

# PR Summary

## PR Checklist

- [ ] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [ ] **Summary:** This PR's summary describes the scope and intent of the change.
- [ ] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [ ] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-01-28 09:43 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/smbshare/New-SmbGlobalMapping.md
> +The **New-SmbGlobalMapping** cmdlet creates an SMB global mapping on the SMB client to an SMB share. Global mappings allow all users to use the same mapping. Its primary use is for Windows Containers
```suggestion
The **New-SmbGlobalMapping** cmdlet creates an SMB global mapping on the SMB client to an SMB share. Global mappings allow all users to use the same mapping. Its primary use is for Windows Containers. Global mappings support standalone and failover cluster SMB shares, they do not support DFS Namespace folder shares.
```

2023-01-28 09:44 UTC, JohanFreelancer9 requested changes
Copy review - @nedpyle, kindly commit the suggested change. Many thanks.

2023-01-31 09:18 UTC, JohanFreelancer9 approved these changes

2023-02-13 20:09 UTC, nedpyle commented
@JohanFreelancer9 do I need to do anything else here for this to be published?

2023-02-14 06:04 UTC, JohanFreelancer9 commented
@nedpyle, nothing more is required from you at this time. @scanum, could you please help to get this merged. Thanks.

2023-02-20 08:16 UTC, dariomws approved these changes
I think this cmdlet is also available in Windows Server 2019 and 2016.

2023-02-20 12:32 UTC, get-itips approved these changes

2023-02-21 15:22 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-21 21:21 UTC, merged