Update New-ScheduledTaskPrincipal.md
MicrosoftDocs/windows-powershell-docs pull request #3286
Opened 2023-03-21 16:12 UTC by PiJoCoder

Submitted via Learn Editor.

2023-03-21 21:45 UTC, PiJoCoder commented
#sign-off

2023-03-25 12:22 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/scheduledtasks/New-ScheduledTaskPrincipal.md
> +- - Interactive
```suggestion
- Interactive
```

2023-03-25 12:24 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/scheduledtasks/New-ScheduledTaskPrincipal.md
> +For more information on LogonType values, see [Principal.LogonType](/windows/win32/taskschd/principal-logontype#property-value)
```suggestion
For more information about LogonType values, see [Principal.LogonType](/windows/win32/taskschd/principal-logontype#property-value)
```

2023-03-25 12:28 UTC, JohanFreelancer9 requested changes
Copy review - @PiJoCoder, kindly commit the suggested changes. Many thanks.

2023-03-27 02:49 UTC, JohanFreelancer9 approved these changes

2023-03-27 04:13 UTC, PiJoCoder commented
#sign-off

2023-03-27 16:04 UTC, PiJoCoder commented
#sing-off

2023-04-03 18:47 UTC, PiJoCoder commented
@JohanFreelancer9 do you know how we move this PR forward?

2023-04-04 18:34 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 do you know how we move this PR forward?

@scanum, please assist.

2023-04-10 03:27 UTC, scanum commented
@sdwheeler 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-10 13:06 UTC, sdwheeler approved these changes

2023-04-12 04:15 UTC, scanum commented
@tiburd Hope all is well. Could you please help us merge? Thanks!

2023-04-12 14:53 UTC, merged