Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #3301
Opened 2023-04-14 14:21 UTC by msbemba

made changes to -CheckForSignaturesBeforeRunningScan as per the group policy description

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3251

2023-04-14 14:21 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-14 14:22 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-04-14 14:22 UTC, msbemba commented
CC :  @scanum

2023-04-15 17:36 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/defender/Set-MpPreference.md
> +This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or to the ones started from the command line using "mpcmdrun -Scan"
```suggestion
This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan"
```

2023-04-15 17:36 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or to the ones started from the command line using "mpcmdrun -Scan"
```suggestion
This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan"
```

2023-04-15 17:36 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or to the ones started from the command line using "mpcmdrun -Scan"
```suggestion
This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan"
```

2023-04-15 17:36 UTC, JohanFreelancer9 requested changes
Copy review.

2023-04-16 08:52 UTC, JohanFreelancer9 approved these changes

2023-04-17 09:20 UTC, dariomws approved these changes

2023-04-17 09:20 UTC, dariomws commented on docset/winserver2016-ps/defender/Set-MpPreference.md
> +This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan"
```suggestion
This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or scans started from the command line using "mpcmdrun -Scan".
```

2023-04-17 09:20 UTC, dariomws commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan"
```suggestion
This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan".
```

2023-04-17 09:20 UTC, dariomws commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan"
```suggestion
This setting applies to scheduled scans, but it has no effect on scans initiated manually from the user interface or on scans started from the command line using "mpcmdrun -Scan".
```

2023-04-17 15:52 UTC, get-itips approved these changes

2023-04-27 03:39 UTC, scanum commented
@tiburd hope all is well. Could you please help me merge this PR? Thanks!

2023-04-27 15:51 UTC, merged