Fix typo in Remove-NetSwitchTeamMember.md
MicrosoftDocs/windows-powershell-docs pull request #3306
Opened 2023-04-17 20:02 UTC by JonnyTech

The argument is `Name`, not `Member`. Using the incorrect string yields an error message.

# PR Summary

This changes fixes a typo in the documentation for `Remove-NetSwitchTeamMember`.

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-04-20 03:37 UTC, JohanFreelancer9 approved these changes

2023-10-02 18:06 UTC, get-itips requested changes
Can you please make the same edit for the other OS versions of the article?

2024-11-22 18:50 UTC, JonnyTech commented
> Can you please make the same edit for the other OS versions of the article?

@get-itips done (I think!)

2024-11-22 19:11 UTC, JonnyTech commented
> @JonnyTech please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree

2024-12-18 01:23 UTC, JonnyTech commented
Hello, what needs to be done for this PR to get merged - did I miss something?

2025-03-10 21:06 UTC, JonnyTech commented
@get-itips, still waiting for you to approve the changes that you requested - or @scanum can you do it so that I can finally close this please?

2025-03-20 11:51 UTC, closed without merging