Fix typo for Copy-GPO.MD
MicrosoftDocs/windows-powershell-docs pull request #3313
Opened 2023-04-22 00:11 UTC by henryriveraCS

# PR Summary
Fixing a typo where a period was used instead of space between "session" and "a".

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

2023-04-22 06:00 UTC, JohanFreelancer9 approved these changes

2023-10-02 18:00 UTC, get-itips approved these changes

2023-10-02 19:00 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-04 16:54 UTC, tiburd commented
close > reopend

2023-10-18 17:10 UTC, msbemba approved these changes
Approved. Regarding the errors, I do not see learn-validation VS Code extension in this PR.

2023-10-20 15:25 UTC, msbemba commented on docset/winserver2022-ps/grouppolicy/Copy-GPO.md
> +```
```powershell

2023-10-20 15:26 UTC, msbemba requested changes

2023-10-20 15:26 UTC, msbemba commented on docset/winserver2022-ps/grouppolicy/Copy-GPO.md
> +```
```powershell

2023-10-20 15:26 UTC, msbemba commented on docset/winserver2022-ps/grouppolicy/Copy-GPO.md
> +PS C:\> Copy-GPO -SourceName "TestGpo1" -SourceDomain "test.contoso.com" TargetName "TestGpo1" -TargetDomain "sales.contoso.com"
Copy-GPO -SourceName "TestGpo1" -SourceDomain "test.contoso.com" TargetName "TestGpo1" -TargetDomain "sales.contoso.com"

2023-10-20 15:28 UTC, msbemba reviewed
Could you please change line 72 73 and 74 to below?

```powershell
Copy-GPO -SourceName "TestGpo1" -SourceDomain "test.contoso.com" TargetName "TestGpo1" -TargetDomain "sales.contoso.com"
```

2023-10-20 15:29 UTC, msbemba requested changes
Please change line 72,73 and 74 to fix the errors

```powershell
Copy-GPO -SourceName "TestGpo1" -SourceDomain "test.contoso.com" TargetName "TestGpo1" -TargetDomain "sales.contoso.com"
```

2024-04-29 18:35 UTC, closed without merging