pshsummit doc-a-thon #3323
MicrosoftDocs/windows-powershell-docs pull request #3346
Opened 2023-04-27 22:50 UTC by thedavecarroll

# PR Summary

- Resolves #3323 

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-04-27 22:52 UTC, thedavecarroll commented
@microsoft-github-policy-service agree

2023-04-27 23:25 UTC, sdwheeler requested changes
I made some suggestion but not on all files. Make the same changes to all files.

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Disable-TlsCipherSuite.md
> +```powershell
````suggestion
```
````

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Disable-TlsCipherSuite.md
> +(http://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
-WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](http://go.microsoft.com/fwlink/?LinkID=113216).
```

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Disable-TlsEccCurve.md
> +```powershell
````suggestion
```
````

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Disable-TlsEccCurve.md
> +This will disable the ECC Curve 'curve25519'.
```suggestion
This will disable the ECC Curve `curve25519`.
```

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Disable-TlsSessionTicketKey.md
> +```powershell
````suggestion
```
````

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Disable-TlsSessionTicketKey.md
> +(http://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
-WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](http://go.microsoft.com/fwlink/?LinkID=113216).
```

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Enable-TlsCipherSuite.md
> +```powershell
````suggestion
```
````

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Enable-TlsCipherSuite.md
> +HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL can also configure
```suggestion
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL` can also configure
```

2023-04-27 23:25 UTC, sdwheeler commented on docset/winserver2022-ps/tls/Enable-TlsCipherSuite.md
> +This command enables cipher suite named TLS_DHE_DSS_WITH_AES_256_CBC_SHA. This command adds the
```suggestion
This command enables cipher suite named `TLS_DHE_DSS_WITH_AES_256_CBC_SHA`. This command adds the
```

2023-05-01 23:32 UTC, thedavecarroll commented
I think cleaned up what was requested. I wasn't able to merge the latest main in the web UI.

2023-05-02 18:34 UTC, michaeltlombardi approved these changes

2023-05-02 18:41 UTC, merged