Added PS to PS code block and separated output bloks,
MicrosoftDocs/windows-powershell-docs pull request #3358
Opened 2023-04-27 23:13 UTC by XXLMandalorian013

Add PS to code blocks and added out blocks that where tied into code blocks.

# PR Summary

- Resolves #3355

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-04-28 00:04 UTC, michaeltlombardi requested changes

2023-04-28 00:04 UTC, michaeltlombardi commented on docset/winserver2022-ps/remoteaccess/Get-RemoteAccessRoutingDomain.md
> +```powershell
We always want to have a blank line around block elements, like headings and code blocks

````suggestion

```powershell
````

2023-04-28 00:04 UTC, michaeltlombardi commented on docset/winserver2022-ps/remoteaccess/Get-RemoteAccessRoutingDomain.md
> +```output
````suggestion
```Output
````

2023-04-28 00:04 UTC, michaeltlombardi commented on docset/winserver2022-ps/remoteaccess/Get-RemoteAccessUserActivity.md
> +```powershell
````suggestion

```powershell
````

2023-04-28 00:04 UTC, michaeltlombardi commented on docset/winserver2022-ps/remoteaccess/Get-RemoteAccessUserActivity.md
> +```powershell
````suggestion

```powershell
````

2023-04-28 00:04 UTC, michaeltlombardi commented on docset/winserver2022-ps/remoteaccess/Get-RoutingProtocolPreference.md
> +```powershell
````suggestion

```powershell
````

2023-04-28 00:04 UTC, michaeltlombardi commented on docset/winserver2022-ps/remoteaccess/Get-VpnAuthProtocol.md
> +```powershell
````suggestion

```powershell
````

2023-05-02 21:23 UTC, sdwheeler commented
Retrigger build

2023-05-02 22:23 UTC, merged