formatting #3371
MicrosoftDocs/windows-powershell-docs pull request #3372
Opened 2023-04-28 03:34 UTC by Snozzberries

# PR Summary

    - Resolves #3371

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-04-28 07:33 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsWebEnrollment.md
> +  `Install-AdcsWebEnrollment -?`
```suggestion

    `Install-AdcsWebEnrollment -?`
```

2023-04-28 07:34 UTC, JohanFreelancer9 requested changes
Copy review - @Snozzberries, minor suggested change. Many thanks.

2023-04-28 17:03 UTC, Snozzberries commented
Commit applied. Thanks!

2023-04-29 00:42 UTC, JohanFreelancer9 approved these changes

2023-05-01 15:42 UTC, michaeltlombardi requested changes
One minor fix - we use bold for type, parameter and property names, code-formatting for cmdlets, variables with the `$` prefix, parameters with the `-` prefix, and specific values.

2023-05-01 15:42 UTC, michaeltlombardi commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsWebEnrollment.md
> +Specifies a `PSCredential` object for the CA Web Enrollment. To obtain a credential object, use the
```suggestion
Specifies a **PSCredential** object for the CA Web Enrollment. To obtain a credential object, use the
```

2023-05-03 19:19 UTC, michaeltlombardi approved these changes

2023-05-03 19:19 UTC, merged