formatting #3373
MicrosoftDocs/windows-powershell-docs pull request #3374
Opened 2023-04-28 03:40 UTC by Snozzberries

# PR Summary

    - Resolves #3373

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-04-28 07:51 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsOnlineResponder.md
> +  `Install-AdcsOnlineResponder -?`
```suggestion

    `Install-AdcsOnlineResponder -?`
```

2023-04-28 07:52 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsOnlineResponder.md
> +  `Install-AdcsOnlineResponder -?`
```suggestion

    `Install-AdcsOnlineResponder -?`
```

2023-04-28 07:53 UTC, JohanFreelancer9 requested changes
Copy review - @Snozzberries, minor suggested change, please.

2023-04-28 17:04 UTC, Snozzberries commented
Commit applied. Thanks!

2023-04-29 00:59 UTC, JohanFreelancer9 approved these changes

2023-05-01 15:44 UTC, michaeltlombardi approved these changes

2023-05-01 15:44 UTC, merged