formatting #3375
MicrosoftDocs/windows-powershell-docs pull request #3376
Opened 2023-04-28 04:09 UTC by Snozzberries

# PR Summary

    - Resolves #3375

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-04-28 08:09 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +Specifies remote certification authority (CA) that the Network Device Enrollment Service uses. This
```suggestion
Specifies the remote certification authority (CA) that the Network Device Enrollment Service uses. This
```

2023-04-28 08:09 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +Specifies a **PSCredential** object that this cmdlet use to connect to the NDES role service. To
```suggestion
Specifies a **PSCredential** object that this cmdlet uses to connect to the NDES role service. To
```

2023-04-28 08:09 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +  `Install-AdcsNetworkDeviceEnrollmentService -?`
```suggestion

    `Install-AdcsNetworkDeviceEnrollmentService -?`
```

2023-04-28 08:10 UTC, JohanFreelancer9 requested changes
Copy review - @Snozzberries, minor suggested changes, please. Many thanks.

2023-04-28 17:14 UTC, Snozzberries commented
Updated with changes.

2023-04-29 01:07 UTC, JohanFreelancer9 approved these changes

2023-05-01 15:47 UTC, michaeltlombardi requested changes
Minor suggestions around the specific values from the examples - we don't want to include the wrapping quotes when we format them as code.

2023-05-01 15:47 UTC, michaeltlombardi commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +is a member of the local computer's `IIS_USRS` group.
```suggestion
This command displays the default settings when NDES is using a service account without making any
changes to the configuration. This command uses the service account named `CONTOSO\svcNDES` that
is a member of the local computer's `IIS_USRS` group.
```

2023-05-01 15:47 UTC, michaeltlombardi commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +the local computer's `IIS_USRS` group. The command also specifies several non-default parameters.
```suggestion
This command installs the NDES using a service account named `CONTOSO\svcNDES` that is a member of
the local computer's `IIS_USRS` group. The command also specifies several non-default parameters.
```

2023-05-03 19:18 UTC, michaeltlombardi approved these changes

2023-05-03 19:18 UTC, michaeltlombardi commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +    ServiceAccountPassword = (read-host "Set user password" -assecurestring)
```suggestion
    ServiceAccountPassword = (Read-Host "Set user password" -AsSecureString)
```

2023-05-03 19:18 UTC, michaeltlombardi commented on docset/winserver2022-ps/adcsdeployment/Install-AdcsNetworkDeviceEnrollmentService.md
> +    ServiceAccountPassword = (read-host "Set user password" -assecurestring)
```suggestion
    ServiceAccountPassword = (Read-Host "Set user password" -AsSecureString)
```

2023-05-04 13:06 UTC, merged