Issue 3408
MicrosoftDocs/windows-powershell-docs pull request #3409
Opened 2023-04-29 23:37 UTC by RobBiddle

# PR Summary

- Resolves Issue #3408 
## PR Checklist

- [ ] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [ ] **Summary:** This PR's summary describes the scope and intent of the change.
- [ ] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [ ] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-05-01 18:54 UTC, michaeltlombardi commented on docset/winserver2022-ps/addsdeployment/Uninstall-ADDSDomainController.md
> +the user to enter credentials using the Windows security login UI.
```suggestion
Specifies the user name and password that corresponds to the account used to install the domain
controller. Use the `Get-Credential` cmdlet to prompt the user to supply a password in place of an
existing **System.Management.Automation.PSCredential** type. This causes Windows PowerShell to
prompt the user to enter credentials using the Windows security login UI.
```

2023-05-01 18:54 UTC, michaeltlombardi commented on docset/winserver2022-ps/addsdeployment/Uninstall-ADDSDomainController.md
> +user to enter credentials.
```suggestion
Specifies the account credentials to use when you create or remove the DNS delegation. If you do
not specify a value, the account credentials that you specify for the AD DS installation or removal
are used to remove the DNS delegation. As an alternative, you can specify the asterisk (`*`) to
prompt the user to enter credentials.
```

2023-05-01 18:55 UTC, michaeltlombardi commented on docset/winserver2022-ps/addsdeployment/Uninstall-ADDSDomainController.md
> +domain controller.
```suggestion
Indicates that Windows PowerShell ignores any inconsistency that it detects with the value that you
specify for the **LastDomainControllerInDomain** parameter. For instance, if you specify
**LastDomainControllerInDomain** but Windows PowerShell detects that there is actually another
active domain controller in the domain, you can specify the **IgnoreLastDCInDomainMismatch**
parameter to have Windows PowerShell continue the removal of AD DS from the domain controller
despite the inconsistency that it has detected. Similarly, if you do not specify
**LastDomainControllerInDomain** but Windows PowerShell cannot detect that another domain
controller is in the domain, you can specify **IgnoreLastDCInDomainMismatch** to have Windows
PowerShell continue to remove AD DS from the domain controller.
```

2023-05-01 18:56 UTC, michaeltlombardi commented on docset/winserver2022-ps/addsdeployment/Uninstall-ADDSDomainController.md
> +[AD DS Simplified Administration](https://go.microsoft.com/fwlink/?LinkID=237244).
```suggestion
Indicates that only a base set of validations is performed. This behavior is equivalent to the
validations that were performed when using `Dcpromo.exe` in earlier versions of Windows Server to
add a new domain controller. When this switch parameter is set, it specifies that additional
preliminary checks should be bypassed. For more information on the scope of these additional
preliminary checks that the **ADDSDeployment** module performs by default when using Windows Server
2012, refer to the table in the section ADPrep and Prerequisite Checking Architecture in
[AD DS Simplified Administration](https://go.microsoft.com/fwlink/?LinkID=237244).
```

2023-05-02 10:46 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/addsdeployment/Uninstall-ADDSDomainController.md
> +domain controller from which AD DS is being removed.
```suggestion
the domain controller from which AD DS is being removed.
```

2023-05-02 10:46 UTC, JohanFreelancer9 requested changes
Copy review - @RobBiddle, one minor additional change, please. Many thanks.

2023-05-02 14:05 UTC, michaeltlombardi commented on docset/winserver2022-ps/addsdeployment/Uninstall-ADDSDomainController.md
> +
```suggestion
```

2023-05-02 18:32 UTC, michaeltlombardi approved these changes

2023-05-02 18:32 UTC, merged