Update Remove-AppxPackageAutoUpdateSettings.md
MicrosoftDocs/windows-powershell-docs pull request #3536
Opened 2023-06-23 08:34 UTC by msbemba

Added Information for Synopsis, Description and example

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3073

2023-06-23 08:34 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-06-23 11:37 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/appx/Remove-AppxPackageAutoUpdateSettings.md
> +Removes settings configured for a particular Windows App.
```suggestion
Removes settings configured for a particular Windows app.
```

2023-06-23 11:37 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/appx/Remove-AppxPackageAutoUpdateSettings.md
> +The 'Remove-AppxPackageAutoUpdateSettings' PowerShell cmdlet removes the settings configured for a specific or all installed Windows Apps in relation to Auto Update and Repair.
```suggestion
The 'Remove-AppxPackageAutoUpdateSettings' PowerShell cmdlet removes the settings configured for a specific or all installed Windows apps in relation to the Auto Update and Repair settings.
```

2023-06-23 11:37 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/appx/Remove-AppxPackageAutoUpdateSettings.md
> +This will remove the Auto Update and Repair settings for a specific Windows App that has been installed and registered to the signed-in user.
```suggestion
This example removes the Auto Update and Repair settings for a specific Windows app that has been installed and registered to the signed-in user.
```

2023-06-23 11:38 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-23 13:04 UTC, JohanFreelancer9 approved these changes

2023-07-04 19:32 UTC, get-itips approved these changes

2023-07-07 06:13 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-07-07 18:01 UTC, merged