Hyper v vfd update
MicrosoftDocs/windows-powershell-docs pull request #3566
Opened 2023-07-26 14:19 UTC by Xelu86

# PR Summary

- Updated Hyper-V Module with current information
- Cmdlet name - Changed bolded text to code spans
- Parameters - Changed italic text to bold
- Parameters - Changed code span text to bold
- Applied text contractions
- Applied syntax reflows
- Fixed indented code blocks

## PR Checklist

- [X] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [X] **Summary:** This PR's summary describes the scope and intent of the change.
- [X] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [X] **Style:** This PR adheres to the [style guide][style].

2023-07-28 18:33 UTC, get-itips approved these changes
Can you please check if these changes can be applied to other OS versions of the cmdlet's article? Thank you

2023-07-31 04:30 UTC, JohanFreelancer9 approved these changes

2023-07-31 15:29 UTC, michaeltlombardi requested changes

2023-07-31 16:17 UTC, michaeltlombardi commented on docset/winserver2022-ps/hyper-v/New-VFD.md
> +New-VFD "C:\floppy.vfd"
Upon reflection and conversation with @Xelu86, I think this should be treated as a non-illustrative example.

2023-07-31 16:18 UTC, michaeltlombardi commented on docset/winserver2022-ps/hyper-v/New-VFD.md
> +New-VFD "C:\floppy.vfd"
After reflection and conversation with @Xelu86, we're going to keep this as-is.

2023-07-31 17:19 UTC, michaeltlombardi approved these changes

2023-07-31 17:20 UTC, merged