Introducing new Cluster Group Affinity Rule commands
MicrosoftDocs/windows-powershell-docs pull request #3570
Opened 2023-07-27 15:40 UTC by robinharwood

# PR Summary

Adding new command to the module.

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2023-08-23 19:08 UTC, get-itips commented
@scanum seems is still a draft

2023-09-11 15:16 UTC, michaeltlombardi requested changes
Minor corrections and suggestions for further documentation.

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +Adds a cluster group to a named affinity rule.
Can we extend this description? Currently, it's the same as the synopsis.

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +### Example 1
Missing descriptive name for the example.

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +For more information about Windows PowerShell background jobs, see
```suggestion
For more information about PowerShell background jobs, see
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +Specifies the input object that is used in a pipeline command.
Can we specify more information about the input object for the user?

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +The Affinity rule in question that groups will be added to.
```suggestion
The Affinity rule to add the groups to.
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +generate any output.
Can this be more descriptive of the output object and include its type for the user?

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +### Microsoft.Management.Infrastructure.CimInstance#root/MSCLUSTER/MSCluster_AffinityRule
Can we add descriptions for these types, when and how they're used and returned?

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +### Example 1
Missing descriptive name after the example number.

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +This example removes the cluster group MyGroup from the affinity rule named MyRule.
```suggestion
This example removes the cluster group `MyGroup` from the affinity rule named `MyRule`.
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +This example adds the group named MyGroup to the affinity rule named MyRule on the cluster named.
```suggestion
This example adds the group named `MyGroup` to the affinity rule named `MyRule` on the cluster named `MyCluster`.
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +For more information about Windows PowerShell background jobs, see
```suggestion
For more information about PowerShell background jobs, see
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +The groups to be removed from the affinity rule.
```suggestion
The groups to remove from the affinity rule.
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +Specifies the input object that is used in a pipeline command.
Can this be more specific to the cmdlet?

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +The name of the affinity rule to remove groups from
```suggestion
The name of the affinity rule to remove groups from.
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +Returns an object representing the item with which you are working. By default, this cmdlet doesn't
Can this be more descriptive of the output object and include its type?

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +this parameter is omitted or a value of `0` is entered, then Windows PowerShell&reg; calculates an
```suggestion
this parameter is omitted or a value of `0` is entered, then PowerShell calculates an
```

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Remove-ClusterGroupFromAffinityRule.md
> +### Microsoft.Management.Infrastructure.CimInstance#root/MSCLUSTER/MSCluster_AffinityRule
Can we add descriptions for these types - when and how they're used or returned?

2023-09-11 15:16 UTC, michaeltlombardi commented on docset/winserver2022-ps/failoverclusters/Add-ClusterGroupToAffinityRule.md
> +this parameter is omitted or a value of `0` is entered, then Windows PowerShell&reg; calculates an
```suggestion
this parameter is omitted or a value of `0` is entered, then PowerShell calculates an
```

2023-09-25 14:19 UTC, michaeltlombardi approved these changes

2023-09-25 14:37 UTC, michaeltlombardi commented
@robinharwood - happy to merge this one if you're finished with it.

2023-09-25 15:00 UTC, robinharwood commented
Yes please @michaeltlombardi, I was waiting for the first PR so that link wasn't broken 😄

2023-09-25 17:23 UTC, merged