Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #3588
Opened 2023-08-06 01:27 UTC by msbemba

Added OobeEnableRtpAndSigUpdate

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3501

2023-08-06 01:30 UTC, msbemba commented
@JohanFreelancer9 Please copy review

CC : @scanum

2023-08-06 07:00 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +False - (Default)	If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```suggestion
This setting allows you to configure whether real-time protection and Security Intelligence Updates are enabled during Out of Box experience (OOBE).

Valid values are:
True - If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```

2023-08-06 07:00 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/defender/Set-MpPreference.md
> +False - (Default)	If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```suggestion
True - If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
False (Default)	- If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```

2023-08-06 07:00 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/defender/Set-MpPreference.md
> +This setting allows you to configure whether real-time protection and Security Intelligence Updates are enabled during OOBE (Out of Box experience).
```suggestion
This setting allows you to configure whether real-time protection and Security Intelligence Updates are enabled during Out of Box experience (OOBE).
```

2023-08-06 07:04 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +False - (Default)	If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```suggestion
This setting allows you to configure whether real-time protection and Security Intelligence Updates are enabled during Out of Box experience (OOBE).

Valid values are:
True - If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```

2023-08-06 07:05 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-07 06:27 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/defender/Set-MpPreference.md
> +False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```suggestion
- True - If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
- False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```

2023-08-07 06:27 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```suggestion
- True - If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
- False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```

2023-08-07 06:27 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```suggestion
- True - If you enable this setting, real-time protection and Security Intelligence Updates are enabled during OOBE.
- False (Default) - If you either disable or don't configure this setting, real-time protection and Security Intelligence Updates during OOBE aren't enabled.
```

2023-08-07 06:27 UTC, JohanFreelancer9 requested changes
Apologies @msbemba, some more, please.

2023-08-07 06:48 UTC, JohanFreelancer9 approved these changes

2023-08-15 04:58 UTC, scanum commented
Hi @tiburd hope all is well. Could you please help with this PR? Thanks!

2023-08-15 16:27 UTC, merged