Update Move-ADObject.md
MicrosoftDocs/windows-powershell-docs pull request #3592
Opened 2023-08-06 02:36 UTC by msbemba

Added a statement about password when it moves within the object is moved across domains in the forest

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3514

2023-08-06 02:37 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-08-06 07:33 UTC, JohanFreelancer9 commented on docset/winserver2012-ps/activedirectory/Move-ADObject.md
> +The Cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```suggestion
The cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```

2023-08-06 07:34 UTC, JohanFreelancer9 commented on docset/winserver2012r2-ps/activedirectory/Move-ADObject.md
> +The Cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```suggestion
The cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```

2023-08-06 07:34 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/activedirectory/Move-ADObject.md
> +The Cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```suggestion
The cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```

2023-08-06 07:34 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/activedirectory/Move-ADObject.md
> +The Cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```suggestion
The cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```

2023-08-06 07:34 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/activedirectory/Move-ADObject.md
> +The Cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```suggestion
The cmdlet also moves the password when a user or computer object is moved across domains within a forest.
```

2023-08-06 07:35 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-07 06:20 UTC, JohanFreelancer9 approved these changes

2023-09-25 16:29 UTC, get-itips approved these changes

2023-10-02 05:21 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 07:38 UTC, JohanFreelancer9 requested changes
@msbemba, please commit the two suggested changes that you seem to have missed. Many thanks.

2023-10-02 07:47 UTC, JohanFreelancer9 approved these changes

2023-10-02 20:28 UTC, merged