Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #3622
Opened 2023-09-13 14:14 UTC by msbemba

AddedDisable cache maintenance to the parameters

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3502

2023-09-13 14:14 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-09-13 15:53 UTC, JohanFreelancer9 commented on docset/winserver2016-ps/defender/Set-MpPreference.md
> +Defines whether the cache maintenance idle task will perform the cache maintenance or not. Allowed values are 1- Cache maintenance is disabled and 0- Cache maintenance is enabled (default).
```suggestion
Defines whether the cache maintenance idle task will perform the cache maintenance or not. Allowed values are 1 - cache maintenance is disabled, and 0 - cache maintenance is enabled (default).
```

2023-09-13 15:55 UTC, JohanFreelancer9 commented on docset/winserver2019-ps/defender/Set-MpPreference.md
> +Defines whether the cache maintenance idle task will perform the cache maintenance or not. Allowed values are 1- Cache maintenance is disabled and 0- Cache maintenance is enabled (default).
```suggestion
Defines whether the cache maintenance idle task will perform the cache maintenance or not. Allowed values are 1 - cache maintenance is disabled, and 0 - cache maintenance is enabled (default).
```

2023-09-13 15:55 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +Defines whether the cache maintenance idle task will perform the cache maintenance or not. Allowed values are 1- Cache maintenance is disabled and 0- Cache maintenance is enabled (default).
```suggestion
Defines whether the cache maintenance idle task will perform the cache maintenance or not. Allowed values are 1 - cache maintenance is disabled, and 0 - cache maintenance is enabled (default).
```

2023-09-13 15:57 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-14 02:32 UTC, JohanFreelancer9 approved these changes

2023-10-02 22:02 UTC, get-itips approved these changes

2023-10-09 05:09 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-09 20:43 UTC, merged