Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #3666
Opened 2023-10-14 17:17 UTC by msbemba

Added disableFP pasrsing parameter

2023-10-14 17:20 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-17 11:17 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +Specifies whether to disable FTP Parsing for Network Protection.
```suggestion
Specifies whether to disable FTP parsing for network protection.
```

2023-10-17 11:18 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-17 13:48 UTC, JohanFreelancer9 approved these changes

2023-10-20 19:50 UTC, get-itips approved these changes

2023-10-22 23:49 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-23 13:40 UTC, merged