Update Get-AppxPackageAutoUpdateSettings.md
MicrosoftDocs/windows-powershell-docs pull request #3671
Opened 2023-10-20 08:09 UTC by RAJU2529

added new command and added description.
**Get-AppxPackageAutoUpdateSettings -ShowUpdateAvailability**

article link
https://learn.microsoft.com/en-us/powershell/module/appx/get-appxpackageautoupdatesettings?view=windowsserver2022-ps

![Screenshot 2023-10-20 133705](https://github.com/MicrosoftDocs/windows-powershell-docs/assets/3296790/19bdd2c1-45ea-44d4-8d69-c04657c18e09)

2023-10-21 04:43 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
> +### Example 4: Get App Package Auto Update settings with showupdateAvailability
```suggestion
### Example 4: Get App Package Auto Update settings for all installed Windows Apps
```

2023-10-21 04:44 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
> +This will return the Auto Update  for all  Windows App that has been
```suggestion
This will return the Auto Update settings for all  Windows Apps that have been
```

2023-10-21 04:45 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-23 14:01 UTC, get-itips commented on docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
> +This will return the Auto Update settings for all  Windows Apps that have been
```suggestion
Display available update information for all installed Windows Apps.
```

2023-10-23 14:01 UTC, get-itips commented on docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
> +installed.
```suggestion
```

2023-10-23 14:02 UTC, get-itips reviewed
please review my suggestion

2023-10-23 14:11 UTC, get-itips commented on docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
> +Display available update information for all installed Windows Apps.
```suggestion
Displays available update information for all installed Windows Apps.
```

2023-10-23 14:11 UTC, get-itips commented on docset/winserver2022-ps/appx/Get-AppxPackageAutoUpdateSettings.md
> +Display available update information for all installed Windows Apps.
sorry, one more thing

2023-10-23 14:17 UTC, get-itips approved these changes

2023-10-23 18:16 UTC, get-itips commented
> @get-itips , Could you tell me when Windows 11 23H2 will be released?

Sorry I don't have details around that

2023-10-24 07:02 UTC, JohanFreelancer9 approved these changes

2023-10-24 13:47 UTC, msbemba approved these changes

2023-11-06 04:12 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-11-06 23:07 UTC, merged