Update Set-MpPreference.md
MicrosoftDocs/windows-powershell-docs pull request #3684
Opened 2023-10-28 21:03 UTC by msbemba

Updated DisableNetworkProtectionPerfTelemetry, DisableSmtpParsing, IntelTDTEnabled and ThrottleForScheduledScanOnly

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3504

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3505

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3506

Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3508

2023-10-28 21:03 UTC, msbemba commented
@JohanFreelancer9 Please copy review

2023-10-28 21:19 UTC, HotCakeX commented
Thank you!

2023-10-30 08:34 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +0 (Default)- 	Network protection telemetry is enabled.
```suggestion
This setting disables the gathering and sending of performance telemetry from network protection. 
The accepted values are 0 and 1.
- 1- Network protection telemetry is disabled.
- 0 (Default) - Network protection telemetry is enabled.
```

2023-10-30 08:34 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +0 (Default)- 	SMTP parsing is enabled.
```suggestion
This setting disables SMTP parsing for network protection.
The accepted values are 0 and 1.
- 1 - SMTP parsing is disabled.
- 0 (Default) - SMTP parsing is enabled.
```

2023-10-30 08:35 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +- 2 - If you configure this setting to disabled, Intel TDT integration will turn off.
```suggestion
- 0 (Default) - If you don't configure this setting, the default value will be applied. The default value is controlled by Microsoft security intelligence updates. Microsoft will enable Intel TDT if there is a known threat.
- 1 - If you configure this setting to enabled, Intel TDT integration will turn on.
- 2 - If you configure this setting to disabled, Intel TDT integration will turn off.
```

2023-10-30 08:35 UTC, JohanFreelancer9 commented on docset/winserver2022-ps/defender/Set-MpPreference.md
> +
```suggestion
- 1 (Default) - If you enable this setting, CPU throttling will apply only to scheduled scans.
- 0 - If you disable this setting, CPU throttling will apply to scheduled and custom scans.
```

2023-10-30 08:35 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-30 15:19 UTC, JohanFreelancer9 approved these changes

2023-11-06 13:24 UTC, get-itips approved these changes

2023-11-12 00:33 UTC, scanum commented
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-11-13 15:55 UTC, merged