NEW - SMBClientAccessToServer cmdlet
MicrosoftDocs/windows-powershell-docs pull request #3783
Opened 2024-03-08 14:29 UTC by Xelu86

# PR Summary

This is a new SMB cmdlet, SMBClientAccessToServer, for WS25.

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2024-03-12 20:19 UTC, sdwheeler requested changes
See my suggested changes.

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Block-SmbClientAccessToServer.md
> +-Identifier <String> [-Description <String>] [-Force] [-CimSession <CimSession[]>]
A space is required after the first line.
```suggestion
 -Identifier <String> [-Description <String>] [-Force] [-CimSession <CimSession[]>]
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Block-SmbClientAccessToServer.md
> +[Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet. The default is the
```suggestion
[Get-CimSession](/powershell/module/cimcmdlets/get-cimsession) cmdlet. The default is the
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Get-SmbClientAccessToServer.md
> +[Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet. The default is the
```suggestion
[Get-CimSession](/powershell/module/cimcmdlets/get-cimsession) cmdlet. The default is the
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Grant-SmbClientAccessToServer.md
> +This example grants SMB client access to a server named "Server01" based on the client's
Put parameter values in backticks.
```suggestion
This example grants SMB client access to a server named `Server01` based on the client's
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Grant-SmbClientAccessToServer.md
> +[Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet. The default is the
```suggestion
[Get-CimSession](/powershell/module/cimcmdlets/get-cimsession) cmdlet. The default is the
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Grant-SmbClientAccessToServer.md
> +will depend on the `-IdentifierType` parameter that you're using.
In paragraphs, use backticks for syntax examples; bold for parameter names.
```suggestion
will depend on the **IdentifierType** parameter that you're using.
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Grant-SmbClientAccessToServer.md
> +`-IdentifierType` parameter are:
```suggestion
**IdentifierType** parameter are:
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Revoke-SmbClientAccessToServer.md
> +[Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet. The default is the
```suggestion
[Get-CimSession](/powershell/module/cimcmdlets/get-cimsession) cmdlet. The default is the
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Revoke-SmbClientAccessToServer.md
> +will depend on the `-IdentifierType` parameter that you're using.
```suggestion
will depend on the **IdentifierType** parameter that you're using.
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Revoke-SmbClientAccessToServer.md
> +`-IdentifierType` parameter are:
```suggestion
**IdentifierType** parameter are:
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Unblock-SmbClientAccessToServer.md
> +certificate. This command runs without prompting for confirmation as the `-Force` parameter is set
```suggestion
certificate. This command runs without prompting for confirmation as the **Force** parameter is set
```

2024-03-12 20:19 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Unblock-SmbClientAccessToServer.md
> +[Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet. The default is the
```suggestion
[Get-CimSession](/powershell/module/cimcmdlets/get-cimsession) cmdlet. The default is the
```

2024-03-12 20:25 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Block-SmbClientAccessToServer.md
> +Block-SmbClientAccessToServer [-Name] <String[]> -IdentifierType <IdentifierType>
You are missing the H3 parameter set names for both parameter blocks.

2024-03-12 20:26 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Get-SmbClientAccessToServer.md
> +```
Missing parameter set names.

2024-03-12 20:30 UTC, sdwheeler reviewed
Fix the order of **Confirm** and **WhatIf** parameters. Add Parameter Set names. Update the parameters with the proper parameter set names.

2024-03-12 20:30 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Get-SmbClientAccessToServer.md
> +Parameter Sets: (All)
Incorrect parameter set

2024-03-12 20:30 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Get-SmbClientAccessToServer.md
> +```
**Confirm** and **WhatIf** parameters go at the end of the list before CommonParameters.

2024-03-12 20:30 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Get-SmbClientAccessToServer.md
> +
**Confirm** and **WhatIf** parameters go at the end of the list before CommonParameters.

2024-03-12 20:30 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Grant-SmbClientAccessToServer.md
> +```yaml
**Confirm** and **WhatIf** parameters go at the end of the list before CommonParameters.

2024-03-12 20:30 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Revoke-SmbClientAccessToServer.md
> +Aliases: cf
**Confirm** and **WhatIf** parameters go at the end of the list before CommonParameters.

2024-03-12 20:30 UTC, sdwheeler commented on docset/winserver2025-ps/smbshare/Unblock-SmbClientAccessToServer.md
> +```yaml
**Confirm** and **WhatIf** parameters go at the end of the list before CommonParameters.

2024-03-20 20:20 UTC, nedpyle requested changes
more to come

2024-03-20 20:20 UTC, nedpyle commented on docset/winserver2025-ps/smbshare/Block-SmbClientAccessToServer.md
> +The `Block-SmbClientAccessToServer` cmdlet is used to prevent SMB clients from accessing a
When using SMB over QUIC client access control

2024-03-20 20:20 UTC, nedpyle commented on docset/winserver2025-ps/smbshare/Get-SmbClientAccessToServer.md
> +a specified server. When you run this cmdlet, it'll return a list of all SMB client connections to
not a list of connections, but a list of allowed and blocked connections for SMB over QUIC client access control

2024-03-20 20:20 UTC, nedpyle commented on docset/winserver2025-ps/smbshare/Grant-SmbClientAccessToServer.md
> +Grants SMB client access to a specified server.
for SMB over QUIC client access control

2024-03-20 20:20 UTC, nedpyle commented on docset/winserver2025-ps/smbshare/Revoke-SmbClientAccessToServer.md
> +# Revoke-SmbClientAccessToServer
I want to add better explanation of revoke vs grant vs block vs unblock, will get back to you

2024-04-15 20:20 UTC, merged