Broken links - JasonGerend - 1
MicrosoftDocs/windows-powershell-docs pull request #3900
Opened 2024-11-08 21:48 UTC by Albertyang0

Hi @JasonGerend, I've fixed the broken links. Please verify. Thanks!

See: https://dev.azure.com/msft-skilling/Content/_workitems/edit/340770

# PR Summary

## PR Checklist

- [ ] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [ ] **Summary:** This PR's summary describes the scope and intent of the change.
- [ ] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [ ] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2024-11-21 21:52 UTC, Albertyang0 commented
#sign-off

2024-11-22 19:36 UTC, JasonGerend requested changes
I made some suggestions on things to change--take a look and see what you think. Thanks for helping us fix these links! :)

2024-11-25 22:28 UTC, JasonGerend approved these changes

2024-11-25 22:29 UTC, JasonGerend commented
#sign-off

2024-11-25 22:31 UTC, merged